### ISSUE TITLE
Flatlist rendering errors with search

### ISSUE THREAD

**Issue by osvaldokalvaitir** [Nozbe/WatermelonDB#1000]
I am facing some rendering problems with FlatList items when doing research.

I have an array of products, if I make a map on this array and search for a word it works normal. But if I do the same thing with FlatList, some texts are overlapping. It looks like it doesn't render completely.

![wa](https://user-images.githubusercontent.com/40433049/115129141-93100980-9fb9-11eb-9741-c006e14c9996.PNG)
![wa2](https://user-images.githubusercontent.com/40433049/115129144-a7540680-9fb9-11eb-92b3-54acc2ded82c.PNG)

List.js
```
function List({ products }) {
  const renderItem = ({ item }) => {
    return <ListItem product={item} />;
  };

  return (
    <FlatList
      data={products}
      keyExtractor={(item) => item.id}
      renderItem={renderItem}
    />
  );
}

const enhanceProducts = withObservables(
  ['products', 'search'],
  ({ database, search }) => ({
    products: database
      .get('products')
      .query(
        Q.where('title', Q.like(`%${Q.sanitizeLikeString(search)}%`)),
      )
      .observeWithColumns(
        'title',
        'stock',
        'price',
      ),
  }),
);

export default withDatabase(enhanceProducts(List));
```

ListItem.js
```
function ListItem({ product }) {
  return (
    <ListItemLargeText>{title}</ListItemLargeText>
  );
}

const enhanceProduct = withObservables(['product'], ({ product }) => ({
  product: product.observe(),
}));

export default withDatabase(enhanceProduct(ListItem));
```

I reduced the code, the fields I think do not influence, because the map is working.

I am very grateful if anyone can help me.

**Comment by radex** [comment]
Sorry, this isn't an appropriate place to ask React Native questions

**Comment by osvaldokalvaitir** [comment]
@radex ok, I wasn't thinking that my mistake was in the Flatlist but in withObservables.

**Comment by radex** [comment]
@osvaldokalvaitir withObservables just renders inner component with props filled out, the problem is with your FlatList setting.

PS: Try using Watermelon with synchronous/jsi: true in the adapter - synchronous operation avoids a lot of downstream rendering issues

**Comment by osvaldokalvaitir** [comment]
@radex I will study about it, thank you very much.
