### ISSUE TITLE
Sync failed with "out of memory" error when trying to push 60 images in one push

### ISSUE THREAD

**Issue by alonroth** [Nozbe/WatermelonDB#1007]
Hi

I'm not sure it's a WatermalonDB problem but I thought maybe you encounter this before or could point me in the right direction.

One of our users experiencing consistent crashes when he opens the app and tries to push his changes to the server (443 new items, 200 of them are images) but we don't get any crash report/sentry alert although the user is opt-in for crash reports on his iPhone 11 Max.

When we were tried to reproduce this crash, we tried to push ~150 items (60 of them are images) and the sync failed and we got OOM exception on iPhone 8 but without a crash:
{"message":"Out of memory","name":"Error","stack":"stringify@[native code]

It worth to mention that we are sending the image files as base 64 as a column of the item after they are resized to maximum 1000x1500 pixels.

Thanks!

**Comment by hamzaawais96** [comment]
@alonroth can i ask how are you sending the images? is it in base64 format?

**Comment by radex** [comment]
> It worth to mention that we are sending the image files as base 64 as a column of the item after they are resized to maximum 1000x1500 pixels.

yeah that's just not going to scale. For sure work could be done for sync push to be more resilient in terms of memory pressure. PRs are welcome. But I'm just not sure if the approach you took to deal with images is the right one. I would not recommend storing large images as base64 text and then synchronizing that with other text.

**Comment by ChrisSimoniMBT** [comment]
> Hi
> 
> I'm not sure it's a WatermalonDB problem but I thought maybe you encounter this before or could point me in the right direction.
> 
> One of our users experiencing consistent crashes when he opens the app and tries to push his changes to the server (443 new items, 200 of them are images) but we don't get any crash report/sentry alert although the user is opt-in for crash reports on his iPhone 11 Max.
> 
> When we were tried to reproduce this crash, we tried to push ~150 items (60 of them are images) and the sync failed and we got OOM exception on iPhone 8 but without a crash: {"message":"Out of memory","name":"Error","stack":"stringify@[native code]
> 
> It worth to mention that we are sending the image files as base 64 as a column of the item after they are resized to maximum 1000x1500 pixels.
> 
> Thanks!

If you can follow along with my potentially incoherent jargon, this is how a resolved a similar issue. https://github.com/Nozbe/WatermelonDB/issues/650#issuecomment-1352144423
