### ISSUE TITLE
unsafeSql not working

### ISSUE THREAD

**Issue by hukpavlo** [Nozbe/WatermelonDB#1009]
Hi, I use the 0.21.0 version and there is no type for the unsafeSql field. Also, this unsafeSql doesn't work for me. I'm trying to console.log it, but nothing happens.

![image](https://user-images.githubusercontent.com/40897161/116012052-e4ab3a80-a630-11eb-9969-d1d42a2a76fc.png)

**Comment by radex** [comment]
Look into the source code: https://github.com/Nozbe/WatermelonDB/blob/master/src/Schema/index.js

Here are TS typings for you to contribute a fix for: https://github.com/Nozbe/WatermelonDB/blob/master/src/Schema/index.d.ts

**Comment by sidferreira** [comment]
@radex I'm setting some time to do a full review on all TS.

**Comment by hukpavlo** [comment]
What about unsafeSql not working? Typings is not a big deal...

**Comment by sidferreira** [comment]
@hukpavlo `unsafeSql` is called only when building the DB. You can debug like this:

change `unsafeSql` to:
```
unsafeSql: (baseSql) => {
  const mySql = `.....`;
  const finalSql = `${baseSql}${mySql}`;
  console.log(`>>> unsafeSql: `, finalSql);
  return baseSql;
}
```

run the app, it should output all the SQL. Then grab an SQLite tool (`DB Browser for SQLite for example`) and run the generated sql.

**Comment by sidferreira** [comment]
@hukpavlo did it help?

**Comment by hukpavlo** [comment]
Sorry, haven't tried yet, I'll allocate some time on Saturday (I don't use it in commercial project so not the main priority).
BTW, should I create a pull request to fix typescript issue, or you'll fix it after your global ts refactoring?

**Comment by hukpavlo** [comment]
@sidferreira Thanks, it works well now.
