### ISSUE TITLE
How to query for all changed records including deleted status

### ISSUE THREAD

**Issue by ruben4mobile** [Nozbe/WatermelonDB#1013]
I would like to have a counter to know how many items we need to sync to the backend? And i would like to use the enhance options with withObservables like so
```
const uploadButtonObservable = withObservables<
  UploadButtonPropsIn,
  UploadButtonPropsOut
>([], () => {
  const collection = database.collections.get(tableName);
  return {
    changedCount: collection
      .query(Q.where('_status', Q.notEq('synced')))
      .observeCount(),
  };
});
```

The problem is that by default the query is extend to exclude _status = 'deleted'

So How should I tackle this?

**Comment by radex** [comment]
use this api: https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/type.js#L37 - or if you're SQL-only, you can run a raw SQL query

**Comment by ruben4mobile** [comment]
True I have tried that and it indeed give the ids's, but it is not observable, so I can't use it with `withObservable` so how can I get that result to my UI in a reactive way.

**Comment by radex** [comment]
you can use https://github.com/Nozbe/WatermelonDB/blob/master/src/Database/index.js#L178 to get a signal whenever there's a change in the DB, upon which you can refetch the value

**Comment by ruben4mobile** [comment]
How can I execute a raw query that doesn't return a Record. I'm only interested in a count of deleted records but  also with a when clause, because I have multiple parts that needs to be sync individually.

**Comment by ruben4mobile** [comment]
Fixed it with 
```
async function getChangedAndUpdatedItems(
  activeAnalysisId: string,
  setUpdatedRecords: React.Dispatch<React.SetStateAction<number>>
): Promise<void> {
  try {
    const updatedRecords = await rawCountQuery(
      `select count(*) as "count" from "${AnalysisPartsTable.name}" where "analysis_id"='${activeAnalysisId}' and "_status" != 'synced'`
    );
    setUpdatedRecords(updatedRecords);
  } catch {
    //On faillure we return 0
    setUpdatedRecords(0);
  }
}
```
in combination with https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/type.js#L37

**Comment by radex** [comment]
you have a lot of trust in the incoming data… are you sure you're not setting yourself up for a sql injection epic fail? :P

**Comment by ruben4mobile** [comment]
If there was a way to get the data without this risk I  would use it. Problem is that there are possibly multiple projects to sync separately explaining the need for the where clause. I could possibly start a new database per project and drop some raw queries, but not all
