### ISSUE TITLE
Write up preferred way to reset local database

### ISSUE THREAD

**Issue by theVasyl** [Nozbe/WatermelonDB#102]
What would be the recommended way to trigger a complete deletion (and recreation) of the database?

**Comment by radex** [comment]
`database.unsafeResetDatabase()`

note that it's "unsafe" because it doesn't update query or model observers. Which means this is only safe to do when there are no `withObservables`-enhanced components mounted in the component tree, and you're not going to reuse any `Model` instances you may have stored.

Feel free to contribute an update to documentation (and Database/index.js comment) that clarifies this.

Also we'd be happy to accept an enhancement that makes the database reset safe to do

**Comment by theVasyl** [comment]
Thanks for the quick info, @radex .

What exactly do you mean by "stored" model instances. The ones currently in the db?
Anything that is currently used by some component?

A quick check revealed that our current navigation setup in no way satisfies these conditions.
Will check, but if it proves too cumbersome, our take on the solution will have to wait for a sprint or even a couple. Sorry.

**Comment by radex** [comment]
> What exactly do you mean by "stored" model instances. The ones currently in the db?
Anything that is currently used by some component?

Essentially any Model instance you have in the JavaScript — don't touch it anymore, since after reset it won't correspond to something in the database.

> A quick check revealed that our current navigation setup in no way satisfies these conditions.

What we do is we have a "isLoggedIn" React context, and in the root of the component tree, if we're not logged in, we display components that don't use Watermelon.

**Comment by radex** [comment]
@theVasyl IS this a solved issue? Can I close it?

If you had 10 minutes to update to documentation (and Database/index.js comment) that clarifies this and send a quick PR, that would be 💯

**Comment by radex** [comment]
@theVasyl Hey, just checking again — is this still relevant to you?

**Comment by sebastian-schlecht** [comment]
@radex we were working together on this, I think you can close the issue.

**Comment by radex** [comment]
@sebastian-schlecht Alright! Although

**Comment by nullgr4vity** [comment]
@sebastian-schlecht good morning ... currently I'm working on the project where I have the same requirement like you guys had - db reset without logout. I would appreciate a lot any experience you guys could share with.

**Comment by isaachinman** [comment]
It seems a little strange that the official advice is to use an unsafe method.

Here's what I've come up with. In my case I specifically _do_ want observables to update, as otherwise I get some `useEffect` running incorrectly:

```tsx
await database.write(async () => {
  const collections = Object.values(database.collections.map)

  for (const collection of collections) {
    await collection.query().destroyAllPermanently()
  }
})
```

**Comment by heliocosta-dev** [comment]
> It seems a little strange that the official advice is to use an unsafe method.
> 
> Here's what I've come up with. In my case I specifically _do_ want observables to update, as otherwise I get some `useEffect` running incorrectly:
> 
> ```tsx
> await database.write(async () => {
>   const collections = Object.values(database.collections.map)
> 
>   for (const collection of collections) {
>     await collection.query().destroyAllPermanently()
>   }
> })
> ```

Just tried this one and indeed seems to be a more elegant way. Thanks for sharing. However, it doesn't seem to reset `lastPulledAt` and cannot use turbo sync again as well. How are you handling these?

**Comment by isaachinman** [comment]
I'm only using this functionality on logout, and actually still call `unsafeResetDatabase` _after_ safely destroying all collections.

Again, I find it pretty strange that there's no first-class "safe" way to reset Watermelon.

**Comment by heliocosta-dev** [comment]
> I'm only using this functionality on logout, and actually still call `unsafeResetDatabase` _after_ safely destroying all collections.
> 
> Again, I find it pretty strange that there's no first-class "safe" way to reset Watermelon.

I see. That does make sense yeah. Have you ever came across that `Application error! Unexpected 3 Database subscribers were detected during database.unsafeResetDatabase() call. App should not hold onto subscriptions or Watermelon objects while resetting database.` message? If so, how did you end up solving it?

My current hook looks like this:

```ts
const useDatabaseData = <T extends Model>({
  tableName,
  query = [],
  count,
}: {
  tableName: TableName;
  query?: Q.Clause[];
  count?: boolean;
}) => {
  const { localUser } = useAuth();

  const data = useObservableEagerState(
    useObservable(
      inputs$ =>
        inputs$.pipe(
          switchMap$(([_database, _query]) => {
            const dbQuery = _database.get(tableName).query(JSON.parse(_query));
            if (count) {
              return dbQuery.observeCount(false);
            }
            return dbQuery.observe();
          }),
        ),
      [database, JSON.stringify(query), localUser?.id],
    ),
  );

  return data as T[] | number;
};
```

I wonder which could be a good approach for handling subscriptions (to later unsubscribe) here?

**Comment by isaachinman** [comment]
I don't have any further info for you. The way the Watermelon code is written assumes you will unmount/remove observable subscribers on your own, before calling `unsafeResetDatabase`.
