### ISSUE TITLE
How to config getJSIModulePackage for multiple JSI packages?

### ISSUE THREAD

**Issue by 18601673727** [Nozbe/WatermelonDB#1023]
Pardon my ignorances here, I'm trying to implement `WatermelonDB` and `React Native Reanimated` together into one single app, and here's my `MainApplication.java`
```
@Override
protected JSIModulePackage getJSIModulePackage() {
  return new JSIModulePackage() {
    @Override
    public List<JSIModuleSpec> getJSIModules(
      final ReactApplicationContext reactApplicationContext,
      final JavaScriptContextHolder jsContext
    ) {
      final List<JSIModuleSpec> specs = new ArrayList<>();
      specs.add(new ReanimatedJSIModulePackage());
      specs.add(new WatermelonDBJSIPackage());
      return specs;
    }
  };
}
```
Since I have no JAVA experience, so this code is total junk, but the idea of how to enable both JSI Modules in `getJSIModulePackage()` is a problem I cound't overcome, could someone please to help?

**Comment by radex** [comment]
you need to call both packages' getJSIModules() in your getJSIModules implementation, not add those packages - note that JSIModulePackage and JSIModuleSpec are different types

**Comment by marcocesarato** [comment]
Something like this?
```
@Override
protected JSIModulePackage getJSIModulePackage() {
  return new JSIModulePackage() {
    @Override
    public List<JSIModuleSpec> getJSIModules(
      final ReactApplicationContext reactApplicationContext,
      final JavaScriptContextHolder jsContext
    ) {
      new ReanimatedJSIModulePackage().getJSIModules(reactApplicationContext, jsContext);
      new WatermelonDBJSIPackage().getJSIModules(reactApplicationContext, jsContext);
      return Arrays.asList();
    }
  };
}
```

**Comment by 18601673727** [comment]
Thanks a lot @radex @marcocesarato , the code now compiles indeed! But could be better to verify the results(JSI Mode on or not) since `JSIModules` got never returned?

```java
import java.util.Arrays;

import com.facebook.react.bridge.JSIModulePackage;
import com.facebook.react.bridge.JSIModuleSpec;
import com.facebook.react.bridge.ReactApplicationContext;
import com.facebook.react.bridge.JavaScriptContextHolder;
import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage;
import com.swmansion.reanimated.ReanimatedJSIModulePackage;

protected JSIModulePackage getJSIModulePackage() {
  return new JSIModulePackage() {
    @Override
    public List<JSIModuleSpec> getJSIModules(
      final ReactApplicationContext reactApplicationContext,
      final JavaScriptContextHolder jsContext
    ) {
      new ReanimatedJSIModulePackage().getJSIModules(reactApplicationContext, jsContext);
      new WatermelonDBJSIPackage().getJSIModules(reactApplicationContext, jsContext);
      return Arrays.asList();
    }
  };
}
```

**Comment by marcocesarato** [comment]
> Thanks a lot @radex @marcocesarato , the code now compiles indeed! But could be better to verify the results(JSI Mode on or not) since `JSIModules` got never returned?
> 
> ```java
> import java.util.Arrays;
> 
> import com.facebook.react.bridge.JSIModulePackage;
> import com.facebook.react.bridge.JSIModuleSpec;
> import com.facebook.react.bridge.ReactApplicationContext;
> import com.facebook.react.bridge.JavaScriptContextHolder;
> import com.nozbe.watermelondb.jsi.WatermelonDBJSIPackage;
> import com.swmansion.reanimated.ReanimatedJSIModulePackage;
> 
> protected JSIModulePackage getJSIModulePackage() {
>   return new JSIModulePackage() {
>     @Override
>     public List<JSIModuleSpec> getJSIModules(
>       final ReactApplicationContext reactApplicationContext,
>       final JavaScriptContextHolder jsContext
>     ) {
>       new ReanimatedJSIModulePackage().getJSIModules(reactApplicationContext, jsContext);
>       new WatermelonDBJSIPackage().getJSIModules(reactApplicationContext, jsContext);
>       return Arrays.asList();
>     }
>   };
> }
> ```

If you check `ReanimatedJSIModulePackage` and `WatermelonDBJSIPackage` JSI getter method you will see that they are returning an empty list like `Arrays.asList()` and they probably initialize the module directly on Context object so you don't really need to return something

**Comment by radex** [comment]
yes, this is correct, however it would be safer to collect responses, concatenate them, and return them properly. It would be nice to have this snippet in the Installation guide for others to use

**Comment by marcocesarato** [comment]
```java
@Override
protected JSIModulePackage getJSIModulePackage() {
  return new JSIModulePackage() {
    @Override
    public List<JSIModuleSpec> getJSIModules(
      final ReactApplicationContext reactApplicationContext,
      final JavaScriptContextHolder jsContext
    ) {
      List<JSIModuleSpec> modules = Arrays.asList();
      List<JSIModuleSpec> reanimatedModule = new ReanimatedJSIModulePackage().getJSIModules(reactApplicationContext, jsContext);
      List<JSIModuleSpec> watermelonDBModule = new WatermelonDBJSIPackage().getJSIModules(reactApplicationContext, jsContext);
      modules.addAll(reanimatedModule);
      modules.addAll(watermelonDBModule);
      return modules;
    }
  };
}
```

**Comment by 18601673727** [comment]
Guessing this issue could be closed, appreciates for all the help!

**Comment by radex** [comment]
@18601673727 Hey, multiple people helped you out with what will be a common problem - the kind thing to do would be to contribute to the project's documentation: https://github.com/Nozbe/WatermelonDB/tree/master/docs-master - find the right document, hit edit, and explain to future users how to solve this problem

**Comment by 18601673727** [comment]
> @18601673727 Hey, multiple people helped you out with what will be a common problem - the kind thing to do would be to contribute to the project's documentation: https://github.com/Nozbe/WatermelonDB/tree/master/docs-master - find the right document, hit edit, and explain to future users how to solve this problem

Sure @radex, very much like to do!
