### ISSUE TITLE
Is there a way to iterate over a collection during a migration?

### ISSUE THREAD

**Issue by WJimmyCook** [Nozbe/WatermelonDB#1028]
Hi,

I need to add a new column to a table. I want to populate the data in the new column based on existing records in the collection during the migration step(s). I look in the docs and github issues but I couldn't find anything, is this possible?

Thanks.

**Comment by radex** [comment]
I'm afraid it's not. We definitely need a proper mechanism to perform _data_ migrations. IF you're using SQLiteAdapter, you can use `migrationEvents` to see when migration happened and use that as a hook to perform, say, an unsafe SQL query (or any standard Watermelon work) before letting the rest of the app run
