### ISSUE TITLE
[Question] is there a way of checking sync status

### ISSUE THREAD

**Issue by MikeGlennFWC** [Nozbe/WatermelonDB#1068]
Is there a way in the watermelon DB api to check the status of a sync? Or what jobs are queued?

What i mean is, if i am syncing periodically, or imagine if the user is able to sync manually as well, if they were to trigger consecutive manual syncs, then can we check if the last sync has finished committing it's data to SQLlite?

Watermelon throws a warning and says it safely handles this, but i feel we should be able to check what the interface is doing and act accordingly.

Does this sound possible, or should we just let it happen? I don't think it could be debounced, because we don't know how long the sync will take.

I can't see anything in the docs around this.

Thanks
Mike

**Comment by radex** [comment]
@MikeGlennFWC You need to `await` the promise returned by `synchronize()`. When it resolves, it means that the sync is complete. If multiple bits of UI trigger it, write your own code to centralize the responsibility for running synchronize, queueing, whatever you need.

**Comment by KrisLau** [comment]
@MikeGlennFWC Did you ever figure out how to do this? I awaited my `synchronize()` call but it seems to be calling pullChanges multiple times within the `synchronize` which triggers the concurrent sync error.
```
 LOG  ---------------------------------
 LOG  synchronize is called...
 LOG  pullChanges...
 LOG  pullChanges...                              <--- why is this pull happening?
 LOG  pushChanges...
 LOG  pullChanges called...                       <--- Second sync to bump timestamp 
 LOG  ---------------------------------
 WARN  Possible Unhandled Promise Rejection (id: 12):
Diagnostic error: [Sync] Concurrent synchronization is not allowed. More than one synchronize() call was running at the same time, and the later one was aborted before committing results to local database.
```

**Comment by MikeGlennFWC** [comment]
I may be mistaken, but i did have `synchronize()` in a React Context,  i moved this to `App.js`

The main thing i implemented, which is the same to this day, even if it absolutely hacky. is this `isSyncing`

```js
export const doSync = async () => {
  let url;
  let token;
  let credentials = await EncryptedStorage.getItem('secure_credentials');

  if (credentials !== null) {
    credentials = JSON.parse(credentials);
    url = credentials.url;
    token = credentials.token;
  }

  if (!url || !token || isSyncing) {
    console.log('skipping sync');
    return;
  }

  isSyncing = true;
  await synchronize({
    database,
    pullChanges: async ({lastPulledAt, schemaVersion, migration}) => {
      const response = await fetch(
        `${url}/api/sync?lastVersion=${lastPulledAt}&schemaVersion=${schemaVersion}&migration=${migration}`,
        {
          headers: {
            Accept: 'application/json',
            Authorization: 'Bearer ' + token,
            'Accept-Encoding': 'gzip,deflate',
          },
        },
      );

      if (!response.ok) {
        isSyncing = false;
        throw new Error(await response.text());
      }
      const {changes, timestamp} = await response.json();

      return {changes, timestamp};
    },
    pushChanges: async ({changes, lastPulledAt}) => {
      const response = await fetch(
        `${url}/api/sync?lastVersion=${lastPulledAt}`,
        {
          method: 'post',
          headers: {
            'Content-Type': 'application/json',
            Authorization: 'Bearer ' + token,
            Accept: 'application/json',
          },
          body: JSON.stringify(changes),
        },
      );

      if (!response.ok) {
        isSyncing = false;
        throw new Error(await response.text());
      }
    },
    migrationsEnabledAtVersion: 1,
  });

  isSyncing = false;
};
```

**Comment by KrisLau** [comment]
So I had implemented something similar except with hooks but it doesn't seem to be working. For some reason, the pull changes seems to be triggered multiple times within a single `synchronize` call

My code: 
```
import React, {createContext, useContext, useEffect, useState} from 'react';
import {debounceTime, filter, skip} from 'rxjs/operators';
import 'react-native-get-random-values';
import {v4 as uuidv4} from 'uuid';
import database from '../database';
import {synchronizeWithServer} from '../database/helpers';

const SyncContext = createContext();
function useSync() {
  return useContext(SyncContext);
}

function SyncProvider({children}) {
  const [isSyncing, setIsSyncing] = useState(false);

  async function sync() {
    if (!isSyncing) {
      const sessionID = uuidv4();
      setIsSyncing(true);
      await synchronizeWithServer(sessionID);
      setIsSyncing(false);
    }
  }

  useEffect(() => {
    return database
      .withChangesForTables([
        'table_name',
        'table_name',
      ])
      .pipe(
        skip(1),
        // ignore records simply becoming `synced`
        filter(
          changes =>
            !changes.every(change => change.record.syncStatus === 'synced'),
        ),
        // debounce to avoid syncing in the middle of related actions
        debounceTime(500),
      )
      .subscribe(async () => await sync());
  }, []);

  const value = {
    isSyncing,
    sync,
  };

  return <SyncContext.Provider value={value}>{children}</SyncContext.Provider>;
}

export {SyncContext, SyncProvider, useSync};
```
I also created an issue for my specific issue: https://github.com/Nozbe/WatermelonDB/issues/1256

**Comment by MikeGlennFWC** [comment]
This was exactly the reason i moved it out of the ReactContext, the entire stack was being re-rendered, calling synchronise again and again.

Honestly, I cannot tell you that i'm giving you sound advice here, because i'm not that good at React, but i moved the sync logic to App.js and things were much better.

What i can tell you though for certain, you are trying to use a setState incorrectly, which could be why your code is ignoring isSyncing. Due to the nature of setState being async, by the time you reach your `if (!isSyncing)`, the value may not yet be set to true, so the program will continue, you cannot use a setState if you need a result from it instantly.

**Comment by KrisLau** [comment]
@MikeGlennFWC Oh that fixed it, it was just the `setState` that was messing it up! Thanks so much for taking the time to reply me!

For your constant re-rendering problem, I'm not sure if it's exactly the same but I ran into the same thing awhile back. For me, I basically just needed to unsubscribe in my `useEffect`. Hopefully this https://github.com/Nozbe/WatermelonDB/issues/1233 helps you too
