### ISSUE TITLE
App crashes when executing the same function multiple times

### ISSUE THREAD

**Issue by osvaldokalvaitir** [Nozbe/WatermelonDB#1074]
I have a list that allows the user to change the quantity. It turns out that if I quickly click on the amount several times, or if I click when rendering a list, the application seems to crash and the message appears:

```
[WatermelonDB] Enqueued action: [Function _callee3]
 LOG  [WatermelonDB] Running action: [Function _callee3]
 WARN  [WatermelonDB] The action you're trying to perform (unnamed) can't be performed yet, because there are 2 actions in the queue. Current action: unnamed. Ignore this message if everything is working fine. But if your actions are not running, it's because the current action is stuck. Remember that if you're calling an action from an action, you must use subAction(). See docs for more details.
``` 
 
I run my code inside a function as it is in the documentation: 

```
          await database.action(async () => {
            await firstItem.update(item => {
              item.quantity = quantityValue;
              item.total = total;
            });
          });
```

![image](https://user-images.githubusercontent.com/40433049/122280040-22a13e00-cebf-11eb-936d-6cd646464a89.png)

ps: I read some issues with this error, but no response

**Comment by radex** [comment]
The warning is correct, but not dangerous. You need to find the real cause of crash. I suggest running the app via Xcode so that debugger stops on crash - you'll see whether that's a native crash, or RN induces a crash because of an uncaught JS error.

PS: Add Error Boundaries to your react app if you haven't already

**Comment by osvaldokalvaitir** [comment]
I'm still doing some tests, I don't have a mac to use Xcode, I only develop on Android, but note that the error happens if I make multiple requests to the database too fast.

I'll look at the error limits too, thanks

**Comment by MikeGlennFWC** [comment]
@radex, having a similar problem to this, qr codes are scanned and entered into a table. We can reach about 30 scans before the app crashes, there are no logs associated with this from react native. It’s not consistent, seems random.

I’ve tried using the @next version, to use 0.23.1-3 as I can see some attempts to fix a crash there. Are these crashes related?

We’re using Hermes and JSI. Is there workaround at all? Or is there a way to get lower level debug messages from android that could aid a fix?

**Comment by MikeGlennFWC** [comment]
@radex please disregard my last comment. I believe we have found our issue, each time we were storing to 🍉, we were also playing a sound. Actually, we believe the sound library is causing our crash, it was just coincidental that there are fixes in 🍉 for an app crash on Android.

Of course, seeing as we are running in production with 🍉 we will continue to monitor the situation.
