### ISSUE TITLE
Is there a function that I can call to check if a synchronization is happening?

### ISSUE THREAD

**Issue by luk3skyw4lker** [Nozbe/WatermelonDB#1075]
My app has some syncs that sometimes run together, so I have the warning that the sync process is happening concurrently. So I thought that maybe the library would offer a function to check if a sync process is running right now or not.

**Comment by radex** [comment]
@luk3skyw4lker Duplicate: https://github.com/Nozbe/WatermelonDB/issues/1068#issuecomment-861219204

**Comment by luk3skyw4lker** [comment]
Sorry for duplicating!
