### ISSUE TITLE
withObservables import

### ISSUE THREAD

**Issue by taxidermic** [Nozbe/WatermelonDB#1081]
Hi! Thank you for this great lib! I tried to upgrade from 0.20.0 to 0.22.0 and can't find the new location of `withObservables` method

In Changelog it's written:

```
withObservables is now a dependency of WatermelonDB for simpler installation and consistent updates. You can (and generally should) delete @nozbe/with-observables from your app's package.json
```

I used to import it from `@nozbe/with-observables` and since it's deleted from package.json, I tried to import it from `@nozbe/watermelondb`.  But it's not exported there, where is the new import location? I'm using typescript

Examples still import it from `@nozbe/with-observables`

**Comment by radex** [comment]
Just delete from package.json, don't change any imports
