### ISSUE TITLE
Records retrieval by multiple conditions on a many-to-many relationship

### ISSUE THREAD

**Issue by nmeibergen** [Nozbe/WatermelonDB#1082]
Considering the simple example of having articles and tags. I want to find articles that satisfy multiple tags. To this end I am following the architecture:

```
export default appSchema({
    version: 1,
    tables: [
        tableSchema({
            name: 'articles',
            columns: [{
                    name: 'text',
                    type: 'string'
                },
                {
                    name: 'created_at',
                    type: 'number'
                },
                {
                    name: 'updated_at',
                    type: 'number'
                }
            ]
        }),
        tableSchema({
            name: 'tags',
            columns: [{
                name: 'name',
                type: 'string',
                isIndexed: true
            }, ]
        }),
        tableSchema({
            name: 'article_tags',
            columns: [{
                    name: 'article_id',
                    type: 'string',
                    isIndexed: true
                },
                {
                    name: 'tag_id',
                    type: 'string',
                    isIndexed: true
                },
            ]
        }),
    ]
})
```

and correspondingly `Article`, `Tag` and `ArticleTags` models in line with the many-to-many relationship setup as presented within the documentation [here](https://nozbe.github.io/WatermelonDB/Relation.html#many-to-many-relation).

The user will now have a list of tags from which it can select. Based on this selection I want to show all articles that have all selected tags. Furthermore if a new article is created/deleted/updated with the selected tags the list of articles should also refresh. Therefore an observable list of these articles seems sensible. However executing a query that returns these articles would look something along the lines of

```
SELECT article_id
FROM article_tags
LEFT JOIN tags ON tag_id = tags.id
WHERE tag.name IN ('tag1', 'tag2')
GROUP BY article_id
HAVING COUNT(tag_id) = 2;
```

Based on this my question is twofold:  
1. Is there a clean WatermelonDB approach to this problem or will I have to work with `unsafeFetchRecordsWithSQL` and build reactivity by manually determining the changes made in the app? 
2. Furthermore, am I correct to notice that `unsafeSqlExpr` is only available as a substitute for where clauses, or should I be able to execute the `GROUP BY` and `HAVING` statements with this function?

**Comment by radex** [comment]
I don't think it's possible currently to express this query in Watermelon's query language - the count thing is the killer.

However, v0.23 prerelease has a feature you need to solve this cleanly: https://github.com/Nozbe/WatermelonDB/blob/master/CHANGELOG-Unreleased.md , https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Query.md#unsafe-sql-queries 

Essentially, you'll be able to express this as raw SQL but without sacrificing clean reactive ability. You're correct that `Q.unsafeSqlExpr` is only for the WHERE subexpressions.

**Comment by nmeibergen** [comment]
Awesome, you rock my world! The pre-release indeed seems to solve this issue. I'll try to work with that instead! Thank you.

**Comment by radex** [comment]
@nmeibergen Should be stable to use in production (we do)

**Comment by nmeibergen** [comment]
Great! It seems te work as expected. Thank you for this very nice framework! I closed the issue.
