### ISSUE TITLE
Android JSI, Sync Error: Failed To execute db update - sqlite error 1 (cannot rollback - no transaction is active)

### ISSUE THREAD

**Issue by Moh-Kassim** [Nozbe/WatermelonDB#1083]
After Enabling JSI On Android, Sync Function sometimes failed with error 
`Failed To execute db update - sqlite error 1 (cannot rollback - no transaction is active)`
and it never works again

**Comment by radex** [comment]
@Moh-Kassim Try upgrading to latest 0.23 pre-release (should be stable enough to use in production IMO) - see changelog-unreleased for upgrade details. I think this error should be fixed there

**Comment by Moh-Kassim** [comment]
> @Moh-Kassim Try upgrading to latest 0.23 pre-release (should be stable enough to use in production IMO) - see changelog-unreleased for upgrade details. I think this error should be fixed there

okay I will check and keep you updated

**Comment by Moh-Kassim** [comment]
@radex Thanks, we tested this for 2 days in production, and it's okay now
only once we got the error `Failed to get a row for query - sqlite error 11 (database disk image is malformed)`
but it never happened again, any suggestions about how could this happened?

**Comment by Moh-Kassim** [comment]
@radex this happened when opening database viewer from flipper, this error starts emitting on sync

**Comment by radex** [comment]
@Moh-Kassim try version `v0.23.1-0`, I think this should fix the image is malformed error
