### ISSUE TITLE
UUID Repeated

### ISSUE THREAD

**Issue by wisi-treinta** [Nozbe/WatermelonDB#1084]
Hi guys, I have an application with multiple sessions and devices. Sometimes when I use the synchronization of my local DB with the online DB, I see that the uuid was repeated and the documentation explain this shouldn't happen.

Do you think that I should to use other library to generate the uuid and ignore the uuid by watermelon?

Someone have the same error?

HELP ME!!

**Comment by radex** [comment]
>  I see that the uuid was repeated

Can you elaborate? You haven't explained how you reached the conclusion that WatermelonDB has independently generated the same random ID more than once, and I've never seen that happen

**Comment by radex** [comment]
@wisi-treinta so, what happened?
