### ISSUE TITLE
why Query result empty, but find result value

### ISSUE THREAD

**Issue by supermaverickws** [Nozbe/WatermelonDB#1095]
![image](https://user-images.githubusercontent.com/61172354/125499857-fe09cfb7-909d-4ff6-953d-16b80cb44398.png)

**Comment by acdcjunior** [comment]
You may have a run condition. Print `contextKey` before the first `const data = ...` statement (before line 95, if I'm not mistaken)

**Comment by supermaverickws** [comment]
![image](https://user-images.githubusercontent.com/61172354/125553170-8e72f902-9616-4034-9984-90bb6aad208b.png)
@acdcjunior

**Comment by supermaverickws** [comment]
I had done it as your way. but it's not good

**Comment by acdcjunior** [comment]
Have you tried querying without the `Q.where()`? To see if the object appears within the full result set?

Also, how's the mapping of the `context_key` in the model class?

**Comment by supermaverickws** [comment]
![image](https://user-images.githubusercontent.com/61172354/125554373-b9d1d462-3310-42fb-b347-204a9982d9d5.png)
![image](https://user-images.githubusercontent.com/61172354/125554454-644ed94a-a002-4e07-a7a3-d349608599d4.png)
@acdcjunior

**Comment by supermaverickws** [comment]
@acdcjunior do you know any other reason? have any config enable console the last sql  ?

**Comment by supermaverickws** [comment]
I have to give up to use it.

**Comment by acdcjunior** [comment]
Don't give up just yet. The name of the mapped column matters in the query and may differ from the one in the returned object.
Have you tried using `contextKey` instead?

**Comment by acdcjunior** [comment]
Also, if you post the actual mapping code can be of help for us to reproduce the problem

**Comment by supermaverickws** [comment]
@acdcjunior  Yes. You are right.  I changed contextKey, it works. 
 I finally change android sqlite location to sdcard. find that. thank your support
