### ISSUE TITLE
Close db connection after jest testing ends

### ISSUE THREAD

**Issue by AgusMaris** [Nozbe/WatermelonDB#1099]
Hi people im trying to do some integration/unit testing on the db using jest. In order to do it i had to mock the database adapter from SQLiteAdapter to LokiJsAdapter.

`jest.mock("./data/database");`

in my mocked database.js file:
`const adapter = new LokiJSAdapter({
  schema,
  useWebWorker: false,
  useIncrementalIndexedDB: true,
});`
`export default new Database({
  adapter,
  modelClasses: [
    Producto
  ],
  actionsEnabled: true
});`

It works but it seems that jest detects some leaks and from what i have seen it is because i didnt close the connection with the db correctly after all tests have passed, how can i close the connection once all my tests are done?

I get this output once all my tests have been executed
![image](https://user-images.githubusercontent.com/50555289/125707506-4bd86d96-7c2f-4b79-8ba1-a5dce9237195.png)

**Comment by radex** [comment]
I haven't encountered that. You need to run the --detectOpenHandles debug, and debug it yourself -- please share your findings, maybe very useful to others!

**Comment by AgusMaris** [comment]
> I haven't encountered that. You need to run the --detectOpenHandles debug, and debug it yourself -- please share your findings, maybe very useful to others!

Sorry, I´ve been busy these days and couldnt advance further with this. Now, i´ve tried only mocking the adapter for better separation and still works but the issue remains, the test process seems like it keeps running even though all test were completed succesfully.
Here is a screenshot of the output after `npx jest --detectOpenHandles`
![image](https://user-images.githubusercontent.com/50555289/126105348-1469272c-9c39-46b5-a865-3233121ae593.png)

So, nothing else changes from the output from what i can see and i dont know how and where to start debugging it. I will give some steps to reproduce this behaviour

1. Set-Up watermelonDB using the docs from 2.1 to 2.4 (using sqlite adapter and splitting adapter and db into separate files)
2.  Set-Up a test to create a record to a table
3. Create a new adapter file in `__mocks__ `inside the data folder and paste the code for the LokiJsAdapter
4. Mock the adapter with` jest.mock(<rootDir>/model/adapter)`
5. Run the test 

After trying using `--forceExit` i realised that if i used console.log() on any function called by a test that didnt pass, it wouldnt print it to the console, it would only do if i didnt force exit it

**Comment by kassy-hub** [comment]
Same here.
In my case, disable `autosave` in `LokiJSAdapter`'s constructor, and works well.

`autosave` option in LokiJS will add timer and not clear automatically.
ref: https://github.com/techfort/LokiJS/blob/189e103c9f19fc8e14a8cf17ccfe1469f8f78258/src/lokijs.js#L2901-L2937

**Comment by AgusMaris** [comment]
Will try tomorrow and update the issue with the results

Thanks for replying!

**Comment by AgusMaris** [comment]
Done, now I instance LokiJSAdapter with this options and works!

```
const adapter = new LokiJSAdapter({
  schema,
  useWebWorker: false,
  useIncrementalIndexedDB: true,
  extraLokiOptions:{
    autosave:false
  }
});
```
