### ISSUE TITLE
Link iOS module error

### ISSUE THREAD

**Issue by anhtuank7c** [Nozbe/WatermelonDB#110]
## Environment:
```
    System:
      OS: macOS 10.14
      CPU: x64 Intel(R) Core(TM) i7-4770HQ CPU @ 2.20GHz
      Memory: 396.60 MB / 16.00 GB
      Shell: 3.2.57 - /bin/bash
    Binaries:
      Node: 8.12.0 - ~/.nvm/versions/node/v8.12.0/bin/node
      Yarn: 1.10.1 - /usr/local/bin/yarn
      npm: 6.4.1 - ~/.nvm/versions/node/v8.12.0/bin/npm
      Watchman: 4.9.0 - /usr/local/bin/watchman
    SDKs:
      iOS SDK:
        Platforms: iOS 12.0, macOS 10.14, tvOS 12.0, watchOS 5.0
      Android SDK:
        Build Tools: 23.0.1, 23.0.2, 23.0.3, 25.0.0, 25.0.1, 25.0.2, 25.0.3, 26.0.0, 26.0.1, 26.0.2, 26.0.3, 27.0.0, 27.0.1, 27.0.2, 27.0.3, 28.0.1, 28.0.2, 28.0.3
        API Levels: 21, 23, 24, 25, 26, 27, 28
    IDEs:
      Android Studio: 3.1 AI-173.4907809
      Xcode: 10.0/10A255 - /usr/bin/xcodebuild
    npmPackages:
      react: 16.6.0-alpha.8af6728 => 16.6.0-alpha.8af6728 
      react-native: 0.57.3 => 0.57.3 
      @nozbe/watermelondb: ^0.6.2
```

## Error

<img width="733" alt="screen shot 2018-10-25 at 10 42 31 am" src="https://user-images.githubusercontent.com/3163410/47474797-f4205180-d842-11e8-8a0a-e8c7ad38c105.png">

**Comment by radex** [comment]
please read the install guide. you missed a step

https://github.com/Nozbe/WatermelonDB/blob/master/docs/Installation.md

**Comment by anhtuank7c** [comment]
@radex I already create a Bridging Header.  (Step 3)

**Comment by radex** [comment]
did you create an empty Swift file, and included it in the project?

**Comment by anhtuank7c** [comment]
@radex My big mistake is removed `Swift` file right away then.
Everything looks good now. Thank you.

**Comment by radex** [comment]
@anhtuank7c Do you think we could improve the Installation guide to make this more clear? You're not the first person who got tripped up by this step :) If so, please hit edit on the Installation.md file and send a quick PR

**Comment by thecookieorg** [comment]
Hey @radex 
I was keep getting the ** BUILD FAILED ** ":CFBundleIdentifier", Does Not Exist error. Solved by adding an empty Swift file. Docs are excellent, I'm excited to try the watermelon! :)
