### ISSUE TITLE
Xcode 12.4 Archive error

### ISSUE THREAD

**Issue by hoaphantn7604** [Nozbe/WatermelonDB#1101]
I can build release, but when I archive, I get this error.

<img width="709" alt="Screen Shot 2021-07-16 at 10 07 57" src="https://user-images.githubusercontent.com/50919571/125885755-162d351d-083d-4bec-a2ed-93c522397883.png">

**Comment by conext18** [comment]
I'm having the same problem, do you have a solution for this?
