### ISSUE TITLE
Module '"@nozbe/watermelondb/sync"' has no exported member 'hasUnsyncedChanges'

### ISSUE THREAD

**Issue by Salalf01** [Nozbe/WatermelonDB#1107]
Greetings. I'm trying to use this build in function but I get this error when is imported. Could i get information if i missed something to avoid this message? I imported like your docs says.
![Untitled](https://user-images.githubusercontent.com/31637622/126357313-dc368981-2856-43c5-b288-91c96e312565.png)

**Comment by KrisLau** [comment]
I have the same error for `hasUnsynchedChanges`, `synchronize`, and most WatermelonDB imports but it builds ok.

**Comment by KrisLau** [comment]
I have the same error for `synchronize`, and most WatermelonDB imports but it builds ok so I usually just ignore it. `hasUnsyncedChanges` is erroring out though. Did you ever figure it out?

**Comment by KrisLau** [comment]
Not sure if this will help you but for me I was just not using the hook correctly. The import still shows that error but it works when I run the app

**Comment by Salalf01** [comment]
Indeed. It works when the app runs, I just keep getting the same error.

**Comment by KrisLau** [comment]
@Salalf01 Don't forget to close this issue if your issue is resolved, thanks!
