### ISSUE TITLE
Select column crashes the app

### ISSUE THREAD

**Issue by RajeshRam** [Nozbe/WatermelonDB#1110]
When using  select column in unsafeFetchRecordsWithSQL() app crashes.
 Is it possible to fetch only column data in the watermelon db. I want to use the Distinct query.
Is there any solution available for this.

**Comment by radex** [comment]
use 0.23 pre-release version and read the changelog for details

**Comment by RajeshRam** [comment]
@radex 
The issue still there when i try to select data it crashes

My code  atatched below
```
const fetcheddata = await database.collections
			.get("TABLE_NAME")
			.query(
				Q.unsafeSqlQuery('select COLUMN_NAME from TABLE_NAME')
			).fetch()
```

**Comment by Jonovono** [comment]
@RajeshRam did you ever resolve this?

@radex i'm on latest and seeing this too, I've been through the docs and can't see what I am doing wrong.

example:

```
const enhance = withObservables(['sites'], ({}) => {
  const sites = database
    .get('sites')
    .query(Q.unsafeSqlQuery(`SELECT * FROM sites`))
    .observe();
  return {
    sites,
  };
});
```

**Comment by PEZO19** [comment]
For anyone bumping into that problem: `Q.unsafeSqlQuery` and `unsafeFetchRaw` together.

```js 
const rawResultSet = database
    .get('a_tableName')
    .query(Q.unsafeSqlQuery(`SELECT things FROM a_tableName`))
    .unsafeFetchRaw();
```

To make it that "raw" "observable" (automatically refetch on **relevant** change), we need to use `experimentalJoinTables` +- `experimentalNestedJoin` as mentioned [here](https://github.com/Nozbe/WatermelonDB/issues/1111#issuecomment-1076200138).

**Comment by arys** [comment]
@PEZO19, I don't understand, what we have to pass to `experimentalJoinTables`? we don't joining anything here

```
    const collection = getLocalDb().database.get<SessionTime>('session_times')
    return collection
      .query(
        Q.experimentalJoinTables([]),
        Q.unsafeSqlQuery('SELECT DISTINCT date(time) as time FROM session_times ORDER BY time ASC'),
      )
      .observe()
```

**Comment by PEZO19** [comment]
@arys Sorry, the mention is not clear to me. I did not say we need `experimentalJoinTables` above. I agree with you, you do not need it there.
