### ISSUE TITLE
How to experimentalJoinTables and experimentalNestedJoin for more 'involved' queries?

### ISSUE THREAD

**Issue by nmeibergen** [Nozbe/WatermelonDB#1111]
I have a data retrieval that looks as follows:

```
const query = `WITH 
x as (
    SELECT n.id
    FROM notes n
    INNER JOIN note_tags nt ON nt.note_id = n.id
    LEFT JOIN tags t ON nt.tag_id = t.id
    WHERE [some conditions]
    GROUP BY nt.note_id HAVING COUNT(nt.id) = [some value]
),
y as (
    SELECT t.*
    FROM tags t
    INNER JOIN note_tags nt on nt.tag_id = t.id
    WHERE nt.note_id IN x
    [some grouping and ordering]
),
z as (
    SELECT t.* 
    FROM tags t
    INNER JOIN note_tags nt on nt.tag_id = t.id 
    WHERE [some conditions based on y]
    [some grouping and ordering]
)

SELECT * 
FROM
( 
    SELECT *, 1 AS filter
    FROM  y
    UNION ALL
    SELECT *, 2 AS filter
    FROM z
)
ORDER BY filter`

return database.collections.get('tags').query(
Q.experimentalJoinTables([...]),
Q.experimentalNestedJoin([...]),
Q.unsafeSqlQuery(query)
)
```

The result should be observed. To do so we should use `experimentalJoinTables` and `experimentalNestedJoin`. However it is now not very clear what the `experimentalJoinTables` and `experimentalNestedJoin` require from me:
1. In `y` and `z` we retrieve from tags and join on note_tags 
As the collection is on `tags` I presume here that `experimentalJoinTables(['note_tags']) is sufficient. Can you confirm?
2. In `x` we retrieve from notes and inner join on note_tags and nest join on tags. 
How do we include the correct `experimentalJoinTables` here? For it seems to imply that the 'base' table is `tags` even though we are actually retrieving from `notes`.

**Comment by KrisLau** [comment]
@nmeibergen Did you ever figure it out? I'm currently trying to figure out how to join 4 tables

**Comment by radex** [comment]
Yes, the `experimentalJoinTables and experimentalNestedJoin` APIs are confusing and need to be improved.

I believe the difference is only important for encoding SQL from JS-defined queries (Q.on) - otherwise it wouldn't be clear how to join tables. Since you're defining a query by SQL, you only need these join tables declarations for observation.

ergo, you can just do `Q.experimentalJoinTables('note_tags', 'notes')`
