### ISSUE TITLE
[SYNC] Sync behavior after a long time offline

### ISSUE THREAD

**Issue by davidmartos96** [Nozbe/WatermelonDB#1114]
Hello! We are looking into Watermelon for syncing functionality and we are unsure about a certain use case.

Imagine 2 devices (D1, D2):
1. D1 is offline and updates column A of row with ID 1
2. D2 updates the same column but with a different value
3. D2 syncs
4. D1 starts sync and has a conflict with column A, and, since it's a local change, it keeps the original updated value, even though this happened before. 

Is this a expected behavior in the sync algorithm?
Wouldn't this mean that you lose the most recent changes? What if D1 hasn't synced for a long time? The user may not be aware of the old changes that are now obsolete.

We are still trying to grasp the library, any feedback would be appreciated.
Thanks!

**Comment by radex** [comment]
yes, this is the expected behavior - locally changed columns win the conflict.

**Comment by davidmartos96** [comment]
Thanks @radex ! From your experience, do you think it would make sense to use a hybrid approach (clientwins-serverwins)? When a long time has passed since the last sync, use a custom conflict resolver with "server wins", else use WatermelongDB default "client wins". That way obsolete client changes are not prioritized. Or even turn it into a user's decision via UI.

**Comment by radex** [comment]
@davidmartos96 I would not recommend that. Synchronization is a very difficult problem, and when conflicts arise, by definition, there is no perfect way of automatically resolving that. It's possible to implement server-wins conflict resolution, but you are likely to find that doing this haphazardly causes more problems than it solves. Having said that, dig into the docs and code - you'll see that there is a hook where you can override default conflict resolver

**Comment by tom-at-pixel** [comment]
_Meta/off-topic: @radex I'm looking through open issues to see if I should be concerned about anything, and it seems like half the issues (like this one) are resolved or stale, yet they are not marked as "closed". Is the issue bot disabled on this repo?_

**Comment by radex** [comment]
Seems like maybe the bot broke?
