### ISSUE TITLE
Retrieving a calculated value in an observable unsafeSqlQuery query

### ISSUE THREAD

**Issue by nmeibergen** [Nozbe/WatermelonDB#1115]
Suppose a somewhat involved query that requires to be retrieved by means of the `unsafeSqlQuery`, say

```
const query = `SELECT t1.*, COUNT([something]) as count
FROM table1 t1,
INNER JOIN table2 t2 on t1.id = t2.id
WHERE [conditions]
GROUP BY t.id
HAVING [conditions]`

database.collections.get('table1').query(
   Q.unsafeSqlQuery(query)
)
```

This query is observed by means of `withObservables` and will neatly return the records required from t1 as expected. However we will not be able to access the `count`, for we will only get the properties that are defined in the schema which `count` is not, it is calculated. I expected it to be located in the model object property `_raw` but that seems to reflect the exact data stored in the db for each item retrieved based on `id`.

Is there some obvious way in which we can access the 'raw' database results in addition to the properties defined for the model in the schema, such that `count` becomes available? 
If there is not and it is sensible to have this functionality I'd be happy to look into how the result might be extended as such.

**Comment by radex** [comment]
@nmeibergen check out 🍉 0.23 and `.unsafeFetchRaw()` on Query. This will allow you to retrieve arbitrary columns from a query… however, you will *not* get a proper javascript instance of your Model. it's an either/or situation. However, it should be doable to have both - I encourage you to look into the code and propose a detailed design for a solution (if it requires changes in 🍉 at all)

**Comment by nmeibergen** [comment]
@radex The usafe of `unsafeFetchRaw` will indeed allow me to retrieve the required data, but I was under the impression that the resulting query cannot be observable, correct? In this particular case I am looking for observability as well. Is `unsafeFetchRaw` still suitable?

**Comment by radex** [comment]
In principle, it could be observable, however, no such functionality is hooked up. This observation strategy would be suitable: https://github.com/Nozbe/WatermelonDB/blob/master/src/observation/subscribeToQueryReloading/index.js -- but it's not generic, calls "normal" fetch. You could improve this situation.

**Comment by PEZO19** [comment]
@radex Regarding https://github.com/Nozbe/WatermelonDB/issues/1115#issuecomment-886520807:

May I ask if this is still the proposed solution in case of "raw sql" (like sum) + "observe"? May I ask how do you solve such an issue at Nozbe?
