### ISSUE TITLE
Support like and notLike operator

### ISSUE THREAD

**Issue by ieschalier** [Nozbe/WatermelonDB#112]
What do you think about add **like** and **notLike** operator to query ?

It could be a good optimization for applications with search feature in large amount of data.

## Proposal

```js
commentCollection.query(
  Q.where('label', Q.like('a%')),
)
```

**Comment by radex** [comment]
this should be possible, not super difficult, but not trivial either. If someone wants to implement this, I can give guidance as for where to start

**Comment by ieschalier** [comment]
I'm ok to implement it. Can you give me some advice ?

**Comment by radex** [comment]
Sure, you need these parts:

- QueryDescription/index.js is where operators are defined
- adapters/sqlite/encodeQuery is where the query is converted to SQL (react native)
- adapters/lokijs/encodeQuery is the same but for LokiJS (web)
- observation/encodeMatcher is where the query is encoded into a **matcher function**, which can tell whether a `Model` object matches a query or not. This is necessary for observing queries. More details here: https://github.com/Nozbe/WatermelonDB/issues/15#issuecomment-419713849
- Tests! The first three items have low-level unit tests to see if the right output is generated from the query language
- … and then there's the integration test in `__tests__/databaseTests` that checks every single operator on every supported database to see if it actually works

**Comment by ieschalier** [comment]
@radex My first PR to WatermelonDB has been sent 🙂. I'm waiting for your feedback

**Comment by sonikro** [comment]
Hello, great work guys.

While this is not approved yet, is there any alternative way of doing a LIKE query ? I really need this feature to implement a filter by Customer Name in my App.

Thanks.

**Comment by radex** [comment]
@sonikro if it needs to be a fuzzy search… no good solution comes to mind, sorry. I suggest you temporarily use the Watermelon fork @ieschalier has. His PR is almost ready, should work fine — but might take a week or two until it's realeased

**Comment by sonikro** [comment]
Thanks @radex , that's exactly what Im doing right now.

**Comment by radex** [comment]
merged and shipped. cc @sonikro
