### ISSUE TITLE
Question: How to track database updates?

### ISSUE THREAD

**Issue by thecoorum** [Nozbe/WatermelonDB#1127]
I'm rendering elements from the database in view that don't have any dynamic props to track in `withObservables`, so how can I track/render new values in the database?

**The case I'm trying to solve:**
I have a "Home" screen where view with the database data mounted, on another screen I'm creating a new record in the database and then navigating to the "Home" screen again and can't see a new record. How I can solve it?

As I understood, if I'm passing an empty array to `withObservables` it will not track the changes, am I right?

**Comment by radex** [comment]
you need to observe a query using withObservables, deps array is irrelevant here — I don't understand what is unclear to you, you need to show your code

**Comment by thecoorum** [comment]
@radex, I resolved the issue by doing `.query().fetch()` when finishing the database update, so now everything renders correctly for me. Thanks for the reply!
