### ISSUE TITLE
Is the id too short?

### ISSUE THREAD

**Issue by mk1020** [Nozbe/WatermelonDB#1128]
Hello everyone. My IDs are of this type: "k7u43vmmc68a2cqs". Is this how it should be? The feeling that it is short, to ensure uniqueness..

**Comment by radex** [comment]
please read the documentation https://nozbe.github.io/WatermelonDB/Advanced/Sync.html#local-vs-remote-ids

**Comment by haifahrul** [comment]
Hi,

this link https://nozbe.github.io/WatermelonDB/Advanced/Sync.html#local-vs-remote-ids is broken.

Is the id unique each device?
