### ISSUE TITLE
Add typescript documentation

### ISSUE THREAD

**Issue by TheRafaelFarias** [Nozbe/WatermelonDB#1151]
Hey guys, I'm using watermelon on a Typescript project, and although I'm getting to use it's really hard without documentation and I'm sure isn't only me, since Typescript is used on many projects

**Comment by woohoou** [comment]
Please !!

**Comment by hamzaawais96** [comment]
Any update on this?

**Comment by CallumFerguson** [comment]
please

**Comment by przbadu** [comment]
https://github.com/Nozbe/WatermelonDB/tree/master/examples/typescript

This is the only example with typescript support I can see.

**Comment by przbadu** [comment]
also checkout this demo app

https://github.com/przbadu/TodoApp

**Comment by radex** [comment]
This would be super nice, closing this to move discussion to https://github.com/Nozbe/WatermelonDB/issues/1516
