### ISSUE TITLE
Clarification on the Relations doc & some other questions

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1158]
In the [docs](https://nozbe.github.io/WatermelonDB/Relation.html?highlight=immutable#defining-relations), it explains the two arguments of the relation and immutable relation
> The first argument is the table name of the related record, and the second is the column name with an ID for the related record.

But it doesn't explain what the thing that comes after the relation is?
> @immutableRelation('posts', 'post_id') **post**

**Comment by radex** [comment]
that's an arbitrary name of a class property. you pick whatever you want

**Comment by KrisLau** [comment]
@radex  Ohh ok thank you for the swift reply, closing this issue! Would you also be able to help me with #1153 ?

**Comment by KrisLau** [comment]
@radex  Ohh ok thank you for the swift reply, closing this issue! Would you also be able to help me with #1153 ?
