### ISSUE TITLE
TypeError: undefined is not an object (evaluating 'value.observe')

### ISSUE THREAD

**Issue by elsyslab-ark** [Nozbe/WatermelonDB#1159]
I was trying to connect my user model to react component, but throwing an error .please let me know if I have missed anything since it is my first to set up this. attaching component below

import React from 'react';
import {View, StyleSheet} from 'react-native';
import CustomTextInput from '../../Common/CustomTextInput';
import withObservables from '@nozbe/with-observables';

const Login = () => {
  React.useEffect(() => {
    didMount();
  }, []);
  const didMount = async () => {};
  return (
    <View style={styles.container}>
      <CustomTextInput />
    </View>
  );
};

const enhance = withObservables(['user'], ({user}) => ({
  user,
}));
const EnhancedComment = enhance(Login);
export default EnhancedComment;

const styles = StyleSheet.create({
  container: {
    flex: 1,
  },
});

**Comment by KrisLau** [comment]
I'm having a similar problem. Did you ever find a solution?

**Comment by elsyslab-ark** [comment]
> I'm having a similar problem. Did you ever find a solution?

Nope. I was able to use their Example project and it works fine. But whenever I'm trying to do it from scratch running into issues

**Comment by Acetyld** [comment]
Same, can we get a answer on this asap? @radex

**Comment by KrisLau** [comment]
if you change the `{user}` to `{database}` so it looks like this:
```
const enhance = withObservables([], ({database}) => ({
user: database.get('user').query().observe(),
}));
```
It should work but yeah I'm not sure why

**Comment by Acetyld** [comment]
So if we take a look at the documentation @nozbetravis provided (i quess) you can see it tells ur to pass blogs as blogs=blogs. But what is comment?  Does this bassicly mean we have to do blogs={database.get('blogs').query()}?
Or is it better to use withDatabase and then":

export default compose(
  withDatabase,
  withObservables([], ({ database }) => ({
    blogs: database.get('blogs').query(),
  }),
)(BlogList)

**Tbh i find the whole documentation kinda "fady?". I switched 1,5 year ago only functional components. And stopped using hoc, but this projects looks so good i wouldt mind to use it. But it seems so wonky. And there are not that much examples. The only exampel is passing the stuff through navigation wich is a no go for me.**

`import withObservables from '@nozbe/with-observables'
const enhance = withObservables(['comment'], ({ comment }) => ({
  comment // shortcut syntax for `comment: comment.observe()`
}))
const EnhancedComment = enhance(Comment)
export default EnhancedComment

`
_Now, if we render <EnhancedComment comment={comment} />, it will update every time the comment changes._

**Comment by Acetyld** [comment]
Also i just noticed:
```
export default compose(
    withDatabase,
    withObservables(['blog'], ({database}) => ({
            blog: database.get('blog').query(),
        }),
    ),
)(WaterMelonDB);
```
WaterMelonDB.js

```
       <DatabaseProvider database={database}>
                                    <App/>
                                </DatabaseProvider>
                                ```
                                Main.js
                                
                                This doenst work either

**Comment by KrisLau** [comment]
Yup I use `withDatabase` and `compose`. Also in your code:
```
export default compose(
    withDatabase,
    withObservables(['blog'], ({database}) => ({
            blog: database.get('blog').query(),
        }),
    ),
)(WaterMelonDB);
```
you missed out the `.observe()`. It should be:
```
export default compose(
    withDatabase,
    withObservables(['blog'], ({database}) => ({
            blog: database.get('blog').query().observe(),
        }),
    ),
)(WaterMelonDB);
```

**Comment by Acetyld** [comment]
Yhea didint change anything sadly, atm working on realm again.
