### ISSUE TITLE
Performance efficient SUM operation

### ISSUE THREAD

**Issue by przbadu** [Nozbe/WatermelonDB#1161]
I used raw unsafeSqlQuery for this. Raw sql used in unsafesqlquery is returning expected result in query browser, but it is returning empty [] with watermelon query builder:

```
  records
    .query(
      Q.unsafeSqlQuery(
        'select transaction_type, SUM(amount) as sum from transactions' +
          ' group by transaction_type',
      ),
    )
    .observe();
```

but In same query if I use `select * from table_name group by kind` then it is returning grouped result. Does watermelondb supports selecting individual columns and `SUM` function?

> NOTE: also note that, I found https://github.com/Nozbe/WatermelonDB/issues/910 thread, but I am not sure if that is efficient way of doing it. Also I have many situation where I want to select other columns like formated date column and all, so it would be great if we can select virtual columns that are not in schema.

**screenshot of android studio App Inspection tool**

![Screenshot_2](https://user-images.githubusercontent.com/4189129/132625018-5e1601ff-e0e8-4110-a215-3c65ce544bde.png)

**Comment by radex** [comment]
>  Does watermelondb supports selecting individual columns and SUM function?

Yes and no. You can do an unsafeSqlQuery, as you did, and then run `.unsafeFetchRaw()` on the Query - in that case you can have arbitrary columns returned in the query. When using normal fetch/observe, the query must return exactly all columns of a table, no more, no less - otherwise, it's just not possible to construct a class instance of your model.

**Comment by przbadu** [comment]
Thank you @radex  for your response, I think I got your point, will try that soon.

**Comment by przbadu** [comment]
Thanks @radex It worked, and I was facing issue observing the `.unsafeFetchRaw()` queries, which is giving error to me, but I found https://github.com/Nozbe/WatermelonDB/issues/1115 issue which mentioned exact same problem that I have. So I will do further digging.

Thanks for this wonderful library :)
