### ISSUE TITLE
How to query deleted IDs?

### ISSUE THREAD

**Issue by arcln** [Nozbe/WatermelonDB#1164]
I saw that when calling `markAsDeleted()`, the IDs of deleted documents are kept. How can I query the list of thoose IDs? I need them to handle a complex sync scenario. Thanks.

**Comment by Hannes1** [comment]
Don't know if this would help but, I currently handle the sync like this:

```javascript
    pushChanges: async ({ changes, lastPulledAt }) => {
      const syncTimestamp = new Date().getTime();
      // Map through tables in changes object from pull.
      await Promise.all(
        map(changes, async (row, table) => {
          const tableObj = syncObj[table];

          // Map through created, deleted and updated in each table in changes object from pull.
          await Promise.all(
            map(row, async (arrayOfChanged, changeName) => {
              const isDelete = changeName === 'deleted';

              // Map through each change in created, deleted and updated respectively.
              await Promise.all(
                map(arrayOfChanged, async doc => {
                  const itemValue = isDelete ? null : (doc.valueOf() as any);
                  const itemId = isDelete
                    ? doc.toString()
                    : itemValue[tableObj.idName];
                  const itemData = isDelete ? null : omit(itemValue, ommited);
```

Note: So I only get the id's from newly deleted items since last push/pull

**Comment by arcln** [comment]
Thanks but this doesn't help. I want to implement an idempotent sync with a server I don't control (Google Drive). My probem is during pull. There is a file on server that is not on the device. This file could either be :

- Created remotely since last sync by another device
- Deleted locally since last sync (and not pushed yet, because pull occurs before push)

The current behaviour is that the file is marked as created by my implementation, and the sync fails because the document "exists locally but is marked as deleted".

I would like to query the database with the document ID and find out if its known to be deleted.

**Comment by Hannes1** [comment]
There seems to be getDeletedRecords on the adapter maybe this could help...


![Screenshot_20210915-164601_Samsung Internet](https://user-images.githubusercontent.com/39419636/133455704-1087c43c-1720-432d-96a5-502fa419c63c.jpg)

**Comment by arcln** [comment]
That's exactly what I was looking for. Closing as resolved by using `database.adapter.getDeletedRecords()`.
