### ISSUE TITLE
withObservables with await

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1172]
A user can have multiple teams so I'm storing the `teamID` using AsyncStorage but since getting items from AsyncStorage is asynchronous, I'm struggling to figure out how to connect the components with `withObservables` and the `teamID`. Currently I'm using `useEffect` to mimic `withObservables` but it's not as reactive. Any suggestions?

**Comment by radex** [comment]
https://rxjs-dev.firebaseapp.com/api/index/function/from

**Comment by KrisLau** [comment]
@radex I'm sorry for the slew of questions but I don't think I quite understood that document? How would I go about hooking up the `from` with `withObservables`? Would it just be like this:
```
```

**Comment by KrisLau** [comment]
@radex I've tried reading a number of other tutorials on the RxJS from but no matter what I try I keep getting an error: 
![image](https://user-images.githubusercontent.com/46275463/135125224-31428efe-3207-43b0-a035-1bf5d2a728ee.png)

**Comment by KrisLau** [comment]
If anyone can shed a light as to where I'm messing up on using the `from` operator please let me know, it would be much appreciated!

**Comment by KrisLau** [comment]
I moved my data to a HOC and used `fromRenderProps`: https://github.com/ReactiveX/rxjs/discussions/6967#discussioncomment-2865250
