### ISSUE TITLE
Multi-company is compatible

### ISSUE THREAD

**Issue by osvaldokalvaitir** [Nozbe/WatermelonDB#1181]
Hi, my database is a multi-company! In almost all my tables I have a company_id field telling me which company this record is.

In the example of a user logged in with company 1, changes to company 2, when synchronizing it will send data from both companies, would there be a way to filter for each table how to do this synchronization? 

Filtering for example only data from company 1, or only data from company 2 or even a select?

**Comment by radex** [comment]
> would there be a way to filter for each table how to do this synchronization?

no. you'd have to make some changes to the synchronization code to achieve that.

are you sure what you're doing is the right approach? If you're synchronizing "companies" separately… do you also show the data completely separately? If so, you could consider using multiple independent `Database` instances

**Comment by osvaldokalvaitir** [comment]
So, currently the companies are in the same database and are updated together, there is no division. But I liked the idea of ​​making multiple database instances. Do you have any examples I could follow to do? Instance creation and recovery?

**Comment by radex** [comment]
> Do you have any examples I could follow to do?

It's as simple as creating more `Database` instances, there's no magic

**Comment by osvaldokalvaitir** [comment]
> > Do you have any examples I could follow to do?
> 
> It's as simple as creating more `Database` instances, there's no magic

Right, thanks!! I'm seeing some issues here and I'll see what I do!!
