### ISSUE TITLE
Retrieving column value after querying returning strange result

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1187]
I've managed to get my relations to work correctly but for some reason now after querying, I can't access the columns other than the ID. For example, I would do a query like this:
```
let teamMembers = await database
    .get('team_member')
    .query(
      Q.where('team_id', currentTeam.teamID),
      Q.where('team_season_id', currentTeam.teamSeasonID),
      Q.on('member_role', 'role_id', Q.oneOf(roles)),
    );
```

Then I would try to access a column:
`teamMembers[0].profileID`

What I would expect is for it to just return the column's value but I'm getting:

> {"_columnName": "profile_id", "_isImmutable": false, "_model": {"__changes": {"_isScalar": false, "_value": [Circular], "closed": false, "hasError": false, "isStopped": false, "observers": [Array], "thrownError": null}, "_isEditing": false, "_preparedState": null, "_raw": {"_changed": "", "_status": "created", "id": "57c8a71b-393c-401d-886d-d0143cdee177", "profile_id": "d13c3844-e905-4612-b01b-47b2a4fd1980", "team_id": "d2388fd6-ba35-4c2b-99d8-3ed293579356", "team_season_id": "bf604102-f2de-45d5-a990-2df1c10ad2a6"}, "_relationCache": {"profileID": [Circular], "teamID": [Relation], "teamSeasonID": [Relation]}, "_subscribers": [], "collection": {"_cache": [RecordCache], "_subscribers": [Array], "changes": [Subject], "database": [Database], "modelClass": [Function TeamMember]}}, "_relationTableName": "profile"}

I've tried adding a `.fetch()` to the end of the query but it doesn't seem to change anything

**Comment by KrisLau** [comment]
@radex @rozPierog ?

**Comment by Stophface** [comment]
@KrisLau Hey, 
me again ;) It seems like we are running into the same challenges. I am struggeling with relations too. In one of my models `country` I want to make a relation to anther table, `continent`. Each country can only have one associated continent.

```
import { Model } from '@nozbe/watermelondb';
import { field, immutableRelation } from '@nozbe/watermelondb/decorators';
import { COUNTRY_TABLE } from 'constants/database';

export class Country extends Model {
    static table = COUNTRY_TABLE;

    @field('name')
    name;

...

    @immutableRelation('continent', 'continent_id') 
    continent;
}

```

Is that correct?
I am trying to read the joined data like this

```
const countries = await database.get(COUNTRY_TABLE).query().fetch();
const joinedData = await countries[0].continent.fetch();
```

but this gives me

> Error: Invalid record ID continent#1

Any ideas what might be the problem?

**Comment by Stophface** [comment]
@KrisLau it seems we are running into the same challenges... Might you be able to help me with this: 
https://github.com/Nozbe/WatermelonDB/issues/1353

**Comment by pixelsomatic** [comment]
I'm getting the same kind of result, the data that I want is coming inside the "_raw" object as well

**Comment by KrisLau** [comment]
Mine was just that `profileID` was a relation so to access it I just needed to use `profileID.id`
