### ISSUE TITLE
WithObservables not reacting on create but does on delete

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1191]
When I create a new team, the list does not update but when I delete it reacts immediately. The query reacts when I just do a black query but if I do the `Q.on` query. it doesn't react

**Comment by rohankm** [comment]
This is happening with me also! it does not reactive on updates!

btw how did u solve this?

**Comment by KrisLau** [comment]
@rohankm you have to observe the dependent tables that you are doing a `Q.on` on. Basically if you have a table like `class_student`  and `students` you would have to observe both if you are depending on `class_student` records. Also for updates, you need to use `observeWithColumns`: https://nozbe.github.io/WatermelonDB/Components.html#advanced-observing-sorted-lists
