### ISSUE TITLE
Sync pull changes server side win implementation

### ISSUE THREAD

**Issue by nctin470** [Nozbe/WatermelonDB#1200]
I realized that pull changes in synchronize adopt a per-column client-side win strategy when in conflict, how would it be possible if I want to the record to completely take the server side version without using any locally changed fields since last pull. 
(e.g.)
- both server and client has record 'A'. 
- Server changes record A, attribute _name_ to "name1'
- Client changes record A, attribute _name_ to "name 2"
- When synced, both server and client's record A has _name_ as "name 1"

would clearing the _status and _changed field pertaining to the _raw fields allow complete server version replacement?

**Comment by nctin470** [comment]
As per thread in https://github.com/Nozbe/WatermelonDB/issues/1114#issuecomment-887330205. Resolved by using the conflict resolver. 

Side Note: I noticed that synchronize in typescript index file in watermelondb/sync doesn't have conflict resolver as argument. Is there a particular reason why?

**Comment by radex** [comment]
> Side Note: I noticed that synchronize in typescript index file in watermelondb/sync doesn't have conflict resolver as argument. Is there a particular reason why?

Send a PR to fix the typescript typings.
