### ISSUE TITLE
xcode build failed

### ISSUE THREAD

**Issue by Hamidrezana** [Nozbe/WatermelonDB#1202]
I followed installation in doc, but I get following error when running on iOS:

```
Undefined symbols for architecture arm64:
  "type metadata for Swift.StaticString", referenced from:
      WatermelonDB.StringError.init(_: Swift.String, function: Swift.StaticString, file: Swift.StaticString
```

**Comment by KrisLau** [comment]
I'm not sure but there are some suggestions here:
https://stackoverflow.com/questions/64226884/undefined-symbols-for-architecture-arm64-xcode-12

Before doing any of those, I would clean the project in XCode, do a `pod install`, and validate any project settings under build time errors.

**Comment by Hamidrezana** [comment]
I have fixed it by updating swift packages

**Comment by Axort** [comment]
> I have fixed it by updating swift packages

Hey @Hamidrezana did you do a `pod update`? Or what packages do you mean?
