### ISSUE TITLE
TS2339: Property 'localStorage' does not exist on type 'Database'

### ISSUE THREAD

**Issue by mikemikhaylov** [Nozbe/WatermelonDB#1218]
Hi,
Property localStorage seems to be missing on Database [TS declaration](https://github.com/Nozbe/WatermelonDB/blob/master/src/Database/index.d.ts) 
Code like this 
`const userId = await database.localStorage.get("user_id")`
gives an error 

> TS2339: Property 'localStorage' does not exist on type 'Database'

If we change code to `const userId = await (database as any).localStorage.get("user_id")`
Everything works as expected.

@nozbe/watermelondb version is 0.24.0

**Comment by sonivaibhav27** [comment]
I think it is slightly changes of accessing the localstorage
you can use like
`const data = await database.adapter.getLocal("user_id")`

**Comment by mikemikhaylov** [comment]
> I think WatermenlonDB has slightly changed of accessing the localstorage you can use like `const data = await database.adapter.getLocal("user_id")`

@radex can you please confirm or deny that?

**Comment by radex** [comment]
database.adapter.getLocal is the old API, now considered an internal detail, you should be using database.localStorage.get
