### ISSUE TITLE
Returning Null when using relation.

### ISSUE THREAD

**Issue by sonivaibhav27** [Nozbe/WatermelonDB#1225]
Hi , I have a table where all categories are saved and i have another table of Bill and having a Category_ID of categories .
But when i access the category from Bill object , it is returning Null.

Bills.ts
```
export default class BudgetBill extends Model {
  static table = DatabaseConfig.tables.BudgetBills;
  @field('Type') billType!: number;
  @field('Amount') billAmount!: number;
  @field('Remark') billRemark!: string;
  @date('Date_at') billDate!: Date;
  @field('DateAsYearAndMonth') monthAndYearOfBill!: number;
  @relation(DatabaseConfig.tables.Categories, 'Category_Id')
  Category!: CategoryType;
}

```

Categories.ts
```
class Categories extends Model {
  static table = DatabaseConfig.tables.Categories;
  @field('Category_Id') CategoryId!: string;
  @field('Category_Name') CategoryName!: string;
  @field('IsDeleted') IsDeleted!: number;
  @field('ColorCode') CategoryColorCode!: string;
  @field('Category_Type') CategoryType!: number;
}
export default Categories;
```

Accessing it :
```
onst sanitizeOutputBills: DetailBillType[] = bills?.map(bill => {
      return {
        typeOfBill: bill.billType === 1 ? 'income' : 'expense',
        billAmount: bill.billAmount!,
        category: bill.Category,
      };
    });
    const a = await bills[0].Category.fetch();
```

**Comment by awgv** [comment]
Hello, @sonivaibhav27. I think you might be forgetting to set up [associations](https://nozbe.github.io/WatermelonDB/Model.html#children-to-many-relation-fields) on your tables. I don’t do TypeScript, but it should—hopefully—be something like that in JS:
```JS
// Bills.
static associations = {
  [DatabaseConfig.tables.Categories]: { type: 'belongs_to', key: 'Category_Id' },
}

// Categories.
static associations = {
  [DatabaseConfig.tables.BudgetBills]: { type: 'has_many', foreignKey: 'Category_Id' },
}

@children(DatabaseConfig.tables.BudgetBills) BudgetBills // Or whatever the property’s name will be.
```
Also, I noticed your categories have the `Category_Id` field—if I’m not missing anything, I don’t think that WatermelonDB supports one-to-many on the same table (#885), so you’ll have to manage the relationship manually for now.

**Comment by sonivaibhav27** [comment]
HI @awgv Thank you for the response.
I want to achieve something like this in the link below, kindly look at it .Can you suggest how to achieve this.?

https://docs.google.com/document/d/1Pc-BRws88FO7mh44ntt30whhno0_d9mJCc5Dr4mdGDs/edit?usp=sharing

**Comment by awgv** [comment]
If I understood you correctly, from a brief look, your models plus the associations that I posted should work, what doesn’t work exactly?

**Comment by sonivaibhav27** [comment]
Thank you so much for taking out time for my queries.😇
what about querying? I have PieChart that will show label as Category and Total Amount associated with that category? 
I want all category and its associated bills, how can i achieve this? since i can't make a individual record to each category to get associated bills.

**Comment by awgv** [comment]
Frankly, there’s just too little information to give a proper advice, especially in terms of performance, because there’re lots of variables at play—your target environment, for one. Just follow the documentation to make something that works, then go from there. But just so you know, if you’re tying to avoid the `N+1` problem, WatermelonDB doesn’t have “eager loading” (#763), but then again, if you only need to get the total amount of bills for each category, there’re [methods](https://nozbe.github.io/WatermelonDB/Query.html?highlight=fetchcount#executing-queries) specifically for that: `observeCount()`/`fetchCount()`.

**Comment by sonivaibhav27** [comment]
Thank you @awgv . I did the following for accessing all bills
```
...
 const erecord = await database.get('Category').query().fetch();
    const arecord = await Promise.all(
      erecord.map(async record => await record.Bills),
    );
    const flat = arecord.flat(2);
    console.log({flat});
 ...
```
