### ISSUE TITLE
Sync error handling

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1226]
Are there any good examples of error handling for sync in both the frontend and backend that I can reference? I'm having trouble with the `pullChanges` & `pushChanges` changing records to synced even though some records failed to be pushed or pulled.

EDIT: I added try catch to throw 503 error if any error occurs and it works but something about it feels off

**Comment by Skullcan** [comment]
If you follow the implementation of the backend suggested in the docs correctly you shouldn't have problems with 'failed records'.

What do you mean by failed to be pushed or pulled?

**Comment by KrisLau** [comment]
Thanks for taking the time to help! 

So the main problem is after a change is made, it'll pullChanges, pushChanges, then attempts to pullChanges again so that results in a bunch of: `[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will update existing record instead.]`

Not sure if I'm supposed to use the timestamps for `created_at` or `updated_at` from the client in the server (as opposed to the server auto creating/updating their own timestamps). Or am I supposed to use `sendCreatedAsUpdated: true`?

**Comment by KrisLau** [comment]
@Skullcan Thanks for taking the time to help! 

So the main problem is after a change is made, it'll pullChanges, pushChanges, then attempts to pullChanges again so that results in a bunch of: `[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will update existing record instead.]`

Not sure if I'm supposed to use the timestamps for `created_at` or `updated_at` from the client in the server (as opposed to the server auto creating/updating their own timestamps). Or am I supposed to use `sendCreatedAsUpdated: true`?

**Comment by Skullcan** [comment]
> * So the main problem is after a change is made, it'll pullChanges, pushChanges, then attempts to pullChanges again so that results in a bunch of: `[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will update existing record instead.]`
>   Not sure if I'm supposed to use the timestamps for `created_at` or `updated_at` from the client in the server (as opposed to the server auto creating/updating their own timestamps). Or am I supposed to use `sendCreatedAsUpdated: true`?
> * Sometimes when I make changes pullChanges is called by itself without pushChanges being called somehow?

I used the fields individually and have no problem at all. But I always trust the server with the timestamps since I have data shared between users. And I don't use sendCreatedAsUpdated parameter.
I suggest you check the [Docs](https://nozbe.github.io/WatermelonDB/Advanced/Sync.html#implementing-your-sync-backend) about how to implement the pull endpoint. Your need can be different than mine.

One problem I had in my implementation tho was that the changes in pullChanges were triggering another withChangeForTables and thus calling for another Sync(). Make sure that only the local changes trigger the Sync() method. That solved all the problems with consecutive/inconsistent Syncs for me.


> * ~`debounceTime` doesn't seem to be working suddenly cause the sync is being called like 10 times~ Working now but for some reason even with no changes this one reappears sometimes

Debounce is weird because of the nature of async calls and racing conditions. What function are you using to debounce the call?
I had a lot of problems and fixed then using the debounce() from lodash like this:
```
next: () => {
  const syncing = debounce(() => syncDatabase(),200);
  syncing();
}
```

**Comment by KrisLau** [comment]
Apologies in advance, a lot of probably dumb questions haha

> I used the fields individually and have no problem at all. But I always trust the server with the timestamps since I have data shared between users. And I don't use sendCreatedAsUpdated parameter. I suggest you check the [Docs](https://nozbe.github.io/WatermelonDB/Advanced/Sync.html#implementing-your-sync-backend) about how to implement the pull endpoint. Your need can be different than mine.
> 
So your server timestamps are different from the WatermelonDB timestamps and it works fine? Also what do you mean by trust the server timestamp? I return `Date.now()` from my pullChanges endpoint on the server as the `last`. Is that what you mean by trusting the server timestamp?


> One problem I had in my implementation tho was that the changes in pullChanges were triggering another withChangeForTables and thus calling for another Sync(). Make sure that only the local changes trigger the Sync() method. That solved all the problems with consecutive/inconsistent Syncs for me.
> 
How do you check for this? I think this is probably what is causing `Diagnostic error: [Sync] Concurrent synchronization is not allowed. More than one synchronize() call was running at the same time, and the later one was aborted before committing results to local database` even though I check whether or not the promise is resolved


> Debounce is weird because of the nature of async calls and racing conditions. What function are you using to debounce the call? I had a lot of problems and fixed then using the debounce() from lodash like this:
> 
> ```
> next: () => {
>   const syncing = debounce(() => syncDatabase(),200);
>   syncing();
> }
> ```
I'm using the RxJS `debounceTime` but I think after reading your previous point I believe that it's not a problem with the debounce but a similar problem as yours where the pullChanges is triggering the the sync again
```
 useEffect(() => {
        return database.withChangesForTables([
            'table_name1',
            'table_name2',
        ]).pipe(
            skip(1),
            // ignore records simply becoming `synced`
            filter(changes => !changes.every(change => change.record.syncStatus === 'synced')),
            // debounce to avoid syncing in the middle of related actions
            debounceTime(500),
        ).subscribe(async () => await sync());
    }, [])
```

**Comment by Skullcan** [comment]
> So your server timestamps are different from the WatermelonDB timestamps and it works fine? Also what do you mean by trust the server timestamp? I return `Date.now()` from my pullChanges endpoint on the server as the `last`. Is that what you mean by trusting the server timestamp?

No, they are not different.
I meant I always trust the values in the control fields created_at, updated_at and deleted_at in my database.
And you are right in your approach, you have to return the Date.now() in your sync backend as your last.

> Because technically the problem with mine is for example, the client runs `pullChanges` and it grabs the record `test1` for the table `Test` from the server and pushes nothing. Then I create another record called `test2` on the client so sync is triggered again where the problem is essentially like this:
> 
> `pullChanges`: nothing pulled & lastPulledAt timestamp is updated `pushChanges`: pushes `test2` & the timestamps on the server record are updated by Postgres `pullChanges`: Attempts to pull `test2` because it was technically created after the last `pullChanges` & lastPulledAt timestamp is updated
> 

Oh I see, I had this problem in another project.. only managed to work around it by creating a sync_id.. and in my pullChanges I only return the changes with Ids that are not the current syncId from the ones I sent from the same client.
Something like this...
```
const created = map(changes[table].created, n=> {
  const newReg = omit(n, defaultExcluded);
  if (n.sync_id !== syncId) return newReg;
  return false;
});
```

This way, even if the created/updated at have a newer timestamp, the syncId prevent the attempt to create a record that was created by the same client.
But then again, my need may be different than yours, so I don't know if this approach works for you.

> How do you check for this? I think this is probably what is causing `Diagnostic error: [Sync] Concurrent synchronization is not allowed. More than one synchronize() call was running at the same time, and the later one was aborted before committing results to local database` even though I check whether or not the promise is resolved
> 
The triggered withChangeForTables from the remote server always have the 'synced' status. So I filter then and only call sync when I have at least 1 record that needs to be pushed.
Debug it and check if this is your case too.
```
const watchForChanges = databse.withChangesForTables(['orders']).subscribe({
  next: d => {
      const changedRecords = filter(d, c => c.record.syncStatus !== 'synced');
      if (changedRecords.length) {
        // Sync();
      }
    },
    error: e => logErrors(e)
});
```
I see you did the basically the same thing in your .pipe() function.. well.. I tried doing this way.. Didn't work for me.. so I did something like the code above. And now it's working fine. The withChangesForTables only start a new sync if I change something locally.

> I'm using the RxJS `debounceTime` but I think after reading your previous point I believe that it's not a problem with the debounce but a similar problem as yours where the pullChanges is triggering the the sync again

It is probably the case, yes.


*Please take into consideration that the codes are just a mockup and not optimized. I wouldn't use them in production.*

**Comment by KrisLau** [comment]
> No, they are not different. I meant I always trust the values in the control fields created_at, updated_at and deleted_at in my database. And you are right in your approach, you have to return the Date.now() in your sync backend as your last.
> 
Ohh ok I see, thank you!
</br>

> Oh I see, I had this problem in another project.. only managed to work around it by creating a sync_id.. and in my pullChanges I only return the changes with Ids that are not the current syncId from the ones I sent from the same client. Something like this...
> 
> ```
> const created = map(changes[table].created, n=> {
>   const newReg = omit(n, defaultExcluded);
>   if (n.sync_id !== syncId) return newReg;
>   return false;
> });
> ```
> 
> This way, even if the created/updated at have a newer timestamp, the syncId prevent the attempt to create a record that was created by the same client. But then again, my need may be different than yours, so I don't know if this approach works for you.
>
I'd rather not add a sync ID because I feel like it'd add a lot of overhead once the database gets big enough but it's definitely a good option for me to consider
</br>

> The triggered withChangeForTables from the remote server always have the 'synced' status. So I filter then and only call sync when I have at least 1 record that needs to be pushed. Debug it and check if this is your case too.
> 
> ```
> const watchForChanges = databse.withChangesForTables(['orders']).subscribe({
>   next: d => {
>       const changedRecords = filter(d, c => c.record.syncStatus !== 'synced');
>       if (changedRecords.length) {
>         // Sync();
>       }
>     },
>     error: e => logErrors(e)
> });
> ```
> 
> I see you did the basically the same thing in your .pipe() function.. well.. I tried doing this way.. Didn't work for me.. so I did something like the code above. And now it's working fine. The withChangesForTables only start a new sync if I change something locally.
> 
I actually just realized that I had another problem that I forgot to mention! For some reason, my `created_at` and `updated_at` is being set to `0.0` after sync. Is this expected behavior? If not, have you ever encountered this problem and how did you fix it?

**Comment by Skullcan** [comment]
>I actually just realized that I had another problem that I forgot to mention! For some reason, my created_at and updated_at is being set to 0.0 after sync. Is this expected behavior? If not, have you ever encountered this problem and how did you fix it?

It's not expected.
Had this problema before, check the type of the field in your schema and the returned type from your backend.
They must be `number` in your schema and use the decorator `@date` in your model.
`{ name: 'created_at', type: 'number' },`
`@readonly @date('created_at') createdAt;`

**Comment by KrisLau** [comment]
@Skullcan All my timestamp fields are declared as `number` types and with the `@date` decorator in their respective models. On my backend, I'm using Postgres, and ObjectionJS which returns the timestamps like this `"created_at": "2021-12-23T15:16:10.388Z"` in the `changes` object when I logged it from the frontend. That seems correct to me but is that what is expected?

**Comment by KrisLau** [comment]
@Skullcan Just tested returning it without the timestamps but that didn't work either

**Comment by Skullcan** [comment]
Your timestamp fields in postgres can be stored the way you are doing, but the watermelon sync function expect the Unix Timestamp in the `changes`.

You will have to convert the Human readable timestamp from postgre to Unix timestamp before returning they to the `changes`.
So your `"2021-12-23T15:16:10.388Z"` have to be changed to `1640278863`

Here is a snippet of the tail end of my `changes` object

```
[
  {
    "id": "15",
    "description": "xxxx",
    "value": 0.0,
    "created_at": 1640027440305,
    "updated_at": 1640027440305,
    "deleted_at": null
  }
],
  "updated": [],
  "deleted": []
  }
},
"timestamp": 1640279142732
```

This might be the reason you are having problems with the sync altogether tbh.

**Comment by KrisLau** [comment]
@Skullcan Ok I'll test that out next week and let you know if it works, thanks so much for all the help!

**Comment by KrisLau** [comment]
@Skullcan Sorry for taking so long to get back to you but I just tested it and it worked for stopping the timestamps from getting set to `0.0`! Still getting the `[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will update existing record instead.]` though :/

**Comment by Skullcan** [comment]
When I had this problem I solved using the SyncId method as I mentioned before, but then again, my project was expected to not be big and the extra overhead was not a problem.

Maybe you could try using the 'sendCreatedAsUpdated' flag and see if it helps. There's a discussion about something similar to your problem here #649

**Comment by KrisLau** [comment]
`sendCreatedAsUpdated` worked like a charm, thanks so much for all the help you've been a lifesaver!

**Comment by Skullcan** [comment]
> `sendCreatedAsUpdated` worked like a charm, thanks so much for all the help you've been a lifesaver!

I'm glad I could help!

**Comment by KrisLau** [comment]
@Skullcan Sorry I keep coming back looks like I'm running into one more problem.. Deletes seem to be causing errors?  When `sendCreatedAsUpdated ` is false:
```
[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally and is marked as deleted. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will delete local record and recreate it instead.]
```
 When `sendCreatedAsUpdated ` is true, the `pushChanges` fails. any clue what might be causing that?

**Comment by KrisLau** [comment]
@Skullcan Sorry to keep coming back but it looks like I'm still having problems but my deletes are causing errors?  When `sendCreatedAsUpdated ` is false:
```
[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally and is marked as deleted. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will delete local record and recreate it instead.]
```
 When `sendCreatedAsUpdated ` is true, the timestamps are getting set to 0.0 again.

**Comment by KrisLau** [comment]
@Skullcan Also previously converting the datetime timestamp from postgres to Unix timestamp fixed my problem with the timestamps being set to 0.0 but it seems to be acting up again and I'm not sure what changed as I have not changed any of the sync code

**Comment by Skullcan** [comment]
I see, well I've never had any of this happen to me.
Maybe you should debug the API calls and see what is arriving vs what is being store in the postgre/watermelon.

Then you can determine if your problem is in the backend or the app.
When I was implementing this, what helped me alot is Ngrok. It provides a web interface for you to analyze all the gets/posts your backend / react native is making/receiving.

**Comment by KrisLau** [comment]
@Skullcan I managed to fix it! Hopefully it stays that way 🤣 

Here's how I fixed it in case anyone else needs help with it:
- Timestamps being set to `0.0`
    I'm not sure why it only does it for some records and not others but my timestamps were being sent back as strings so I had to parse all my timestamps to integers in the knex setup. This comment on the knex forums is what ultimately helped me: https://github.com/knex/knex/issues/3071#issuecomment-509429039
- `[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will update existing record instead.]`
   Upon creation & update of the record on the server, I set the timestamps to the timestamps of the local database record instead of letting postgres automatically update the timestamps.
- `...Will delete local record and recreate it instead`
    I had to separate the creation and update sync from the deletion sync because of the foreign key constraints. The order of the former and latter had to be reversed. I couldn't use cascade deletions because I needed to add my deleted records to my deleted records table
- I later ran into an issue where the deletes were still not syncing but it was because of a type conversion issue

**Comment by KrisLau** [comment]
@radex Would this cause problems with sync?? It just occurred to me that my second fix (where I set the timestamps of the 
server records to the local DB timestamps) might cause a different problem where other clients might not get those records. 

If for example client 1 creates `Team A` at timestamp `1` (fake example timestamp) . Client 2 syncs at timestamp `2`. Client 1 syncs its data at timestamp `2` but due to my "fix", the timestamp on the server for the `Team A` record would be `1`. In this case, Client 2 would not get `Team A`, right?

**Comment by Dallas62** [comment]
Same issue there, to solve it, as @KrisLau mentioned. I use the `created_at` of the client.

To avoid weird case, I check the given `created_at`, it must be lower than the current server time. If not, I use the server time as creation date. The `updated_at` is the server time to keep it visible as updated (if `created_at` lower than `latest_pulled_at`).

In this situation, the error occurs only if there is a `created_at` is upper than `latest_pulled_at` (from the client which create the entity).
An other one can occur if the `created_at` is lower than `latest_pulled_at` and current entry doesn't exist one the client (listed as updated but not existing locally).
Both should not happen too often and are handled by WatermelonDB.
