### ISSUE TITLE
Timestamps NOT in milliseconds 

### ISSUE THREAD

**Issue by pooryamd** [Nozbe/WatermelonDB#1231]
Hi,
I'm working on a project with sync to a Laravel backend (using [Lavavel-Watermelon](https://github.com/nathanheffley/laravel-watermelon/)).
My problem is when my Android App sends push to Laravel, timestamp fields (created_at, ...) are in millisecond and Laravel returns an error, trying to save some strange date: 53926-05-11 03:59:11 !!!!
Obviously, Laravel is not considering dates to have mollisecond!
Actually, I trimed 3 last digits on server side and it is working now, But I need more consistency and hopping no need to do extra data manipulations!

Why is date/timestamp fields being saved as millisecond whereas for example last_pulled_at is not?!?!

**Comment by radex** [comment]
this is a question to https://github.com/nathanheffley/laravel-watermelon/

**Comment by radex** [comment]
this is a question to https://github.com/nathanheffley/laravel-watermelon/

**Comment by pooryamd** [comment]
Thank You,
But: Why is date/timestamp fields being saved as millisecond whereas for example last_pulled_at is not?!?!
