### ISSUE TITLE
Is deletion of a model item observable?

### ISSUE THREAD

**Issue by nmeibergen** [Nozbe/WatermelonDB#1238]
In the documentation in paragraph 2.6 on 'Connecting to React Components' it states: '[..] The only problem is that this is not reactive. If the Comment is updated or deleted, [..]', suggesting that wrapping it inside `withObservables` will make updates and deletes trigger a refresh of the corresponding React component.

However, within my code I notice that yes, lists on which a deletion occurs will trigger a refresh of the component and thus provide a new list without the item that was deleted, but if I have a component which fetches a single item and passes that into a `withObservables` I don't get any refresh after deletion. 

As an example:

```
const Comment = ({ comment }) => {

  const onPress = () => {
    comment.markAsDeleted();
  }

  useEffect(() => {
    // I would expect to be able to observe a change here, or actually a refresh of the whole component because of the deletion
  }, [comment.syncStatus]) 

  return <View>
    <Text>{comment.body}</Text>
    <TouchableOpacity onPress={onPress}>Delete me</TouchableOpacity>
  </View>
}

const LiveComment = withObservables(['commentId'], ({ commentId }: { commentId: string }) => ({
        comment: database.comments.findAndObserve(commentId)
}))(Comment)
```

In the above stylized exampled I use `comment.syncStatus`, alternatively I have tried looking at the `_status` column value, without any success.

Is this indeed the expected behaviour or should there be some refresh and am I doing something wrong? Furthermore, if this is the expected behaviour what is the suggested approach to detect a deletion such as the above?

PS. I am using the latest version of Watermelon, i.e. 0.24.1-1

**Comment by radex** [comment]
deletions are propagated by completing the observable, i.e:

```js
import { tap as tap$ } from 'rxjs/operators'

database.comments.findAndObserve(commentId).pipe(
   tap$(undefined, undefined, () => {
      // action to perform when comment is deleted
   })
)
```

**Comment by nmeibergen** [comment]
Alright, great!
