### ISSUE TITLE
Generating models from JSON schema

### ISSUE THREAD

**Issue by bennidi** [Nozbe/WatermelonDB#1242]
I am reading through WatermelonDB docs and they look really nice. I would love to give it a try. But I already have a model definition layer based on JSON schema and custom extensions.

I wonder if there is a way to generate model classes dynamically at runtime rather than defining them statically.

Any pointers on that would be very much appreciated.

**Comment by KrisLau** [comment]
From what I know, I don't think there are any ways to dynamically generate the model classes.
