### ISSUE TITLE
synchronize.pullChanges – Type mismatch on Migration arg?

### ISSUE THREAD

**Issue by kaxline** [Nozbe/WatermelonDB#1244]
I might be wrong about this, but it seems that the `migration` arguement in the `pullChanges` function isn't the correct type.

It's imported as a `Migration` with props `toVersion` and `steps`:

https://github.com/Nozbe/WatermelonDB/blob/4eea337b5052b8933ce32cd51a5f69592aeff809/src/sync/index.d.ts#L19

https://github.com/Nozbe/WatermelonDB/blob/4eea337b5052b8933ce32cd51a5f69592aeff809/src/Schema/migrations/index.d.ts#L31

But the docs say to expect an object with `from`, `tables`, and `columns`:

https://github.com/Nozbe/WatermelonDB/blob/4eea337b5052b8933ce32cd51a5f69592aeff809/docs/Advanced/Sync.html#L476

It looks like the correct args are actually passed to the `pullChanges` function, but that the type for the `migration` arg should be changed to `MigrationSyncChanges`:

https://github.com/Nozbe/WatermelonDB/blob/487a2a05e1a5c34fd78634c9fadc28032dbd9a3d/src/Schema/migrations/getSyncChanges/index.js#L11

**Comment by radex** [comment]
TypeScript types are community-developed. Flow types are the source of truth - if you found a mismatch, please send a pull request with a fix
