### ISSUE TITLE
WatermelonDB Sync function generating a Possible Unhandled Promise Rejection

### ISSUE THREAD

**Issue by doobe01** [Nozbe/WatermelonDB#1246]
Whenever I click the button to call sync I get: Error: Invalid hook call. Hooks can only be called inside of the body of a function component. This could happen for one of the following reasons:
1. You might have mismatching versions of React and the renderer (such as React DOM)
2. You might be breaking the Rules of Hooks
3. You might have more than one copy of React in the same app
See https://reactjs.org/link/invalid-hook-call for tips about how to debug and fix this problem.

**Any ideas?**

```
import` { synchronize } from '@nozbe/watermelondb/sync';
import { database } from '../../index';

const SYNC_API_URL = 'https://example.com/sync';

export async function sync() {
  await synchronize({
    database,
    pullChanges: async ({lastPulledAt}) => {
      const response = await fetch(SYNC_API_URL, {
        method: 'GET',
        headers: {'Authorization': 'Bearer' + $(user.token)},
        body: JSON.stringify({lastPulledAt}),
      });
      if (!response.ok) {
        throw new Error(await response.text());
      }

      const {changes, timestamp} = await response.json();
      return {changes, timestamp};
    },
    pushChanges: async ({changes, lastPulledAt}) => {
      const response = await fetch(
        `${SYNC_API_URL}?lastPulledAt=${lastPulledAt}`,
        {
          method: 'POST',
          headers: {'Authorization': 'Bearer' + $(user.token)},
          body: JSON.stringify(changes),
        },
      );
      if (!response.ok) {
        throw new Error(await response.text());
      }
    },
  });
}
```

**Comment by radex** [comment]
this is a react problem in your app, not 🍉

**Comment by heyalexchoi** [comment]
@radex on a new install of react native which requires react 18, along with watermelondb which requires withObservables which in turn requires react 16/17 as a peer dependency, I believe the default expected behavior would then be for npm to install react 17 under watermelondb's node_modules which would then throw this error. I am seeing this issue as well. 

I think maybe if withObservables' peer dependency on react is bumped to 18, you would see this disappear. will make an issue.

**Comment by ChrisSimoniMBT** [comment]
@heyalexchoi Try setting the `resolver.disableHierarchicalLookup` to true in your metro config.
