### ISSUE TITLE
Failed to prepare query statement - sqlite error 1 (no such table: posts)

### ISSUE THREAD

**Issue by maidul98** [Nozbe/WatermelonDB#1248]
I have started a bare react-native project and have been following the install guide over at https://nozbe.github.io/WatermelonDB/ch02-00-learn-to-use.html

However when I do the following I get: `Failed to prepare query statement - sqlite error 1 (no such table: posts)`

```
  useEffect(() => {
    const asycFunc = async () => {
      await database.write(async () => {
        const postsCollection = await database.get('posts').create(post => {
          post.title = 'New post'
          post.subtitle = "dsdsd"
          post.body = 'Lorem ipsum...'
          post.is_pinned = true
        })
      })
    }

    asycFunc()
  }, []);

```
My schema and modal look identical to the guide above. I'm missing something here? Thank you

**Comment by SaltedBlowfish** [comment]
Copy / paste your schema, migrations, models, and your app's index file (or wherever you import your models).

**Comment by maidul98** [comment]
Was some kind of cache issue, worked after computer restarted
