### ISSUE TITLE
[Unhandled promise rejection: TypeError: null is not an object (evaluating '_index.default.get('tests').create')]

### ISSUE THREAD

**Issue by mawlicious** [Nozbe/WatermelonDB#1253]
When moving along with the very basic example for React Native from the docs with the following code:

```js
await database.write(async () => {
      const newPost = await database.get('tests').create(test => {
        test.name = 'Mark'
        test.age = 15
      })
    })
    const allTests = database.get('tests')
    console.log(allTests)
```

I get greeted with the following error:

`[Unhandled promise rejection: TypeError: null is not an object (evaluating '_index.default.get('tests').create')]`

**Comment by SaltedBlowfish** [comment]
@mawlicious Try providing the model as the type parameter to `await database.get()`

E.g., 

```
await database.write(async () => {
  await database.get<Test>('tests').create(test => {
    test.name = 'Mark';
    ...
  });
});
```

**Comment by mawlicious** [comment]
since I've moved on from watermelon, I will just close this issue if others ever run into the same problem, thanks!!

**Comment by jotilohana** [comment]
I'm facing the same issue
didn't find any solution

**Comment by fluoroom** [comment]
have you found any by now? i'm facing it now
