### ISSUE TITLE
Can we access SQLite mathematical functions

### ISSUE THREAD

**Issue by nmeibergen** [Nozbe/WatermelonDB#1266]
I'd like to access the mathematical functions as described [here](https://www.sqlite.org/lang_mathfunc.html). This however can only be achieved if the amalgamation is compiled with `-DSQLITE_ENABLE_MATH_FUNCTIONS`. Is there a way we can 'easily' achieve this?

**Comment by rafaelboniolo** [comment]
@nmeibergen How do it? I'm tried without success. Help me!
