### ISSUE TITLE
_raw is always empty

### ISSUE THREAD

**Issue by amhed** [Nozbe/WatermelonDB#1282]
I'm running into an issue similar to these ones: 
- https://github.com/Nozbe/WatermelonDB/issues/104
- https://github.com/Nozbe/WatermelonDB/issues/682

When using `create` the write operation succeeds into writing, but the object is always written with empty values. Inspecting the return object I can see that `_raw` has all the fields defined by the schema, but they all have the default values instead.

schema
```ts
import { appSchema, tableSchema } from '@nozbe/watermelondb';

export const schema = appSchema({
  version: 5,
  tables: [
    tableSchema({
      name: 'wallet',
      columns: [
        { name: 'walletId', type: 'string', isIndexed: true },
        { name: 'currencyCodeStr', type: 'string', isIndexed: true },
      ],
    }),
  ],
});
```

Model
```ts
import { Model } from '@nozbe/watermelondb';
import { field } from '@nozbe/watermelondb/decorators';

export class WalletWMO extends Model {
  static table = 'wallet';

  @field('walletId')
  walletId!: string;

  @field('currencyCodeStr')
  currencyCodeStr!: string;
}
```

Code to insert
```ts
database.write(async () => {
  const table = database.get<WalletWMO>('wallet');
  const result = await table.create((record: WalletWMO) => {
    record.walletId = this.id;
    record.currencyCodeStr = this.currencyCode.rawValue;
  };);
});
```

And yet, the underlying `_raw values are empty/default

<img width="259" alt="image" src="https://user-images.githubusercontent.com/579291/158071367-9b558519-efbd-4a13-9bd6-8d77ad3bedd7.png">

Tsconfig has 
```
"experimentalDecorators": true,
"emitDecoratorMetadata": true,
```

BabelConfig has
```
const plugins = [
    'react-hot-loader/babel',
    ['@babel/plugin-proposal-private-methods', { loose: true }],
    ['@babel/plugin-proposal-private-property-in-object', { loose: true }],
    ['@babel/plugin-proposal-class-properties', { loose: true }],
    ['@babel/plugin-proposal-decorators', { legacy: true }],
    [
      '@babel/plugin-transform-runtime',
      {
        helpers: true,
        regenerator: true,
      },
    ],
]
```

**Comment by amhed** [comment]
Inspecting transpiled JS it looks like decorator metadata is being issued: 

```js
__decorate([
  (0,decorators.field)('walletId'),
  __metadata("design:type", String)
], WalletWMO.prototype, "walletId", void 0);
__decorate([
  (0,decorators.field)('currencyCodeStr'),
  __metadata("design:type", String)
], WalletWMO.prototype, "currencyCodeStr", void 0);
```

**Comment by amhed** [comment]
Update: I'm deploying this on a shared data layer for both react and react-native. The React-Native side executes flawlessly. Only the web side bombs :o

**Comment by amhed** [comment]
Aaaaand I had a different target for the web version. Set to ES2020 :)

**Comment by leejunhui** [comment]
@amhed Hi, I met the same issue - the _raw always empty. The web version you set is the version in babel config or ts config? Formerly my project use webpack, so everything is fine.But when I try to migrate to vite, on the dev environment, the _raw field in watermelondb is always empty.

**Comment by kegesch** [comment]
@leejunhui I have the same problem. Just migrated to Vite + Typescript and the _raw fields are empty. Did you get it running in the end?

**Comment by leejunhui** [comment]
> @leejunhui I have the same problem. Just migrated to Vite + Typescript and the _raw fields are empty. Did you get it running in the end?

sorry, I haven't sovled the problem.I think the truly cause is the lack of support of javascript decorator of esbuild~

**Comment by parsagholipour** [comment]
Any solution to use this with Vite?

**Comment by Alarees** [comment]
add ._raw in create function


` database.write(async () => {
        const contact = await contactsCollection.create(contact => {
          contact._raw.contact_name = new_contact.contact_name;
          contact._raw.contact_phone = new_contact.contact_phone;
        });
      });
`

**Comment by GitMurf** [comment]
> @amhed Hi, I met the same issue - the _raw always empty. The web version you set is the version in babel config or ts config? Formerly my project use webpack, so everything is fine.But when I try to migrate to vite, on the dev environment, the _raw field in watermelondb is always empty.

@leejunhui did you ever figure this out?! I am running into exactly the same issue using vite and the nodejs sqlite adapter in Watermelon.

**Comment by GitMurf** [comment]
@kegesch @parsagholipour did you end up settling on a solution / workaround or figure out the problem? I also am using vite and TypeScript and running into the EXACT same issues.

@Alarees your solution does work (hard setting the `_raw` properties) but in the Watermelon docs it explicitly says you should not do that. So I am wondering how this can be fixed (or a workaround) in a supported / recommend way by Watermelon. @radex can you provide some guidance here please? Thanks so much!
