### ISSUE TITLE
Project doesn't compile after installing watermelondb with Expo 

### ISSUE THREAD

**Issue by pablolucio97** [Nozbe/WatermelonDB#1292]
I'm getting the error below. This appoints to babel.config.js file, but I've added the decoratorsBeforeExport options and the error persists. Someone can help? I appreciate that.

![Screenshot_1648210785](https://user-images.githubusercontent.com/54117323/160119586-457b517a-2f98-4e17-93b2-4878c90362d5.png)

Babel file:

![babel](https://user-images.githubusercontent.com/54117323/160119263-e0c16eb2-2f17-4237-8799-53200efce5fb.png)

Specs:

Reat Native version: 0.64.3
WatermelonDB version: 0.24.0
Expo SDK version: SDK 44
System: Windows 10;

**Comment by KrisLau** [comment]
https://github.com/Nozbe/WatermelonDB/issues/758

**Comment by pablolucio97** [comment]
Thnks man, I'll eject it.

**Comment by KrisLau** [comment]
No problem!

**Comment by KrisLau** [comment]
Hey just fyi there's another issue related to expo 

- https://github.com/Nozbe/WatermelonDB/pull/1249

Also, don't forget to close this issue if your issue is solved!

**Comment by radex** [comment]
should be fixed in 0.25.x
