### ISSUE TITLE
How to get lastPulledAt timestamp from watermelonDB?

### ISSUE THREAD

**Issue by PragyaSingla** [Nozbe/WatermelonDB#1296]
I want to show date & time in the application when data synced last time. Is there any way to get below timestamp in components that we are using in sync process.

{
    "timestamp": 1649049653, --- this value
    "changes": {}
}

Thanks

**Comment by bureyburey** [comment]
Seems there is an exposed function `getLastPulledAt(database)`

https://github.com/Nozbe/WatermelonDB/blob/master/src/sync/impl/index.js#L17

**Comment by PragyaSingla** [comment]
> Seems there is an exposed function `getLastPulledAt`
> 
> https://github.com/Nozbe/WatermelonDB/blob/master/src/sync/impl/index.js#L17
> 
> usage is as folllows:
> 
> ```
> import {getLastPulledAt} from "@nozbe/watermelondb/sync/impl";
> 
> const lastPulledAt = await getLastPulledAt(databaseInstance);
> ```

Thanks @bureyburey, it worked.

We need to add below in some .d.ts file. If file doesn't exist then create types.d.ts file in root directory and add below line.

declare module '@nozbe/watermelondb/sync/impl';
