### ISSUE TITLE
How do we achieve paging queries?

### ISSUE THREAD

**Issue by XiaoJianPeng** [Nozbe/WatermelonDB#130]

**Comment by cjh804263197** [comment]
I have same question

**Comment by dkaushik95** [comment]
I am guessing if the underlay is an SQL adapter, maybe using limit?

**Comment by jacekk** [comment]
@dkaushik95 FYI: https://github.com/Nozbe/WatermelonDB/issues/113 Not resolved yet.

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/issues/113 describes why this is much harder than it seems, and a suggested workaround. If it doesn't work, please describe the exact use case in as much detail as you can.

**Please contribute a quick PR to the documentation explaining this for others :)**

Closing this, as it's a duplicate

**Comment by LovesWorking** [comment]
React Query works good for me for this.
