### ISSUE TITLE
Pass parameters from context provider to `withObservables`

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1323]
So currently I'm storing my global state in async provider and sending that to each individual screen using react navigations params, however I was told that it would be better to store this using Context API similar to how firebase auth is setup. I setup my context API with this global state now but I'm unsure how to send this to the `compose()` so that I can use it in the observable database queries?

### Code
Context Provider:
```
import React, {createContext, useContext, useState} from 'react';

const ExampleContext= createContext();
function useExample() {
  return useContext(ExampleContext);
}

function ExampleProvider({children}) {
  const [exampleState, setExampleState] = useState(null);

  const value = {
    exampleState,
    setExampleState
  };

  return (
    <ExampleContext.Provider value={value}>
      {children}
    </ExampleContext.Provider>
  );
}

export {ExampleContext, ExampleProvider, useExample};
```

Component:
```
export default compose(
  withDatabase,
  withObservables([], ({database}) => ({
    variableName: database
      .get('table_name')
      .query()
      .observe(),
  })),
)(Component)
```

### What I'm trying to do
```
export default compose(
  withDatabase,
  withObservables([], ({database}) => {
    const example = useExample;
    return {
        variableName: database
          .get('table_name')
          .query()
          .observe(),
    };
  }),
)(Component)
```
but I get an invalid hook call so I'm wondering if there is a way to use RxJS/recompose to do so or if there is a different approach I can use pass this global state to all my screens without redux. I have also tried passing my HOC to the withObservables using withContext from recompose to no avail but I likely messed something up there so any help would be appreciated

**Comment by KrisLau** [comment]
Nevermind I'm dumb and just realized it doesn't function like a hook so I can just use it directly in the withObservables

**Comment by KrisLau** [comment]
https://github.com/ReactiveX/rxjs/discussions/6967#discussioncomment-2865250

**Comment by Stophface** [comment]
@KrisLau I am having a similar trouble with database. I am not sure how to make the initialzed database available to the app. Upon very first App start, I initialize the database like this

```
 const adapter = new SQLiteAdapter({
        schema: Foo,
        dbName: databasePathAndName,
        jsi: false,
        onSetUpError: error => {
            console.log(`[Database]: Error on bundled database: .... Error: `, error);
        }
    });

    const database = new Database({
        adapter,
        modelClasses: [
            Foo,
            Bar,
            Cat,
            SomeTable,
        ],
    });


Then, I can pass it down via the context API, something like

```
<DatabaseProvider
    database={database} />
        <App />
<DatabasePovider />
```

However, these lines `const database = new Database({...` I only call once, upon very first App start, when the user opens the App for the very first time. I do not need to initialize the `database` every time again. Thus, I am not having a database object, because `const database = new Database({...` is never called. Because of that, there is not `database` I can pass to the `<DatabaseProvider database={database} />`. 

But how can my app access the database then? Do how did you solve this?

**Comment by Stophface** [comment]
@KrisLau Thanks for responding. I know about the Database Provider, `withDatabase()` and the `useDatabase()` hook. But it all comes down to the same problem. I initialize the database _once_, upon first start of the App. During this process I can export the database from where I initialize it and pass it to the i.e. Database Provider.

But what if I restart the app?! Then I do not initialize the database again. I am not calling these lines `const databaseObject = new Database({...` again, because that would overwrite mit already initialized database with all my data in it. If I do not call these lines, there is nothing to export from the file, where I initialize it...

Looking at `react-native-sqlite-storage` I'd simply pass a database name with a flag "read only" to some function, something along these lines
```

        SQLite.openDatabase(
            {
                name: SOME_DATABASE_NAME,
                createFromLocation: 1,
                readOnly: true,
            }, database => database.transaction....
```

But this does not seem to be possible with `watermelonDB`. I was thinking about saving the created database object with `redux-persist`, so that I do not loose it. But this seems wrong... I either miss something fundamentally here or I missunderstand something.

**Comment by KrisLau** [comment]
You can still export the database without calling it again. I reload my app numerous times and the import works fine and always refers to the same instance of the database without reinitializing or overwriting the database. Just import it in any screen and you will see that it works no matter how many times you reload. 

Also I'm not sure from your comments if you have already tried importing it and are running into issues after reloading or if you are just expecting it to have issues before trying it.  If you have already tried it the problem is with the way you are setting up the database.

It's very outdated as it uses `actions` (which has been deprecated) but you can look at this tutorial to see a rough idea of how other people use WatermelonDB: https://blog.logrocket.com/offline-app-react-native-watermelondb/

**Comment by Stophface** [comment]
@KrisLau This is how I set up my database. It is a pre populated database, so I have to move it from the APK Bundle to a place, where the App and WatermelonDB can access it (this is done with `copyDatabase()`). After moving it, I create the WatermelonDB instance and then I delete the original database.
```

async function setupDatabase(databasePathAndName, dbName) {
    await copyDatabase(databasePathAndName, dbName);
    const adapter = new SQLiteAdapter({
        schema: foo,
        dbName: databasePathAndName,
        jsi: false,
        onSetUpError: error => {
            console.log(`[Database]: Error on bundled database: "${dbName}.db", Failed on setupDatabase(). Error: `, error);
            store.dispatch(databaseFail());
        }
    });

    const database = new Database({
        adapter,
        modelClasses: [
           A,
           B,
           C,
           D
        ],
    });
    
    store.dispatch(databaseInitialized(
    deleteDatabase(dbName);
}
```

This works. But when I call `setupDatabase()` another time, it overwrites my already created database...

**Comment by Stophface** [comment]
@KrisLau You are probably unaware of it, but you solved my problem by pin pointing me into the right direction! I think the problem was, that I always passed the complete path to `new SQLiteAdapter({...`. Passing it the database name, after moving it from my application bundled, and it worked!
Thanks for sticking with me KrisLau!

**Comment by KrisLau** [comment]
@Stophface You should not need to do that if you follow the setup as per the documentation. Please refer to my previous comment.

**Comment by Stophface** [comment]
@KrisLau You have to do that if you want to use a pre populated database. See this https://github.com/Nozbe/WatermelonDB/issues/774

**Comment by KrisLau** [comment]
@Stophface Yup, my bad I realized later and added an edit with the way I do it in my current app. Since all users should get the same prepopulated data in my case, I just prepopulated the backend DB and ensure that the user syncs when they first open the app

**Comment by Stophface** [comment]
@KrisLau Do you have an idea how to achieve this https://github.com/Nozbe/WatermelonDB/issues/1397 ?

**Comment by KrisLau** [comment]
@Stophface 

- https://github.com/Nozbe/WatermelonDB/issues/1323#issuecomment-1145118110

**Comment by Stophface** [comment]
Thanks @KrisLau

**Comment by Stophface** [comment]
@KrisLau have you experience with updating a record in the database?

**Comment by Stophface** [comment]
@KrisLau thanks!
