### ISSUE TITLE
Sync fails with error Invalid comparisonRight.

### ISSUE THREAD

**Issue by nijeeshvayalassery** [Nozbe/WatermelonDB#1324]
Hi,

We are getting following  sync error some times,
**Invalid comparisonRight** 
We could not find the correct reason because the issue occurring is in production.  if Once this error has occurred, following all sync's are getting failed.

**Comment by KrisLau** [comment]
Invalid `comparisonRight` is when you either reference a column that doesn't exist in the schema or you pass in data that is the wrong type (e.g: setting a number field with a string, null to a required field, etc). You'll need to check your data properly

**Comment by KrisLau** [comment]
@nijeeshvayalassery If the answer solved your problem don't forget to close the issue and if possible leave a comment with how you solved your issue to help future people who might run into similar issues, thanks!

**Comment by radex** [comment]
Inactive, closing
