### ISSUE TITLE
Does WatermelonDB support encryption?

### ISSUE THREAD

**Issue by owencraston** [Nozbe/WatermelonDB#1328]
I am wondering if there is any support for encryption with watermelonDB? This is a requirement for our application. I was looking at [this issue](https://github.com/Nozbe/WatermelonDB/issues/51) and it seemed like nothing materialized from this thread. I noticed these proposals all use [SQLCipher](https://github.com/sqlcipher/sqlcipher) and I am wondering if it somehow works if you use the built in [SQLite Encryption extension](https://www.sqlite.org/see/doc/release/www/index.wiki)?

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/pull/907 there's an unfinished PR for this
