### ISSUE TITLE
Recompose/pulling `compose` into WatermelonDB

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1360]
Are there any plans to fork recompose/pull `compose` (and anything useful to WDB like `fromRenderProps`) into WatermelonDB since it hasn't been maintained since 2018 and its `compose` seems to be integral to observing multiple tables at once?

**Comment by Mohamed-kassim** [comment]
@KrisLau you tried @shopify/react-compose ?

**Comment by KrisLau** [comment]
@Mohamed-kassim Thank you for that, I never saw that before! I was using brodybits/react-recompose but I didnt realize shopify had a fork as well. I'll close the issue since that should be perfect for me

**Comment by Garabed96** [comment]
Should this not be a feature request to the documentation since recompose@latest is not compatible with react 18
