### ISSUE TITLE
Defining models guide for typescript? (Error: "Property 'id' has no initializer and is not definitely assigned in the constructor.")

### ISSUE THREAD

**Issue by mfbx9da4** [Nozbe/WatermelonDB#1361]
Hi, I'm new to watermelonDB but having trouble defining my model. There doesn't seem to be a typescript guide. For a start you need to enable `experimentalDecorators` in tsconfig which doesn't seem to be documented.

I am currently facing the error  "Property 'id' has no initializer and is not definitely assigned in the constructor."

```ts
import { Model } from '@nozbe/watermelondb'
import { field, text, date } from '@nozbe/watermelondb/decorators'

export default class Me extends Model {
  static table = 'me'
  @text('id') id: string // ❌ throws error "Property 'id' has no initializer and is not definitely assigned in the constructor."
}
```

**Comment by radex** [comment]
Closing for now to consolidate it to these issues:

https://github.com/Nozbe/WatermelonDB/issues/1516

https://github.com/Nozbe/WatermelonDB/issues/1481

@mfbx9da4 your contributions to docs would be highly appreciated
