### ISSUE TITLE
Create record with id

### ISSUE THREAD

**Issue by mfbx9da4** [Nozbe/WatermelonDB#1362]
I would like to create a record with a specific id but it seems watermelon always generates a new id e.g. 

How can I do this?
```tsx
database.get<Message>('messages').prepareCreate(x => { x.id = 'foo' })
```

**Comment by mayank-01-ms** [comment]
Getting error [TypeError: Cannot assign to property 'id' which has only a getter] while using ._raw.id = id.
Also, if I use ._setRaw('id', model.id), this throws an error as columnSchema for id is not defined.
