### ISSUE TITLE
Which is the latest version of this library?

### ISSUE THREAD

**Issue by clmoreno** [Nozbe/WatermelonDB#1376]
Hi!! I have a question about versioning, i have been using watermelon for about a year, but i haven't seen updates or new releases, I'm wondering if I'm missing something or is it correct that v0.24.0 is the last version available ?  I'm not trying to ask for something or getting explanations, don't misunderstand my question, i just want to know the state of the library or if help is needed in some aspect i can help to keep developing and maintenance of this awesome db  :)

**Comment by radex** [comment]
0.24 is the latest version, yes.
