### ISSUE TITLE
Any solution for FMDB conflict?

### ISSUE THREAD

**Issue by KennanChan** [Nozbe/WatermelonDB#1384]
I am trying to setup watermelon db on an existing RN project which already uses FMDB to access SQLite database.
When I build the project, XCode gives me a bunch of duplicate symbol errors between FMDB and WatermelonDB.
I am new to iOS development. Does anyone know how to resolve it?

**Comment by KrisLau** [comment]
Is there a reason you are using two different client DBs? I would assume that would cause errors even if you manage to resolve the duplicate symbol errors but I'm not 100% sure

**Comment by KennanChan** [comment]
> 

An experienced iOS developer told me that same symbol cannot be declared multiple times. OC does not provide the namespace thing.
The thing I don't get through is why WDB ships the header files of FMDB. Why FMDB should be "merged" into WDB rather than as a dependency of WDB.

I am now preparing to implement a WDB SQLite adapter with FMDB myself.

My case is:
I use WDB in a mobile web project which integrates into an RN project by WebView
Currently I use LokiAdapter so database resides in the browser's IndexedDB.
But the database grows so fast. The storage limit of IndexedDB is a fatal issue now.
To resolve the issue, I created a new WDB adapter in the mobile web project to replace LokiAdapter. The adapter bridges adapter interface calls to a coresponding SQLiteAdapter created in RN through the message tunnel provided by WebView.
The adapter works as expected on an RN example project but fails to build on my real-world project due to FMDB conflict.

**Comment by KrisLau** [comment]
@KennanChan I'm not really experienced with this myself so hopefully @radex can offer some insight into solving this

**Comment by radex** [comment]
@KennanChan It would be preferable for FMDB in 🍉 to be a CocoaPods dependency. This way, 🍉 and you could reuse the same source for FMDB.

I highly encourage you to send a pull request where 🍉 is reworked slightly to use FMDB via CP. This shouldn't be too difficult to set up

**Comment by radex** [comment]
Closing, given inactivity. Still happy to a accept FMDB via CP pull requests
