### ISSUE TITLE
Handle withObservables errors

### ISSUE THREAD

**Issue by amcjml** [Nozbe/WatermelonDB#1385]
Hi,
How can I handle withObservables errors, like "Record customers#1915 not found"
In this case the app got crashed and closed in production.
I need to show an error message instead of crashing app.

Can you help me please?

PS: I'm using watermelondb with a remote MySQL database.

**Comment by KrisLau** [comment]
You didn't include any of your code so no one can really help. If you're using `.find` in your `withObservables`, you should swap to `.query` and that way you can just check the length of the array returned to check if no matching results were found.

**Comment by amcjml** [comment]
Thanks for your reply,

My code is like:

- `EnhancedPost`

```
const Post = ({ post, comments }) => (
  <article>
    <h1>{post.name}</h1>
    <p>{post.body}</p>
    <h2>Comments</h2>
    {comments.map(comment =>
      <EnhancedComment key={comment.id} comment={comment} />
    )}
  </article>
)

const enhance = withObservables(['post'], ({ post }) => ({
  post,
  comments: post.comments,
}))

const EnhancedPost = enhance(Post)
export default EnhancedPost
```

- `EnhancedComment`

```
const Comment = ({ comment, author }) => (
  <div>
    <p>{comment.body} — by {author.name}</p>
  </div>
)

const enhance = withObservables(['comment'], ({ comment }) => ({
  comment,
  author: comment.author,
}))
const EnhancedComment = enhance(Comment)
```

in this example, if author not found will throw the error "Record authors#ID not found"

**Comment by KrisLau** [comment]
@amcjml I'm not sure if I'm being dumb but I don't know what is going on since I don't see a query in the code anywhere?
```
    user: database
      .get('user')
      .query(
        Q.where('id', 'whatever-id-123'),
      )
      .observe(),
```

**Comment by amcjml** [comment]
Thanks for your time @KrisLau.
I don't need to do any query, I have models and relations between them.
So here I will get author without using any query:

```
const enhance = withObservables(['comment'], ({ comment }) => ({
  comment,
  author: comment.author,
}))
```
I can transform this `author: comment.author,` to this:
 ```
author: database
      .get('author')
      .query(
        Q.where('id', comment.author_id),
      )
      .observe(),
```

Is this right ? and I can do the length count later in the component ?

**Comment by KrisLau** [comment]
Yup that should work

**Comment by amcjml** [comment]
The query return empty result because `comment.author_id` is undefined
```
author: database
     .get('author')
     .query(
       Q.where('id', comment.author_id),
     )
     .observe(),
```

**Comment by amcjml** [comment]
Well done!
I use: `comment.author.id` instead of `comment.author_id`.
