### ISSUE TITLE
Using watermelon jsi with react native new fabric arch 

### ISSUE THREAD

**Issue by batuhansahan** [Nozbe/WatermelonDB#1386]
I am trying to enable jsi implementation on android but 
it keeps give errors on console.
I followed[ jsi implementation guide](https://nozbe.github.io/WatermelonDB/Installation.html) on document page and i was already using watermelon jsi without fabric with no problem.

```
 WARN  [🍉] JSI SQLiteAdapter not available… falling back to asynchronous operation. 
This will happen if you're using remote debugger, and may happen if you forgot to recompile native app after WatermelonDB 
update

 LOG  Running "AwesomeApp" with {"fabric":true,"initialProps":{"concurrentRoot":true},"rootTag":1}
```
remote debugger is not active and i tried recomplite multiple times

`"@nozbe/watermelondb": "^0.24.0"`
`"react-native": "0.70.0"`
ios is ok.
android is not.

should i remove all watermelon jsi codes from mainapplication.java is it a good idea.

**Comment by rizkhal** [comment]
Hy @batuhansahan, Are you already trying to query and doesn't error?

**Comment by ebnersilva** [comment]
I am still having the same issue even after applying the suggested actions in the issue here. Is there anyone else that is facing the same problem?

**Comment by shenyu1019** [comment]
same problem
