### ISSUE TITLE
Writing big query - more than 20 000 writers in queue at once

### ISSUE THREAD

**Issue by alicja99** [Nozbe/WatermelonDB#1390]
I have to write more than 20 000 records, and I because of more than 13 000 writers waiting in the queue, there is app crash because of lacking RAM space. Is it any wait to split data into the chunks and load it separately?  Do Writer run on the native thread and there is no way to wait for theirs execution?

**Comment by alicja99** [comment]
@mfbx9da4 using one writer helped with this. So far I saw in documentation turbo login is used to sync with the backend.

**Comment by Stophface** [comment]
@mfbx9da4 Could you give an example how to do this?
