### ISSUE TITLE
[ 0.24.0] Android significantly slower than iOS

### ISSUE THREAD

**Issue by tonygomez** [Nozbe/WatermelonDB#1394]
react-native: 0.68.2
@nozbe/watermelondb: 0.24.0
ndk: 20.1.5948944
JSI installed
hermes enabled

Same queries and code running in iOS is fast. When running on android the queries take 5 seconds longer. What are we missing in android that can be causing this significant performance degradation?

**Comment by radex** [comment]
make absolute sure that JSI is *really* enabled.

run a profiler from android studio to find out where the time is being spent.

remember that an average Android device is a few times slower than an average iOS device, and even when comparing top to top devices, you can see 2x difference in CPU-heavy workloads

**Comment by tonygomez** [comment]
Disabling JS debugging sped up the emulator. Thank you for the help!
