### ISSUE TITLE
How to build this query with watermelonDB's Syntax

### ISSUE THREAD

**Issue by Stophface** [Nozbe/WatermelonDB#1400]
I am not able to build this query 

```
SELECT 
    *
FROM 
    foo 
WHERE 
    kitten 
IN 
    ('a', 'b', 'c') 
AND  
    bar = 1;
```
I tried with

```
.query(
    Q.where('bar', 1),
    Q.and(Q.where('kitten', Q.oneOf('a', 'b', 'c'))),
)
```

But this not returning anything. I assume it is because `Q.where()` inserts a `WHERE`, thus constructing the query like this

```
SELECT 
    *
FROM 
    foo 
WHERE 
    kitten 
IN 
    ('a', 'b', 'c') 
AND WHERE <-- another WHERE 
    bar = 1;
```

which is not what I need. Any ideas how to construct this query?

**Comment by radex** [comment]
your query seems fine. use `query._sql()` to inspect the output if you want to verify that

**Comment by Stophface** [comment]
@radex I get this

    select "foo".* from "foo" where "foo"."kitten" in ('a', 'b', 'c') and "foo"."_status" is not 'deleted'


It works when I input it like this

```
.query(
    Q.unsafeSqlQuery(
        `SELECT foo.csomeCl FROM foo WHERE kitten IN ('a', 'b', 'c')  AND bar = 1    
    ),
).unsafeFetchRaw();
```

**Comment by davidkhuu** [comment]
According to the docs (https://nozbe.github.io/WatermelonDB/Query.html#multiple-conditions), I think you just need to remove the `Q.and` from the original WatermelonDB query you had.
```
.query(
  Q.where('bar', Q.eq(1),
  Q.where('kitten', Q.oneOf(['a', 'b', 'c']),
)
```

**Comment by Stophface** [comment]
Nope, that is giving me `[Diagnostic error: Passed undefined to query]` eventhough there is nothing `undefined`, at least not in the variables I am passing...

**Comment by radex** [comment]
@Stophface Have you figured out your issue?

**Comment by Stophface** [comment]
@radex I am using [Q.unsafeSqlQuery](https://watermelondb.dev/Query.html#unsafe-sql-queries) to work around this.

**Comment by radex** [comment]
@Stophface TBH I don't understand wat issue you have. I tried reproducing it, but it works just fine.

Your first example had a syntax error, but Watermelon catches it. It does not produce the SQL you said it does.

**Comment by Stophface** [comment]
@radex Maybe the problem is on my side. I worked around it with `Q.unsafeSqlQuery` which works fine for my case. I am not seeing the downside of using `Q.unsafeSqlQuery` over the JS Syntax, so its fine for me. Closing this now :) Thanks for coming back!
