### ISSUE TITLE
NativeModules.DatabaseBridge is not defined

### ISSUE THREAD

**Issue by Fox333-Lab** [Nozbe/WatermelonDB#1408]
Hi All,

i am new to using watermelondb and now getting below 2 error when running in android emulator

**Note:** 
I am using react 60+, 0.69.6 to be precise
App is created using expo cli

![image](https://user-images.githubusercontent.com/67701997/194709795-3633725c-91ff-41da-877a-c3a26a69e932.png)

![image](https://user-images.githubusercontent.com/67701997/194709853-79c1d9e1-8b68-4117-8d2e-318127932839.png)

Can anybody help please,

Thanks in advance

**Comment by val089** [comment]
I have got the same problem

**Comment by mrfrigerio** [comment]
You have to install the SQLite module,  so, if you are using expo, run this line on terminal:
`npx expo install expo-sqlite`

**Comment by KrisLau** [comment]
https://github.com/Nozbe/WatermelonDB/pull/1249

**Comment by starfreck** [comment]
I started facing the same issue with  Expo 48.0.10 

"dependencies": {
    "@morrowdigital/watermelondb-expo-plugin": "^2.1.0",
    "@nozbe/watermelondb": "^0.25.5",
    "@pchmn/expo-material3-theme": "^1.0.1",
    "@react-native-community/masked-view": "^0.1.11",
    "@react-navigation/native": "^6.1.6",
    "@react-navigation/stack": "^6.3.16",
    "axios": "^1.3.5",
    "dotenv": "^16.0.3",
    "expo": "^48.0.10",
    "expo-constants": "~14.2.1",
    "expo-secure-store": "~12.1.1",
    "expo-splash-screen": "~0.18.1",
    "expo-sqlite": "~11.1.1",
    "expo-status-bar": "~1.4.4",
    "react": "18.2.0",
    "react-native": "0.71.6",
    "react-native-gesture-handler": "~2.9.0",
    "react-native-keyboard-aware-scroll-view": "^0.9.5",
    "react-native-safe-area-context": "^4.5.0",
    "react-native-screens": "^3.20.0",
    "react-native-svg": "13.4.0",
    "react-navigation": "^4.4.4",
  },

Does anyone know how to fix it?

**Comment by Usman-0250** [comment]
anybody fixed it ?

**Comment by KrisLau** [comment]
@Usman-0250 Everything related to this thread has been fixed as of the latest version of WatermelonDB if you read the thread linked on my old comment: https://github.com/Nozbe/WatermelonDB/issues/1408#issuecomment-1381916457.

**Comment by Usman-0250** [comment]
> npx expo install expo-sqlite

not work in expo

**Comment by KrisLau** [comment]
@Usman-0250 You just need to follow the instruction in the watermelonDB docs and make sure all your package versions (for expo and 🍉 ) are up to date. Also it doesnt work with new architecture yet if you are using jsi. Aside from that, no one can help you as you have not provided any information on your errors or setup.

**Comment by Usman-0250** [comment]
> @Usman-0250 You just need to follow the instruction in the watermelonDB docs and make sure all your package versions (for expo and 🍉 ) are up to date. Also it doesnt work with new architecture yet if you are using jsi. Aside from that, no one can help you as you have not provided any information on your errors or setup and the error described on this thread has been resolved

"@morrowdigital/watermelondb-expo-plugin": "^2.3.3",
    "@nozbe/watermelondb": "^0.27.1",
    "plugins": [
      "expo-font",
      ["@morrowdigital/watermelondb-expo-plugin"],
      [
        "expo-build-properties",
        {
          "android": {
            "kotlinVersion": "1.8.10",
            "packagingOptions": {
              "pickFirst": ["**/libc++_shared.so"]
            }
          }
        }
      ],
      "expo-router"
    ]
    npx expo install expo-build-properties
    and follow this page https://www.themorrow.digital/blog/how-to-use-watermelondb-with-react-native-expo and it is not work

**Comment by KrisLau** [comment]
@Usman-0250 Like I previously mentioned, the error described on this thread has been resolved so the issue is somewhere with your own setup. I would recommend using the official watermelon db to setup instead of the blog post and doing it in a brand new project to test. If you are still running into issues after that, create a new issue ideally with that fresh project linked.
