### ISSUE TITLE
Advanced Fields @json

### ISSUE THREAD

**Issue by daviddunnington** [Nozbe/WatermelonDB#1416]
is it possible to have a JSON field populated during sync? 

I have my model set up with this field like below, however, when I call the sync function to pull the data from our backend we get a null value in the bom field however all other fields populate fine. 

```
const sanitizeBom = (data: any) => data;

export default class Product extends Model {
  static table = 'products';

  @field('name') segment: string | undefined;
  @field('launch_date') launchDate: string | undefined;
  @field('expiry_date') expiryDate: string | undefined;
  @field('image') image: string | undefined;
  @json('bom', sanitizeBom) bom: any | undefined;
  @date('created_at') createdAt: number;
  @date('updated_at') updatedAt: number;
  @date('deleted_at') deletedAt: number | undefined | null;
}
```

**Comment by daviddunnington** [comment]
I managed to solve this, I had to update the API so the data returned was returned as a JSON string rather than an array.

**Comment by aledebla03** [comment]
could you give an example of the array formatted in a string? thanks
