### ISSUE TITLE
Swap Watermelon ID for one that comes from API

### ISSUE THREAD

**Issue by AndresdoSantos** [Nozbe/WatermelonDB#1417]
Hi guys, my question is simple, sorry for not following the question template.

I just want to know if there is a way I can change the ID that Watermelon creates for an ID that comes from my API or do I need to create another field in the schema that references the ID of my API (ex: idApi)?

**Comment by Yarkhan** [comment]
See https://nozbe.github.io/WatermelonDB/CRUD.html#advanced

> To override the record.id during the creation, e.g. to sync with a remote database, you can do it by record._raw property. Be aware that the id must be of type string.

```javascript
await database.get('posts').create(post => {
  post._raw.id = serverId
})
```

**Comment by ivanarifin** [comment]
Hi i still have some questions about this, how do i implement this in my sync function?

https://watermelondb.dev/docs/Sync/Frontend#using-synchronize-in-your-app

in here the changes from my api sends me an id of number, i want to use it in my watermelondb, even if it has to be converted to string
