### ISSUE TITLE
Where is the database stored in iOS?

### ISSUE THREAD

**Issue by azmainamin** [Nozbe/WatermelonDB#1434]
In Android, the WatermelonDB Sqlite is stored in /data/<packageName>/databases.

What is the path for iOS? 

Thank you!

**Comment by azmainamin** [comment]
Bumping this up again

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/blob/c4495f981db1e212be5db1c9779f60ffad62f073/native/ios/WatermelonDB/DatabaseDriver.swift

**Comment by azmainamin** [comment]
Hi @radex . I am a complete newbie to iOS dev. I looked over the file you shared but couldn't find the exact path. Any help would be welcome! 

I am trying to convince my team to use WatermelonDB and they are asking questions regarding the safety of data i.e. will other apps be able to access data stored in WatermelonDB? To answer that, I wanted to show them that WatermelonDB is being stored in the app container, and therefore, won't be exposed to other apps.

**Comment by ChrisSimoniMBT** [comment]
> Hi @radex . I am a complete newbie to iOS dev. I looked over the file you shared but couldn't find the exact path. Any help would be welcome!
> 
> I am trying to convince my team to use WatermelonDB and they are asking questions regarding the safety of data i.e. will other apps be able to access data stored in WatermelonDB? To answer that, I wanted to show them that WatermelonDB is being stored in the app container, and therefore, won't be exposed to other apps.

https://github.com/Nozbe/WatermelonDB/blob/c4495f981db1e212be5db1c9779f60ffad62f073/native/ios/WatermelonDB/DatabaseDriver.swift#L230

**Comment by azmainamin** [comment]
Thank you!

**Comment by ChrisSimoniMBT** [comment]
> Thank you!

I was also trying to figure this out and I'm not sure where that actually is. Looks like its the users home directory for "personal items" and not the app container(https://developer.apple.com/documentation/foundation/filemanager/1407693-url)? Either way, you can pass a custom path in the `dbName` parameter when you create your adapter.

**Comment by azmainamin** [comment]
> > Thank you!
> 
> I was also trying to figure this out and I'm not sure where that actually is. Looks like its the users home directory for "personal items" and not the app container(https://developer.apple.com/documentation/foundation/filemanager/1407693-url)? Either way, you can pass a custom path in the `dbName` parameter when you create your adapter.

I am not well versed in iOS development tbh. @radex would you be able to confirm this: ` Looks like its the users home directory for "personal items" and not the app container` ? It would be greatly appreciated!

**Comment by ChrisSimoniMBT** [comment]
> > > Thank you!
> > 
> > 
> > I was also trying to figure this out and I'm not sure where that actually is. Looks like its the users home directory for "personal items" and not the app container(https://developer.apple.com/documentation/foundation/filemanager/1407693-url)? Either way, you can pass a custom path in the `dbName` parameter when you create your adapter.
> 
> I am not well versed in iOS development tbh. @radex would you be able to confirm this: ` Looks like its the users home directory for "personal items" and not the app container` ? It would be greatly appreciated!

I have confirmed that databases are stored in /App/DSGSDF-dfsgDF-3453/Documents directory or w/e it is. I believe this would be in the "App Container" on iOS. Its the same directory you get from `FileSystem.documentDirectory` in Expo: https://docs.expo.dev/versions/latest/sdk/filesystem/#documendirectory
