### ISSUE TITLE
Doesn't work with `use_frameworks!` 

### ISSUE THREAD

**Issue by KrisLau** [Nozbe/WatermelonDB#1436]
RNFirebase now requires `use_frameworks!` which seems to cause a number of WatermelonDB errors when building like:
```
Could not build Objective-C module 'WatermelonDB'
```

![image](https://user-images.githubusercontent.com/46275463/202760116-1401671f-2cb8-46f6-bf8f-391be50dab79.png)

**Comment by radex** [comment]
#1285 duplicate
