### ISSUE TITLE
Throws Error

### ISSUE THREAD

**Issue by passionate2023** [Nozbe/WatermelonDB#1450]
Demo throws the following error https://watermelondb.now.sh/

Please provide a fix .....How to lookup for the demo in the project?

![image](https://user-images.githubusercontent.com/117767352/206622259-78b4e14d-2303-4ab6-8a5b-009082c47001.png)

**Comment by radex** [comment]
Duplicate: https://github.com/Nozbe/WatermelonDB/issues/1415
