### ISSUE TITLE
Copy type definitions for sync implementation files

### ISSUE THREAD

**Issue by ChrisSimoniMBT** [Nozbe/WatermelonDB#1454]
I'd like to make a custom sync implementation only rewriting the synchronize function to handle pulling changes differently. I believe this will be easily possible but I'm getting a bunch of missing type declaration file errors on imports. I also believe this is what docs meant by keeping your sync impl close to standard watermelondb sync.

It would be nice if we included these type definition files in the npm package so we can more easily reuse these core functions in our own sync.

If this isn't the proper way to go about this let me know.

**Comment by radex** [comment]
@ChrisSimoniMBT I think 0.25.x fixes it… if not, check out latest 0.26 pre-release, and please contribute if there's still something missing
