### ISSUE TITLE
Is this repo abandoned ?

### ISSUE THREAD

**Issue by paulrostorp** [Nozbe/WatermelonDB#1456]
Is this repo abandoned ? There has been very little activity of late, what is the status of this project ?

**Comment by paulrostorp** [comment]
I now see there have been a few pre-releases in the past year... I tried installing but I am facing several issues.

Are there any known blockers that prevent a release ?

**Comment by yashgada** [comment]
This is a goldmine of a project I think, I hope its not abandoned

**Comment by radex** [comment]
No, it's not abandoned, it's simply matured to the point that I rarely need to make modifications to it, and unfortunately I haven't had much time this year to improve on issues facing community users

**Comment by Dallas62** [comment]
Hi @radex,
Good to hear from you, I understand that you don't have many times but blocking issues should be fixed before micro optimisation (commit logs).
Specially: https://github.com/Nozbe/WatermelonDB/issues/1285
Regards

**Comment by Dallas62** [comment]
I can also mention this one: https://github.com/Nozbe/WatermelonDB/issues/1078
Both appear on installation step.

**Comment by paulrostorp** [comment]
There hasn't been any official release since over a year, only pre-releases (https://www.npmjs.com/package/@nozbe/watermelondb?activeTab=versions)

@radex Is this on purpose ? Are those pre-releases considered ready for production use ?

**Comment by radex** [comment]
@paulrostorp Not all of them are ready for production use, they are for internal uses. It's best to stick to the latest release unless you need one of the fixes/features in a prerelease

**Comment by paulrostorp** [comment]
@radex I see some features that I think would be valuable to many (especially on the migration functionality)/

I think the codebase could benefit from more community support/review if those features/fixes were made available to all 😄
