### ISSUE TITLE
Error using Kotlin 1.7

### ISSUE THREAD

**Issue by MarcoAurelioPosControle** [Nozbe/WatermelonDB#1467]
Using React Native "0.70.6" and watermelondb "0.24.0" I got Kotlion version error.

I made some changes on file "gradle.properties" in "node_modules\@nozbe\watermelondb\native\android"

ReactNativeWatermelonDB_kotlinVersion=1.7.20 // <- line changed
ReactNativeWatermelonDB_compileSdkVersion=28
ReactNativeWatermelonDB_buildToolsVersion=28.0.3
ReactNativeWatermelonDB_targetSdkVersion=28
ReactNativeWatermelonDB_minSdkVersion=16

After this got this error 

node_modules\@nozbe\watermelondb\native\android\src\main\java\com\nozbe\watermelondb\DatabaseDriver.kt: (18, 9): 'when' expression must be exhaustive, add necessary 'Compatible' branch or 'else' branch instead

I made more changes on the file "DatabaseDriver.kt" in "node_modules\@nozbe\watermelondb\native\android\src\main\java\com\nozbe\watermelondb"

    constructor(context: Context, dbName: String, schemaVersion: SchemaVersion) :
            this(context, dbName) {
        when (val compatibility = isCompatible(schemaVersion)) {
            is SchemaCompatibility.NeedsSetup -> throw SchemaNeededError()
            is SchemaCompatibility.NeedsMigration ->
                throw MigrationNeededError(compatibility.fromVersion)
            else -> throw AssertionError() // <- Inserted line
        }
    }
    
    
After this changes I was able to run the app.

**Comment by awalmubarak** [comment]
After hours of battling with this, your solution finally worked for me. Thanks for sharing.
I'll like to point out that it didn't work on version `0.24.1-10` (which I ended up installing trying to find a solution to this).
I had to switch back to version `0.24.0` to get your solution to work.

**Comment by radex** [comment]
@MarcoAurelioPosControle @awalmubarak This is an issue when compiling under Kotlin 1.7. You can downgrade to 1.5, patch this one line, and there will be a proper fix in 🍉 0.25.2: https://github.com/Nozbe/WatermelonDB/commit/59bf79a0b4cd52c203b6105b9b6d82a21ac9e590
