### ISSUE TITLE
v0.25.2 - TypeError: undefined is not an object (evaluating 'this.map')

### ISSUE THREAD

**Issue by Dallas62** [Nozbe/WatermelonDB#1505]
The version 0.25.2 introduce a regression from 0.25.1, the same code `new WatermelonDatabase(...)` produce an Unhandled Promise Rejection.

```js
    const adapter = new SQLiteAdapter({
      schema,
      migrations,
      jsi: true,
    })

    this.database = new WatermelonDatabase({
      adapter:adapter,
      modelClasses: [
        ...Models
      ],
    });
```

Produce:
```
undefined is not an object (evaluating 'this.map') [TypeError: undefined is not an object (evaluating 'this.map')]
 WARN  Possible Unhandled Promise Rejection (id: 0):
TypeError: undefined is not an object (evaluating 'this._init')
```

**Comment by radex** [comment]
@Dallas62 Can you verify if `0.25.3-0` works on your configuration?

**Comment by enahum** [comment]
@radex 025.3-0 is working for me, 25.2 was throwing the `map` undefined error

**Comment by radex** [comment]
Apologies for the mixup, it slipped through the cracks while testing, I'll release 0.25.3 shortly

**Comment by Dallas62** [comment]
Thanks, will test tomorrow!
