### ISSUE TITLE
Diagnostic error: NativeModules.DatabaseBridge is not defined (after upgrading to react-native: 0.71.1)

### ISSUE THREAD

**Issue by marvanov** [Nozbe/WatermelonDB#1508]
First of all, thank you for the quality product!😉

Versions:
     "react-native": "0.70.4",
     "@nozbe/watermelondb": "^0.24.0",
worked, but after upgrading to versions:
     "react-native": "0.71.1",
     "@nozbe/watermelondb": "^0.25.3",
emulation on an **android** device gives an error:

**Diagnostic error: NativeModules.DatabaseBridge is not defined! This means that you haven't properly linked WatermelonDB native module. Refer to docs for more details**

What can I do about it? Thanks!

**Comment by pmtu95** [comment]
I have the same issue, seems like version > 0.25.0 missing auto-link, you can link manually or downgrade to version 0.24.0

**Comment by radex** [comment]
Please follow the manual linking guide, I'll fix auto linking in 0.25.5 later today/tomorrow

**Comment by radex** [comment]
@pmtu95 @marvanov @bennygenel @yuri-lomashko-itechart Please confirm that 0.25.5 fixes this issue

**Comment by bennygenel** [comment]
@radex I can confirm that 0.25.5 fixes this issue for me.

**Comment by marvanov** [comment]
@radex Everything is great now, thank you so much!

**Comment by Mubashir-rehma** [comment]
I'm also on `"@nozbe/watermelondb": "^0.27.1"` and facing similler issue. am using expo

**Comment by mcnaveen** [comment]
This is how I resolved the issue.

After installing the dependencies, I removed the installed app via adb shell and ran the start command again. 

It seems to be working just fine. Also, I got this in Terminal.

It's always a good idea to reinstall the development application when you setup deps which has a native bridge.

![image](https://github.com/Nozbe/WatermelonDB/assets/8493007/84fa8008-40e5-4cd3-87d6-97384646bc58)

**Comment by farhadjaman** [comment]
> This is how I resolved the issue.
> 
> After installing the dependencies, I removed the installed app via adb shell and ran the start command again.
> 
> It seems to be working just fine. Also, I got this in Terminal.
> 
> ![image](https://private-user-images.githubusercontent.com/8493007/305123040-84fa8008-40e5-4cd3-87d6-97384646bc58.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDk4NjQ1OTAsIm5iZiI6MTcwOTg2NDI5MCwicGF0aCI6Ii84NDkzMDA3LzMwNTEyMzA0MC04NGZhODAwOC00MGU1LTRjZDMtODdkNi05NzM4NDY0NmJjNTgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDMwOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDAzMDhUMDIxODEwWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NGY4Njc0ZTU4NDJjZTc1ZDk0MjdiNzgwYmRkMDVkMWIzN2I4ZTBiMDgxYWFmZGQ2NzgyZDdkZjgxZDE3MGMxMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.lZOPCeGObhCQjVli2BiL97nnjOZyFg3EDExb7DdQZNo)
> 
> It's always a good idea to reinstall the development application when you setup dependencies which has a native bridge.

Hi, I wanted to run it on development mode, rather than installing it everytime i need to debug it. Have you found any solution for that?

**Comment by Usman-0250** [comment]
I am getting same issue in `^0.27.1` version, any one please help here

**Comment by Felipe-G-Melo** [comment]
@Mubashir-rehma 
Consegui resolver o erro na versão 0.27.1 seguindo os seguintes passos: 
1. No arquivo `android/settings.gradle` adicionei essas linhas 
```
include ':react-native-watermelondb'
project(':react-native-watermelondb').projectDir = new File(rootProject.projectDir, '../node_modules/@nozbe/watermelondb/native/android')
```
![image](https://github.com/user-attachments/assets/387a2d40-eb51-4c60-842f-264179ddda50)

2. Depois no arquivo `android/app/build.gradle`
```implementation project(':react-native-watermelondb')```
![image](https://github.com/user-attachments/assets/d2b2a440-e0b7-474e-b227-0e2c6d32bfab)

3. Por fim no arquivo `MainApplication.kt`
```
import com.nozbe.watermelondb.WatermelonDBPackage;
override fun getPackages(): List<ReactPackage> {
  val packages = PackageList(this).packages
  // Packages that cannot be autolinked yet can be added manually here, for example:
  // packages.add(new MyReactNativePackage());
  packages.add(WatermelonDBPackage());
  return packages
}
```
![image](https://github.com/user-attachments/assets/c46661b3-9511-4519-8a73-549463091cb1)
