### ISSUE TITLE
TypeError: Attempted to assign to readonly property. only on IOS

### ISSUE THREAD

**Issue by devleul** [Nozbe/WatermelonDB#1525]
I was building a native React app that makes use of WatermelonDb. On Android, adding and updating records is doable without any problem; but, on iOS, I receive the following error and unable to edit record?

`TypeError: Attempted to assign to readonly property. only on IOS`

The code I use to update record: 

`export const editDataDB = async (data, id) => {
  try {  
    let pre = await database.collections.get("sample").find(id);
    if (pre) {
      await database.write(async () => {
        await pre.update((entry) => {
          entry.name = data.name;
        });
      });
    }
  } catch (e) {}
}`

Schema: 
`tableSchema({
      name: "sample",
      columns: [
        { name: "name", type: "string" },
        { name: "updated_at", type: "number" },
      ],
    }),`

Model: 
`export default class Sample extends Model {
  static table = "sample";
  @text("name") name;
  @readonly @date("updated_at") updatedAt;
}`

my environment: 
react-native: 0.69.7
@nozbe/watermelondb": "^0.25.5"

**Comment by Puneet-Chicmic** [comment]
Hi @devleul , can you please share how did you resolve this issue? I am also getting issue only in IOS regarding 'Attempted to assign to readonly property'.
