### ISSUE TITLE
Problem with RN new architeture and JSI Module: Unable to find JSIModule for class UIManager

### ISSUE THREAD

**Issue by truediogo** [Nozbe/WatermelonDB#1526]
When i try to use Watermelon JSI Module with new React Native Architeture/Fabric i get the following error when i open the app in android:

**Unable to find JSIModule for class UIManager**

![Captura de Tela 2023-02-06 às 10 00 45](https://user-images.githubusercontent.com/53327356/216977845-d409a26d-5ded-464b-b3b9-a07cd270b697.png)

Without the JSI Module override in MainApplication.java the application works

-  "react-native": "0.71.2"
-  "@nozbe/watermelondb": "0.25.5"

**Comment by radex** [comment]
@truediogo https://github.com/Nozbe/WatermelonDB/issues/1386
