### ISSUE TITLE
Supporting react-native 0.7X.X

### ISSUE THREAD

**Issue by KevinBrustolin** [Nozbe/WatermelonDB#1529]
Hello,

I'm not able to have watermelondb working, does it support react-native 0.71.2. ?

Thanks.

**Comment by radex** [comment]
yes

**Comment by KevinBrustolin** [comment]
My problems came from two things : 

First, in the documentation, `2.2.2 Setup` is using default export for the schema, and then in `2.2.3 Schema` it's using named export so adapter in `index.js` file was causing an error `Invariant Violation: "AwesomeProject" has not been registered` because scheme wasn't defined.

Second, I had to import withObservables module from `import withObservables from '@nozbe/watermelondb/node_modules/@nozbe/with-observables';` not from `import withObservables from '@nozbe/with-observables'`
