### ISSUE TITLE
<jsc/JSCRuntime.h> not found

### ISSUE THREAD

**Issue by mbpictures** [Nozbe/WatermelonDB#1538]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@nozbe/watermelondb@0.24.0` for the project I'm working on.

After upgrading to react-native version 0.71.3 I got a compile error, that the file "jsc/JSCRuntime.h" couldn't be found.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp b/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp
index b920271..47ed5a9 100644
--- a/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp
+++ b/node_modules/@nozbe/watermelondb/native/android-jsi/src/main/cpp/JSLockPerfHack.cpp
@@ -1,5 +1,5 @@
 #include "JSLockPerfHack.h"
-#include <jsi/JSCRuntime.h>
+#include <jsc/JSCRuntime.h>
 
 using namespace facebook;
 
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by radex** [comment]
fixed in 0.25
