### ISSUE TITLE
Re-rendering observed list component after row id update (trigger withObservables manually?)

### ISSUE THREAD

**Issue by maXXCZ1** [Nozbe/WatermelonDB#1541]
Hi,

back with more complex (and i believe interesting) problem than last time:

Let's say i have standard observed list which uses Flatlist to render Items like so:

```
export const FavList= withObservables(
  ["user"],
  ({user}) => {
    return {
      userFavouriteUsers: database
        .get("user_favourite_user")
        .query(
          Q.where("user_id", user.id),
          Q.where("_status", Q.notEq("deleted")),
        ),
    };
  },
)(ListRaw);
```

My problem is, that our back end is **updating WM id's** to ours after sync. 
I know, it is not recommended, i can't do nothing about it for now.

Sou if i add item to the list, list has new item with WM id: 
`asddfg123456asd`
New item is present, list is re-rendered, everything is fine.

I stay on the FlatList screen, so withObservables are not re-triggered.
But when i try to remove item, i remove item which now (because sync finished "as we speak") has id for example: `5086`
Item is removed. List is re-rendered.
**BUT**
In cache there is still original item with id `asddfg123456asd` hanging.
So if i decide to add same item again, i suddenly have two same rows in list, both with WM ids (sync for doubled item has not finished yet).

The flow in console looks like this:
We entered list of items with some synced IDs:

```
 LOG  item ID 4889
 LOG  item ID 4529
 LOG  item ID 5139
 LOG  item ID 5865
 LOG  item ID 5225
```

We added new item to the list (sync is not finished yet).

```
 LOG  item ID 4889
 LOG  item ID 4529
 LOG  item ID 5139
 LOG  item ID 5865
 LOG  item ID 5225
 LOG  item ID fh1akwz9ueqjaaaa
```

We removed the item with ID 5086:

```
 LOG  item ID 4889
 LOG  item ID 4529
 LOG  item ID 5139
 LOG  item ID 5865
 LOG  item ID 5225
 LOG  item ID fh1akwz9ueqjaaaa
```

We add same item again:
```
 LOG  item ID 4889
 LOG  item ID 4529
 LOG  item ID 5139
 LOG  item ID 5865
 LOG  item ID 5225
 LOG  item ID fh1akwz9ueqaaaa
 LOG  item ID at85b8aso4aaaaa
```

So, basically. If i remove the item, it will be removed, but all these hanging cached rows will be there and adding one to another.
Question is, how to ged rid of these?

I ran through documentation as well as issues here.
Tried `observeWithColumns`, tried `unsafeClearCachedRecords`.

I tried to set state in  `<Parent />` and set it as "dependency" for observable like so:

```
const Parent = () => {
const [forceRefresh, serForceRefresh] = useState(false);

return (
<FavList user={user} forceRefresh={forceRefresh} setForceRefresh={setForceRefresh}/>
)
}
```

```
export const FavList= withObservables(
  ["user, forceRefresh"],
  ({user, forceRefresh}) => {
    return { ...
```
then setForceRefresh(prevState => !prevState) from child in hope of "manually" trigger withObservable.
I observed each item in renderItem function of Flatlist.
No luck.
When i leave screen with list and enter egain (re-trigger withobservables) everything is correctly loaded and cached.

Is there any straight or hacky way to solve this? I am running out of ideas.

Thank you for your time.

**Comment by ororsatti** [comment]
your id in the backend are increamental? if not, cant you just replace the default id generator in wmdb to one of yours and tous not change the id in the backend

**Comment by radex** [comment]
there's no "correct" way to do this, because Watermelon doesn't officially support changing record's IDs.

some hacks you can try:

1. You can add `joins, sortBy, take, skip` to your query to force observation to be in "reload on changes" mode. this should remove unwanted items from the list.

2. `collection._cache.map.remove(id)`

**Comment by maXXCZ1** [comment]
Thank you for help.

What @ororsatti suggested is not possible to implement in our situation, despite being interesting alternative.

I went with least violent solution (in my opinion) that @radex suggested in his first point, which is actually similar to solution i already came up with. I just struggle to generalize it for now, but here is the basic idea if anyone in future will run into similar problem.

The idea behind this is, that count is always observed **correctly**, but model(s) are hanging in cache. So we observe both query for some table and count for this exact query as well. Then we compare both in child's useEffect and trigger observable manually with use of take, whenever it happens.

Parent:
```
const Parent = () => {
const [take, setTake] = useState(100);

return (
<FavList user={user} take={take} setTake={setTake} />
)
}
```
```
Observables:
export const FavList= withObservables(
  ["user, take"],
  ({user, take}) => {
    return {
      userFavouriteUsers: database
        .get("user_favourite_user")
        .query(
          Q.where("user_id", user.id),
          Q.where("_status", Q.notEq("deleted")),
          Q.take(take), // <=============== Important trigger
        ),
         userFavouriteUsersCount: database
        .get("user_favourite_user")
        .query(
          Q.where("user_id", user.id),
          Q.where("_status", Q.notEq("deleted")),
          Q.take(take),
        ).observeCount(false),
    };
  },
)(ListRaw);
```

```
Child:
const ListRaw= (user, userFavouriteUsers, userFavouriteUsersCount, setTake ) => {

const focused = isFocused(); //Trigger useEffect whenever we focus screen

 /*other code */

  useEffect(() => {
    if (userFavouriteUsers?.length !== userFavouriteUsersCount) {
      setTake((prevState) => prevState + 5);
    }
  }, [userFavouriteUsers, isFocused, userFavouriteUsersCount]);

return <PerfectlyObservedFlatlist data={data} renderItem={renderITem} .../>
}
```

**Comment by radex** [comment]
That's not what I meant with adding `take` - just that adding it at all (without changing it) should be enough to force full data fetch.

But there's one more thing you can try - instead of doing `.observe()`, try `.observeWithColumns(['id'])`. I guess if the only thing that changes is the id, the query won't re-fetch
