### ISSUE TITLE
Test a watermelondb

### ISSUE THREAD

**Issue by popo63301** [Nozbe/WatermelonDB#155]
Hi guys ! 

This project looks amazing. I would like to know if you have planned to help people test a watermelonDB? As it requires an interaction with a local SQLite DB or Indexeddb, how about creating an official mock for watermelonDB so that people can test their app using Jest?

**Comment by radex** [comment]
@popo63301  Testing with Jest works :)

**Comment by radex** [comment]
closing this; let me know if you're having troubles running Watermelon in Jest env

**Comment by sidferreira** [comment]
Not working for me :/

**Comment by lucianomlima** [comment]
@radex can give an example? How to mock?

**Comment by sidferreira** [comment]
I suggest you use SQLite memory when testing the DB...

**Comment by stylder** [comment]
.

**Comment by JeandeCampredon** [comment]
Any news on that ?

**Comment by sidferreira** [comment]
Will share a workaround later

**Comment by yan-brito** [comment]
hi guys, can someone give a mock example please?

**Comment by filipepiresg** [comment]
hi guys, can someone give a mock example please?

**Comment by craigmulligan** [comment]
I've been using the node.js adapter mocking it via jest.

```javascript
jest.mock(
  '@nozbe/watermelondb/adapters/sqlite/makeDispatcher/index.native.js',
  () => {
    return jest.requireActual(
      '@nozbe/watermelondb/adapters/sqlite/makeDispatcher/index.js',
    );
  },
);
```

It's been working great! You can see some notes on my full setup here: https://craigmulligan.com/posts/testing-with-watermelon/

Happy to submit a PR for docs or a jest module folks can include to automatically do the mocking if the maintainers are interested?

**Comment by shahulul1** [comment]
I am getting Error when I using 
const syncStoreMaster = database.get<SyncStoreMaster>('sync_store_master'),
jest.spyOn(syncStoreMaster,'query').mockImplementations(()=> Promise.resolve([]))
 Cannot use spyOn on a primitive value; undefined given? anyone can give an example for mocking the data on table ?

**Comment by craigmulligan** [comment]
@shahulul1, have you tried mocking it with sqlite3? see [my comment above](https://github.com/Nozbe/WatermelonDB/issues/155#issuecomment-1544596172)
