### ISSUE TITLE
@text decorator discards trailing newlines

### ISSUE THREAD

**Issue by arcln** [Nozbe/WatermelonDB#1560]
https://github.com/Nozbe/WatermelonDB/blob/e9e1c34cd5b5d200a0df36305db49a283a01c8a8/src/decorators/text/index.js#L34

Why is `.trim()` called here ?

**Comment by ororsatti** [comment]
I don't know the reason behind, but I can only guess its to conserve space.
empty whitespaces don't have any actual meaning, and are taking the same space as a normal char would. if you want to mark a white space you can explicitly define it using ascii representation. 
If you want to allow it, you can define @json decorator and pass your sanitizer

**Comment by radex** [comment]
@arcln  `@text` is meant to be used as a convenience. for user-provided text, and hence can be expected to do things like trimming or normalizing. If you do not wish for this behavior, simply use `@field`, which does not add any magic behavior.
