### ISSUE TITLE
is there a forecast when watermelon will support react-native-windows?

### ISSUE THREAD

**Issue by Victor0814gui** [Nozbe/WatermelonDB#1568]
I have an rnw application that needs an offline database implementation, but for android and ios I am already using watermelon, and I need this implementation to also work for windows, what should I do to extend this compatibility

**Comment by radex** [comment]
@Victor0814gui there's no forecast - but you can implement it yourself. here's the instructions you might need: https://github.com/Nozbe/WatermelonDB/blob/master/docs-website/docs/docs/Implementation/DatabaseAdapters.md#adding-new-react-native-operating-systems
