### ISSUE TITLE
Limitations on Pull Changes

### ISSUE THREAD

**Issue by AndresGX** [Nozbe/WatermelonDB#1572]
I'm trying to pull a data to sync on my device with payload of 27.11 MB when `synchronize` is executed with that I got this error

### Error
`RangeError: Maximum call stack size exceeded `

![image](https://user-images.githubusercontent.com/87664730/227280180-983f8cfd-c829-4328-ad0e-83134c082985.png)

Watermelon has any limitations to pull data or any way to sync that info by chunks or another way?

**Comment by radex** [comment]
@AndresGX Try latest 0.26 pre-release - https://github.com/Nozbe/WatermelonDB/blob/master/CHANGELOG-Unreleased.md -- it should fix the problem you're experiencing

**Comment by ebnersilva** [comment]
This works for me @radex . Thanks!
