### ISSUE TITLE
Automatic create/update tracking does not work for synced records

### ISSUE THREAD

**Issue by bradpurchase** [Nozbe/WatermelonDB#1586]
I am using automatic create/update tracking in my database and I've noticed that records where `status == "synced"` do not appear to save `created_at`/`updated_at` values. For any `created` or `updated` record these values are persisted as expected, but synced records all have values of `0.0` for both.

Feel free to close this if this is intentional (perhaps the idea is that synced records should get their `created_at`/`updated_at` value from the remote DB?), but it seems like it could be a bug given that newly synced records are technically created when they are persisted in the database (though also could be a false assumption). Thanks!

**Comment by radex** [comment]
No, that should (and does) work without trouble. Are you sure that it isn't your sync giving you new values of created_at/updated_at ?

**Comment by bradpurchase** [comment]
Thanks for confirming, I think this must be some issue with my sync/backend.
