### ISSUE TITLE
LokiWebWorker is not a constructor

### ISSUE THREAD

**Issue by mmaass** [Nozbe/WatermelonDB#1622]
Expo 48, watermelonDB 0.25.5. Android and iOS integration works. React Native Web integration via expo webpack does not work.

The current error is this 
<img width="450" alt="Screenshot 2023-07-07 at 14 51 07" src="https://github.com/Nozbe/WatermelonDB/assets/576477/332f880a-7e83-4c4f-9c01-0d67302d483a">

When debugging the LokiWebWorker has the value of the global window object
<img width="1338" alt="Screenshot 2023-07-07 at 15 04 25" src="https://github.com/Nozbe/WatermelonDB/assets/576477/c6be9f29-8361-4c02-a9af-5d917b4ff7aa">

I'm not even sure were to begin tackling this issue. 😥

**Comment by radex** [comment]
Try `useWebWorker: false` ?

**Comment by mmaass** [comment]
Tnx, this did the trick.
