### ISSUE TITLE
Are the benefits of lazy loading lost when using the Loki adapter?

### ISSUE THREAD

**Issue by hyperparsa** [Nozbe/WatermelonDB#164]
Asking since Loki describes itself as a in-memory database.

**Comment by radex** [comment]
Yes, some of the benefits are indeed lost. The primary use case is still React Native, where you have full lazy loading. On the web, the data will be fetched to JS code at launch, but it still happens asynchronously on a separate thread, and the hardest processing is still done on demand. So there still should be a benefit, but I haven't benchmarked against other web-only frameworks.

Let me know if you have more questions about this, and I'll reopen
