### ISSUE TITLE
Android broken build on React Native 072.3

### ISSUE THREAD

**Issue by tayyab-135** [Nozbe/WatermelonDB#1641]
Android build failed did not work with react native stable version

follow all steps that mentioned in documation with and without auto linking

**Comment by noelzappy** [comment]
> Android build failed did not work with react native stable version
> 
> follow all steps that mentioned in documation with and without auto linking

@tayyab-135 The latest version of React Native as at now is `0.72.3` and not `0.73.2` is that what you meant?

**Comment by tayyab-135** [comment]
i fixed this issue as conflicts in gradle and kotlin version  

it works for following versions
react native : 0.73.2
watermelondb: "^0.26.0",
kotlinVersion = '1.6.21'
classpath 'com.android.tools.build:gradle:7.1.2'
Without native code

**Comment by tayyab-135** [comment]
> > Android build failed did not work with react native stable version
> > follow all steps that mentioned in documation with and without auto linking
> 
> @tayyab-135 The latest version of React Native as at now is `0.72.3` and not `0.73.2` is that what you meant?

yes it's 0.72.3

**Comment by mattjbrill** [comment]
I know this issue was closed, but for anyone that finds themselves here, this may be a possible resolution: https://github.com/Nozbe/WatermelonDB/issues/1653#issuecomment-1699796264
