### ISSUE TITLE
How to set up with react native despite properly linking in android as per watermelon documentation.

### ISSUE THREAD

**Issue by krishkam** [Nozbe/WatermelonDB#1650]
Constantly running into an issue while compiling my react native application after installing watermelondb, hence build is failing afterwards forever.

FAILURE: Build failed with an exception.

* What went wrong:
Some problems were found with the configuration of task ':watermelondb:packageDebugResources' (type 'MergeResources').
  - Gradle detected a problem with the following location: 'C:\Users\xxx\node_modules\@nozbe\watermelondb\native\android\build\generated\res\rs\debug'.

    Reason: Task ':watermelondb:packageDebugResources' uses this output of task ':nozbe_watermelondb:compileDebugRenderscript' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':nozbe_watermelondb:compileDebugRenderscript' as an input of ':watermelondb:packageDebugResources'.
      2. Declare an explicit dependency on ':nozbe_watermelondb:compileDebugRenderscript' from ':watermelondb:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':nozbe_watermelondb:compileDebugRenderscript' from ':watermelondb:packageDebugResources' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.
  - Gradle detected a problem with the following location: 'C:\Users\Krishan Bhardwaj\Desktop\UI_Proj\patientmobile\node_modules\@nozbe\watermelondb\native\android\build\generated\res\resValues\debug'.

    Reason: Task ':watermelondb:packageDebugResources' uses this output of task ':nozbe_watermelondb:generateDebugResValues' without declaring an explicit or implicit dependency. This can lead to incorrect results being produced, depending on what order the tasks are executed.

    Possible solutions:
      1. Declare task ':nozbe_watermelondb:generateDebugResValues' as an input of ':watermelondb:packageDebugResources'.
      2. Declare an explicit dependency on ':nozbe_watermelondb:generateDebugResValues' from ':watermelondb:packageDebugResources' using Task#dependsOn.
      3. Declare an explicit dependency on ':nozbe_watermelondb:generateDebugResValues' from ':watermelondb:packageDebugResources' using Task#mustRunAfter.

    Please refer to https://docs.gradle.org/8.0.1/userguide/validation_problems.html#implicit_dependency for more details about this problem.

this is my config in app/build.gradle

buildscript {
    ext {
        buildToolsVersion = "33.0.0"
        minSdkVersion = 21
        compileSdkVersion = 33
        targetSdkVersion = 33
       kotlinVersion = "1.6.0"
        // kotlinVersion = "1.6.21"
        // We use NDK 23 which has both M1 support and is the side-by-side NDK version from AGP.
        ndkVersion = "23.1.7779620"
        multiDexEnabled = true // add this

and  my react versions are  
    "react": "18.2.0",
    "react-native": "^0.72.1",

1. is it even compatible with 0.72.1 react-native?

**Comment by krishkam** [comment]
Closed this issue as it required no manual linking with latest version of reactive native mine is 0.72. i removed all the code i tried to link in the app gradles files and settings.gradle after which it started working after compilation successfully hence closing here.

**Comment by HECHONG999** [comment]
are you sure you are using react-native  is 0.72?  it can't work normally.

**Comment by eoisaac** [comment]
> are you sure you are using react-native is 0.72? it can't work normally.

I did the same as @krishkam, I'm using RN 0.72.5 with Expo. I had tryied to manual linking  and didn't build. I just rollback all the code that i added in `android/settings.gradle`, `android/app/build.gradle` and `../MainApplication.java` and start working.
