### ISSUE TITLE
Is data storage on LokiJSAdapter persistent for RN Windows?

### ISSUE THREAD

**Issue by ransfordnyarko** [Nozbe/WatermelonDB#1655]
I am currently able to sync data on React Native windows app, however after the closing the application and opening it the data that has been synced disappears. However the models are present and I am still able to run queries but my database is empty on opening the application for a second time. I want to find out if data storage on LokiJS is persistent and the configuration required to keep it persistent

**Comment by radex** [comment]
LokiJSAdapter is meant to be used on the web mostly. It does work in Node and RN, but there's no persistence set up in these environments, so it's in-memory only. You definitely want to use SQLiteAdapter

**Comment by ransfordnyarko** [comment]
Thank you
