### ISSUE TITLE
Failed to run, after upgrade react native to 0.73.0-rc.3

### ISSUE THREAD

**Issue by foneazmi** [Nozbe/WatermelonDB#1695]
After upgrade version react native got this issue
<img width="1234" alt="image" src="https://github.com/Nozbe/WatermelonDB/assets/26783512/964f0b9f-c373-4a30-8525-4cbe38a3b774">

**Comment by jahead** [comment]
Same issue as over here
https://github.com/greentriangle/react-native-leveldb/pull/25

**Comment by foneazmi** [comment]
hi @jahead 

saw your pull request on react native leveldb
I already add namespace but still got this issue

![image](https://github.com/Nozbe/WatermelonDB/assets/26783512/74a29844-0f70-4cdf-9ec7-0b2283717a39)

**Comment by foneazmi** [comment]
Hi @zkteco-home 

test on latest stable react native, work smoothly
no need to change anything
