### ISSUE TITLE
Followed Supabase Blog For Watermelon Setup, But throwing Bridge is Null errors

### ISSUE THREAD

**Issue by RaghavBhat02** [Nozbe/WatermelonDB#1700]
So I followed this blog post: https://supabase.com/blog/react-native-offline-first-watermelon-db, but I have not been able to get it working. After copying over the settings from the "Setting up WatermelonDB native dependencies" portion, I followed the setup portion of the Watermolon docs, and created schemas and models, following the watermelon docs. I didn't go past "Setting up WatermelonDB native dependencies"

But my app, now simply errors out, not sure why the bridge would be null:
![image](https://github.com/Nozbe/WatermelonDB/assets/66137961/f9dc34a3-2fe0-4be2-b3c3-344981f9500b)

**Comment by SashaGoncharov19** [comment]
Bump. Same error.

**Comment by thiagobrez** [comment]
@RaghavBhat02 @SashaGoncharov19 Follow the Watermelon docs installation instead of the article

Instead of adding the config to `app.json` as the article suggests, you can generate the native directories with `npx expo prebuild`, and then add the dependencies to the `Podfile` in  [2. Link WatermelonDB's native library (using CocoaPods)](https://watermelondb.dev/docs/Installation#ios-react-native)

**Comment by RaghavBhat02** [comment]
will that mean I have to make my project no longer an expo managed project? so that I can access the podfile?

**Comment by ozanmakes** [comment]
@RaghavBhat02 I think you need to use custom dev client after following this tutorial, with a command such as `eas build --profile development --platform ios` (assuming you have set up your eas.json). This way the necessary native modules will be included in your custom expo client build.

Documentation:
https://docs.expo.dev/develop/development-builds/introduction/
https://docs.expo.dev/develop/development-builds/create-a-build/

This is the full source code for the app in the article you linked. This will give you more pointers:https://github.com/bndkt/sharemystack/
