### ISSUE TITLE
cant resolve module ../observable from node_modules/rxjs ....

### ISSUE THREAD

**Issue by lasway** [Nozbe/WatermelonDB#1710]
when i use this codes 
const adapter = new SQLiteAdapter({
  schema,
  migrations,
  // jsi: true, /* Platform.OS === 'ios' */
  // (optional, but you should implement this method)
  onSetUpError: error => {
    // Database failed to load -- offer the user to reload the app or log out
  }
})

// Then, make a Watermelon database from it!
export const database = new Database({
  adapter,
  modelClasses: [
    OptionModel,
    ProductStockHistoryModel,
    ProductStockModel,
    SpecialProductModel,
    SupplierModel,
    AddoProductModel,
    SaleModel,
    ProductSaleModel,
    ExpenseModel,
  ],
})

im getting the error that some file doesnot exist while if i comment those lines the project runs perfectly

here is the error im getting
error: Error: Unable to resolve module ../../Observable from C:\Users\DELL\Desktop\projects\addo-app\node_modules\rxjs\dist\cjs\internal\observable\dom\animationFrames.js:

None of these files exist:
  * node_modules\rxjs\dist\cjs\internal\observable(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\rxjs\dist\cjs\internal\observable\index(.native|.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  2 | Object.defineProperty(exports, "__esModule", { value: true });
  3 | exports.animationFrames = void 0;
> 4 | var Observable_1 = require("../../Observable");
    |                             ^
  5 | var performanceTimestampProvider_1 = require("../../scheduler/performanceTimestampProvider");
  6 | var animationFrameProvider_1 = require("../../scheduler/animationFrameProvider");
  7 | function animationFrames(timestampProvider) {
    at ModuleResolver.resolveDependency (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:137:15)
    at DependencyGraph.resolveDependency (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\node-haste\DependencyGraph.js:260:43)
    at Object.resolve (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\lib\transformHelpers.js:177:21)
    at Graph._resolveDependencies (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:432:35)
    at Graph._processModule (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:218:38)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async Graph._addDependency (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:314:20)
    at async Promise.all (index 3)
    at async Graph._processModule (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:263:5)
    at async Graph._addDependency (C:\Users\DELL\desktop\projects\addo-app\node_modules\react-native\node_modules\metro\src\DeltaBundler\Graph.js:314:20)

**Comment by lucaswitch** [comment]
Please remove your node-modules and package-lock.json and force a full reinstall of the system, and let us know if it helps.

**Comment by lucaswitch** [comment]
> Please remove your node-modules and package-lock.json and force a full reinstall of the system, and let us know if it helps.
This library requires 7.8.0 that should be automatically installed when watermelon is installed, for some reason the rxjs is not (present?) on your installation.

**Comment by Syed-Hasnain-Askari** [comment]
When I use this code in index.js fie in react native

`
import { Amplify } from 'aws-amplify';
import amplifyconfig from './src/amplifyconfiguration.json';
Amplify.configure(amplifyconfig);
`
I'm getting error like this

error: Error: Unable to resolve module ./internal/operators/timeout from E:\eventual-mvp-app\node_modules\rxjs\dist\cjs\index.js:

None of these files exist:
  * node_modules\rxjs\dist\cjs\internal\operators\timeout(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  * node_modules\rxjs\dist\cjs\internal\operators\timeout\index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
  77 | var SequenceError_1 = require("./internal/util/SequenceError");
  78 | Object.defineProperty(exports, "SequenceError", { enumerable: true, get: function () { return SequenceError_1.SequenceError; } });
> 79 | var timeout_1 = require("./internal/operators/timeout");
     |                          ^
  80 | Object.defineProperty(exports, "TimeoutError", { enumerable: true, get: function () { return timeout_1.TimeoutError; } });
  81 | var UnsubscriptionError_1 = require("./internal/util/UnsubscriptionError");
  82 | Object.defineProperty(exports, "UnsubscriptionError", { enumerable: true, get: function () { return UnsubscriptionError_1.UnsubscriptionError; } });
    at ModuleResolver.resolveDependency (E:\eventual-mvp-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:127:15)
    at DependencyGraph.resolveDependency (E:\eventual-mvp-app\node_modules\metro\src\node-haste\DependencyGraph.js:271:43)
    at E:\eventual-mvp-app\node_modules\metro\src\lib\transformHelpers.js:176:21
    at resolveDependencies (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:56:25)
    at visit (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:107:30)
    at async Promise.all (index 1)
    at async visit (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:116:5)
    at async Promise.all (index 0)
    at async visit (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:116:5)
    at async Promise.all (index 13)

**Comment by lasway** [comment]
> Please remove your node-modules and package-lock.json and force a full reinstall of the system, and let us know if it helps.

i did this but it didnt work but i had to delete all the metro.config with empty configuration so the metro server use the fallback default and i didint get any error anymore

**Comment by lasway** [comment]
> > Please remove your node-modules and package-lock.json and force a full reinstall of the system, and let us know if it helps.
> > This library requires 7.8.0 that should be automatically installed when watermelon is installed, for some reason the rxjs is not (present?) on your installation.

it was there, i have done all the possible solving technique.

**Comment by lasway** [comment]
> When I use this code in index.js fie in react native
> 
> ```
> import { Amplify } from 'aws-amplify';
> import amplifyconfig from './src/amplifyconfiguration.json';
> Amplify.configure(amplifyconfig);
> ```
> 
> I'm getting error like this
> 
> error: Error: Unable to resolve module ./internal/operators/timeout from E:\eventual-mvp-app\node_modules\rxjs\dist\cjs\index.js:
> 
> None of these files exist:
> 
> * node_modules\rxjs\dist\cjs\internal\operators\timeout(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
> * node_modules\rxjs\dist\cjs\internal\operators\timeout\index(.android.js|.native.js|.js|.android.jsx|.native.jsx|.jsx|.android.json|.native.json|.json|.android.ts|.native.ts|.ts|.android.tsx|.native.tsx|.tsx)
>   77 | var SequenceError_1 = require("./internal/util/SequenceError");
>   78 | Object.defineProperty(exports, "SequenceError", { enumerable: true, get: function () { return SequenceError_1.SequenceError; } });
> 
> > 79 | var timeout_1 = require("./internal/operators/timeout");
> > |                          ^
> > 80 | Object.defineProperty(exports, "TimeoutError", { enumerable: true, get: function () { return timeout_1.TimeoutError; } });
> > 81 | var UnsubscriptionError_1 = require("./internal/util/UnsubscriptionError");
> > 82 | Object.defineProperty(exports, "UnsubscriptionError", { enumerable: true, get: function () { return UnsubscriptionError_1.UnsubscriptionError; } });
> > at ModuleResolver.resolveDependency (E:\eventual-mvp-app\node_modules\metro\src\node-haste\DependencyGraph\ModuleResolution.js:127:15)
> > at DependencyGraph.resolveDependency (E:\eventual-mvp-app\node_modules\metro\src\node-haste\DependencyGraph.js:271:43)
> > at E:\eventual-mvp-app\node_modules\metro\src\lib\transformHelpers.js:176:21
> > at resolveDependencies (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:56:25)
> > at visit (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:107:30)
> > at async Promise.all (index 1)
> > at async visit (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:116:5)
> > at async Promise.all (index 0)
> > at async visit (E:\eventual-mvp-app\node_modules\metro\src\DeltaBundler\buildSubgraph.js:116:5)
> > at async Promise.all (index 13)

try deleting the node_modules and install again but use yarn insteady of npm, then clear all the caches both for dependencies and android/IOS builds, or try forcing the metro bundle to use default fallback while we figuring another solution we can use. my email laswaykelvin2910@gmail.com you can check me if you got any update on this issue.

**Comment by lasway** [comment]
Hello, I have not yet found a solution for my issue. I have cleared
everything in the metro.config file, and now it's empty; that's how it's
working.
Regards,
Lasway
