### ISSUE TITLE
"Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome"

### ISSUE THREAD

**Issue by ry1091997** [Nozbe/WatermelonDB#1726]
When we create data in the write function ( await database.write(async () => {
      const newPost = await postsCollection.create(post => {
        post.title = 'New post';
        post.body = 'Lorem ipsum...';
      });
      console.log(newPost);
    });
) it shows ""Invariant Violation: Calling synchronous methods on native modules is not supported in Chrome"" error in debug mode and I am not able to debug and it only works in terminal

**Comment by radex** [comment]
See Hermes docs for modern RN debugging workflow. The old Chrome workflow simply does not work with JSI
