### ISSUE TITLE
Web Bundling failed

### ISSUE THREAD

**Issue by PepeIksde** [Nozbe/WatermelonDB#1733]
When I launch the application on iOS, I keep having problems with web bundling. Can someone help me with this?

Web Bundling failed 297ms
The package at "node_modules/@nozbe/watermelondb/adapters/sqlite/sqlite-node/Database.js" attempted to import the Node standard library module "fs".
It failed because the native React runtime does not include the Node standard library.

**Comment by radex** [comment]
you can't import sqlite-node on iOS
