### ISSUE TITLE
Wrong type definition in LocalStorage get

### ISSUE THREAD

**Issue by tiagoevanp** [Nozbe/WatermelonDB#1759]
https://github.com/Nozbe/WatermelonDB/blob/62774d5ebc4aa9ed6a2f61c8d4e795b32322cec6/src/Database/LocalStorage/index.d.ts#L14

The return type shouldn't be `undefined` instead of `void`?
Reading the comments there I have no idea why the return could be void... any reason for it?

**Comment by radex** [comment]
In Flow, `void` is the type of `undefined`. Seems like that was converted 1:1 to TS, though TS's meaning is slightly different. Fixed on master.
