### ISSUE TITLE
"Is there a way to sync specific tables?"

### ISSUE THREAD

**Issue by KartikDevarde2601** [Nozbe/WatermelonDB#1764]
"I have multiple tables, but there is one table for which I only want to save data to the local database and not to the server. Watermelon DB give all created update table .... I have searched through the documentation and other resources, but I haven't found a solution yet. Can anyone help me with this?"

**Comment by killerchip** [comment]
@KartikDevarde2601 You can always filter out the entries from this table, so they are not sent to the backend. This can happen inside your 'push' function in the `sync` function:
https://watermelondb.dev/docs/Sync/Frontend

**Comment by KartikDevarde2601** [comment]
Thank you for your suggestion. I basically take readings from medical devices using sensors. I don't want to synchronize a table with a large 60,000 row single reading because I think it might have a performance impact when I synchronize. Therefore, that's not a good idea. Additionally, I also don't want to save the reading permanently on the local device.

**Comment by martyfitzer-ids** [comment]
@radex I also considered the above solution to excluding data from syncing, but I saw in the [documentation](https://watermelondb.dev/docs/Sync/Frontend#adding-logging-to-your-sync:~:text=You%20MUST%20NOT%20mutate%20or%20store%20arguments%20passed%20to%20pushChanges().%20If%20you%20need%20to%20do%20any%20processing%20on%20it%2C%20do%20it%20before%20returning%20the%20object.%20Watermelon%20treats%20this%20object%20as%20%22consumable%22%20and%20can%20mutate%20it%20(for%20performance%20reasons)) that the arguments passed to pushChanges should not be mutated. Is there an alternative way to exclude a table or column from being synced?

Docs:
> You MUST NOT mutate or store arguments passed to pushChanges(). If you need to do any processing on it, do it before returning the object. Watermelon treats this object as "consumable" and can mutate it (for performance reasons)

**Comment by GitMurf** [comment]
@martyfitzer-ids did you ever figure this out? Thanks!

**Comment by martyfitzer-ids** [comment]
> @martyfitzer-ids did you ever figure this out? Thanks!

I ended up just filtering out the tables I didn't want to sync during the push request. I made a shallow copy of the changes object to apply the filtering to to avoid mutating the changes object passed into pushChanges to respect the watermelon docs.
