### ISSUE TITLE
What browsers are supported?

### ISSUE THREAD

**Issue by CochiorasBogdan** [Nozbe/WatermelonDB#177]
Hello, What is the minimum Browsers versions, ECMASCIPT 5,6 supported by the project? Tried to test the demo website on IE 11 and get the following error:
SCRIPT1010: Expected identifier
vendors~main.29a8fc921753281c4dcf.js (1,14244)
![capture](https://user-images.githubusercontent.com/6114176/49578417-5f853500-f952-11e8-8a50-368c93aa09b3.JPG)

**Comment by radex** [comment]
I don't know, we haven't tested legacy browsers. I suspect there are missing Babel transformations. Feel free to contribute to this pull request: https://github.com/Nozbe/WatermelonDB/pull/145
