### ISSUE TITLE
Sync feature not working question

### ISSUE THREAD

**Issue by Protonosgit** [Nozbe/WatermelonDB#1792]
Hi, I just tried implementing the sync feature of watermelondb with supabase and ran into an issue I cant really fix:
When requesting a sync using the rpovided example snippet to my database it simply fails with: **TypeError: Cannot read property '_resetCount' of undefined**.
This seems to happen even before a request is even made to my database directly after invoking  `synchronize`.
I tried resetting the whole app multiple times and adding/removing fields but the error persists.

I might be stupid but there is always some data present in the database before requesting a sync inserted by my own sync system. Might this be the problem? Should the database be completly empty before requesting the first sync?

Update: It doesnt work with an empty database either and synclogger shows the same error

**Comment by Protonosgit** [comment]
Seems to have been a weird import issue on my side and is now solved but there definetly should have been a warning from watermelondb in such cases!

**Comment by Pcfilho** [comment]
Hey, @Protonosgit I'm having the same issue could you show here what was the problem and how did you fix it?

**Comment by Protonosgit** [comment]
> Hey, [@Protonosgit](https://github.com/Protonosgit) I'm having the same issue could you show here what was the problem and how did you fix it?

I think i had this issue because one of my imports was wrong or missing completely. 
Could be another reason this is thrown but that's what fixed it for me.

**Comment by Pcfilho** [comment]
I fixed it, the problem was that i was not passing the database to my `syncronize` correctly, i double checked it and now it is working
