### ISSUE TITLE
Unable to update columns which uses @date in model?

### ISSUE THREAD

**Issue by homocodian** [Nozbe/WatermelonDB#1804]
schema
```ts
export const Table = {
  note: {
    name: "note",
    columns: [
      {
        name: "deleted_at",
        type: "string",
        isOptional: true,
        isIndexed: true
      }
    ] satisfies ColumnSchema[]
  }
} as const;

export default appSchema({
  version: 13,
  tables: [
    tableSchema({
      name: Table.note.name,
      columns: Table.note.columns
    })
  ]
});
```
model
```ts
import { Table } from "./schema";

export default class Note extends Model {
  static table = Table.note.name;

  @date("deleted_at") deletedAt!: Date | null;

  @readonly @date("created_at") createdAt!: Date;
  @date("updated_at") updatedAt!: Date;
}
```
changing deletedAt column to use @field works
```ts
  @field("deleted_at") deletedAt!: string| null;

  @readonly @date("created_at") createdAt!: Date;
  @date("updated_at") updatedAt!: Date;
}
```

**Comment by nhanders** [comment]
@homocodian it seems there is an issue with the schema you have provided. `@date` fields need `number` types. 

```
export const Table = {
  note: {
    name: "note",
    columns: [
      {
        name: "deleted_at",
        type: "number",
        isOptional: true,
        isIndexed: true
      }
    ] satisfies ColumnSchema[]
  }
} as const;
```

**Comment by homocodian** [comment]
> @homocodian it seems there is an issue with the schema you have provided. `@date` fields need the `type` to be `"number"`. 
> 
> ```
> export const Table = {
>   note: {
>     name: "note",
>     columns: [
>       {
>         name: "deleted_at",
>         type: "number",
>         isOptional: true,
>         isIndexed: true
>       }
>     ] satisfies ColumnSchema[]
>   }
> } as const;
> ```

I have already tried that

**Comment by nhanders** [comment]
@homocodian how are you trying to perform the update?

**Comment by homocodian** [comment]
> @homocodian how are you trying to perform the update? 
```ts 
static async delete(id: string) {
    await database.write(async () => {
      const note = await notes.find(id);
      // capture updatedAt timestamp in some global state
      note.update((note) => {
        note.deletedAt = Date.now();
      });
    });
  }

  static async undo(id: string) {
    await database.write(async () => {
      const note = await notes.find(id);
      note.update((note) => {
        note.deletedAt = null;
       // doesn't work, even state return correct previous timestamp
//.   updated_at not marked as readonly 
        note.updatedAt = someGlobalState.get(note.id) ?? undefined;
      });
    });
  }
```
Actually I am sorting query results based on updated_at, if the user deletes the note and I want that to be back at its place not at the top bcz of updated_at changed to latest timestamp, can I somehow stop updated_at column to update at certain actions such delete and undo

**Comment by nhanders** [comment]
I'm just going to comment on the first part of the snipped because that was the original question. The issue is that you need to pass a `Date` to `deletedAt`, not a unix timestamp. 

```js
await database.write(async () => {
    const note = await notes.find(id);
    note.update((note) => {
      note.deletedAt = new Date();
    });
  });
}
```

However, when using the `sanitizedRaw` approach to updates/creates, use the unix timestamp.
