### ISSUE TITLE
Possible to overwrite created_at ? 

### ISSUE THREAD

**Issue by arnolicious** [Nozbe/WatermelonDB#1809]
Hey all, great library, absolutely loving it so far!

I'm wondering if there's any way to overwrite / pass my own dates into the automatically tracked `created_at` (and `updated_at`) fields.

My use case is the import of some external data, which already has an older creation date.
I assume I could get around this problem by creating a separate field, but that doesn't seem very elegant :D

**Comment by radex** [comment]
Sure, you can do `record._setRaw('created_at', timestamp)`

**Comment by arnolicious** [comment]
Oh great, thanks!
