### ISSUE TITLE
Rollback on production app

### ISSUE THREAD

**Issue by LukasMod** [Nozbe/WatermelonDB#1815]
Hey, does anyone have an idea how to properly do a rollback of an application on prod?
An update changes the schema, then it turns out we need to do a rollback. How to do it without clearing the database? 

From docs:
[There's no automatic "rollback" feature in Watermelon.](https://watermelondb.dev/docs/Advanced/Migrations#rolling-back-changes)
But maybe someone has a way to do it. I was thinking of synchronizing important data from the backend in onSetUpError().

**Comment by diegolmello** [comment]
Useful workaround:
If data is not corrupted and you can keep the migration, make a new version containing the migration, but removing whatever else you need to remove.
The rollback will require a new version on the stores anyway.
I did it a few years ago and it worked nicely.

**Comment by LukasMod** [comment]
@diegolmello thanks so much!

I created a rollback version with an older version of the application, but with a new build number. I kept migrations.ts and schema.ts as you said and data was preserved. I think this workaround is good enough for me to handle some edge case in bigger app realeses.
