### ISSUE TITLE
jsimodule not working in 0.74.3 version

### ISSUE THREAD

**Issue by arun-saleth** [Nozbe/WatermelonDB#1833]
Hi i am using watermelondb after upgrade react native version 0.74.3 compile error showing.After some research in react native blog they removed jsimodule.

How to fix this issue? @radex

**Comment by lucaswitch** [comment]
Can you try setting jsi:false in the database configuration?

**Comment by arun-saleth** [comment]
@lucaswitch I implemented async calls.so i enabled jsi.

**Comment by lucaswitch** [comment]
This is due react-native itself disabling support for legacy jsi calls.
That is something @radex is working on. 
Feel free to help too!

**Comment by lucaswitch** [comment]
Also duplicated of https://github.com/Nozbe/WatermelonDB/issues/1769

**Comment by arun-saleth** [comment]
@lucaswitch  Thank You so much

**Comment by lucaswitch** [comment]
> @lucaswitch Thank You so much
Happy to help 
You can look further on oficial docs: https://reactnative.dev/blog/2024/08/12/release-0.75#android-jsimodule-has-been-deleted
Cause this issue/migration can affect many libraries.

**Comment by arun-saleth** [comment]
@lucaswitch Thanks for time saving

**Comment by ishan-chhabra** [comment]
Hi, any updates on this? We are unable to use turbo on Android.

Thanks again! :)

**Comment by arun-saleth** [comment]
any updates on this issue?

**Comment by nmarchais** [comment]
With wdb 0.27.1 we can't upgrade many libs.
