### ISSUE TITLE
Using ISO8601 date strings for date fields

### ISSUE THREAD

**Issue by adam-aerobotics** [Nozbe/WatermelonDB#189]
I was wondering what people thought of adding functionality to allow ISO8601 date time strings to be used for date fields in a model. Currently if you try to define an `*_at` field in the schema as a string, it complains that it `...must be of type number and not optional`.

At our company we use date time fields, the benefit of them is their readability, being able to store timezones, and sub-second time precision. Obviously there are many cases to be made for using a unix time number or a date time string, but if there is perhaps some interest or support for being able to support date time strings I can implement them.

**Comment by radex** [comment]
> Currently if you try to define an *_at field in the schema as a string, it complains that it ...must be of type number and not optional

Only for created_at and updated_at, which are treated specially by 🍉. You can use different names.

> sub-second time precision

JS-style timestamps are millisecond-precision

**Comment by adam-aerobotics** [comment]
@radex 

Oh okay! It looks like I didn't do enough research haha! Thanks for the information.

**Comment by onursagir** [comment]
@radex the usage of numeric timestamps does become a real issue when the created_at and updated_at properties come from the database (to set them initially) 

> BigInt type isn't yet properly supported by JSON.stringify.

[NestJS fails to serialize BigInt](https://github.com/nestjs/nest/issues/6919#issuecomment-822215375)
