### ISSUE TITLE
[Sync] Allow for partial push

### ISSUE THREAD

**Issue by esbenp** [Nozbe/WatermelonDB#206]
First of all thank you for WatermelonDB, we've been playing around with using it instead of redux-offline and its a world of difference.

One of our use cases that I have a bit of trouble wrapping my head around is pushing changes to the backend. Our app is for making sales orders (you receive products from the backend, and turn them into orders in the client and send these to the backend). This creates 2 issues when it comes to pushing client changes to backend:

**1. Drafts / Pushing partially**

Usually you work on a sales order for a while before you are done. And you might want to double check the inventory or similar before pushing so you do a pull before approval. This means you might have orders that should not be pushed at all (because they are not ready). I guess you could fix this by adding an `approved` boolean field to your table and then filter orders that you send to the backend using `orders.filter(order => order.approved)` but that would not work since the sync mechanism assumes all records are pushed on a sync, and will blindly set `status=synced` on successful push. Which leads me to the second point

**2. Allow for push response / server side validation**

A very important point for us is that we have server side validation. E.g. an invoice has incremental invoice number but it might come from several clients so there is not way the client can add this. This will be added in the backend and is completely immutable. Another thing is that inventory levels are checked on the server. This means that you might send 10 orders to the backend where 2 will fail due to low inventory levels. But that does not mean the 8 others should fail. 

So my thought is that why not add a response structure for a push? Something like

*Request*
```
{
    "orders": {
        "created": [
            { "id": "order-1", "customer_id": "4321", "error": null },
            { "id": "order-2", "customer_id": "4321", "error": null },
            { "id": "order-3", "customer_id": "4321", "error": null }
        ],
        "updated": [

        ],
        "deleted": [

        ]
    },
    "orders_lines": {
        "created": [
            { "id": "order-line-1", "order_id": "order-1", "product_id": "4321", "quantity": 1, "error": null },
            { "id": "order-line-2", "order_id": "order-2", "product_id": "4321", "quantity": 1, "error": null  },
            { "id": "order-line-3", "order_id": "order-3", "product_id": "4321", "quantity": 1, "error": null  }
        ],
        "updated": [

        ],
        "deleted": [

        ]
    }
}
```

*Response*
```
{
    "orders": {
        "success": [
            { "id": "order-1", "order_number": "4540", "created_at": "2018-01-01 12:00:00" },
            { "id": "order-3", "order_number": "4541", "created_at": "2018-01-01 12:00:00" }
        ],
        "errors": [
            { "id": "order-2", "error": "Not enough in stock" },
        ]
    },
    "orders_lines": {
        "success": [
            { "id": "order-line-1", "created_at": "2018-01-01 12:00:00" },
            { "id": "order-line-3", "created_at": "2018-01-01 12:00:00" }
        ],
        "errors": [
            { "id": "order-line-2", "error": "Not enough in stock"  }
        ]
    }
}
```

The idea here is that you allow the client to only mark successful ones as synced. All the objects in an error array will not be marked as synced. This would also allow for use-case (1) since I can ignore orders with `approved=false` and not include them in the `success` array. This means they would still be marked as unsynced in the database.

This also allows for partial updates with e.g. timestamps, error messages, invoice numbers or similar. Note that this behaviour could be opt-in by simply marking all as synced when returning empty status 200. I am by no means an expert in synchronization so I have no idea the problems this introduces, but I'd love to hear your thoughts around something like this?

**Comment by radex** [comment]
Hey @esbenp. Thanks for the feedback! I'll get back to you with more detail later in the week, but a quick question:

> Usually you work on a sales order for a while before you are done. And you might want to double check the inventory or similar before pushing so you do a pull before approval.

Why? Wouldn't it make your app more powerful to synchronize unapproved orders? Such orders wouldn't be visible to other users and wouldn't trigger any actions, but a backup of the work done is already on the server. What's the harm? It would keep a lot of doors open, such as having the same stuff on multiple devices or platforms

**Comment by radex** [comment]
> 1. Drafts / Pushing partially

Three ideas come to mind, from simplest to hardest:

1. Just Sync Everything — like I suggested before. I think in most cases there's just no harm in this, and only benefits.
2. Per-collection sync enable — currently ALL tables (except for magic localStorage table) are synced. I think a lot of apps might have a need for tables for local stuff (needing more complex stuff than LocalStorage provides), so it's reasonable to add a parameter to `synchronize()` to point to which tables to sync / skip syncing. This complicates your code, since you'd need to have two classes — one for synced orders, one for draft orders. But I think you could easily manage it with subclassing (`AbstractOrder extends Model; Order extends AbstractOrder; DraftOrder extends AbstractOrder` — the first would have most of the common logic, and the other two would just have stuff like `publish()` etc.)
2. New sync status — currenly there's `created, updated, deleted` (local changes waiting to be pushed) and `synced` (no local changes since pulled). There could also be `draft`. Your app would be responsible for managing such status — as this is much simpler on Watermelon's end and more versatile for apps with different needs. Needless to say, records would be recognized by client as changed if `draft`, but would not be pushed until changed to `created`. This seems doable, but further analysis is needed. And lots of tests if one was to implement it

> 2. Allow for push response / server side validation

I'm not sure this fits Watermelon's sync protocol philosophy. (Which is, sync ALWAYS passes. Server does sanitization, not validation. Sync never gets rejected, server deal with issues, not client.)

I might be wrong — again, needs deeper analysis — but I think you'd have to change the API contract to achieve per-record push rejection...

**Comment by cfeeling** [comment]
In my mind, I think it should be up to client for the case "client sends misformatted data (some broken invariant, bad value, whatever), and server rejects it". The work flow might be same as below:
1. client sends misformatted data;
2. server response request with validate result, for example:
```
 "orders": {
        "success": [
            { "id": "order-1", "order_number": "4540", "created_at": "2018-01-01 12:00:00" }
        ],
        "errors": [
            { "id": "order-2", "error": "the provided product was not existed", "code": 123  }
        ]
    },
```
3. according to application specific rules which should be outside of watermelon, client remove the local record which id is `order-2` from local database or mark the local record as `retry-able`;

What should be done in Watermelon is a new function to change the sync-able status manually in that sample work flow.

**Comment by esbenp** [comment]
> * If client sends misformatted data (some broken invariant, bad value, whatever), and server rejects it, what is the client supposed to do with it?

We have a sync page in our app where we display all client errors. I think you could have event hooks ala `onError` etc. so you leave it up to the developer to figure out what to do with it. But yes all rows that are errorneous should simply be marked as not synced. I would have a validation_error table that is ignored by the API (since its only needed locally by the tablet)

```
function onError(table, row, server_response, server_code) {
  collection('validation_errors').write({ type: 'order', id: row.id, error: server_response });
}
```

That means I can have a sync screen that displays all the sync errors that occurred and have a user fix it. One thing I like about `redux-offline` is that it will never retry syncing an action that returned 4xx error but will retry 5xx errors within a decay schedule. So like

```
function onError(table, row, server_response, server_code) {
  if (server_code === 500) {
    queueRetry()
  } else {
    collection('validation_errors').write({ type: 'order', id: row.id, error: server_response });
  }
}
```

Again, just quick pseudo-code - not really well thought through.

> * instead of partly failing the sync request, you might as well explicitly add a flag on the record (e.g. `is_valid`)

So this is kind of what we are doing now. We will try the sync everything model and then have a `status` flag on all tables that determines whether or not this is "draft" or "approved" entity. But it does become really complex with validation errors. Let me give you a good example:

1. You create customer with number 1234
2. Sync happens and customer number 1234 already exists
3. You save the customer in the customers table with `status=draft` and `error=customer number exists` so you know this is not really a "persisted" customer and the tablet will be synchronized and can show `error`
4. You fix the number and save again. Now `status=approved` and `error=null`
5. 2 weeks later you change the customer number back to 1234

What are you supposed to do now? You cannot save it in the database since the customer number already exists - if you did that would mean all your apps would now have 2 customers with the same number, unless you hide the invalid one. And hiding the invalid one would mean customers would disappear in the app left and right whenever somebody updated an existing customer with a validation error. So the only choice you have here is to rollback the entire sync which means nothing will get saved until you fix that single customer number

**Comment by radex** [comment]
@esbenp  All right. Sorry I haven't come back to you quickly. Let me mull this over some more — sync is a tricky subject :) I'll do my best to get back to you with a proper response next Friday.

Will you be willing to work on the implementation of additional sync statuses if we come to a consensus regarding how to approach this?

**Comment by esbenp** [comment]
Yes, we are open for contributing. We are actually on faires this weekend trying out a new version of our app that uses the Just Sync Everything model, so we will definitely have some feedback next week. We definitely have some ideas already so lets talk shop soon :-)

**Comment by radex** [comment]
@esbenp I am very, very sorry about my long procrastination with getting back to you. You mentioned you are trying out the "Just Sync Everything model" — how did it go?

**Comment by sebastian-schlecht** [comment]
Hey guys, just wanted to throw one thought in as I stumbled upon this thread while investigating for another issue we have - not quite the same but related. We are syncing attachments which have files attached (quite a number of them actually). So we would need some sort field that is solely relevant locally, indicating whether the download of the actual file, which is handled outside of watermelon, is already complete. This field however, should not affect sync in any way - it is of no interest to the server. Any take on that? If that's too far for this I might open up a new one.

**Comment by radex** [comment]
@sebastian-schlecht I think it makes sense to make a separate thread for that, since asking Watermelon to ignore a table or a column when syncing seems much more straightforward than additional sync statuses proposed here

**Comment by Darhagonable** [comment]
> Hey guys, just wanted to throw one thought in as I stumbled upon this thread while investigating for another issue we have - not quite the same but related. We are syncing attachments which have files attached (quite a number of them actually). So we would need some sort field that is solely relevant locally, indicating whether the download of the actual file, which is handled outside of watermelon, is already complete. This field however, should not affect sync in any way - it is of no interest to the server. Any take on that? If that's too far for this I might open up a new one.

How did you solve this?

**Comment by Darhagonable** [comment]
@sebastian-schlecht
> Hey guys, just wanted to throw one thought in as I stumbled upon this thread while investigating for another issue we have - not quite the same but related. We are syncing attachments which have files attached (quite a number of them actually). So we would need some sort field that is solely relevant locally, indicating whether the download of the actual file, which is handled outside of watermelon, is already complete. This field however, should not affect sync in any way - it is of no interest to the server. Any take on that? If that's too far for this I might open up a new one.

How did you solve this?
