### ISSUE TITLE
unable to use object spread operator with models

### ISSUE THREAD

**Issue by bgits** [Nozbe/WatermelonDB#210]
When observing a collection it does not seem possible to use the object spread operator to get the values of the fields defined in the model.

ie:
```
const formatField = field => ({
  ...field,
  commitTime: convertToHours(field.commitTime),
  canceled: cancelText(field.canceled)
})

const FunderProfilesTable = ({ profiles }) => <MTable data={profiles.map(formatField)} />

export default withDatabase(withObservables([], ({ database }) => ({
  profiles: database.collections.get('profiles').query().fetch(),
}))(FunderProfilesTable))

```

In the above example, `...field` returns none of the fields, while `...field._raw` will but they are not camelcase. 

Seems like this should be supported unless there is a reason not to use the spread operator in favor of some more idiomatic way to go about this? 

I've created this method on the class for now:

```
  getFields() {
    const validTypes = new Set(['string', 'number', 'boolean'])
    const newObj = {}
    const proto = Object.getPrototypeOf(this)
    const names = Object.getOwnPropertyNames(proto)
    names
      .filter(name => validTypes.has(typeof this[name]))
      .forEach(name => { newObj[name] = this[name] })
    return newObj
  }
```

**Comment by radex** [comment]
> Seems like this should be supported unless there is a reason not to use the spread operator in favor of some more idiomatic way to go about this?

Watermelon records are not "dumb objects", they're class instances. And fields can have transformations, sanitizers… and you might have additional items (e.g. getters) that are not `@fields` in the way. Ergo, it doesn't seem like a great idea to me, to just spread such an object. By tweaking the model definition, you can break a bunch of other places in your code.

I think your workaround is fine :) But I don't think it's right for `@field`s to be enumerable by default
