### ISSUE TITLE
Batch insertion throws an unhandled promise rejection error.

### ISSUE THREAD

**Issue by skhizerabass** [Nozbe/WatermelonDB#214]
I have used the logs and i have more than 600 records to update contactsCreation is an array in which i am storing all the prepareCreate operations. Can you please review my code and explain me what is wrong with the code?

> Unhandled promise rejection, { [TypeError: undefined is not an object (evaluating 'fn.apply(void 0, arguments)')]

```
export async function CreateContact(db, c) {
        const contactsCollection = db.collections.get('contacts');

        return contactsCollection.prepareCreate(contact => transformContactForStore(contact, c));


}


 function transformContactForStore(contact, c) {
    contact._id = c._id;
    contact.name = c.name;
    contact.profileName = c.profileName;
}


var contactsCreation =[];
contactsCreation.push( CreateContact(scope.props.db,contactData));
scope.props.db.action(async () => { 

					
					  await scope.props.db.batch(...contactsCreation);
					  });

```

`

**Comment by vivekkaushal99** [comment]
@skhizerabass Were you able to find a solution to this?

**Comment by bzvikler** [comment]
@vivekkaushal99 I ran into a similar issue while trying to manually set the `id` field on a record. Firstly, I think if you want to set `id` you should use `_raw.id`. Secondly, the `id` field if set manually must be a string, I had an issue where I was setting it to a number straight from my main DB.

**Comment by KrisLau** [comment]
Having a similar ish problem #1185. Any idea what might be happening?
