### ISSUE TITLE
How to create relationships on non id fields is not clear

### ISSUE THREAD

**Issue by bgits** [Nozbe/WatermelonDB#215]
Since Watermelon auto assigns the id field, I'm trying create a relationship between two models on non 'id' fields as per their relationship on the remote resource. the example would be:

```
class Pledge extends Model {
  static table = 'pledges'
  static associations = {
    profiles: { type: 'belongs_to', key: 'id_profile' },
  }

  @field('pledge_id') pledgeId
  @field('owner') owner
  @field('amount') amount

  @relation('profiles', 'id_profile') profile

}

class Profile extends Model {
  static table = 'profiles'
  static associations = {
    pledges: { type: 'has_many', foreignKey: 'id_profile' }
  }

  @field('addr') addr
  @field('type') type
  @field('name') name
  @field('id_profile') idProfile

  @children('pledges') pledges

```

When I try to create the `Pledge` on `pledge.profile.set(profile.id)` the profile is not set and `id_profile` is "0" when it should have a value.

So this is two questions.
1) Would this be the ideal way to model this relationship in Watermelon?
2) Is this the correct way to create the Pledge record?

**Comment by Icemanbeta** [comment]
How are you creating? Since you're not using `.set(profile)` I'm guessing you're not creating the `Profile` first, or if you are, when using `.set` you have to pass the whole model object in. It's clearly in the documentation. If you were just using the `profileId` it should be `pledge.profileId = profile.id`

**Comment by bgits** [comment]
> How are you creating? Since you're not using `.set(profile)` I'm guessing you're not creating the `Profile` first, or if you are, when using `.set` you have to pass the whole model object in. It's clearly in the documentation. If you were just using the `profileId` it should be `pledge.profileId = profile.id`
> 
> https://github.com/Nozbe/WatermelonDB/blob/master/docs/Relation.md#assigning

I am creating the profile first, I'm not passing in the profile object because in order to obtain the profile object it seems I need to query that Collection which returns a promise and `create` throws an invariant error when passing in function that resolves promises. It also seems unperformant to perform that extra query and processing rather than passing reference by ID.

**Comment by bgits** [comment]
> `pledge.profile.id = profile.id` should be good
> 
> Was documentation confusing about this part? Let me know @bgits and please contribute a docs clarification if needed

In my case I'm doing `pledge.profile.idProfile = id` since the `id` field is generated by Watermelon and is different from fields maintaining the relationship on the remote resource. 

In any case when trying `pledge.profile.idProfile = id` in a batchCreate, the `id_profile` field in `_.raw` is always `0`

**Comment by radex** [comment]
> In my case I'm doing pledge.profile.idProfile = id since the id field is generated by Watermelon and is different from fields maintaining the relationship on the remote resource.

that ain't right. `pledge.profile` is not a `Profile` instance, but a `Relation` object. You can't do `pledge.profile.idProfile`. Again, I think docs should be fairly clear on that part

**Comment by bgits** [comment]
> > In my case I'm doing pledge.profile.idProfile = id since the id field is generated by Watermelon and is different from fields maintaining the relationship on the remote resource.
> 
> that ain't right. `pledge.profile` is not a `Profile` instance, but a `Relation` object. You can't do `pledge.profile.idProfile`. Again, I think docs should be fairly clear on that part

It's not clear how to set the relationship in this case, the remote resource `Pledge` has no concept of what the WatermelonDB `id` for `Profile` is. Essentially `pledge.owner == profile.idProfile` Many to one.  

If I already have the profiles table retrieved and I'm adding pledges records, how should I be setting the profile relationship for each pledge?

Is performing a query on `profiles` and then setting with the actual Profile object the way to go here?

**Comment by bgits** [comment]
> From experience using other ORM frameworks for many languages, async is somewhat unique characteristic in javascript that I have learned to just understand the difficulties working with it. Now with that aside, it seems like you're really just having issues with async. But you have two routes, create the record first then set the relationship on the created instance. If you want to set the id directly just set it to the foreign key column. It works for me. The second option is to create the ids using the internal `randomId` export and use `DatabaseBridge` to import it.
> 
> @radex I think the documentation is pretty good for relationships however you guys could benefit from some relationship record creations in the demo. Working code can be extremely helpful to prove it works.

This is not an async issue for me. I did see a thread in the issues about modifying the id however it said that keys need to be globally unique, so in the case where each table uses sequential numbering there will be global collisions, I don't know if this is still the case with WatermelonDB? 

Regarding `DatabaseBridge` I don't recall reading about it in the docs, where can I get more info on it?

**Comment by bgits** [comment]
> @bgits All right, so let me get this straight:
> 
> you have a `Pledge` record, which has its `id` (which is a local-only Watermelon ID), and its `pledgeId` (which is what the remote server assigns to it). And analogous with `Profile`. Correct?
> 
> This is kind of a problem for Watermelon at this moment, since Watermelon assumes all relation IDs are to `id` fields — and that local and remote IDs are consistent.
> 
> See this issue for the discussion on how to deal with local and remote IDs: #216 — if you can, for example, normalize IDs to all be local IDs during synchronization, all will be good.
> 
> Another solution (at least a partial one) is to add a `local id` field to `relation/immutableRelation` decorator. See @esbenp's thread here: #219 — this is an analogous situation. If you'd like to contribute to that, that would be great.
> 
> Let me know if this clears up the situation and what you choose to do in your case :)

For now I resorted to creating these relationships on the `id` fields during the data import and keeping their remote id's on `{model}Id` field. I will see if this degrades into something problematic for me.
