### ISSUE TITLE
[Relations] Allow defining local ID key

### ISSUE THREAD

**Issue by esbenp** [Nozbe/WatermelonDB#219]
Sometimes the local key is not ID, so it would be nice if we could define the local key optionally on associations.

e.g.

```
static associations = associations(
    [Tables.users, { type: 'has_many', foreignKey: Columns.users.company_id, localKey: 'another_key' }]
)
```

Assuming I have read it correctly it would be quite trivial to add in the decorators

```
const localKey = association.localKey || 'id'
const query = childCollection.query(Q.where(association.foreignKey, that[localKey]))
```

I can add the PR if you want? @radex

**Comment by radex** [comment]
> Sometimes the local key is not ID

Can you give me a more specific use case where that's the case? Does that have to do with your local and remote IDs being different, or is it a schema-specific thing?

> Assuming I have read it correctly it would be quite trivial to add in the decorators

Sure! Let's just hash out my small concern above — but if it appears that this is a reasonable feature, then yeah, absolutely send a pull request :)

There's a couple of places that depend on associations. The `@children` decorator is one of them — but another is the implementation of `Q.on` query. So you'd also need to modify `encodeQuery` (with a small test). On top of my head, that's all :)

**Comment by esbenp** [comment]
Our app has `customers` which is a many-to-many intermediate table between 2 companies. So it could look something like

```
id <-- ID of the customer
seller_id <--- ID of the seller company
buyer_id <--- ID of the buyer company
discount <--- the relation contains the terms of the relationship
```

Its common in b2b sales to have multiple customers that are basically the same company. Imagine if you were selling straws to McDonalds stores you might have customer A being McDonalds London and customer B being McDonalds New York, but both customers in the end share the same "company". So all users are attached to `buyer_id` and not `id` of customers. So to get all users of a customer you join them on `buyer_id` and not `id` since a user is attached to a single buyer, but a buyer is many different customers. Idk if it makes sense, but its something along those lines
