### ISSUE TITLE
[Question] Populating database from a file

### ISSUE THREAD

**Issue by JensonMiralles** [Nozbe/WatermelonDB#221]
Is there a way to populate the database from a file containing records for React-Native? 

Thanks!

**Comment by radex** [comment]
@JensonMiralles no specific support. It would indeed be nice if there was a built-in adapter-level `dump` and `load` support, but there's currently none. Would you like to contribute to that feature?

You can use `database.batch` to just add a lot of records all at once.

Or I guess you could hack `synchronize()` to load records from JSON.

**Comment by JensonMiralles** [comment]
I will take a look on that.

Thanks you!

**Comment by radex** [comment]
@JensonMiralles hey, what's the status of the issue?
