### ISSUE TITLE
Static model action to create a new record

### ISSUE THREAD

**Issue by cwagner22** [Nozbe/WatermelonDB#224]
For example:
```
await database.action(async () => {
  const newPost = await postsCollection.create(post => {
    post.title = 'New post'
    post.body = 'Lorem ipsum...'
  })
})
```
Can I move this action to the `Post` model? I need a `create` action with some additional logic and would like having it in the `Post` model. (static method)

**Comment by radex** [comment]
`and would like having it in the Post model. (static method)`

i mean, sure, you can do it, but you'd have to pass `database` as an argument.

I recommend having an object like `ModelRoot` that you inject into the component tree via context that has all the top-level model actions like `root.createPost`

**Comment by cwagner22** [comment]
Thank you. I am not yet familiar with injecting objects like `ModelRoot` into the component tree via context. I'd appreciate a quick example otherwise I'll just keep it simple and do it without.

**Comment by radex** [comment]
Just create your own simple class or object, it doesn't have to be anything specific and use react context to have access to it from components — you'll find description here: https://reactjs.org/docs/context.html
