### ISSUE TITLE
Overriding DB filepath when test is running?

### ISSUE THREAD

**Issue by jakebloom** [Nozbe/WatermelonDB#239]
Hi team,

I notice that when we are in a testing environment, we override the filepath of the database in `DatabaseDriver.swift`:
```
        // In test env, pass name of memory db
        self.database = Database(path: isTestRunning ? dbName : path)
```

I'd love to know the reasoning behind this, since I need to use the original path in my automated end to end tests (I'm using [Detox](https://github.com/wix/Detox)). Using the abridged name (`dbName` instead of `path`) means that FMDB fails to open the database, and the whole app crashes.

I'm happy to write a PR fixing this, but I just need more info, like:
- Why do we need to use `dbName` instead of `path`?
- What do you think a reasonable way to disable this behavior looks like? Something like
```
const adapter = new SQLiteAdapter({
  schema,
  useFullPathInTestEnv: true,
});
```

Would love to know your thoughts.

**Comment by radex** [comment]
@jakebloom Way ahead of you! Check out the latest 🍉 pre-release. I just fixed it couple of days ago.

Now, you can pass an actual `path` to the SQLiteAdapter constructor and it will work correctly. The way Watermelon knows that you're giving a path and not a name is that either you have slashes `/Users/...`, or the name starts with `file:`.

PS. Why don't you use in-memory database for your tests? Faster and more reliable!

**Comment by radex** [comment]
@jakebloom let me know if 🍉 0.10.1 works for you

**Comment by jakebloom** [comment]
Just checked on latest and it works. Thanks @radex!

**Comment by radex** [comment]
🎉
