### ISSUE TITLE
How to create bidirectional (inverse) one-to-one relationships?

### ISSUE THREAD

**Issue by cwagner22** [Nozbe/WatermelonDB#242]
For example, let's say I have a `Person` and a `Passport` tables. One person has only one passport and one passport belongs to one person.

schema.js
```js
    tableSchema({
      name: "persons",
      columns: [
        { name: "passport_id", type: "string" },
        ...
      ]
    }),
    tableSchema({
      name: "passports",
      columns: [
        { name: "person_id", type: "string" },
        ...
      ]
    }),
```

Person.js
```js
export default class Person extends Model {
  static table = "persons";

  @relation("passports", "passport_id") passport;
  ...
}
```

Passport.js
```js
export default class Passport extends Model {
  static table = "passports";

  static associations = {
    persons: { type: "belongs_to", key: "person_id" }
  };
  @relation("persons", "person_id") person;
  ...
}
```

I create a new passport:
```js
database.collections.get("passports").create(passport => {
  passport.person.set(person);
  // ...
});
```

However, I would like being able to access `passport` from `person` as well. Is manually updating `person.passport` the only way? With Realm I believe there is a way to it with [linking objects properties](https://realm.io/docs/javascript/latest/#inverse-relationships).

**Comment by radex** [comment]
Although not idiomatic, I think creating two `belongs_to` associations pointing at each other should work just fine. What's the problem exactly?

**Comment by cwagner22** [comment]
I just wanted to make sure there is no better way than:
1. creating two `belongs_to` associations pointing at each other
2. `create()` the product, `create()` the passport + `passport.person.set(person)`. Then `update()` the product with `person.passport.set(passport)`

**Comment by radex** [comment]
@cwagner22 No, use `batch()` to create and update the two items transactionally. You can prepareCreate a passport and assign it to a variable so you can retrieve the ID to update person. See Actions.md for details

**Comment by cwagner22** [comment]
So just to be clear, there is no way to create them both and then update person, all in `batch()`? When I do that I'm getting the error: `Cannot update uncommitted record`

**Comment by radex** [comment]
hmm… you're right. it would be best to create them at once, but you'd have to override ID when creating to be able to do this.

**Comment by cwagner22** [comment]
Perhaps it would be nice to have the `@children` equivalent for to-one relationships? (`@child`?)

I've found a way to access passport from person without having to set the id manually (to person) by adding this to the Person model:
```js
  @lazy passport = this.collections
    .get("passports")
    .query(Q.where("person_id", this.id));
```

Unfortunately this returns an array of results so I have to do that in my code, which is quite ugly:
`const passport = this.props.passport[0];`

**Comment by radex** [comment]
> Perhaps it would be nice to have the `@children` equivalent for to-one relationships? (`@child`?)

Perhaps! TBH I'm not sure if `to-one` relations (as opposed to just single `belongs_to` relation) is idiomatic. Because you're creating two sources of truth. If you have two objects that are supposed to point at each other, but one of them points at something else, it's en error. It's easier if just one of the objects points at the other (say, Passport points at Person). This way, say, Person, would only have a helper getter to find its Passport, based on a query.

Here's an example of this:

```
  @lazy
  _currentUserQuery: Query<User> = this.collections
    .get(Tables.users)
    .query(Q.where(Columns.users.isMe, true))

  @lazy
  currentUser: Observable<User> = this._currentUserQuery.observe().pipe(
    switchMap(([user]) => {
      invariant(user, `No user marked as isMe=true found`)
      return user.observe()
    }),
  )
```

It would be nice if this could be minified to a single line, using a decorator. If you want to implement something to that point, let me know, and I can give you pointers as to how :)
