### ISSUE TITLE
The development server returned response error code:500

### ISSUE THREAD

**Issue by imrenzarbie** [Nozbe/WatermelonDB#245]
I did all the steps in the docs regarding installation but when, I'm running it as react-native run-android I'm greeted by an error. I haven't created any schema just did the step by step installation 

![capture](https://user-images.githubusercontent.com/24402504/52652478-1f7d9800-2f29-11e9-8187-1b62850793a4.PNG)

**Comment by radex** [comment]
@imrenzarbie hey, did you fix the issue?

**Comment by imrenzarbie** [comment]
no sorry, i didn't find any solution for this

**Comment by imrenzarbie** [comment]
no sorry, i didn't find any solution for this
