### ISSUE TITLE
Working with multiple databases

### ISSUE THREAD

**Issue by diegolmello** [Nozbe/WatermelonDB#251]
Hey, everyone.

I need to have multiple databases instances in my app, but the lib is complaining.

<img width="350" src="https://user-images.githubusercontent.com/804994/52868667-1bb96380-312b-11e9-961f-bdd4a50feeb0.png" />

```js
const serverAdapter = new SQLiteAdapter({
	dbName: 'ServersDB',
	schema: serverSchema
});

const serverDatabase = new Database({
	adapter: serverAdapter,
	modelClasses: [Server]
});

const appAdapter = new SQLiteAdapter({
	dbName: 'AppDB',
	schema: appSchema
});

const appDatabase = new Database({
	appAdapter,
	modelClasses: [Setting]
});
```

### Why do I need multiple databases?
At Rocket.Chat, we have one database to store which servers the user has already signed in and one database per server.
We would need `ServersDB` database to store the servers and one more database per server, e.g. `open.rocket.chat` database.

In this way, we completely separate one server from another.
When the user logs out, we remove his data by cleaning the database and without touching others.

---
We are migrating from Realm to WatermelonDB right now.
With Realm, we do [this](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/realm.js#L341):

```js
const activeDB = new Realm({
	path: `${ path }.realm`,
	schema
})
```

@radex Let me know if there's an easier way to do it.
Thanks.

Great lib, btw... congrats! 🎉🎉🎉

**Comment by radex** [comment]
```
const appDatabase = new Database({
	appAdapter,
	modelClasses: [Setting]
});
```

should be:

```
const appDatabase = new Database({
	adapter: appAdapter,
	modelClasses: [Setting]
});
```

Easy peasy!

> We are migrating from Realm to WatermelonDB right now.

That's awesome! Rocket.chat looks super cool, I'd be very much interested in hearing more from you if you're exploring switching to WatermelonDB :)

**Comment by diegolmello** [comment]
Thanks, @radex!
I was just starring my code like a dumb, because a rewrite everything and worked...

I'll do it anyway, but this comment makes me wonder if it'll work: https://github.com/Nozbe/WatermelonDB/issues/225#issuecomment-460040021

> That's awesome! Rocket.chat looks super cool, I'd be very much interested in hearing more from you if you're exploring switching to WatermelonDB :)

Sure! I'll keep you updated and I'll probably talk more in this repo.
We're planning to rewrite our front end on React too and... well... we'll need a database 👀

**Comment by marcoantoniofassa** [comment]
@diegolmello curious why you migrante from realm tô whatermelondb?

**Comment by diegolmello** [comment]
It's been some time, but there was lots of reasons.
- Realm had their own JSC, so we couldn't migrate to Hermes
- There were a couple of issues the Realm team didn't fix and didn't reply to the community
- The main reason was because WatermelonDB is really good 🍉
