### ISSUE TITLE
[DB] Uh-oh. Database failed to load, we're in big trouble TypeError: Cannot read property 'initialize' of undefined

### ISSUE THREAD

**Issue by hussamkurd** [Nozbe/WatermelonDB#254]
I keep receiving 

> [DB] Uh-oh. Database failed to load, we're in big trouble TypeError: Cannot read property 'initialize' of undefined

When test the database with **jest** 

I trace the error and find that 
at node_modules/@nozbe/watermelondb/adapters/sqlite/index.js:95:35
This 

> var Native = _reactNative.NativeModules.DatabaseBridge;
Native is null

Iam using the following libraries 

    "react-native": "0.58.4",
    "react": "16.8.2",
    "prop-types": "^15.7.2",

And I have the right decorators defined in babel 

What is the problem?

**Comment by radex** [comment]
> What is the problem?

You can't test with a SQLite database in Jest. As you can see in the error, it's a purely native thing. It's possible to do this if you run tests in the simulator, but it's quite complicated to set up.

**Replace SQLiteAdapter with LokiJS adapter** for tests only, as if you were setting up a web project. This should work without problem :)

**Comment by hussamkurd** [comment]
Thanks @radex you save my day!

**Comment by cwagner22** [comment]
I wish there was a testing example (especially with React Native) because I'm struggling with it. I tried to use LokiJSAdapter instead of SQLiteAdapter when jest is running but got multiple modules not found error... (lokijs, lodash.clonedeep etc)

**Comment by radex** [comment]
> but got multiple modules not found error... (lokijs, lodash.clonedeep etc)

Just yarn add loci's, lodash.clonedeep :)

**Comment by cwagner22** [comment]
@radex Is it ok to import both `LokiJSAdapter` and `SQLiteAdapter` in production? Since I don't believe it's possible to conditionally import `LokiJSAdapter`. (I use it only for testing my react native app)

```js
...
import SQLiteAdapter from "@nozbe/watermelondb/adapters/sqlite";
import LokiJSAdapter from "@nozbe/watermelondb/adapters/lokijs";

const watermelonAdapter = __TEST__ ? LokiJSAdapter : SQLiteAdapter 
const adapter = new watermelonAdapter({
  schema: mySchema
});
```

**Comment by radex** [comment]
It is OK — there is no global behavior here. You can use `require()` to conditionally import an Adapter, and if __TEST__ is defined by the right babel plugin, it can strip unnecessary code during compilation :)

**Comment by cwagner22** [comment]
Unfortunately, I get
`error: bundling failed: Error: Unable to resolve module  fs from ~/MyApp/node_modules/lokijs/src/lokijs.js: Module fs does not exist in the Haste module map` when I run the app on ios.

Even conditionally importing lokijs is not avoiding the error:
```js
if (__TEST__) {
  LokiJSAdapter = require("@nozbe/watermelondb/adapters/lokijs");
}
```

**Comment by radex** [comment]
@cwagner22 hmm what if you make a separate index.js for testing setup?

**Comment by cwagner22** [comment]
Ok I've moved the database in `database.js` where I export it and have mocked `__mocks__/database.js` to use `LokiJSAdapter`

**Comment by YajanaRao** [comment]
I am facing the same issue. Can you please give more information on mocking the database object?

**Comment by cwagner22** [comment]
@YajanaRao I did it like that (I think that's all):

_App.js_
```js
import database from "../Models/database";
```

_Models/database.js_
```js
import { Database } from "@nozbe/watermelondb";
import SQLiteAdapter from "@nozbe/watermelondb/adapters/sqlite";

import { mySchema } from "./schema";
import Blog from "./Blog";

const adapter = new SQLiteAdapter({
  dbName: "AppName",
  schema: mySchema
});

export default new Database({
  adapter,
  modelClasses: [Blog]
});
```

_Models/\_\_mocks\_\_/database.js_
```js
import { Database } from "@nozbe/watermelondb";
import LokiJSAdapter from "@nozbe/watermelondb/adapters/lokijs";

import { mySchema } from "../schema";
import Blog from "../Blog";

const adapter = new LokiJSAdapter({
  dbName: "AppName",
  schema: mySchema
});

export default new Database({
  adapter,
  modelClasses: [Blog]
});
```

_Jest setup file:_
```js
jest.mock("../App/Models/database");
```

**Comment by julioxavierr** [comment]
@cwagner22 

Doing this apparently leaves us with some leaked handles, the database process isn't finished after the tests finish running. Were you able to handle that?

**Comment by cwagner22** [comment]
I don't remember having any similar issue. sorry...

**Comment by AkshatShetty101** [comment]
Having the same issue as @julioxavierr. Did you manage to find a solution? Any help would be greatly appreciated.

**Comment by jpierront** [comment]
On my side I extracted the adapter in a new file to reduce code duplication.

_/src/model/\_\_mocks\_\_/adapter.ts_
```javascript
import LokiJSAdapter from '@nozbe/watermelondb/adapters/lokijs';
import schema from '../schema';

const adapter = new LokiJSAdapter({
  schema,
  useWebWorker: false,
  useIncrementalIndexedDB: true,
});

export default adapter;
```

(LokiJSAdapter now require useWebWorker and useIncrementalIndexedDB)

Tests pass but errors are triggered at the end of the execution.

```
 PASS  __tests__/App-test.tsx
  ✓ renders correctly (106 ms)

  console.log
    [WatermelonDB][Loki] Initializing IndexedDB

      at Logger.log (node_modules/@nozbe/watermelondb/utils/common/logger/index.js:19:45)

  console.error
    Diagnostic error: TypeError: LokiMemoryAdapter is not a constructor
        at diagnosticError (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/utils/common/diagnosticError/index.js:17:15)
        at logError (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/utils/common/logError/index.js:13:44)
        at LokiWorker._onError (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/adapters/lokijs/worker/lokiWorker.js:167:27)
        at LokiWorker.<anonymous> (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/adapters/lokijs/worker/lokiWorker.js:86:16)
        at tryCallOne (/Users/julien/Workspace/ReactNativeApp/node_modules/promise/lib/core.js:21:12)
        at /Users/julien/Workspace/ReactNativeApp/node_modules/promise/lib/core.js:122:15
        at flush (/Users/julien/Workspace/ReactNativeApp/node_modules/asap/raw.js:25:25)
        at processTicksAndRejections (internal/process/task_queues.js:75:11) {
      framesToPop: 2,
      name: 'Diagnostic error'
    }

...
 
Test Suites: 1 passed, 1 total
Tests:       1 passed, 1 total
Snapshots:   0 total
Time:        3.118 s, estimated 4 s
Ran all test suites.

```

**Comment by tiagocpeixoto** [comment]
> @cwagner22
> 
> Doing this apparently leaves us with some leaked handles, the database process isn't finished after the tests finish running. 

Set autosave LokiJS option as false.

```
const adapter = new LokiJSAdapter({
  schema,
  useWebWorker: false,
  useIncrementalIndexedDB: true,
  extraLokiOptions:{
    autosave: false
  }
});
```

**Comment by cicerotcv** [comment]
> On my side I extracted the adapter in a new file to reduce code duplication.
> 
> _/src/model/__mocks__/adapter.ts_
> 
> ```js
> import LokiJSAdapter from '@nozbe/watermelondb/adapters/lokijs';
> import schema from '../schema';
> 
> const adapter = new LokiJSAdapter({
>   schema,
>   useWebWorker: false,
>   useIncrementalIndexedDB: true,
> });
> 
> export default adapter;
> ```
> 
> (LokiJSAdapter now require useWebWorker and useIncrementalIndexedDB)
> 
> Tests pass but errors are triggered at the end of the execution.
> 
> ```
>  PASS  __tests__/App-test.tsx
>   ✓ renders correctly (106 ms)
> 
>   console.log
>     [WatermelonDB][Loki] Initializing IndexedDB
> 
>       at Logger.log (node_modules/@nozbe/watermelondb/utils/common/logger/index.js:19:45)
> 
>   console.error
>     Diagnostic error: TypeError: LokiMemoryAdapter is not a constructor
>         at diagnosticError (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/utils/common/diagnosticError/index.js:17:15)
>         at logError (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/utils/common/logError/index.js:13:44)
>         at LokiWorker._onError (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/adapters/lokijs/worker/lokiWorker.js:167:27)
>         at LokiWorker.<anonymous> (/Users/julien/Workspace/ReactNativeApp/node_modules/@nozbe/watermelondb/adapters/lokijs/worker/lokiWorker.js:86:16)
>         at tryCallOne (/Users/julien/Workspace/ReactNativeApp/node_modules/promise/lib/core.js:21:12)
>         at /Users/julien/Workspace/ReactNativeApp/node_modules/promise/lib/core.js:122:15
>         at flush (/Users/julien/Workspace/ReactNativeApp/node_modules/asap/raw.js:25:25)
>         at processTicksAndRejections (internal/process/task_queues.js:75:11) {
>       framesToPop: 2,
>       name: 'Diagnostic error'
>     }
> 
> ...
>  
> Test Suites: 1 passed, 1 total
> Tests:       1 passed, 1 total
> Snapshots:   0 total
> Time:        3.118 s, estimated 4 s
> Ran all test suites.
> ```

Same here

**Comment by YoonJeongLulu** [comment]
any idea with this error?

**Comment by MrCordeiro** [comment]
I'm getting the same errors being logged at the end:

> Diagnostic error: TypeError: LokiMemoryAdapter is not a constructor

My workaround was to use the SQLiteAdapter again for testing:

```js
const adapter =
  isWeb && !isTest
    ? new LokiJSAdapter(lokiConfig)
    : new SQLiteAdapter(sqliteConfig);
```

And then mock it so it doesn't use the native version:

```js
jest.mock(
  "@nozbe/watermelondb/adapters/sqlite/makeDispatcher/index.native.js",
  () => {
    return jest.requireActual(
      "@nozbe/watermelondb/adapters/sqlite/makeDispatcher/index.js",
    );
  },
);
```
