### ISSUE TITLE
Ship with an already existing database

### ISSUE THREAD

**Issue by cwagner22** [Nozbe/WatermelonDB#255]
Is it possible to ship my app with an already existing database? (I could do that with Realm)

I have content that should be available when the user first launches the app. I am wondering if having to generate the database at launch from json (for example) is the only way?

**Comment by radex** [comment]
> Is it possible to ship my app with an already existing database?

I guess, sure, but there's no specific support for this — so you'll either have to pass to JavaScript path to native file in the app bundle with the database (if it's read-only), or move the app bundle stub to the documents directory (if it's the empty database that will then be writable)

Either way, it'll take 3-10 lines of Swift/ObjC/Java/Kotlin to do it :)

**Comment by radex** [comment]
@cwagner22 hey, did you take a look at this problem?

**Comment by cwagner22** [comment]
For now generating the database at first launch is an acceptable solution for me, thanks.

**Comment by radex** [comment]
Alright.
