### ISSUE TITLE
Keeping a FlatList sorted over time without re-render everything

### ISSUE THREAD

**Issue by diegolmello** [Nozbe/WatermelonDB#258]
Hey, guys.
I'm having trouble here trying to keep a `<FlatList />` sorted by date.
In my scenario, I have lots of chats and I need to keep them ordered by activity desc.
I can make it work, but it's causing everything to re-render every time the subscribe updates.

In short, I open a query and only want update state when `room_updated_at` changes in a record.
Everything else is updated inside the row component.
```js
// ChatsList.js
const query = await db.collections.get('chats').query(
  // filters ...
);
this.data = query.observeWithColumns('room_updated_at')
  .pipe(switchMap(data => data.sort((a, b) => a.roomUpdatedAt < b.roomUpdatedAt)));
this.data.subscribe(chats => this.setState({ chats }));
```

I've already set `key` and `keyExtractor` and tried to change `shouldComponentUpdate` to only return true when `roomUpdatedAt` changes, but it returns the same date every time 😕 
```js
// Chat.js
shouldComponentUpdate(nextProps) {
  const { roomUpdatedAt } = this.props.item;
  const { roomUpdatedAt: nextRoomUpdatedAt } = nextProps.item;

  // nextRoomUpdatedAt.toISOString() === roomUpdatedAt.toISOString() ALWAYS EQUALS :(
  if (nextRoomUpdatedAt && roomUpdatedAt &&
    nextRoomUpdatedAt.toISOString() !== roomUpdatedAt.toISOString()) {
    return true;
  }
  return false;
}
```

> @radex: It's generally best to do it on component level, since you can avoid a lot of re-renders this way.

@radex How can I fix it as you said [here](https://github.com/Nozbe/WatermelonDB/issues/218#issuecomment-458436438)?

Note: I'm not very familiar with `RxJs`... examples are welcome.

Thanks.

**Comment by radex** [comment]
> observeWithColumns('room_updated_at')

I think you mean `observeWithColumns(['room_updated_at'])`

Also: Why not use `withObservables` for observing the query? And then each item on the list should be a component that observes its chat using withObservables. And that wrapped in React.memo so that you don't have to fiddle with `shouldComponentUpdate` manually

**Comment by diegolmello** [comment]
Because `appDatabase` will change over time.
The user can switch between server databases and the app must refresh chats list without trouble.

Here's a screenshot:
<img width="350" src="https://user-images.githubusercontent.com/804994/53112083-3caff900-351d-11e9-8b07-9e7dd2a3079b.png" />
There's only `open.rocket.chat` there, but it could have more.
That's why I can't use `withObservables`.

I changed to `observeWithColumns(['room_updated_at'])` and the problem remains.

**Comment by radex** [comment]
> Because `appDatabase` will change over time.
> The user can switch between server databases and the app must refresh chats list without trouble.

That shouldn't be a problem — just tell withObservables to re-observe if db is different:

```
withObservables(['database'], ({ database }) => ({
  chats: database.collections.get('chats').query(xxxxx)
}))
````

**Comment by diegolmello** [comment]
@radex Nice! Apparently, it'll solve some issues. Thanks.
