### ISSUE TITLE
React Native, database don't preserve data

### ISSUE THREAD

**Issue by ndrkltsk** [Nozbe/WatermelonDB#259]
I noticed that others already had the same problem:

When I try to create a new entry, the entry is created but no data is saved; strings are emptry, numbers are zeros.

I already tried to set all dependencies as in example native app, but nothing.
My .babelrc is the same as in the documentation and example app.

**Comment by radex** [comment]
@ndrkltsk Can you please search through Issues (open and closed) for similar issues? A few other people had the exact same issue — I'm 90% sure there's a problem with your babel setup (decorators don't work correctly)

**Comment by ndrkltsk** [comment]
No idea how and why, today the issue disappeared. I literally done nothing, and the machine I'm working on has been turned on all night long.

Thank you, closing.
