### ISSUE TITLE
Bootstrap error on Android with ExpoKit: undefined is not an object (evaluating 'Native.initialize')

### ISSUE THREAD

**Issue by alxmiron** [Nozbe/WatermelonDB#263]
My project, ejected from expo v32

I walked strictly through [the installation guide for Android](
https://github.com/Nozbe/WatermelonDB/blob/8c2030ffa389c9c2b1299e9b0bf981306381930d/docs/Installation.md#android-react-native) and did required steps (except `compile project(':watermelondb')` should be `implementation project(':watermelondb')`, update docs please). But get a runtime error:

```
[DB] Uh-oh. Database failed to load, we're in big trouble, [TypeError: undefined is not an object (evaluating 'Native.initialize')]
- node_modules/@nozbe/watermelondb/utils/common/logger/index.js:43:55 in error
- ... 15 more stack frames from framework internals
```

I made a small investigation: in `var Native = _reactNative.NativeModules.DatabaseBridge` part `DatabaseBridge` is undefined.

**Comment by radex** [comment]
> except `compile project(':watermelondb')` should be `implementation project(':watermelondb')`, update docs please)

I think you're right — can you please send a quick PR with a fix?

> I made a small investigation: in `var Native = _reactNative.NativeModules.DatabaseBridge` part `DatabaseBridge` is undefined.

the native adapter is not defined. So there's likely something wrong with the native setup, and Kotlin DatabaseBridge doesn't get compiled…

**Comment by alxmiron** [comment]
I'm not an expert in android, but I guess that the reason is in different `MainApplication` classes in case of expokit usage. Here is my current `MainApplication.java` and it doesn have `reactNativeHost` like [in example MainApplication.kt](https://github.com/Nozbe/WatermelonDB/blob/master/examples/native/android/app/src/main/java/com/app/MainApplication.kt): 

```
package host.exp.exponent;

import com.facebook.react.ReactPackage;
import com.facebook.react.shell.MainReactPackage;

import java.util.Arrays;
import java.util.List;

import expo.core.interfaces.Package;
import expo.loaders.provider.interfaces.AppLoaderPackagesProviderInterface;
import expo.modules.ads.admob.AdMobPackage;
import expo.modules.analytics.segment.SegmentPackage;
import expo.modules.appauth.AppAuthPackage;
import expo.modules.backgroundfetch.BackgroundFetchPackage;
import expo.modules.barcodescanner.BarCodeScannerPackage;
import expo.modules.camera.CameraPackage;
import expo.modules.constants.ConstantsPackage;
import expo.modules.contacts.ContactsPackage;
import expo.modules.facedetector.FaceDetectorPackage;
import expo.modules.filesystem.FileSystemPackage;
import expo.modules.font.FontLoaderPackage;
import expo.modules.gl.GLPackage;
import expo.modules.google.signin.GoogleSignInPackage;
import expo.modules.localauthentication.LocalAuthenticationPackage;
import expo.modules.localization.LocalizationPackage;
import expo.modules.location.LocationPackage;
import expo.modules.medialibrary.MediaLibraryPackage;
import expo.modules.permissions.PermissionsPackage;
import expo.modules.print.PrintPackage;
import expo.modules.sensors.SensorsPackage;
import expo.modules.sms.SMSPackage;
import expo.modules.taskManager.TaskManagerPackage;
import expolib_v1.okhttp3.OkHttpClient;

import com.nozbe.watermelondb.WatermelonDBPackage;

public class MainApplication extends ExpoApplication implements AppLoaderPackagesProviderInterface<ReactPackage> {

  @Override
  public boolean isDebug() {
    return BuildConfig.DEBUG;
  }

  // Needed for `react-native link`
  @Override
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // Add your own packages here!
        // TODO: add native modules!

        // Needed for `react-native link`
        new MainReactPackage(),
        new WatermelonDBPackage()
    );
  }

  public List<Package> getExpoPackages() {
    return Arrays.<Package>asList(
        new CameraPackage(),
        new ConstantsPackage(),
        new SensorsPackage(),
        new FileSystemPackage(),
        new FaceDetectorPackage(),
        new GLPackage(),
        new GoogleSignInPackage(),
        new PermissionsPackage(),
        new SMSPackage(),
        new PrintPackage(),
        new ConstantsPackage(),
        new MediaLibraryPackage(),
        new SegmentPackage(),
        new FontLoaderPackage(),
        new LocationPackage(),
        new ContactsPackage(),
        new BarCodeScannerPackage(),
        new AdMobPackage(),
        new LocalAuthenticationPackage(),
        new LocalizationPackage(),
        new AppAuthPackage(),
        new TaskManagerPackage(),
        new BackgroundFetchPackage()
    );
  }

  @Override
  public String gcmSenderId() {
    return getString(R.string.gcm_defaultSenderId);
  }

  @Override
  public boolean shouldUseInternetKernel() {
    return BuildVariantConstants.USE_INTERNET_KERNEL;
  }

  public static OkHttpClient.Builder okHttpClientBuilder(OkHttpClient.Builder builder) {
    // Customize/override OkHttp client here
    return builder;
  }
}
```

I also learned what `react-native link {native-library}` does:
1. adds `compile project(':{native-library}')` to dependecies in `android/app/build.gradle`
2. includes project in `android/settings.graddle`
```
include ':{native-library}'
project(':{native-library}').projectDir = new File(rootProject.projectDir, '../node_modules/{native-library}/android')
```
3. imports and create an instance in `MainApplication.java`:
```
  @Override
  public List<ReactPackage> getPackages() {
    return Arrays.<ReactPackage>asList(
        // new MainReactPackage(),
        new WatermelonDBPackage()
    );
```

As you see there is nothing special that we haven't done according to watermelon install guide.

**Comment by radex** [comment]
cc @rozPierog

**Comment by Oscarz90** [comment]
@alxmiron , how did you solve it?

**Comment by rozPierog** [comment]
@alxmiron how about kotlin? Did you add it to your project? maybe this is the root of your problem. [Link to Android installation docs](https://github.com/Nozbe/WatermelonDB/blob/master/docs/Installation.md#android-react-native)

**Comment by alxmiron** [comment]
I made it working with [expo bare workflow](https://docs.expo.io/versions/v32.0.0/bare/hello-world/). I also recommend to read [this article](https://blog.expo.io/you-can-now-use-expo-apis-in-any-react-native-app-7c3a93041331)

**Comment by alxmiron** [comment]
> @alxmiron what about kotlin? Did you add it to your project? maybe this is the root of your problem. [Link to Android installation docs](https://github.com/Nozbe/WatermelonDB/blob/master/docs/Installation.md#android-react-native)

Yes, I added Kotlin as required
