### ISSUE TITLE
Transform column value before db transaction

### ISSUE THREAD

**Issue by arahmanali** [Nozbe/WatermelonDB#273]
> before jumping to the issue i would like to mention that we really like the idea of what WatermelonDB is doing which makes so many use-cases easy for us to implement also looking forward to see more features and improvements in future.

well the problem is while Sync `pullChanges` i am trying to transform some data coming from the server before saving into the database, found out `@json` decorator do the same with **sanitize** but its not working on pull while syncing your db to server.

could anyone highlight why? am i missing anything?

Thanks

**Comment by radex** [comment]
> i am trying to transform some data coming from the server before saving into the database

why not transform it in your `pullChanges` implementation? That should be the appropriate place for this

> found out `@json` decorator do the same with **sanitize** but its not working on pull while syncing your db to server.

Sync works on a lower level than Model decorators — and doesn't know about them.
