### ISSUE TITLE
Build failed 0.59

### ISSUE THREAD

**Issue by jaysonjh** [Nozbe/WatermelonDB#288]
DatabaseBridge.kt: (196, 37): Only safe (?.) or non-null asserted (!!.) calls are allowed on a nullable receiver of type ReadableArray?

**Comment by GustavoMontenegro** [comment]
Hello, in my case watermelon not install in react-native project:
"react": "16.8.3",
"react-native": "0.59.1",
"@nozbe/watermelondb": "^0.10.1",

**Comment by vdlindenmark** [comment]
Just make sure you use the newest version of a package before you create an issue :-).
It's already fixed in `0.11.0`: https://github.com/Nozbe/WatermelonDB/issues/276

**Comment by jaysonjh** [comment]
Upgrade to 0.11.0. It is work now.

**Comment by vdlindenmark** [comment]
Nice! You can close this issue :)
