### ISSUE TITLE
Add npm in install instructions along with yarn

### ISSUE THREAD

**Issue by co16353sidak** [Nozbe/WatermelonDB#299]
I have observed that in the installation instructions, there is a preference of `yarn` over `npm` for the purpose of installation and setup of `watermelonDB`.
While in most cases this is preferred, there are many users who prefer to only use npm as their default package manager in an attempt to aid simplicity.

Shouldn't it be better to add support for npm as well, I pre-assume that npm should also be supported out of the box and this shouldn't be involving anything other than documentation files.
I would also love to work on this as my first contribution here 🥇

**Comment by radex** [comment]
@co16353sidak I think `yarn` is so popular in the community, anyone with enough experience to use a (relatively advanced) library like WatermelonDB is going to be familiar with it.

Nevertheless, if you want, I'll happily merge a pull request updating the documentation to mention both yarn and npm
