### ISSUE TITLE
withDatabase returning undefined component RN v0.59.2

### ISSUE THREAD

**Issue by arosendorff** [Nozbe/WatermelonDB#304]
I've recently updated my app to React Native v0.59.2, and now withDatabase() appears to be returning undefined components in my code. Is this an issue that anyone else has experienced?

I have tested placing just a <View /> in withDatabase(), but that too returns an undefined component. If I remove withDatabase() the component is correctly rendered, albeit without any database props that I want it to have!

I am using WatermelonDB v0.12.0 and with-observables v1.0.3.

**Comment by vdlindenmark** [comment]
It's just working fine for me

**Comment by arosendorff** [comment]
@vdlindenmark Hmm okay, perhaps I have some package conflict somewhere. Do you by any chance have babel-plugin-module-resolver installed? I installed that recently, don't know if that is the problem but I don't know at the moment!

**Comment by vdlindenmark** [comment]
No, I haven't that one installed. I've only changed the version of WatermelonDB and RN, nothing else. So it sounds like a mismatch between some packages that you're using.

**Comment by arosendorff** [comment]
Okay cool, thank you for the help! I'm going to create a clean app to see if I can isolate the issue there.

**Comment by arosendorff** [comment]
I created a new project and the issue went away, so obviously I had some broken code somewhere. I'm going to close this issue.

**Comment by kesha-antonov** [comment]
I'm experiencing same
Did you find the cause?

**Comment by arosendorff** [comment]
@kesha-antonov I didn't find the cause, I have a very unfounded suspicion that it may have been [babel-plugin-module-resolver](https://github.com/tleunen/babel-plugin-module-resolver) (I haven't been using it since the issue). Do you by any chance use it in your code?

**Comment by kesha-antonov** [comment]
Yeah, I do

**Comment by arosendorff** [comment]
#469 seems to be the same issue, and they're also using **module-resolver**! I'm going to try take a look into it this weekend, but I suggest we move the discussion to #469 for now 🙂
