### ISSUE TITLE
Inspecting an item using react-devtools throws an error

### ISSUE THREAD

**Issue by Kabangi** [Nozbe/WatermelonDB#31]
### Steps to reproduce
1. Install https://www.npmjs.com/package/react-devtools
2. Run `react-devtools`
3. Toggle inspector from react-native dev options `cmd+D` on simulator
4. Click on an element that is coming from the DB
5. Observe the attached screenshot error is thrown

<img width="262" alt="screen shot 2018-09-14 at 12 47 12 pm" src="https://user-images.githubusercontent.com/8632600/45543252-c47e3280-b81c-11e8-934e-90ac7eb633e4.png">

**Comment by radex** [comment]
@Kabangi please provide more context — what you're doing, the code, etc. It's very difficult to diagnose your problem just from a screenshot

**Comment by Kabangi** [comment]
Sorry about that. I have added more info to it. 

Note! This might not be a priority since I would assume with the definition of models we already know the properties for each model but would be nice to have.

**Comment by radex** [comment]
@Kabangi is this still an issue?

**Comment by Kabangi** [comment]
Yes, it still is. For now to debug am using DB SQLite browser to check the model values. Tedious but works

**Comment by Kabangi** [comment]
Sometimes I want to inspect a list of models that were dispatched to
components just so am sure data is been saved correctly.

That said, since I filed this; I have learnt to inspect the actual database
which solves the pains I had of not been able to inspect with dev tools.

Feel free to close it.
