### ISSUE TITLE
Expo init

### ISSUE THREAD

**Issue by impactcolor** [Nozbe/WatermelonDB#310]
Are there any instructions to run with Expo init?  The instructions show setup for ios xcode and android.  Expo doesn't create either of those.

**Comment by ymahnovskyy** [comment]
As I know Expo has not include WatermelonDB native code, so for now you can use WatermalonDB only with detached application. Or add feature request to Expo to include it in future releases.

**Comment by radex** [comment]
Yeah, if you want Expo (not ExpoKit) support — you need to contact Expo, not us :)

**Comment by impactcolor** [comment]
Is that a good approach to have? Considering watermelon is being pitched for react and react-native when React-Native is very much pushing the use of Expo.  Any how thanks for your time.

**Comment by Slapbox** [comment]
@impactcolor as was mentioned, it's out of the hands of the maintainers whether they want to or not.
