### ISSUE TITLE
Query property using a dynamic property not changing

### ISSUE THREAD

**Issue by davideweaver** [Nozbe/WatermelonDB#313]
I have the following in a Note model...

```
@lazy attachments = this.collections
            .get('files')
            .query(Q.where('id', Q.oneOf(this.attachmentIds.split(';'))));
}

@field('attachment_ids') attachmentIds; // semi-delimited list of ids
```

but `note.attachments.observe()` does not cause a re-render when `attachmentIds` changes.

How can I write the `attachments` property so that it works like I want it to?

**Comment by davideweaver** [comment]
I figured this out. Essentially I needed to observer when the note changed so the `attachmentIds` would be updated. I'm not sure this is the best way of handling it, but it works.

```
    public observeAttachments() {
        return this
            .observe()
            .pipe(switchMap((note: Note) => {
                return this.collections
                    .get<File>('files')
                    .query(Q.where('id', Q.oneOf(note.attachmentIds)))
                    .observe();
            }));
    }
```
then in my component's `withObservables` I can return...

```
{
    note: note.observe(),
    attachments: note.observeAttachments(),
}
```
In addition to this change, I was able to cleanup the `attachmentIds` property, which I was storing as a semi-delimited string, by using `@json` to convert it into a `string[]`.

```
const sanitizeAttachmentIds = (rawIds: string[]) => {
    return Array.isArray(rawIds) ? rawIds.map(String) : []
};

...

@json('attachment_ids', sanitizeAttachmentIds) public attachmentIds!: string[];
```

+1 for typescript
++1 for watermelondb

**Comment by radex** [comment]
@davideweaver Nice! This is indeed the correct solution — or at least one I would implement.

Here's an even better (for performance) version:

```
@lazy attachments = this.observe()
    .pipe(
      distinctUntilKeyChanged('attachmentIds'),
      switchMap((note: Note) => {
                return this.collections
                    .get<File>('files')
                    .query(Q.where('id', Q.oneOf(note.attachmentIds)))
                    .observe();
            }),
      cacheWhileConnected
    )
```

**Comment by radex** [comment]
See https://github.com/Nozbe/WatermelonDB/blob/master/docs/Advanced/AdvancedFields.md#custom-observable-fields

**Comment by barbalex** [comment]
what is `cacheWhileConnected`?
