### ISSUE TITLE
Tons of hoodie depreciation warnings given by npm

### ISSUE THREAD

**Issue by co16353sidak** [Nozbe/WatermelonDB#315]
While working on setting up watermelondb into a project while following along with the documentation, I found that on installation of watermelons there are plenty of warnings given by npm regarding the use of a depreciated version of hoodie, I have enclosed a screenshot below, hopefully it makes some sense.
<img width="1389" alt="Screenshot 2019-04-11 at 3 01 04 PM" src="https://user-images.githubusercontent.com/35738138/55946849-08c69980-5c6b-11e9-827a-c8f2a91a3332.png">

If this is truly an error, I would love to work on this as my first issue here. 🥇

**Comment by radex** [comment]
I'm not sure if it's an actual issue on wmelon side or not — but If you can update dependencies such that those errors don't show up for you — please do, and submit a pull request :) I'll merge it if CI shows green checkmark
