### ISSUE TITLE
Database callbacks/events

### ISSUE THREAD

**Issue by pkrefta** [Nozbe/WatermelonDB#316]
Hi guys,

Is there any callbacks/events support for database ? I'd like to perform some operations after database is loaded.

e.g
`
const database = new Database({
    adapter,
    modelClasses: [
      Thing
    ],
    actionsEnabled: true,
  }, () => {
  console.log('Database loaded')
})`

I've looked through docs, but haven't found anything related ;)

**Comment by radex** [comment]
There's no "after database load" callback because there's no such thing. The database is available to use immediately.

**Comment by avinashlng1080** [comment]
Hello @radex ,

Do we have events/callbacks at all in watermelonDB and/or how should we implement them ? 

For example, I would like to register events when a migration starts, succeeds/fails and ends.  Can you please suggest, how I should go about that ?

**Comment by radex** [comment]
migrations are handled here:

https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/lokijs/worker/executor.js#L289

for loki and here:

https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/sqlite/index.js#L139

for sqlite

**Comment by avinashlng1080** [comment]
Thanks @radex .  This answers my question.

I have another question.  My use case is that I have several group of databases within the app.  This ' _setUpWithMigrations' will also be where I would need to patch the code if I need to allow migration for the active group of dbs only.

The idea being that I want to keep the app launching as quick as possible and delay as much as possible the migration for the other groups.  Can you please let me know if I'm on the right track here ?

**Comment by radex** [comment]
> I have another question. My use case is that I have several group of databases within the app. This ' _setUpWithMigrations' will also be where I would need to patch the code if I need to allow migration for the active group of dbs only.

I don't really understand what `group of databases` means to you.

**Comment by avinashlng1080** [comment]
Ok, imagine a database having TableA, TableB and TableC.  This is one group.

I will have several group each having the same table.  

When my app launches, it will be on group1 but the user can switch to group2.  Hence, if user is of group2, I would like to first start migration on group2 tables only and then defer the migration to group1.

**Comment by radex** [comment]
@avinashlng1080 Have you measured how much time do migrations take? Is this a real problem? If so, you'll have to implement this feature yourself. Alternative, if the "groups" are completely independent, you might use multiple separate databases

**Comment by avinashlng1080** [comment]
you're right.   I will adopt your strategy. thanks @radex
