### ISSUE TITLE
Recommended way to sort and getLatest of children

### ISSUE THREAD

**Issue by vdlindenmark** [Nozbe/WatermelonDB#320]
Hi! I have one question. I'm building a small chat app. My database has users and messages (relates to each other). The app has a Contactlist which shows all the users and Chatscreens with the messages.

I want to sort my contactlist by the last message for each contact. So the contact with the newest message will be the first one. The model of the contact looks like this now:
```
import { Model } from "@nozbe/watermelondb";
import { field, children, lazy } from "@nozbe/watermelondb/decorators";
import { Q } from "@nozbe/watermelondb";
import { action } from "@nozbe/watermelondb/decorators";

export default class Contact extends Model {
  static table = "contacts";

  static associations = {
    messages: { type: "has_many", foreignKey: "contact_id" }
  };

  @field("name") name;
  @field("image") image;
  @children("messages") messages;
  @lazy unreadMessages = this.messages.extend(Q.where("is_read", false));

  @action async markMessagesAsRead() {
    const unreadMessages = await this.unreadMessages.fetch();
    await unreadMessages.map(
      async message => await this.subAction(() => message.markAsRead())
    );
  }
}

```.

I'm wondering how could I sort the messages by a specific key (send date) and get the latest of it.
So I only can call contact.lastMessage or something like that. What is the recommended way to sort the messages in the model and get the latest?

**Comment by radex** [comment]
There's currently no database-level sorting — see Issues for more details. So it's recommended to just fetch the messages, and sort them as a JavaScript array.

**Comment by vdlindenmark** [comment]
Isn't that not really bad for performance? In that case I need to fetch all of the messages and sort them to only get the last one of each contact. Is there no other recommended way to do this? In an older version of the app we had a key in the contact model which contains the last received message, but that's a little to ugly 😆

**Comment by radex** [comment]
> Is there no other recommended way to do this? 

Not currently :/ Aside from implementing proper query-level sorting (which is hard), a raw query would be a quick workaround for this. There's a PR for this: https://github.com/Nozbe/WatermelonDB/pull/199 but it appears abandoned — I encourage you to pick up where the author left off so we can merge this in :)

**Comment by Bessonov** [comment]
Activity!

**Comment by vdlindenmark** [comment]
I think it's okey to close this issue. Just watch https://github.com/Nozbe/WatermelonDB/pull/199 and wait till it's fixed.
