### ISSUE TITLE
Select only some columns during query

### ISSUE THREAD

**Issue by wojryba** [Nozbe/WatermelonDB#327]
Hi,
we are storing files in some of our entities, and we would like to omit during some of the queries. 

Is there a way to implement selecting only some of the columns form given entity?

**Comment by radex** [comment]
No, that's not currently possible. I'd not recommend storing large chunks of data alongside metadata — I recommend making a separate table for that

**Comment by Stophface** [comment]
There is `Q.unsafeSqlQuery()` which one can use...

```
await database
      .get(TABLE)
      .query(
        Q.unsafeSqlQuery(
          `SELECT ${TABLE}.${COLUMN} FROM ${TABLE`,
        ),
      )
      .unsafeFetchRaw();
```

However, it would be nicer to have that implemented.
