### ISSUE TITLE
getting WARNING: API 'variant.getPackageLibrary()' is obsolete in android studio

### ISSUE THREAD

**Issue by AhmedMKamal** [Nozbe/WatermelonDB#330]
I'm getting the following warning when trying to sync project in android studio

```
WARNING: API 'variant.getPackageLibrary()' is obsolete and has been replaced with 'variant.getPackageLibraryProvider()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
REASON: The Kotlin plugin is currently calling this API. We are working to solve this.
WARNING: Debugging obsolete API calls can take time during configuration. It's recommended to not keep it on at all times.
Affected Modules: android-watermelondb
```

I can run the app using `react-native` cli and everything working as expected but the android studio seems to be not happy with this warning and keep failing the sync process, any ideas?

**Comment by radex** [comment]
@rozPierog any ideas?

**Comment by rozPierog** [comment]
It shouldn't fail whole sync, it's just a warning, not an error. I will look into updating Watermelons gradle in the coming weeks to increase compatibility and gradle/kotlin versions. @AhmedMKamal please try to `File>Invalidate cache/restart` and `Build>Clean`.  If still nothing, make sure that every module is on the same `Build Variant` and let me know if this fixes gradle sync.

**Comment by AhmedMKamal** [comment]
@rozPierog, unfortunately, I did that already but Gradle still not happy ¯\_(ツ)_/¯, as you mentioned It shouldn't fail the whole sync and in fact the sync fails only inside Android studio but using cli everything is working as expected.

**Comment by rozPierog** [comment]
Soo… I've finally have time to look closer into this, and it seems that there is nothing we can do about it. It's a kotlin plugin bug https://youtrack.jetbrains.com/issue/KT-30784 and guys at Jetbrains are working on it (Debug error: `REASON: The Kotlin plugin is currently calling this API. We are working to solve this.`) as I've said before, it's just a warning, it _should not_ cause sync failures.
I'm closing this issue, thanks for reporting!
