### ISSUE TITLE
Seed data for new database

### ISSUE THREAD

**Issue by curiousily** [Nozbe/WatermelonDB#332]
Hey,

Is there a way to add seed data for a new database?

Thanks!

**Comment by radex** [comment]
please search issues first - there was a similar question asked and answered

**Comment by curiousily** [comment]
> please search issues first - there was a similar question asked and answered

I did 5+ searches within the issues before posting this and was unable to find anything related. Oh well, will try a bit more :)

Thanks for the quick reply!

**Comment by azogheb** [comment]
@curiousily - did you find anything? I cannot seem to find any docs or issues on how to pre-load / see the database either?

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/issues/221
