### ISSUE TITLE
[Sync] Replace-mode sync

### ISSUE THREAD

**Issue by esbenp** [Nozbe/WatermelonDB#341]
I have some tables I find it hard to fit within the sync-model. An example is pivot tables. For us, these dont have IDs. And they can be updated in a myriad of ways, so keeping track of deletes is also difficult for various reasons. For many of them we don't keep track of timestamps either. However, I need the data to map tables in Watermelon. I am not sure if this is a bad idea but it would be a lot easier if I could just pull all pivot rows on every sync and then replace the current contents of the table.

For us, an example is product categories. A category can have many products and a product can have many categories. This is not something that can be edited in the Watermelon client, so it's read-only from that perspective. It would be stupidly simple if I could just request ALL product-categories rows on every sync and then just replace all current rows of `products_categories` with the contents given by the server.

Would it make sense to allow for this? Any potential pitfalls? It could be that the server returned something like `replace` instead of `created`

**Comment by radex** [comment]
I'm wary of adding additional sync modes (for the simple reason that sync is complicated enough, and with every new option the complexity you have to think about and test for increases a bunch)…

… but sure, I understand why that would be much easier for you.

Still, keep in mind, that you might have to do the backend work anyway at some point if you decide that there's too many `product_categories` and syncing by replacing is not performant enough. Another potential pitfall is if you try to observe and display in UI them. On every sync they will disappear and re-appear (but with different IDs). 

If you still think you'd like it this way, I can give you some pointers as to how to implement this.

**Comment by esbenp** [comment]
I think you bring up valid points, thanks. I will close for now :-)
