### ISSUE TITLE
Compatible with frameworks other than React? 

### ISSUE THREAD

**Issue by samrat-bhandari** [Nozbe/WatermelonDB#345]
Hello team!

First of all, really excited about the development of watermelondb. 

My question is : can watermelondb be used with other js frameworks like angular or vue? How about without any frameworks (vannila). I am considering using watermelondb in an upcoming project and wanted to know if it would be a viable offline first with sync solution for pwa built with something like polymer or stenciljs (webcomponents), or is there limitations?

**Comment by radex** [comment]
WatermelonDB is not dependent on React. Its API is pure JavaScript + observable Rx. So what makes WatermelonDB play nicely with React is just the `withObservables` HOC. If you can hook up a stream of Rx updates into Angular/Vue, you can use 🍉 there.

If you do, it would be great to open-source whatever is needed for that / or just write how to do this.

Let me know if this answers your question
