### ISSUE TITLE
invariant violation element type

### ISSUE THREAD

**Issue by ozankonur** [Nozbe/WatermelonDB#347]
I'm trying to create postList from Post Items.. I am using ListItem from nativebase components like;

`export const rawPostItem = ({post, user}) => (
    <ListItem avatar noBorder>
      .....
    </ListItem>
);
`
Then ;
`const PostItem = withObservables(['post'], ({ post }) => ({
    post: post.observe(),
    user: post.user.observe(),
}))(rawPostItem);`

and last one;

`const PostsList = ({ posts }) => (
    <View>
        <List>
        {posts.map(post => (
            <PostItem post={post} key={post.id} onPress={() =>alert('Pressed '+post.title)} />
        ))}
        </List>
    </View>
   );
   const enhance = withObservables([], ({database}) => ({
    posts: database.collections.get('posts').query().observe(),
    }));
   export default enhance(PostsList)`

And I am using PostsList like - `<PostList ../>` -

But I am getting error like: Invariant Violation: Element type is invalid: expected a string( for built-in components) or a class/function (for composite components) but got: **undefined**. You likely forgot to export your component from the file it's defined in. Check the render method of rawPostItem.

Any suggestion ?

**Comment by kesha-antonov** [comment]
Hey!
How did you solve it?

**Comment by ozankonur** [comment]
I didnt use nativebase list. I used flatlist

**Comment by kesha-antonov** [comment]
Thanks
