### ISSUE TITLE
Microseconds in timestamps

### ISSUE THREAD

**Issue by pkrefta** [Nozbe/WatermelonDB#367]
Hey guys,

I'm writing sync backend that is using PostgreSQL and by default datetimes are being stored  with microseconds precision. Unfortunately when syncing Watermelon is parseInt'ing lastPulledAt so we get integer when changes are being pulled and this causes problems. I could send PR replacing parseInt with parseFloat but this can be tricky since integers and floats are handled a bit differently (e.g in JSON). I've also noticed that created and updated timestamps are integer.

So what's the strategy here ? Are dates are meant to be precise to seconds rather than micro/miliseconds ? 😃

**Comment by radex** [comment]
all timestamps in 🍉 are standard JS timestamps — i.e. millisecond precision.

`lastPulledAt` never actually checks current Date - it only saves whatever you supply it from the sync fetcher and passes on in the next request. So you can simply pass on an integer with a microsecond-precision timestamp. Or a version number. Or whatever. 🍉 doesn't really care.

I'm not sure why `parseInt` is done on it. Are there actually any integer comparisons on it? I'm cool with it supporting floats, but you'd have to add proper test to make sure this is not a breaking change
