### ISSUE TITLE
this.collections is missing typescript types

### ISSUE THREAD

**Issue by ospfranco** [Nozbe/WatermelonDB#377]
on typescript I have something like:

```
class Foo extends  Model {
  static table = 'Foo';
  static associations = {
    'bar': {type: 'has_many', foreignKey: 'bar'}
  }

  public async createBar(bar: Bar) {
    await this.collections.get('bar') // This fails, because this.collections does not exist on the types
  }
}
```

You can see that this.collections does not exist, types need to be added.

**Comment by radex** [comment]
> types need to be added.

Hey @ospfranco, TypeScript support is 100% community-led, and so I highly encourage you to submit a pull request fixing this issue :)

**Comment by ospfranco** [comment]
I'm not 100% familiar with all the types right now, if nobody can solve this in the next few days I will try to make time produce a PR, thanks!
