### ISSUE TITLE
Edit forms and in-memory records

### ISSUE THREAD

**Issue by crrobinson14** [Nozbe/WatermelonDB#386]
Is there a recommended/ideal pattern for in-memory-only edit operations?

I have an app where the customer wants the user to be able to confirm/cancel changes to a record before submitting it to the server.

Typically that means in the form's constructor you copy an incoming record's properties to local state, wire the input fields to that state, then when leaving the form or hitting save, the user gets a prompt, and if they say yes we call the server to make the update using those local state properties.

But this is a lot of manual work if you get complex forms like master/detail views (order and its line items). You could be copying a lot of items and it's a lot of work to "diff" line items (figure out which to delete, which to add, etc. to the order)

Is there a way to "copy" or "clone" an object to an in-memory version? If you try to set a field on an object right now, you get a `Not allowed to change record outside of create/update()`. Which is fine - that makes total sense. What I want is a record that is "unbound" from the database.

If this is not possible the copy-method does work. I was just wondering if there's a better / more "Watermelon" solution.

**Comment by crrobinson14** [comment]
Update: just talking this through. I've gone with a pattern where in the model classes (since they're just ES6 classes) I've added four additional elements:

```
    editFields = {
        fieldA: '',
        ....
    };

    beginEditing() {
        this.editFields.fieldA = this.fieldA;
        ...
    }

    // NOTE: Must be called inside a "database.action()" wrapper...
    commitChanges() {
        return this.update(record => {
            record.fieldA = this.editFields.fieldA;
            ...
        });
     }
```

Does this feel like a good pattern? It's working well so far and the pattern in code is fairly nice (passed a record, you just call `record.beginEditing()` and tie all your form fields to `record.editFields.fieldN`) but it's extra boilerplate in every model...

**Comment by radex** [comment]
Hey @crrobinson14 

To be honest, I'm not sure how to go about this use case -- I haven't had the chance to think about it very hard. I am aware that many apps have this "forms" use case, though we don't.

When necessary, we simply keep things to change as react state until we're ready to actually update the record.

Your pattern seems like a reasonable way to go. To avoid boilerplate you could consider encapsulating its items into a separate object, and then to each Model you'd only add `editor = new RecordEditor(this)`, and then, e.g. `record.editor.beginEditing()`, `record.editor.commit()`, etc.

**Comment by radex** [comment]
btw. you could also try a pattern like this:

```
record = persistent record
tempRecord = new Model(record._raw, record.collection)

... make changes on tempRecord

when ready, use a helper to copy tempRecord's attributes onto record and update it — then dispose of tempRecord (which was never saved)
```

**Comment by crrobinson14** [comment]
@radex Thank you.
