### ISSUE TITLE
Allow adding newly created records to recordcache

### ISSUE THREAD

**Issue by esbenp** [Nozbe/WatermelonDB#396]
Some times we fetch a collection, add a new model and then need the combined collection (after new models have been added) to do some calculations. A simple example could be adding new lines to an order. It could go something like this:

```
let lines = this.lines.fetch()

// need lines collection for something

// now create a new line
const linesCollection = this.collections.get('lines')
const newLine = linesCollection.prepareCreate(line => {
  line.quantity = 10
  line.price = 100
  return line
})
this.create(newLine)

// we refetch the lines to recalculate the totals
lines = this.lines.fetch()

const totalQuantity = lines.reduce((carry, line) => carry += line.quantity, 0)
```

instead of the second fetch would it make sense to add a methods to `Collection` to manipulate its recordcache? I know I could already use `changeSet` but I am guessing it was not meant for external consumption, or what? Is there some recommended way of avoiding a refetch in a situation like this?

**Comment by radex** [comment]
I would not recommend manipulating `record cache`. this is something that's coupled between the native side and JS side to avoid passing objects over the bridge unnecessarily - and for fast `Collection.find()`.

When you can `Query.fetch()`, it will go over the bridge anyway. Is this a problem? Can't you save the prepared `lines` to database?

also:

```
let lines = this.lines.fetch()

// need lines collection for something

// now create a new line
const linesCollection = this.collections.get('lines')
const newLine = linesCollection.prepareCreate(line => {
  line.quantity = 10
  line.price = 100
  return line
})


temporaryLines = [...lines, newLine]
... do calculations on temporaryLines
```
