### ISSUE TITLE
Write up Pro tips

### ISSUE THREAD

**Issue by radex** [Nozbe/WatermelonDB#4]
Actions:

- invariants
- kwargs
- fast skip

Rendering:
- Prefetching!!!!
- Sorting

Performance tips:
- JSC + standard react basics
- prefetching
- minimy queries
- share query results (filter in js instead of doing multiple similar queries)
- batching

**Comment by fletling** [comment]
+ some best practices and tips on how to bind watermelon db data to react components, i.e. how to avoid unnecessary rerenders in react to keep performance high would be helpful. @sebastian-schlecht might be able to help here.
