### ISSUE TITLE
Database failed to load error

### ISSUE THREAD

**Issue by theixbass** [Nozbe/WatermelonDB#40]
After some time spent to set up this package in react native, got this error:

`[DB] Uh-oh. Database failed to load, we're in big trouble, [TypeError: undefined is not an object (evaluating 'Native.setUp')]`

I am using expo for development.

**Comment by radex** [comment]
Hey, looks like the native module is not set up. Did you go through Installation guide for iOS/Android?

**Comment by theixbass** [comment]
I missed defining the decorators in Model. After defining, I got an error:

`Unable to resolve "@nozbe/watermelondb/decorators"`

**Comment by radex** [comment]
So, is it working now for you or still no? Your error is most likely because you forgot to add the babel plugin to your config. Note that you need to restart the bundler after doing that

**Comment by theixbass** [comment]
Nop. Do you meen - @babel/plugin-proposal-decorators?

**Comment by radex** [comment]
please go through https://github.com/Nozbe/WatermelonDB/blob/master/docs/Installation.md carefully one more time ;)

**Comment by tbergq** [comment]
I got this same error, so I went to the docs. Adding `<appname>-Bridging-Header.h` solved the problem for me.

**Comment by danushan1246** [comment]
@radex

**Comment by radex** [comment]
@theixbass is this a solved issue?

**Comment by radex** [comment]
I assume it is — closing this now. @theixbass let me know if this issue should be reopened

**Comment by davidwadge** [comment]
@theixbass I have the same problem with Expo, how did you resolve in the end?

**Comment by theixbass** [comment]
> @theixbass I have the same problem with Expo, how did you resolve in the end?

I did not...

**Comment by davidwadge** [comment]
Okay, clearly this is not suitable for Expo at this time then. Back to RxDB it is...

**Comment by tbergq** [comment]
Yeah, makes sense, you probably cannot add swift files to expo project.

**Comment by radex** [comment]
I believe you can eject to ExpoKit and then just go through standard Installation steps: https://docs.expo.io/versions/latest/expokit/expokit

**Comment by Slapbox** [comment]
Are there any plans to attempt to support Expo?

**Comment by radex** [comment]
@Slapbox you can eject to ExpoKit. If you want easy built in support in Expo, you have to contact Expo ;)

**Comment by davidwadge** [comment]
To be honest I think it's in your interest to support Expo. Ejecting gives a developer far more choice when it comes to ORMs - you could use Realm, for example. Keeping everything in JS has significant advantages for many development teams.

**Comment by davidwadge** [comment]
The advantage of using Expo is that you keep your codebase _entirely_ in JS. Ejecting turns your codebase into a more native-y one, meaning I could just as well use another ORM, such as Realm for example.

**Comment by radex** [comment]
> Ejecting turns your codebase into a more native-y one, meaning I could just as well use another ORM, such as Realm for example.

Right. That's good, no?

**Comment by davidwadge** [comment]
Imagine you have a team of predominantly React web developers who have little to no experience with native iOS or Android development. In that circumstance, you want to keep as much as possible in JavaScript, which is why Expo exists.

**Comment by radex** [comment]
> In that circumstance, you want to keep as much as possible in JavaScript, which is why Expo exists.

That's cool, but what does that have to do with WatermelonDB? I don't decide what's part of the Expo SDK.

**Comment by Slapbox** [comment]
If people want WatermelonDB support in Expo, this is the place to make it known: https://expo.canny.io/feature-requests/p/add-support-for-watermelondb

**Comment by bemnet4u** [comment]
@david

**Comment by radex** [comment]
@bemnet4u I don't think it's possible, some basic native support is needed — I think. But you can investigage if you'd like

**Comment by drex44** [comment]
I have been facing the same issue. 
I started a new app using react-native. I followed general instructions and android instructions in installation.md.

can anybody help please?

**Comment by asharafshahi** [comment]
> I got this same error, so I went to the docs. Adding `<appname>-Bridging-Header.h` solved the problem for me.

When doing this initially, I wasn't sure where the file needs to go and deleted it to retry.  However, when following the steps again, XCode doesn't prompt to create the bridging header again.  Can you explain exactly how to create this file and which folder it goes into?

**Comment by tbergq** [comment]
<img width="270" alt="Screenshot 2019-06-29 at 19 37 12" src="https://user-images.githubusercontent.com/7705041/60387562-55b94f80-9aa5-11e9-8746-525672a292ba.png">

**Comment by asharafshahi** [comment]
For the next person that deletes the header file, XCode won't prompt you the second time and you'll need to manually create it.  Here are the instructions: [](https://mycodetips.com/ios/manually-adding-swift-bridging-header-1290.html )

**Comment by YajanaRao** [comment]
I am facing the same error in android. I tried linking manually.

**Comment by AbednegoTM** [comment]
facing same error after manual linking

**Comment by SangJunBak** [comment]
FYI for anyone running into this error on IOS, make sure you run `pod update` after this step: 
![Screen Shot 2021-12-28 at 4 50 37 PM](https://user-images.githubusercontent.com/29664023/147609667-ad727b2d-b0e1-4ba3-8a7a-8e998366e645.png)
