### ISSUE TITLE
Migrations are not detected

### ISSUE THREAD

**Issue by wojryba** [Nozbe/WatermelonDB#401]
Hi
I'm trying to implement migrations according to documentation. Unfortunately, I'm not able to make them work.
After adding migrations the message `Migrations can't be newer than schema. Schema is version 1 and migrations cover range from 1 to 2` is not logged to the console in any way.
After setting up new schema and updating version I get a message: 
`[DB] Database needs migrations`
`[DB] Migrations not available for this version range, resetting database instead`

Steps to reproduce:
1. Download example application from this repo. Install and launch it in dev mode.
2. Set up migrations according to documentation. *Perform Migration Setup* and *Step 1* - in step 1 remember to change the name of the table created to something else, as table `comments` already exists.
3. Try to run the app. The message `Migrations can't be newer than schema. Schema is version 1 and migrations cover range from 1 to 2` is not logged to the console in any way.
4. Perform step 2. Add a new table to the schema. Still no message.
5. Perform step 3. Increase the schema version number to match the migrations. You will get the messages:
`[DB] Database needs migrations`
`[DB] Migrations not available for this version range, resetting database instead`

It looks like the SQLiteAdapter doesn't detect migrations.
Is there any solution to this?

**Comment by radex** [comment]
can you paste initialization code of adapter and database obj?

**Comment by wojryba** [comment]
@radex sure:
`
const adapter = new SQLiteAdapter({
  dbName: 'WatermelonDemo',
  schema: mySchema,
  migrations,
})

const database = new Database({
  adapter,
  modelClasses: [Blog, Post, Comment],
  actionsEnabled: true,
})
`
But it's just code from your example, modified according to migrations docs.

**Comment by radex** [comment]
what version of 🍉 are you on? I think you're using pre-release docs with release version where the prop is named `migrationsExperimental`

**Comment by wojryba** [comment]
You are right. I was using version 12. After update to @next everything works;
