### ISSUE TITLE
Synchronization of large collections

### ISSUE THREAD

**Issue by wojryba** [Nozbe/WatermelonDB#403]
Hi,
We have the `_unsafeBatchPerCollection` flag for synchronizing of large databases. But what about the situation in which single collections has more than 20000 records?

For example, 100 000 QR codes. Is there any way to make that work?
If not, could you suggest some workaround for handling such large datasets in a single collection?

**Comment by radex** [comment]
@wojryba this is fixed on master (with the flag, single collection batches are split into 5k records max) - but not released yet. you can use the next tag from npm to try the improvement.

**Comment by radex** [comment]
let me know if this works - if so, please close the issue :)

**Comment by wojryba** [comment]
For 150k of records, we need to add `android:largeHeap="true"` to the manifest. 
After that, changes are applied in batches of 5k, as you said.
Everything seems to work fine :)
