### ISSUE TITLE
How to fetch related records in watermelondb?

### ISSUE THREAD

**Issue by vinaynarayankutty** [Nozbe/WatermelonDB#409]
I want to fetch related records from the table in react-native. I was following watermelon db's official document. 
``` 
import Blog from "./model/Blog";
 import Post from "./model/Post";
 ...
 export default class App extends Component {
 constructor(props){
 }

 generate = async () => {
 const blogsCollection = database.collections.get("blogs");
 const postsCollection = database.collections.get("posts");
 await database.action(async () => {
   const newBlogs = await blogsCollection.create(blog => {
     blog.name = "Anandtech";
   });
  });
  await database.action(async () => {
  const newPosts = await postsCollection.create(post => {
    post.title = "TSB boss to step down after IT fiasco (bbc.com)";
    post.subtitle = `ID: ${post.id}`;
    post.body =
      "Lorem ipsum sociis natoque penatibus et ultrices volutpat.";
    post.blog.set(newBlogs);
  });
  const blog = await Post.blog.fetch();
  console.log("blogblogblog", blog);
});
}
```

I was following their Relation part. I can't understand what's the problem here. Below shows my table schema.
```
export const mySchema = appSchema({
  version: 2,
  tables: [
    tableSchema({
      name: "blogs",
      columns: [{ name: "name", type: "string" }]
    }),
    tableSchema({
      name: "posts",
      columns: [
        { name: "title", type: "string" },
        { name: "subtitle", type: "string" },
        { name: "body", type: "string" },
        { name: "blog_id", type: "string" }
      ]
    })
  ]
});
```

This is the Post model class. 
```export default class Post extends Model {
  static table = "posts";

  static associations = {
    blogs: { type: "belongs_to", key: "blog_id" },
    comments: { type: "has_many", foreignKey: "post_id" }
  };

....

  @relation("blogs", "blog_id")
  blog;
}```

**Comment by drex44** [comment]
The way you're fetching the blog is wrong. You cannot fetch the record using Model.

First you have to get the collection for that table. And then use the collection and the id of the post to get the post. Then you can get the blog object.

https://github.com/Nozbe/WatermelonDB/blob/master/docs/CRUD.md#find-a-record-by-id

You can also query the collection using title of the post. It's mentioned on the same page in above url.

Can you also format your code in triple backticks so that it's easy to read.

**Comment by vinaynarayankutty** [comment]
But did you check this [https://github.com/Nozbe/WatermelonDB/blob/master/docs/Relation.md#fetching](url) , in the fetching section ?

**Comment by vinaynarayankutty** [comment]
Please check the issue #188 I've added screenshots of my code.

**Comment by drex44** [comment]
Yes, I have used it. That is when you already have the object(row) for comment and you want to get the author related to that comment.
In your case, you first need to fetch the post object using collection of it's table and then use post.blog.fetch() to fetch the related blog. 

P.S. Do not add screenshots of your code like that. Instead create a github gist and share it's url. You can share multiple files in one gist.

**Comment by vinaynarayankutty** [comment]
Okay, I have created a gist [https://gist.github.com/vinaynarayankutty/42fd39b064a4c7e8f6949e119f896d5b](url). When I run this, I'm getting this error.
![Screenshot_1563167748](https://user-images.githubusercontent.com/40576238/61196649-c3908880-a6ed-11e9-8ebc-40dddfb7882d.png). I've been trying the v0.2 of your Movie repo. I didn't understand the reason for this error.

**Comment by yanielbf** [comment]
> Okay, I have created a gist [https://gist.github.com/vinaynarayankutty/42fd39b064a4c7e8f6949e119f896d5b](url). When I run this, I'm getting this error.
> ![Screenshot_1563167748](https://user-images.githubusercontent.com/40576238/61196649-c3908880-a6ed-11e9-8ebc-40dddfb7882d.png). I've been trying the v0.2 of your Movie repo. I didn't understand the reason for this error.

Hi, I have the same error, if you can solve, please help me. Greetings.
