### ISSUE TITLE
Improve error messages (for non-Flow users)

### ISSUE THREAD

**Issue by radex** [Nozbe/WatermelonDB#42]
There is a lot of places in Watermelon where it's easy to make a mistake and make the app break with a strange error message — except that Flow can catch those errors before we even run the code.

Still, some of those errors may be hard to understand to someone not familiar with Watermelon internals and especially if you don't use Flow.

A good example is Schema: https://github.com/Nozbe/WatermelonDB/blob/e69aa85a65afb0a3c649792fae9d1fe402d9df59/src/Schema/index.js#L54 — if you mis-format the schema, Watermelon will throw errors at you.

Some examples of Watermelon not doing a great job:

- forgetting `static tables` or `static associations`
- making a `Q.on` query without the proper `association` set
- making a `@children` field without an `association`
- wrong column name in `@field` and other decorators
- Database initializer - if you forget to pass some fields, it will blow up somewhere else
- … probably many more — add in comments stuff you came across

We won't be working on this, since we rely on Flow, but it should be easy for anyone to implement and contribute back to Watermelon :)

**Comment by ymahnovskyy** [comment]
When I set property of model wrong type (for example string for number property) it is not saved without any warning or error.
Should I add separate issue or that should  be fixed in scope of this one?

**Comment by radex** [comment]
> When I set property of model wrong type (for example string for number property) it is not saved without any warning or error.

What do you mean, exactly? Can you give a snippet of code?

**Comment by ymahnovskyy** [comment]
I have model with such columns 
```javascript
      columns: [
        { name: 'x', type: 'number' },
        { name: 'y', type: 'number' },
```

and when I want to create record and set 
```javascript
    obj.x = '1'; // wrong type: string
    obj.y = '2'; // string
```
I didn't see any warning (I don't use Flow) or errors and values x and y of this record in db were x = 0 and y = 0.
