### ISSUE TITLE
Set database directory

### ISSUE THREAD

**Issue by djorkaeffalexandre** [Nozbe/WatermelonDB#424]
Is possible to set database directory to use App Groups on iOS?
I have a Share Extension and want to access data between client and this extension, but I need to set the storage to path of App Group.

**Comment by radex** [comment]
@djorkaeffalexandre you can pass a full file path to `dbName` - so you can pass from your own native code the path to JS to instantiate the SQLiteAdapter. we do this at nozbe 4 :)

PS. Would you mind contributing to the docs so that others can find this pro tip as well?

**Comment by radex** [comment]
@djorkaeffalexandre hey, so did this work for you?
