### ISSUE TITLE
Improve web demo for mobile

### ISSUE THREAD

**Issue by radex** [Nozbe/WatermelonDB#43]
- [ ] remove 300ms delay on iOS
- [ ] add the CSS prop iOS needs to get smooth scrolling views
- [ ] responsive layout?

Contributions welcome!

**Comment by panr** [comment]
I’m on it 😎

**Comment by dipiash** [comment]
Hi @radex !
I'm sorry, I forgot assign pull request to you. But now I can't do this.


I need more information about this point
> * remove 300ms delay on iOS
