### ISSUE TITLE
Dealing with added columns when using sync

### ISSUE THREAD

**Issue by esbenp** [Nozbe/WatermelonDB#430]
I want to add a new column to my database (boolean value). However, since I am using remote sync this value will be incorrect for migrated tables, e.g. all rows will be false, but in reality might be true. The way I am dealing with this on the server is to bump all timestamps to simulate they have been updated. So next time a synchronization is run all rows will have the correct boolean value.

So I am thinking I would be nice if I could know in application land that a migration was run, that way I can trigger an automatic synchronization or display a message to the user if a sync is needed due to a migration. E.g.

```
const adapter = new SQLiteAdapter({
  dbName: 'database',
  onInit: ({ didMigrate }: { didMigrate?: { fromVersion: number, toVersion: number } }) => {
    if (didMigrate && fromVersion < 7 && toVersion >= 7) {
      attemptSync()
    }
  },
  migrations,
  schema: schema,
})
```

Because I introduced a new column in version 7 I could basically force the user to sync straight away, or maybe alert the user to take action

Related: #316, https://github.com/Nozbe/WatermelonDB/pull/62#issuecomment-426970096

**Comment by esbenp** [comment]
Thinking a bit more about this, what is actually recommended with adding columns and doing remote sync? Because even if I bump the timestamps on the server it might be that users synchronize before they download the update and therefore the sync that occurs after update will still have a timestamp after the one i made on the server 🤨

**Comment by esbenp** [comment]
Another option is to pass schema version to sync endpoint `/sync?last_pulled_at=[timestamp]&schema_version=2` and then keep a record of schema version per user on the server. That way the server can determine what to push in case a user migrates from schema x to y

**Comment by radex** [comment]
You're onto something! migration-aware syncs are something that's not properly implemented yet, and it really should be a part of Watermelon.

Would you be interested in contributing and helping out with the implementation?

> and then keep a record of schema version per user on the server. That way the server can determine what to push in case a user migrates from schema x to y.

Nah - the source of truth should be the local database. We can add a magic field in the local database that tracks which schema version the app last successfully synced with, and then if that changes, we can pass

`/sync?last_pulled_at=123123123&schema_version=10&last_pulled_version=9`

the server would then push all changes since last_pulled_at AND all records that have non-default values on columns that have been added between version 9 and 10. 

that would require the server to be aware of schema version differences, but i don't think that's really avoidable -- right?  Unless you have another idea?

> However, this does not work in case the user has multiple clients, so this needs to be logged per device using something like device ID from react-native-device-info

you should never, ever, ever, ever, rely on device ID for anything important. iOS will never give you the true device ID, and the ID it will give you can change at any moment. this also breaks on backup restores etc.

**Comment by esbenp** [comment]
> 
> Would you be interested in contributing and helping out with the implementation?
> 

Yes, sure. I kind of need it now, so it makes sense for me to work on it :-)

> 
> `/sync?last_pulled_at=123123123&schema_version=10&last_pulled_version=9`
> 
> the server would then push all changes since last_pulled_at AND all records that have non-default values on columns that have been added between version 9 and 10.
>

This would be the best since you pull the minimum amount of data needed. However, for us its simpler just to pull all rows in the table (regardless of whether or not something already has default value). Is there any pitfalls I should be aware of doing that? The only thing I could think of was if client has local unsynced writes but since client-wins per property-conflict I don't think that would be an issue, right?

One question that pops up, what should be the migration path for Watermelon itself. I mean if I upgrade Watermelon that a version that supports `last_pulled_version` what should be its initial value? 1? Or null? I suppose this case needs to be handled in user-land, i.e. `last_pulled_version` might be null so account for that possibility.

And how do you go about upgrading Watermelons internal tables? Do a check in adapter init and add column if it does not exist?

> 
> that would require the server to be aware of schema version differences, but i don't think that's really avoidable -- right? Unless you have another idea?
>

Only other way I can see it could work was if client passed the tables that needed "refresh". However, I think it makes more sense to keep this logic on the server.

>
> you should never, ever, ever, ever, rely on device ID for anything important. iOS will never give you the true device ID, and the ID it will give you can change at any moment. this also breaks on backup restores etc.

Yes, this is much better. I actually did the first implementation by saving the device ID - so thanks for your insight haha! Had no idea it could change, although in my case it would not be so bad since it would just pull a full table instead of partial.

**Comment by radex** [comment]
> This would be the best since you pull the minimum amount of data needed. However, for us its simpler just to pull all rows in the table (regardless of whether or not something already has default value). Is there any pitfalls I should be aware of doing that?

Yeah -- just the fact that there's a lot of data and it might be very slow. But the difference is in server-side implementation, right? So the watermelon sync protocol "spec" could say that the server SHOULD return records with non-default values on migrated columns, but MIGHT just return all records in an affected table.

> The only thing I could think of was if client has local unsynced writes but since client-wins per property-conflict I don't think that would be an issue, right?

No, it shouldn't be an issue. I think there is a small likelihood of very minor issues (I don't remember what exactly - something related to deleted records i think -- it's documented either in sync code or sync tests), but I was careful to design the sync protocol in such a way that multiple writes of the same pulled data wouldn't corrupt the data in any way.

> One question that pops up, what should be the migration path for Watermelon itself. I mean if I upgrade Watermelon that a version that supports last_pulled_version what should be its initial value? 1? Or null? I suppose this case needs to be handled in user-land, i.e. last_pulled_version might be null so account for that possibility.

Good point. I think we must specify `last_pulled_version` to be nullable. This will also pop up on first sync, when both last_pulled_at, and last_pulled_schema_version would be null.

> And how do you go about upgrading Watermelons internal tables? Do a check in adapter init and add column if it does not exist?

There are no internal tables. There's a `local_storage` table (that's also accessible in user land), and Watermelon just adds keys `__watermelon_sync_last_pulled_at`.

**Comment by radex** [comment]
anyway, see:

https://github.com/Nozbe/WatermelonDB/blob/master/src/sync/index.js#L61

this is the sync logic - the massive comment at the bottom explains the procedure in quite some detail.

and here you have the logic of storing last_pulled_at:

https://github.com/Nozbe/WatermelonDB/blob/master/src/sync/impl/index.js#L12

we can do something similar for last_pulled_schema_version.

let me know if you need more tips for implementation

**Comment by radex** [comment]
@esbenp Hey, any progress? :)

**Comment by samrat-bhandari** [comment]
@esbenp

**Comment by radex** [comment]
I'm working on a proper solution to migration syncs: https://github.com/Nozbe/WatermelonDB/pull/714

**Comment by radex** [comment]
I'm closing this as there is now support and protocol for migration-aware syncs
