### ISSUE TITLE
How could i configure Adapters like LokiJS

### ISSUE THREAD

**Issue by jembach** [Nozbe/WatermelonDB#441]
Hi,

is it possible to configure Adapters by their costum Settings? like LokiJS.
Their I need to change some defaults to work.

Thank for your help

**Comment by radex** [comment]
> Their I need to change some defaults to work.

what defaults, exactly?

Currently only name is configurable - https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/lokijs/worker/executor.js#L217 - but if you need more settings, send a PR!

**Comment by jembach** [comment]
Sorry for the late answer.
The problem has been solved by myself. Lokijs have themself no config options while setup, that I had thought.
