### ISSUE TITLE
Are Arrays or lists of Standard Field types supported 

### ISSUE THREAD

**Issue by jembach** [Nozbe/WatermelonDB#442]
Hi, 

is it possible to create for a schema an attribute, that contains an array/list of standard datatypes like string,number,bool?

Or do i have to add a new schema containing just a single attribute and add a relation between boths?

Thank for your help

**Comment by radex** [comment]
> Or do i have to add a new schema containing just a single attribute and add a relation between boths?

Yes. There are no arrays, lists unfortunately as a data type -- because SQLite doesn't have that. So the right thing to do is to create a separate table and a relation between them.

**Comment by jembach** [comment]
okay thank you
