### ISSUE TITLE
Relation between multiple parent table to single child table

### ISSUE THREAD

**Issue by jembach** [Nozbe/WatermelonDB#449]
Hi,

is it possible to create a relation from multiple parent tables to a single child table?

For better explanation the problem here is an example:

I have multiple chats. in the chats are multiple members of type user. But some members share the same chats. For decreasing storage size, it would be perfect, when I now just store the user once and connect then all chats with the user with them.

**Comment by radex** [comment]
the child would should have something like `parent_id: string` and `parent_type: string` fields and then you can get the right parent based on type

**Comment by jembach** [comment]
Thank you for your answer
