### ISSUE TITLE
Diagnostic error: Database.batch() can only be called from inside of an Action, but documentation says this should be possible

### ISSUE THREAD

**Issue by IgorBelyayev** [Nozbe/WatermelonDB#457]
I'm getting the following error when trying to call `batch` on a `database` directly:
```
Diagnostic error: Database.batch() can only be called from inside of an Action. See docs for more details.
```

However, in the [docs](https://nozbe.github.io/WatermelonDB/Actions.html) it says that `batch` can be called outside of an `Action`:
```
Call await this.batch in the Action (outside of actions, you can also call .batch() on the Database object)
```

**Comment by radex** [comment]
no, that’s just a badly worded sentence. see: https://nozbe.github.io/WatermelonDB/Actions.html#inline-actions — you always need to call it from an action, what the sentence meant to say is that if you’re not using a method marked with `@action`, but using `database.action`, then you can use `database.batch`. does that make sense? I would very much appreciate a quick PR fixing this documentation mistake

**Comment by hannojg** [comment]
So, it means that when batching: actions marked with `@action` it must be run inside a `database.action(async () => { ...`  - while when batching for example explicit a `.prepareCreate` (outside of a model's definition) it doesn't need to be wrapped around with `action` and we can call directly `database.batch(...`.

Did I get this correct?

**Comment by radex** [comment]
No. All database write operations (batch, create, update, delete) must be wrapped in an action. And you can make an action in two ways: explicitly using `database.action()` block or by marking a function using `@action` decorator

**Comment by igorcaldeira** [comment]
+ 1 
same question here. kinda confusing by the way it's wrote
it would be cool unmark the "wontfix" and have a look :)
