### ISSUE TITLE
Handling database file replacement

### ISSUE THREAD

**Issue by arosendorff** [Nozbe/WatermelonDB#470]
Is there a best-practices way of handling the .db file being deleted and replaced? I'm experimenting with allowing multiple users to login to the app, and I switch out the database file for the user if they have previously logged-in, ensuring no data loss while only showing the logged-in user their data.

Currently I'm just creating a new SQLiteAdapter and setting it to `database.adapter` which seems to work well enough, but I wondered if there was perhaps a better way to deal with this.

**Comment by radex** [comment]
> Currently I'm just creating a new SQLiteAdapter and setting it to database.adapter which seems to work well enough, but I wondered if there was perhaps a better way to deal with this.

the correct way to do this is create a new Database object, with a different dbName. Replacing an adapter on the one database object might lead to bad things™ happening

**Comment by arosendorff** [comment]
> the correct way to do this is create a new Database object, with a different dbName. Replacing an adapter on the one database object might lead to bad things™ happening

Thank you for the info, I will try to avoid those bad things™ in our app!
