### ISSUE TITLE
Model instance dependent json sanitisation

### ISSUE THREAD

**Issue by davidkell** [Nozbe/WatermelonDB#487]
We have a use case with the following parameters:
- There is a single model `MyEntity`
- `MyEntity` has a `kind` field (an Enum) and a `content` field (JSON)
- The JSON schema for the `content` field depends on the `kind`

We want to validate and sanitise the JSON field using the sanitise content field. Is it possible to provide information on the `kind` to the sanitise content function for the `content` JSON field? (We couldn't find a way.)

A more concrete example:

```
export default class MyEntity extends Model {
  static table = 'myentity'

  @field('kind') kind

  @json('content', (content: object) => {
    // Here we want the validation function to depend on the kind.
    // Unfortunately this is not defined.
    validate(this.kind, content)
    return content
  })

}
```

(Another solution would be to have separate model for each distinct kind. Unfortunately, this would not work as we need to dynamically generate new kinds.)

**Comment by rkrajewski** [comment]
@davidkell Hi, indeed there is no way to do it, maybe only if data provided to sanitizer would contain a `kind`, but probably it's not what you look for.

Feel free to contribute - at first look, only what you need is to call sanitizer with `this` context.

here https://github.com/Nozbe/WatermelonDB/blob/master/src/decorators/json/index.js#L42
and here https://github.com/Nozbe/WatermelonDB/blob/master/src/decorators/json/index.js#L45

```js
sanitizer.call(this, json)
```

but I haven't tested this solution.

**Comment by davidkell** [comment]
Thanks, will have a look at this.
