### ISSUE TITLE
Supporting react-native 0.60.x

### ISSUE THREAD

**Issue by jpm-nz** [Nozbe/WatermelonDB#491]
Does the 0.14.0 support react-native 0.60.x?

After upgrading to react-native 0.60.4 I'm getting an error 'Uh-oh. Database failed to load, we're in big trouble.'
Stacktrace:

> C:\xx\node_modules\react-native\Libraries\Core\ExceptionsManager.js:94 [DB] Uh-oh. Database failed to load, we're in big trouble TypeError: Cannot read property 'initialize' of undefined
>     at SQLiteAdapter._callee$ (C:\xx\node_modules\@nozbe\watermelondb\adapters\sqlite\index.js:103)
>     at tryCatch (C:\xx\node_modules\regenerator-runtime\runtime.js:45)
>     at Generator.invoke [as _invoke] (C:\xx\node_modules\regenerator-runtime\runtime.js:271)
>     at Generator.prototype.<computed> [as next] (C:\xx\node_modules\regenerator-runtime\runtime.js:97)
>     at asyncGeneratorStep (C:\xx\node_modules\@nozbe\watermelondb\adapters\sqlite\index.js:30)
>     at _next (C:\xx\node_modules\@nozbe\watermelondb\adapters\sqlite\index.js:32)
>     at C:\xx\node_modules\@nozbe\watermelondb\adapters\sqlite\index.js:32
>     at tryCallTwo (C:\xx\node_modules\promise\setimmediate\core.js:45)
>     at doResolve (C:\xx\node_modules\promise\setimmediate\core.js:200)
>     at new Promise (C:\xx\node_modules\promise\setimmediate\core.js:66)

If not, any idea of when react-native 0.60.x will be supported?

**Comment by radex** [comment]
it does support 0.60 - perhaps your babel config got damaged?

**Comment by aniciom** [comment]
Its working fine by my side using RN 0.60.5, checkout your schema key's value and its declaration when you set up the SQLiteAdapter object, maybe you're misspelling something.

**Comment by YajanaRao** [comment]
I use react native 0.60 and I was asked to manually link the module to get it working.

**Comment by bogdancochioras-clarisoft** [comment]
I also got the following warning regarding autolinking:

```
[!] use_native_modules! skipped the react-native dependency '@nozbe/watermelondb'. No podspec file was found.
    - Check to see if there is an updated version that contains the necessary podspec file
    - Contact the library maintainers or send them a PR to add a podspec. The react-native-webview podspec is a good example of a package.json driven podspec. See
    https://github.com/react-native-community/react-native-webview/blob/master/react-native-webview.podspec
    - If necessary, you can disable autolinking for the dependency and link it manually. See
    https://github.com/react-native-community/cli/blob/master/docs/autolinking.md#how-can-i-disable-autolinking-for-unsupported-library
```

**Comment by radex** [comment]
This is correct. WatermelonDB doesn't support auto linking yet

**Comment by pierroo** [comment]
> This is correct. WatermelonDB doesn't support auto linking yet

Thank you@radex ,

So, how does one install / use Watermelon on React Native 0.60.5?

**Comment by radex** [comment]
@pierroo according to the install instructions in the docs
