### ISSUE TITLE
Error observe method in query

### ISSUE THREAD

**Issue by yanielbf** [Nozbe/WatermelonDB#499]
Good morning, I have trouble when I invoke this function database.collections.get('posts').query().observe() in the HOC withObservable or even if I invoke it outside it throws me an error: (0, _defer.defer) is not a function. Help ASAP, please !!!

**Comment by YajanaRao** [comment]
The walk around for me was to change all defer import from rxjs to `var _defer = require("rxjs");` in node_module

**Comment by yanielbf** [comment]
Hi, thank you for answering. You create a for of project for modify that.??? Greetings

**Comment by YajanaRao** [comment]
I have modified the imports in `node_modules\@nozbe\watermelondb` project. Please do refer the file and line number from the error screen.

**Comment by yanielbf** [comment]
Ok, thank you again. I will try and I will comment if it will work.  Greetings
