### ISSUE TITLE
Full Content Search Example

### ISSUE THREAD

**Issue by prog20901** [Nozbe/WatermelonDB#522]
Hi,

The demo https://watermelondb.now.sh/ shows the title search alone.

How to do a content search ? Also, include the number of hits in brackets before searching..

After search, would like to highlight the search words in all occurrences.

Example, type a word in http://table.branham.org/#/main and see the words....it has both content search as well as title search...

Please advise.

Thanks.

**Comment by radex** [comment]
@prog20901 you just… have to implement that yourself
