### ISSUE TITLE
No driver with tag X available

### ISSUE THREAD

**Issue by djorkaeffalexandre** [Nozbe/WatermelonDB#528]
We use `WatermelonDB` on `Rocket.Chat.ReactNative`, and have a lot of errors with `No driver with tag 2 available` on `fetch()` and on `observeWithColumns().subscribe()`..
Any idea about it?

**Comment by radex** [comment]
@djorkaeffalexandre That's strange, worrying even.

Are you sure you're not creating multiple SQLiteAdapter instances, or Database intances hooked up to the same SQLiteAdapter?

**Comment by djorkaeffalexandre** [comment]
We change databases when user change server using this: `db.setActiveDB(dbName)`
https://raw.githubusercontent.com/RocketChat/Rocket.Chat.ReactNative/develop/app/lib/database/index.js

**Comment by radex** [comment]
is this issue Android-only?

**Comment by djorkaeffalexandre** [comment]
No, ocorres on iOS too. :/

**Comment by radex** [comment]
that's strange -- can you run some debugging on both SQLiteAdapter and DatabaseBridge.swift / DatabaseBridge.kt to figure out what's going on? What you're describing _should_ work just fine

**Comment by djorkaeffalexandre** [comment]
Ok! I'll make it! Thanks <3

**Comment by djorkaeffalexandre** [comment]
@radex How can I debug these files? I've tried to add some `consoleLog` on `DatabaseBridge.swift` but can't see nothing.
