### ISSUE TITLE
How to cache network query ?

### ISSUE THREAD

**Issue by kunaldodiya** [Nozbe/WatermelonDB#533]
Hi, Sending same query with same parameters that give same results every time, instead of sending http request to network, is it possible to cache query to save bandwidth ? I used to use Apollo Client for Graphql, they had this feature to cache network request with several options like cache only, network first, network only etc

**Comment by radex** [comment]
@kunaldodiya you seem to be misunderstanding what WatermelonDB is. It does not deal with network queries.
