### ISSUE TITLE
Large amount of logging on RN 0.61+

### ISSUE THREAD

**Issue by ospfranco** [Nozbe/WatermelonDB#545]
I'm in the process of updating our project to RN 0.61, after I bumped the RN versions I started getting crazy amounts of logs, it slows down performance quite a bit:

![Screenshot 2019-10-28 at 13 39 25](https://user-images.githubusercontent.com/1634213/67679225-eab35300-f988-11e9-8bf0-190f9810c411.png)

Is this behavior known?

**Comment by radex** [comment]
Seems like an issue with a dependency we use. If you pin rambdax to `2.15.0`, does the issue persist?

**Comment by ospfranco** [comment]
Not entirely sure if I did it correctly but I added rambdax `2.15.0` to the project dependencies, did a `yarn install` and ran it again.

The large amount of logging is still there.

**Comment by ospfranco** [comment]
ok, modified yarn.lock, removed all references to rambdax 2.6.1 to rambdax 2.15.0 and the excesive amount of logging is gone

**Comment by arosendorff** [comment]
We also had this issue, it appears that an errant console.log made its way into the rambdax release. [patch-package](https://www.npmjs.com/package/patch-package) is a pretty useful utility if you don't want to add rambdax as a dependency to your project to fix this.

**Comment by ospfranco** [comment]
just for more information about the workaround:
- add patch-package
- go to the node_modules
- you have to modify rambdax.js file in the /dist folder
- Remove the console log in the `values` function

@radex is it possible to get a 14.XX release before 15.XX?

**Comment by yardz** [comment]
I also have the same problem ...

I checked here, rambdax version 3.1.0 no longer has this issue. @radex Is it easy to upgrade?
