### ISSUE TITLE
Is it possible to integrate PostgreSQL with watermelon db  

### ISSUE THREAD

**Issue by amkayondo** [Nozbe/WatermelonDB#551]
I love the watermelon DB and am planning to use it on some applications but the bad news is that am using Postgres. So what to know if it's possible to integrate the two and how to integrate them.

**Comment by radex** [comment]
How are you running Postgres on frontend side?

**Comment by amkayondo** [comment]
Am using react on frontend 😀

**Comment by radex** [comment]
You can run whatever you want on the backend, if you write a sync adapter for it

**Comment by amkayondo** [comment]
@radex thanks alot 🤗🥳

**Comment by weberth-oliveira** [comment]
I need the example react and postgres. Anyware have this example?

**Comment by radex** [comment]
@gyto you mean sync backend?

**Comment by gyto** [comment]
@radex I assume so. My goal is to connect my existing project that already has PostgreSQL DB. Writing the Sync Backend I think is not complicated as I saw your LokiJs setup. But I still struggle to understand the architecture of the watermelonDB itself. Are you going to introduce the sync backend instructions eventually?

**Comment by radex** [comment]
@gyto I think you're confusing the idea of an `adapter` (the abstraction layer between Watermelon's high-level APIs and a physical local database -- e.g. sqlite, LokiJS) and the idea of a `sync backend`. As for the latter, this document contains the specification required for compatibility with Watermelon's built-in sync engine: https://nozbe.github.io/WatermelonDB/Advanced/Sync.html

**Comment by KrisLau** [comment]
@weberth-oliveira Did you end up finding any postgres and WatermelonDB sync examples?

**Comment by gyto** [comment]
@KrisLau per the conversation above, @radex pointed that it was not implemented yet, however, you can use `adapter` to tweak it to your needs.

**Comment by KrisLau** [comment]
@gyto Thanks! I actually found some examples: 

- https://github.com/FLVieira/sync-api/blob/master/src/app/controllers/SynchronizationController.js
- https://github.com/rodrigosuman/rn-offline-first-app/tree/main/backend/src/services/sync
