### ISSUE TITLE
record.prepareUpdate was called on ${this.table}#${this.id} but wasn't sent to batch() synchronously -- this is bad!

### ISSUE THREAD

**Issue by CochiorasBogdan** [Nozbe/WatermelonDB#553]
Hello, I have a hybrid project react-native & react and on the react side the same code gives the following error `record.prepareUpdate was called on ${this.table}#${this.id} but wasn't sent to batch() synchronously -- this is bad!`. After investigating I think it is caused by doing a prepareUpdate on a record and before commiting the update doing a fetch that will include that record, when the fetch is done this error would be thrown. Why it is not ok to use that record or what is the purpose of the error? Can a more CoreData approach be possible using in memory data and commiting records whenever you want since I see there is a RecordCache class that I think handles some caching?

**Comment by radex** [comment]
> Why it is not ok to use that record or what is the purpose of the error?

This is to maintain consistency. When doing what you're doing, you have a situation where the record is updated in memory, and if you fetch it by ID, it will have the new data, but it's not actually in the database… which means, among other things, that if you query it by some attribute, it won't show up in the query. This leads to a lot of really weird edge cases...

Why can't you prepareUpdate synchronously with a batch call?

**Comment by CochiorasBogdan** [comment]
Because of performance reasons, currently some data that is used do create or update handling for about 3000 database entries and it takes a few seconds, and batch all records after handling all those create/updates. Initially we would batch more often and the difference in performance was too big something like 20 times slower. Also some of this updates are done in background without the user knowing about it and it could delay interface actions if the batching is done too often. One of the issues where this happens is like this:
1) I am authenticated in my application and keep a reference to the authenticated user model in memory somewhere in a class, currently I am offline
2) I become online and in background I update the authenticated user data from server, in this situation I think because I am having a reference to the user in memory this issue would occur, as a workaround the solution I think it would be to re-fetch the data that was kept in memory after update 
This is just a simple use case, I think most of these issues are because I am not using the watermelon sync method since we do real-time data updates through sockets and not a full database update since it would be too much data so the provided sync wasn't really an option. So from what I understand when doing a prepare update the record in memory is not updated only the database record is updated and I need to update the memory record manually or the in memory record gets updated when the batch is commited?

**Comment by radex** [comment]
> So from what I understand when doing a prepare update the record in memory is not updated only the database record is updated and I need to update the memory record manually or the in memory record gets updated when the batch is commited?

To be honest, I don't quite understand what you mean to say, so it's hard for me to answer.

>  Initially we would batch more often and the difference in performance was too big something like 20 times slower. 

Have you checked out the prerelease version of 🍉? We improved the batch time by a lot

**Comment by CochiorasBogdan** [comment]
> To be honest, I don't quite understand what you mean to say, so it's hard for me to answer.
I was wondering how the in-memory version of the model is kept in sync with the database version of the model, if I do a prepareUpdate on a record and I already had a reference to it somewhere in the appllication for example as a static object do I need to refetch it to see the updates from prepareUpdate? If the answer is NO would the in-memory object be updated when the batched record is commited?
Here is a simple example of what I was asking:
- I have model X in a variable
- I do prepareupdate on model X for property Z = 1 without doing a batch apply
- would X have Z == 1 or the previous stored value?
- I do a batch apply on X
- what value would X have for Z now, still the previous value or 1?

> Have you checked out the prerelease version of 🍉? We improved the batch time by a lot
I was waiting on a stable version since I tested 0.15.0 or something older a while ago and had some service worker issues on the React side, I saw a lot of improvements regarding performance, looking forward for the release, I will test it out today. Also really appreciate the time invested in this project it is really awesome!

**Comment by radex** [comment]
> I was wondering how the in-memory version of the model is kept in sync with the database version of the model, if I do a prepareUpdate on a record and I already had a reference to it somewhere in the appllication for example as a static object do I need to refetch it to see the updates from prepareUpdate?

There is only one JavaScript object for a record. The object IS the memory representation of the record. When you fetch from the db, you don't get a "view" of the record, that you can start preparing and then save when ready. All parts of the app that have a reference to the record have the same object.

The reason why it's designed this way is to conserve memory and have allow referential equality.

That's why preparedUpdates must be immediately passed off to the database.

**Comment by bogdancochioras-clarisoft** [comment]
Ok, thank you for the clarification, it makes sense. This can be closed.
