### ISSUE TITLE
Observe changes to a query or model

### ISSUE THREAD

**Issue by davidkell** [Nozbe/WatermelonDB#554]
We have a use case where we want to observe the changes to a model.

For example, if the database table currently has items:
```
X, Y, Z
```

If we insert A and update Z->Z', the new database table has items:
```
X, Y, Z', A
```

We would want to have an observable that only emits the changes, in this case `Z', A`.

Does that make sense? (We had a look at using the syncing mechanism, but I don't think it would work for us.)

**Comment by radex** [comment]
You can use https://nozbe.github.io/WatermelonDB/Components.html#advanced-observing-sorted-lists observeWithColumns

**Comment by davidkell** [comment]
That’s what we have currently, but it provides the full list whenever the underlying dataset changes. For example above, it emits the entire list X, Y, Z’, A, whereas we are looking only for Z’, A.

Does that make sense?

At the moment, we are using rxjs pairwise to diff each successive pair of emits. But this won’t scale well as the size of the table grows.

**Comment by radex** [comment]
> We’d be happy to build something ourselves from internal APIs if you can point us in the right direction.)

Yeah, I'm not convinced right now that this is a common use case, so I'd build directly on top of internal APIs.

See:

- https://github.com/Nozbe/WatermelonDB/blob/master/src/observation/simpleObserver/index.js - this implements `query.observe()` for simple queries (no joins)
- https://github.com/Nozbe/WatermelonDB/blob/master/src/observation/observeQueryWithColumns/index.js - this implements `query.observeWithColumns()`

the most important part is observing `Collection.changes`, which emits `change sets` for added/updated/deleted records:

https://github.com/Nozbe/WatermelonDB/blob/master/src/observation/observeQueryWithColumns/index.js#L111

**Comment by davidkell** [comment]
Thanks, we'll have a look.
