### ISSUE TITLE
Add backward compatible migrations for database schema changes

### ISSUE THREAD

**Issue by ymahnovskyy** [Nozbe/WatermelonDB#56]
First, thank you for such promising tool. I'm considering to use WatermelonDB in react-native app. For me that's will be enough possibility to recreate local database from scratch.  As I see now the easiest way is  to create new db and drop old one. So, as I understand for creating we can just change db name? Is there some possibility to drop old db?

**Comment by radex** [comment]
> As I see now the easiest way is to create new db and drop old one.

Right, currently the only way to migrate is to create a new database (you can make a new SQLiteAdapter with a different database name) and manually move the data.

>  Is there some possibility to drop old db?

Not currently.

* * *

**Real migrations are coming soon**. This is something I'll be working on this week and in the coming weeks. I know that this is very crucial for anyone who wants to use Watermelon in production.

**Comment by radex** [comment]
@ymahnovskyy I'm working on this now. Check out https://github.com/Nozbe/WatermelonDB/pull/62 and let me know if this basic API would satisfy your needs

**Comment by radex** [comment]
thanks @febeling !

**Comment by radex** [comment]
shipped
