### ISSUE TITLE
Strict mode not supported on 0.15.0

### ISSUE THREAD

**Issue by bogdancochioras-clarisoft** [Nozbe/WatermelonDB#560]
Hello, after installing the latest version 0.15.0 I receive at runtime the redscreen on the mobile device (iOS) with the following error:
```
Unhandled JS Exception: Strict mode does not allow function declarations in a lexically nested statement.

no stack
```

**Comment by radex** [comment]
what version of iOS?

are you using terser?

**Comment by bogdancochioras-clarisoft** [comment]
iOS 9.1, iPhone 5 simulator with latest XCode, RN 0.61.4
About Terser I am not sure since the project was created with `react-native init MyAwesomeProject --template typescript` and it is not ejected.

**Comment by radex** [comment]
> iOS 9.1

i think that might be the problem, as I changed babel not to transpire some things that are well supported...

do you have to support iOS this old?

**Comment by bogdancochioras-clarisoft** [comment]
It seems it works on iOS 13.2. Not sure if iOS 9 should be supported, usually tablet users have versions this old. Do you know the minimum supported iOS and Android versions now with the changes?

**Comment by radex** [comment]
> Do you know the minimum supported iOS and Android versions now with the changes?

I don't -- you could check on Xcode simulators

you can also check the section here that talks about Terser:

https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Advanced/Sync.md

this could fix this issue

**Comment by afiller** [comment]
We have the problem as well. It seems to come from iOS 9.x. The JS engine bundled there does not seem to support all code/formats/functionality used in WatermelonDB. My first idea also was to solve it with additional Babel packages, but since I don't have iOS 9 simulators anymore it is quite hard to find out which commands lead to the problem. Maybe the @-syntax in the model classes.

**Comment by radex** [comment]
assuming this has been fixed, closing
