### ISSUE TITLE
0.15 unsafeResetDatabase not finishing?

### ISSUE THREAD

**Issue by ospfranco** [Nozbe/WatermelonDB#564]
I'm testing the 0.15 update and some of our tests got broken:

![Screenshot 2019-11-12 at 14 47 42](https://user-images.githubusercontent.com/1634213/68677057-a2388f80-055b-11ea-8263-1cf433d28604.png)

Very simple test that just mounts a sample lokiJS database and tries to wipe it.

Any suggestions?

**Comment by radex** [comment]
are you using new LokiJSAdapter modes?

**Comment by ospfranco** [comment]
```
import uuidv4 from 'uuid/v4';
import { Database } from '@nozbe/watermelondb';
import LokiJSAdapter from '@nozbe/watermelondb/adapters/lokijs';

const setupTestAdapter = (schema: any, dbName?: string) => {
  // First, create the adapter to the underlying database:
  const adapter = new LokiJSAdapter({
    dbName: dbName ? dbName : uuidv4(),
    schema,
  });

  return adapter;
};

const setupTestDb = (adapter: any, modelClasses: any) => {
  // Then, make a Watermelon database from it!
  const database = new Database({
    adapter,
    modelClasses,
    actionsEnabled: true,
  });

  return database;
};

export { setupTestAdapter, setupTestDb };
```

This is the set up code

**Comment by ospfranco** [comment]
I added some logging into the watermelon code, here is what I found:

```
console.warn node_modules/@nozbe/watermelondb/Database/index.js:203
    clear caches DONE
// All the steps pass except the unsafe database reset call to the worker thread

  console.warn node_modules/@nozbe/watermelondb/adapters/lokijs/WorkerBridge.js:50
    sending UNSAFE_RESET_DATABASE []
// Added an extra unsafe reset database call to see what happens

  console.warn node_modules/@nozbe/watermelondb/adapters/lokijs/WorkerBridge.js:50
 sending UNSAFE_RESET_DATABASE []
// The original unsafe reset database call message is sent

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Initializing IndexedDB  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Database loaded

// The database just then starts loading??

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Empty database, setting up

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Database is now reset

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Initializing IndexedDB

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Database loaded

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Setting up schema

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB][Worker] Database collections set up

  console.warn node_modules/@nozbe/watermelondb/adapters/lokijs/WorkerBridge.js:39
    worker response RESPONSE_SUCCESS
// One worker reponse is returned as success and the resolve method of the callback is triggered, but the callback does not propagate

  console.log node_modules/@nozbe/watermelondb/utils/common/logger/index.js:21
    [DB] All set up in 32ms
```

could it be at all possible that that the creation of the database has somehow become async?

**Comment by radex** [comment]
> could it be at all possible that that the creation of the database has somehow become async?

Database setup has always been asynchronous, except that it's hidden from developers because if you schedule more actions (like unsafeResetDatabase), they will be queued and won't resolve until database is set up.

> // One worker reponse is returned as success and the resolve method of the callback is triggered, but the callback does not propagate

that's weird... check the WorkerBridge class which handles pushing messages between worker and main app.

Also: consider using `useWebWorker: false` option in LokiJS…

**Comment by ospfranco** [comment]
Ah, you are right @radex, the logged RESPONSE_SUCCESS is for the setup call, not for the unsafe reset action, which means the unsafe reset actions are actually never returning

**Comment by radex** [comment]
> also, useWebWorker: false doesn't seem to be doing anything

doh, right -- it will in the browser but there is no change in test environment...

in this case check out the workerMock file -- there are the send/reveive calls there. also lokijs/worker/executor -- you can find the unsafeResetDatabase method there and try to figure out why does it never complete

**Comment by ospfranco** [comment]
Seems this change causes the problem, not sure what would be the solution though:

https://github.com/Nozbe/WatermelonDB/commit/a770eaa6748753e7f76253a6ee639ce7b209708e

Removing the `loki,close` fixes it
