### ISSUE TITLE
observe syncStatus on HOC

### ISSUE THREAD

**Issue by ospfranco** [Nozbe/WatermelonDB#573]
Hey, we are trying to provide our users with more information when elements have been synced and what not, for that I have something similar to this:

Enhancer:
```typescript
const enhance = compose<IInner, IOuter>(
    withObservables(['ticket'], ({ ticket }) => ({
      ticket: ticket.observe(),
      attachments: ticket.attachments.observeWithColumns(['syncStatus'])
    })),
);
```

on my render function:
```typescript
public render() {
    const {
      ...,
      attachments,
    } = this.props;

    const synced = ticket._raw._status === 'synced' && attachments.every((x) => x.syncStatus === 'synced')
```

So, it works fine when adding new attachments to a ticket, the synced value get's correctly calculated to false, however when one of the attachment changes it's sync status to `synced`, the observer is not firing again.

I also tried to do some rxjs piping, on the Ticket entity itself:

```
  // The idea here is valid, but somehow the observer is not being triggered when
  // the syncStatus property on the attachment changes
  // @lazy
  // public attachmentsSynced = this.attachments
  //   .observeWithColumns(['syncStatus'])
  //     map((x: Attachment[]) => x.every(a => a.syncStatus === 'synced')),
  //     distinctUntilChanged(),
  //   );
```

Which now has led me to believe, the syncStatus field is not observable per se, is there anyway to make this work?

**Comment by radex** [comment]
you're not using `observeWithColumns` correctly — it takes names of _database columns_, not JS fields as an argument - so observe `['_status']` and it should work fine.

A good improvement (please contribute!) would be for `observeWithColumns()` to check, in dev mode, if columns passed are valid

**Comment by ospfranco** [comment]
aha, right, my bad then, thx! I will see if I can make time to produce a PR.
