### ISSUE TITLE
Live sync of client db with the server db

### ISSUE THREAD

**Issue by chelovekdrakon** [Nozbe/WatermelonDB#579]
As I understood from the docs -- synchronization should be triggered manually to sync server and client DB.
Is it any way to keep live connection and listen for updates from backend? (like web sockets)

P.S. Do you have any community Chat? In Slack / Telegram or whatever?

**Comment by chelovekdrakon** [comment]
Ideal functionality I would like to have :
1) sync SQLite with server DB using native module (to avoid useless transactions over the bridge)
2) Listen to SQLite data updates from Js

**Comment by radex** [comment]
> Is it any way to keep live connection and listen for updates from backend? (like web sockets)

sure, but you have to build it

> P.S. Do you have any community Chat? In Slack / Telegram or whatever?

no

> sync SQLite with server DB using native module (to avoid useless transactions over the bridge)

syncing goes through javascript at this time

**Comment by chelovekdrakon** [comment]
@radex maybe you can suggest how can I achieve database live synchronization? :)
I'm trying to design the system right now to achieve that :)

**Comment by radex** [comment]
> maybe you can suggest how can I achieve database live synchronization? :)

keep a web socket between client and server and server should ping client when relevant changes are made -- then just trigger watermelon's synchronization procedure.

an advanced version that would require watermelondb integration would be to send actual sync contents in the web socket ping to avoid multiple roundtrips. if you want to do that -- check out src/synchronization and please contribute

**Comment by chelovekdrakon** [comment]
@radex good idea! thank you! Will think about both :)
