### ISSUE TITLE
Cascading deletion with side effect

### ISSUE THREAD

**Issue by saschahofmann** [Nozbe/WatermelonDB#582]
I would like to delete records and their children (and their children) and delete some other records as a side effect. 

I would like to recursively call my `markAsDeleted` function for children and so on. My approach works the first time I am deleting a record but if I try to delete a second record it fails. Here's the code:
```javascript
@action async markAsDeleted(){
  const parent = await this.parent.fetch()
  await parent.update(p => /* some update */)
  await this.collections.get('SideTable').query(Q.where('id', Q.eq(this.id))).destroyAllPermanently()
  const children = this.children.fetch()
  children.forEach(c = > c.markAsDeleted())
  super.markAsDeleted()
}
```

But I am receiving a `Diagnostic error: Model.markAsDeleted() can only be called from inside of an Action.` error. Tried different combinations of awaits and batching the deletes. That brought me to the problem that I need to call batch with prepareMarkAsDeleted where it is hard to do side effects in because of the sync nature. 

It is very likely that I haven't understood something correctly so every hint would be highly appreciated! On that note: Thank you for putting so much time into this 🙏

**Comment by radex** [comment]
@saschahofmann take a look at the implementation of these (experimental):

https://github.com/Nozbe/WatermelonDB/blob/master/src/Model/index.js#L168-L184

 methods. They do what you want, except for the side effect.

And read the docs → Actions to understand Actions :)

**Comment by saschahofmann** [comment]
I actually tried reimplementing the `experimentalMarkAsDeleted` but I didn't manage to call the side effect twice. Do I also need to overwrite the `prepareMarkAsDeleted`?

**Comment by saschahofmann** [comment]
Can I somehow fetch other records because the prepare... Functions are synchronous, aren't they?

**Comment by saschahofmann** [comment]
I finally found a solution. My initial thought was to recursively call the markAsDeleted method as shown above with the side effects. Now I am fetching all children from the tree, perform my side effects on them and then do the batch deletion.
```javascript
@action async markAsDeleted(){
  const parent = await this.parent.fetch()
  await parent.update(p => /* some update */)
  const children = this.children.fetch()
  for (let i = 0; i < children.length; i++) {
      const cldrn = await children[i].children.fetch()
      cldrn.forEach(c => children.push(c))
    }
  await this.collections.get('SideTable').query(Q.where('id', Q.oneOf([this.id, ...children.map(c => c.id)]))).destroyAllPermanently()
  children.forEach(c = > c.prepareMarkAsDeleted())
  await this.collection.database.batch(...children, this.prepareMarkAsDeleted())
}
```
Is that the way to go? Should I put my side effects in the batch action as well? Do you have a rule of thumb when to perform actions in a batch?

**Comment by radex** [comment]
> Is that the way to go? Should I put my side effects in the batch action as well? Do you have a rule of thumb when to perform actions in a batch?

The rule of thumb is: always batch related actions.
