### ISSUE TITLE
Update in markAsDeleted not observed

### ISSUE THREAD

**Issue by saschahofmann** [Nozbe/WatermelonDB#586]
In #582 I tried to run an update from inside a custom `markAsDeleted`. Now it seems to me that this update is not observed inside the changed component.

More specifically: I have a parent component that has multiple children. The parent has a column containing the sort order of its children (a list of children ids). When I delete a child, this sort order needs to be updated. As described in #582 , I am using a batch update to do that. 

Somehow the component observing the parent record is not rerendered when a child is deleted. However, if I force a rerender the changes are reflected. Any ideas what I could be doing wrong?

**Comment by radex** [comment]
on the surface of it, can't see what you're doing wrong. If you post self-contained snippet of code then maybe we can see something in this

**Comment by saschahofmann** [comment]
Ok let's see, on the child I have an action:
```javascript
  @action async markAsDeleted() {
    const children = await this.children.fetch()
    blocks.forEach(b => b.prepareMarkAsDeleted())
    const batch = [...children]
    if (this.parentId) {
    const parent =await this.parent.fetch()
    batch.push(
        parent.prepareUpdate(p => {
          const newSort = parent.sortOrder
          newSort.splice(newSort.indexOf(this.id), 1)
          p.sortOrder = newSort
        })
      )
    }
    await this.collection.database.batch(...batch, this.prepareMarkAsDeleted())
  }
```
Then I am observing the parent like that:

```javascript
export default withObservables(
  ['parentId'],
  ({ parentId, database }) => ({
    parent: database.collections.get('parent).findAndObserve(parentId)
  })
)(_Parent)
```
As mentioned above, markAsDeleted does the update but I need to force a rerender for that to be reflected.

**Comment by saschahofmann** [comment]
ohhhhh, is that because I have the parentId in the to observe list and not the parent record itself?

**Comment by saschahofmann** [comment]
Nevermind, I wasn't using the withObservable-wrapped componend. Sorry.
