### ISSUE TITLE
Model.destroyPermanently() can only be called from inside of an Action when it is called from inside an action

### ISSUE THREAD

**Issue by hannojg** [Nozbe/WatermelonDB#589]
<img width="1046" alt="Screenshot 2019-12-13 at 14 44 53" src="https://user-images.githubusercontent.com/16821682/70804657-4f026880-1db7-11ea-8e89-6e8006342209.png">

Hey, I implemented the pattern on how to delete objects exactly [like your documentation](https://nozbe.github.io/WatermelonDB/CRUD.html#delete-a-record) states it. And usually, it works, but from time to time I receive the error you can see above, which really confuses me a lot because I am calling it from inside an action. 
The code you see above isn't called from any other actions, it's invoked when the user clicks on a delete button.

**Comment by Siemko** [comment]
You are not `await`ing database action. In docs, it is stated, that you should.

**Comment by olegderecha** [comment]
https://watermelondb.dev/docs/Writers

```
await database.write(async () => {
    const updatedEntity = await entity.updateSubmitStatus('deleted');
});
```
