### ISSUE TITLE
Adapter for expo-compatible SQLite

### ISSUE THREAD

**Issue by Jakst** [Nozbe/WatermelonDB#591]
Hey, amazing project you've got here.

I was looking into using this with Expo, and saw that it is not possible currently, as discussed in #310. However, since the architecture with adapters is quite flexible, couldn't the bundled native db driver be replaced with the one provided by [`expo-sqlite`](https://docs.expo.io/versions/latest/sdk/sqlite/) (which actually is the same project as https://github.com/andpor/react-native-sqlite-storage)?

That would make WatermelonDB compatible with expo, while letting you get rid of the native code parts in the project. It could also be added as an additional adapter of course.

Would this be a possible way forward?

**Comment by radex** [comment]
@Jakst I would not recommend it, because Watermelon's native adapter is better optimized, but indeed I see no reason why this wouldn't work. In fact, it should be fairly easy to write an `expo-sqlite` adapter for Watermelon and I would encourage you to prepare a PR with it, if that's important to you and you're not willing to eject from expo

**Comment by Jakst** [comment]
Sometimes convenience > performance 🙂 I'll experiment locally and see if I can get something working in the next couple of weeks. If I do I'll put in some extra effort to make a PR.

But also, could the performance optimizations you have in 🍉 be built into expo-sqlit3 as well? Or are they too specific to the 🍉 use case?

**Comment by radex** [comment]
@Jakst They're mostly specific to 🍉…

**Comment by almakary** [comment]
@Jakst Did it work on your end locally?

**Comment by Jakst** [comment]
@almakary I managed to get it roughly working, but it was more work than I thought. 

I've got nothing to share with you though, because my computer and I had already scrapped the idea of getting to something production ready.

**Comment by almakary** [comment]
@Jakst Thanks for letting me know. We were thinking about giving it a try but it sounds it's not gonna be a good idea unless we eject.
