### ISSUE TITLE
Migrate to IncrementalIndexedDB

### ISSUE THREAD

**Issue by saschahofmann** [Nozbe/WatermelonDB#594]
I am playing around with the `experimentalUseIncrementalIndexedDB: true` flag for the LokiJSAdapter and first thought that this was flushing my local storage database but interestingly if I disable the flag my data reappears. So I assume it creates a second database. Is there a way for me to migrate the default IndexedDB to the Incremental one?

**Comment by radex** [comment]
@saschahofmann Indeed, it creates a new database with a different schema. You're welcome to contribute migration code. more details here: https://github.com/techfort/LokiJS/pull/808
