### ISSUE TITLE
Online docs

### ISSUE THREAD

**Issue by radex** [Nozbe/WatermelonDB#6]
Currently, the whole documentation is available just on GitHub in Markdown form.

It would be nice to have a website (like React Native, Jest, React Navigation, etc.) with those docs, and API  reference automatically build from source.

It would be great if someone wanted to help out with this!

**Comment by mobily** [comment]
I think we should use https://docusaurus.io

**Comment by radex** [comment]
ooh! That's the thing!

**Comment by xarrijorge** [comment]
Have you decided to use docusaurus or still go with the static site?

**Comment by radex** [comment]
No decision was made. Doesn't docusaurus generate static sites?

**Comment by xarrijorge** [comment]
I'm not really familiar with it. I think it is a static site generator (like Gatsby). We could use Gatsby as another alt.

**Comment by jpbretanha** [comment]
You also could use to [docz](https://www.docz.site)

**Comment by isurusiri** [comment]
Hi guys, Nice work 👏 

I created a sample using my fork of WatermelonDB in [GitBook](https://gitbook.io). If that meets the requirements maybe we could consider it as an option.

[Check it out >>](https://isurus.gitbook.io/watermelondb/)

**Comment by radex** [comment]
Hey @isurusiri, good stuff — is there a way to (easily) add API docs from the JS source?

**Comment by isurusiri** [comment]
I think [documentationjs](http://documentation.js.org/) is what you are looking for, if I'm correct. 

Also if docs are in MD format, GitBook can simply import the content and sync all future updates.

**Comment by radex** [comment]
Hmm @isurusiri… if I understand correctly, this requires documentation comments specifying params, returns, etc… This seems like a waste of developer time, given that we use Flow and so a Babel-based script should be able to just extract all available methods, type information about those methods, a comment above, and spit out HTML docs.

Do you know of a tool that could do something like that? IT would be great to have API docs, but it's difficult for us to justify spending a lot of extra time maintaining it if the code is already largely self-documented through Flow

**Comment by isurusiri** [comment]
Yeah, got it. I'm not aware of such a tool but I'll look into it.

**Comment by radex** [comment]
thank you!
