### ISSUE TITLE
[Question] [TS] Collections query with withObservables HOC

### ISSUE THREAD

**Issue by JensonMiralles** [Nozbe/WatermelonDB#604]
Hi guys! I have a question:

This is a Typescript question, the `database.collections.get('table').query()` has `Query<Model>` type, but the `withObservables` HOC using the `ObservableifyProps` helper requires `Observable<Table[]>` how to a convert the result of `database.collections.get('table').query()` to observable? 🧐

PS: the `withObservables` works perfectly, but the typescript is giving me this error:
```
Type 'Query<Model>' is missing the following properties from type 'Observable<Table[]>': _isScalar, source, operator, lift, and 5 more
```

cheers! 🎉

**Comment by radex** [comment]
`...query().observe()` will return the actual Observable.

But I think the better route if for you to contribute an improvement to `withObservables` so that the shorthand syntax type checks when using TypeScript

**Comment by JensonMiralles** [comment]
> `...query().observe()` will return the actual Observable.
> 
> But I think the better route if for you to contribute an improvement to `withObservables` so that the shorthand syntax type checks when using TypeScript

It worked, thank you! I'm just a beginner on TypeScript but I'll see what I can do!

I'll close this issue now, thanks again!
