### ISSUE TITLE
 DataCloneError: The object can not be cloned.

### ISSUE THREAD

**Issue by waqas19921** [Nozbe/WatermelonDB#606]
I have used this awesome library in react.

Getting this error `Unhandled Promise Rejection: DataCloneError: The object can not be cloned.`
When i am using this library in **Safari** in an **iframe**.

Below are the logs from the console.
```
[DB][Worker] Initializing IndexedDB


[Error] Diagnostic error: SecurityError: IDBFactory.open() called in an invalid security context
diagnosticError — index.js:20
logError — index.js:18
$Try_1_Catch — lokiWorker.js:88
promiseReactionJob

	error (08ec40b9a057ce8887b7.worker.js:2914)
	logError (08ec40b9a057ce8887b7.worker.js:2869)
	$Try_1_Catch (08ec40b9a057ce8887b7.worker.js:2241)
	promiseReactionJob

[Error] Unhandled Promise Rejection: DataCloneError: The object can not be cloned.
	postMessage (08ec40b9a057ce8887b7.worker.js:2213)
	(anonymous function) (08ec40b9a057ce8887b7.worker.js:2213)
	(anonymous function) (08ec40b9a057ce8887b7.worker.js:2348)
	$Try_1_Catch (08ec40b9a057ce8887b7.worker.js:2242)
	promiseReactionJob
```

<img width="592" alt="Screenshot 2020-01-16 at 5 23 04 PM" src="https://user-images.githubusercontent.com/17469425/72524969-e3635d80-3884-11ea-826d-184b13e11121.png">

Error is on this line 
```
_this.workerContext.postMessage({
          type: type,
          payload: payload
        });
```
Safari is not able to convert the `payload`
**Any ideas how to fix this.**
Thanks in advance.

**Comment by radex** [comment]
@waqas19921 Read the error. IndexedDB is not supported inside frames: https://stackoverflow.com/a/17753024

**Comment by waqas19921** [comment]
@radex Its working on every other browser. And this stackoverflow thread is 6 years old.

**Comment by radex** [comment]
assuming this has been fixed, closing

**Comment by tony** [comment]
I got this when I had a URL in my CSS

double check your stylesheets:

```css
// GitHub icon via https://github.com/facebook/docusaurus/blob/5872bbc735118071a29a435457b247d7fa21a906/website/src/css/custom.css
// License MIT
.header-github-link:hover {
  opacity: 0.6;
}
```

The top comment with the URL messed up the minification.
