### ISSUE TITLE
GIS Queries

### ISSUE THREAD

**Issue by cranesandcaff** [Nozbe/WatermelonDB#607]
I'm working on an application involving heavy amounts of GeoJSON and GIS data.

I'd be interested to know if it's possible to add spatialite and GIS focused querying to WatermelonDB.

I'd of course handle the implementation, interested in where I would start and if Nozbe thinks it's even possible.

https://github.com/Ryandev/spatialite-iOS

Suggests it's possible to add extend Sqlite with Spatialite but I know there would be additional work involved.

**Comment by radex** [comment]
@cranesandcaff I know nothing about geoJSON/GIS, so I don't know where to start with this.

Seems like there are `sqlite` extensions for handling those types of queries. So it seems reasonable for me that you would add this extension to your app, and use raw SQL queries in WatermelonDB.

It's too niche to bundle directly with WatermelonDB, but if it's necessary for this `spatialite` library to have access to raw `sqlite3` object, you could contribute an API to DatabaseAdapter to allow access to that object in your code

**Comment by cranesandcaff** [comment]
That's what I was thinking, we could create our own adapter building on the DatabaseAdapter. Providing access to the raw sqlite3 object would probably make it really easy. 

I think that's a good starting point. I'll look into that. Thank you, can I leave open for more questions and conversation? I'd like make a different library closely related to/building on watermelon to add the queries and column type.

**Comment by radex** [comment]
@cranesandcaff did you get this done in the end? ;)

**Comment by dpyeates** [comment]
Would love to hear where you got with this? I have a database containing thousands of objects with lat/lon locations. I want to be able to do a distance search from my current location. i.e. "give me all objects within 100 miles of my location ordered by distance"?
