### ISSUE TITLE
Conflict with mauron85 / react-native-background-geolocation

### ISSUE THREAD

**Issue by lander854** [Nozbe/WatermelonDB#610]
ERROR LOG

ld: warning: directory not found for option '-L/Users/aislanlander/projetos/nectar-fields-sales/ios/Nectar Field Sales'
duplicate symbol '_OBJC_IVAR_$_FMResultSet._query' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMResultSet.o)
duplicate symbol '_OBJC_IVAR_$_FMResultSet._statement' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMResultSet.o)
duplicate symbol '_OBJC_CLASS_$_FMResultSet' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMResultSet.o)
duplicate symbol '_OBJC_METACLASS_$_FMResultSet' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMResultSet.o)
duplicate symbol '_OBJC_IVAR_$_FMResultSet._columnNameToIndexMap' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMResultSet.o)
duplicate symbol '_OBJC_IVAR_$_FMResultSet._parentDB' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMResultSet.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._openFlags' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._databaseOutPool' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._databaseInPool' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_CLASS_$_FMDatabasePool' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_METACLASS_$_FMDatabasePool' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._path' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._lockQueue' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._delegate' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._maximumNumberOfDatabasesToCreate' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabasePool._vfsName' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabasePool.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabaseQueue._openFlags' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabaseQueue.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabaseQueue._path' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabaseQueue.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabaseQueue._queue' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabaseQueue.o)
duplicate symbol '_OBJC_CLASS_$_FMDatabaseQueue' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabaseQueue.o)
duplicate symbol '_OBJC_METACLASS_$_FMDatabaseQueue' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabaseQueue.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabaseQueue._vfsName' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabaseQueue.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabaseQueue._db' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabaseQueue.o)
duplicate symbol '_OBJC_IVAR_$_FMStatement._query' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._checkedOut' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMStatement._useCount' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMStatement._statement' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._isExecutingStatement' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_CLASS_$_FMStatement' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_METACLASS_$_FMStatement' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._dateFormat' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._shouldCacheStatements' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._cachedStatements' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._openResultSets' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._logsErrors' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._crashOnErrors' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._openFunctions' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._traceExecution' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_FMDBBlockSQLiteCallBackFunction' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._maxBusyRetryTimeInterval' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_FMDBExecuteBulkSQLCallback' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._databasePath' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_CLASS_$_FMDatabase' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_METACLASS_$_FMDatabase' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMStatement._inUse' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._startBusyRetryTime' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
duplicate symbol '_OBJC_IVAR_$_FMDatabase._db' in:
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/@mauron85_react-native-background-geolocation/lib@mauron85_react-native-background-geolocation.a(FMDB.o)
    /Users/aislanlander/Library/Developer/Xcode/DerivedData/nectarApp2-hacinsxfzidyctcyojunblerlvav/Build/Products/Debug-iphonesimulator/libWatermelonDB.a(FMDatabase.o)
ld: 47 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by lander854** [comment]
Seems that the two packages use some functions in common, making ios build process fail

**Comment by radex** [comment]
just remove the FMDB folder from build in one of the packages and you'll be good

**Comment by rafwell** [comment]
I've the same problem. @radex can you explain how can I do this? I'm not an iOS dev.
Thanks.
