### ISSUE TITLE
Database records batch delete

### ISSUE THREAD

**Issue by markorusic** [Nozbe/WatermelonDB#611]
Hi, I've noticed an issue where it's not possible to delete multiple records at the same time. 

For example, the follwing code deletes records one by one:
```js
db.collections.get('comments').query().destroyAllPermanently()
```

Is it possible to delete multiple records at the same time?

**Comment by Alek997** [comment]
Same problem

**Comment by markorusic** [comment]
I dug up the solution:

```js
const comments = await db.collections
  .get('comments')
  .query()
  .fetch()

const deleted = comments.map(comment => comment.prepareDestroyPermanently())

db.batch(...deleted)
```

**Comment by NikolaMasulovic** [comment]
Exellent job!

**Comment by radex** [comment]
@NikolaMasulovic  @markorusic Check out `record.experimentalDestroyPermanently()` -- this will delete record & all its children

**Comment by skam22** [comment]
> I dug up the solution:
> 
> ```js
> const comments = await db.collections
>   .get('comments')
>   .query()
>   .fetch()
> 
> const deleted = comments.map(comment => comment.prepareDestroyPermanently())
> 
> db.batch(...deleted)
> ```

for performance issues (with a large array of items to delete), you should be passing a single array instead of spreading it.

the corrected code should be:

```javascript
const comments = await db.collections
  .get('comments')
  .query()
  .fetch()

const deleted = comments.map(comment => comment.prepareDestroyPermanently())

db.batch(deleted)
```

**Comment by Renato1478** [comment]
This is still not usable for a list of, lets say... 50k items... Takes too long.

**Comment by heidji** [comment]
Neither of these pass the Typescript check. I assume this is a typing error, just FYI

> > I dug up the solution:
> > const comments = await db.collections
> >   .get('comments')
> >   .query()
> >   .fetch()
> > 
> > const deleted = comments.map(comment => comment.prepareDestroyPermanently())
> > 
> > db.batch(...deleted)
> 
> for performance issues (with a large array of items to delete), you should be passing a single array instead of spreading it.
> 
> the corrected code should be:
> 
> const comments = await db.collections
>   .get('comments')
>   .query()
>   .fetch()
> 
> const deleted = comments.map(comment => comment.prepareDestroyPermanently())
> 
> db.batch(deleted)
