### ISSUE TITLE
Watermelon limitations

### ISSUE THREAD

**Issue by lander854** [Nozbe/WatermelonDB#614]
Hello, I would like to know the limitations, size, records, etc if any in this database, anyone knows?

**Comment by radex** [comment]
there are no hard limits. I'm running an app with ~70000 records / 50MB database and it works just fine on decent devices.

Biggest limitation at the moment is that adding tens of thousands of records at the same time is quite slow, but I'm working on improving that (and you can help contribute to this cause!)

**Comment by INBINCOMOBI** [comment]
what is the maximum size of an attachment in a blob?
