### ISSUE TITLE
Warn about missing collections

### ISSUE THREAD

**Issue by esbenp** [Nozbe/WatermelonDB#616]
If you forgot to add a model to `Database` you will get a cryptic typeerror ala

![Screenshot 2020-01-31 at 15 07 56](https://user-images.githubusercontent.com/934819/73545551-d2494d80-443b-11ea-9807-424f5d36843c.png)

I would suggest some warning in `getAllRecordsToApply` but I am uncertain how to add something like that when using `rambdax`??

```
const getAllRecordsToApply = (
  db: Database,
  remoteChanges: SyncDatabaseChangeSet,
): AllRecordsToApply =>
  piped(
    remoteChanges,
    map((changes, tableName: TableName<any>) => {
      const collection = db.collections.get((tableName: any))

      invariant(collection, `You are trying to sync a collection named ${tableName}, but currently this collection does not exist.` + 
        `Have you remembered to add it to your Database constructor\'s modelClasses property?`)
      
      return recordsToApplyRemoteChangesTo(collection, changes),
    },
    promiseAllObject,
  )
```

something like this?

**Comment by radex** [comment]
> something like this?

yeah! though maybe return `Promise.reject` instead - the error will propagate better
