### ISSUE TITLE
Create two record related to each other batch

### ISSUE THREAD

**Issue by lander854** [Nozbe/WatermelonDB#619]
Hello, thanks for this DB, its awesome!
I'm having a little dificulty creating two records, I have a contact table that can have several adresses ( another table ) and i'm creating it like this:
```

 database.action(async action => {
    let newData = [];
    await newContato.map(data => newData.push(prepareContato(data)));
 // returns a preparecreate function
    console.log(newContato);
    console.log(newData);
    await database.batch(...newData).then(async () => {
      const allContatos = await contatosCollection.query().fetch();
    });
  });

```
and in contact table i've created this 

```
 static table = 'contatos';
  static associations = {
    enderecos: {type: 'has_many', foreignKey: 'id_cliente'},
  };
  @action async addAdress(newEndereco) 

```
where can I call the action so that it creates the batched contacts with respective adress

my api returns an contacts objects inside an array with 20 contacts each, inside each contact there is an adress array

**Comment by torkcavera** [comment]
I have a similar problem

**Comment by zecakeh** [comment]
You can create your adresses with only the contact id, so you can create them at the same time:

```javascript
prepareEnderecos (data) {
  const enderecos = [];
  for (endereco of data.cliente.enderecos) {
    // This would be equivalent to addAddress
    const newEndereco = database.collections.get('enderecos').prepareCreate(endereco => {
      // In the model, cliente is the property corresponding to id_cliente field in the table
      // Relations should take care of everything from there
      endereco.cliente.id = data.cliente.id;
      // set other properties…
    )}
    enderecos.push(newEndereco);
  }
  return enderecos;
}
```

And you add them to the batch:

```javascript
newContato.map(data => {
  newData.push(prepareContato(data));
  const enderecos = prepareEnderecos(data);
  // This is spread syntax, you can use array.concat() instead
  newData = [...newData, ...enderecos];
});
```

Beware also [in the doc](https://nozbe.github.io/WatermelonDB/Schema.html#naming-conventions) it says to use `cliente_id` for the table schema and not `id_cliente` so relations might not work properly if you keep that name.

**Comment by radex** [comment]
@lander854 did this fix your problem?
