### ISSUE TITLE
Complex and dynamic queries

### ISSUE THREAD

**Issue by romulomachado** [Nozbe/WatermelonDB#627]
Hello, thanks for this great project!

Is there a way to create dynamic queries?

I have a `Video` model, with a many-to-many relationship to a `Tag` model. 

I wanna combine some filters on my query and failing to see how I'd do that.

```js
const videos = await DB.collections
    .get('videos')
    .query(
      // dynamically create the Q's here
      // i.e. 
      // Q.where('duration', Q.lte(300)),
      // Q.on('video_tags', 'tag_id', '133'),
      // Q.on('video_tags', 'tag_id', '82'),
    )
    .fetch();
```

Sorry if I'm missing a big thing here.

**Comment by radex** [comment]
i don't understand what the question/problem is

**Comment by romulomachado** [comment]
I'm trying to pass multiple `Q`s to `.query()`, but I'm not sure how to.

Something like:

```javascript
let userQuery = [Q.where('duration', Q.lte(300)), Q.on('video_tags', 'tag_id', '133'), ...];

...
const videos = await DB.collections
    .get('videos')
    .query(userQuery)
    .fetch();
```

The problem is that `.query()` doesn't expect an array.

**Comment by radex** [comment]
`.query(...userQuery)`

**Comment by romulomachado** [comment]
Sorry if that was too dumb of me. :grimacing: 

Thank you!
