### ISSUE TITLE
Deep fetch

### ISSUE THREAD

**Issue by punksta** [Nozbe/WatermelonDB#628]
is there a way how to deep fetch table and all it's relations using one query?

lets say I have 
```
class Post  extends Model {
 @filed("text") text
 @relation('users', 'author_id') author
}
```

I want to fetch array of posts with users using one sql query.

```
const postArray = await postCollection.querry().fetch()
console.log(postArray)
```
>

```
[{text: "hello" author: {user_id: "1", name: "admin" } }]
``` 

I know I can `observe` nested tables, but I assume it makes additional  request per each `observe`?

**Comment by radex** [comment]
```
await Promise.all(posts.map(post => post.author.fetch()))
```

**Comment by punksta** [comment]
@radex will it by compiled into one sql query?

**Comment by radex** [comment]
no. but you can get it done in two queries. one to fetch posts, and second to find users that have a post where they're the author
