### ISSUE TITLE
TypeScript: This expression is not callable.     Not all constituents of type 'Object | RawDecorator' are callable.

### ISSUE THREAD

**Issue by shiundu** [Nozbe/WatermelonDB#629]
This expression is not callable.   
Not all constituents of type 'Object | RawDecorator' are callable.

`declare module '@nozbe/watermelondb/utils/common/makeDecorator' {`
`import { ReplaceReturn } from '@nozbe/watermelondb/utils/common'`

  `export type Descriptor = Object`

Someone was working on types, has this been fixed?. Is there anything I can do to help.

**Comment by radex** [comment]
@shiundu have you checked if https://github.com/Nozbe/WatermelonDB/pull/613 fixes this issue?

**Comment by shiundu** [comment]
@radex Not really,

This https://github.com/Nozbe/WatermelonDB/issues/559#issuecomment-551880181 seems to fix it, but I thought it had already been merged. 

"@nozbe/watermelondb": "^0.15.0",

![Screenshot 2020-02-26 at 15 01 58](https://user-images.githubusercontent.com/3198610/75351848-139d1380-58a9-11ea-92de-aab6b5d7f79b.png)

**Comment by WeslleyNasRocha** [comment]
I can confirm, the fix it's not working, i used the same workaround from #559

`node_modules/@nozbe/watermelondb/utils/common/makeDecorator/index.d.ts`

```typescript
export type Descriptor = any;
```

**Comment by AndreasA** [comment]
Same here.  Still the same error.

**Comment by azizhk** [comment]
Hi @radex can you send out a release on npm.

**Comment by AndreasA** [comment]
Hi again, I am not sure if this should be the same issue but it is also TypeScript / types related.


For the new `import { setGenerator } from '@nozbe/watermelondb/utils/common/randomId';`

the typedefinition file is missing.

**Comment by azizhk** [comment]
@AndreasA Yeah the Typescript definitions are community maintained. You can create a PR to get them added.
Something like this should do the trick.

```ts
declare module '@nozbe/watermelondb/utils/common/randomId' {
  export type Generator = () => string;
  export function setGenerator(newGenenerator: Generator): void
}
```

**Comment by AndreasA** [comment]
Yeah, I already added something like this locally and it works but would be nice if it is in the main project. Might add a PR later, if I find a bit of free time

**Comment by AndreasA** [comment]
Something else with the `Descriptor = any` the `readonly` decorators still cannot be called without adding `()` at the end.

**Comment by AndreasA** [comment]
> @AndreasA Yeah the Typescript definitions are community maintained. You can create a PR to get them added.
> Something like this should do the trick.
> 
> ```ts
> declare module '@nozbe/watermelondb/utils/common/randomId' {
>   export type Generator = () => string;
>   export function setGenerator(newGenenerator: Generator): void
> }
> ```
Done:
https://github.com/Nozbe/WatermelonDB/pull/648

**Comment by neolitec** [comment]
Same issue for `@field`:

![image](https://user-images.githubusercontent.com/433017/81849150-1f04f000-9524-11ea-9a23-4c0e300ed8f0.png)

**Comment by azizhk** [comment]
@neolitec What version do you use? 0.16.0?

**Comment by neolitec** [comment]
@azizhk yes, 0.16.0.
Hum I think you'll talk about 0.16.1-0+ that seems to be fixed beta versions :)
Thanks :)
