### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `fs` 

### ISSUE THREAD

**Issue by shiundu** [Nozbe/WatermelonDB#631]
error: bundling failed: Error: Unable to resolve module `fs` from `node_modules/@nozbe/watermelondb/node_modules/lokijs/src/lokijs.js`: fs could not be found within the project.

 "react-native": "^0.61.5",
 "@nozbe/watermelondb": "^0.16.0-9",
  "@nozbe/with-observables": "^1.0.6-0",

![Screenshot 2020-02-26 at 23 07 40](https://user-images.githubusercontent.com/3198610/75392713-ea9e7200-58ec-11ea-9abb-6bf94da8eb9a.png)

**Comment by azizhk** [comment]
As far I understand LokiJS does not support React Native. https://github.com/techfort/LokiJS/issues/716

You need to use the `SQLiteAdapter`.
https://nozbe.github.io/WatermelonDB/Installation.html?highlight=SQLiteAdapter#set-up-database
