### ISSUE TITLE
React native connected component enzyme Jest test not rendered correctly

### ISSUE THREAD

**Issue by muhamad-rizki** [Nozbe/WatermelonDB#634]
hello, I'm trying to test my connected container with hoc withObservables(), but when I do unit test using enzyme it's not rendered correctly. I used this for unit testing:
```
    const component = shallow(<ProfileContainer route={{ params: { user: { photo: '' } } }} store={store} />);
    expect(component.dive().dive()).toMatchSnapshot();
```

I got a snapshot with empty string. Where ProfileContainer is like this:
```
const enhance = withObservables(['randomizer'], ({ route: { params: { user } } }) => ({
  user: WaterMelonDB.userDb().findAndObserve(user.id),
  licenses: WaterMelonDB.licenseDb().query(Q.where('user_id', user.id)).observe(),
}));

export default enhance(ProfileContainer);
```

it's rendered correctly if I run it on real device. anyone can help? thanks in advance

**Comment by radex** [comment]
remember that withObservables is asynchronous - first it renders null, and only then it renders the actual content. so your test setup must support that

**Comment by muhamad-rizki** [comment]
> remember that withObservables is asynchronous - first it renders null, and only then it renders the actual content. so your test setup must support that

so how I do setup my test so I can render the component properly? can you give me some example?

**Comment by azizhk** [comment]
Can you try `jest.runAllTimers();`

```js
const component = shallow(<ProfileContainer route={{ params: { user: { photo: '' } } }} store={store} />);
jest.runAllTimers();
expect(component.dive().dive()).toMatchSnapshot();
```

https://jestjs.io/docs/en/timer-mocks#run-all-timers
