### ISSUE TITLE
undefined is not an object (evaluating 'this.schema.version')

### ISSUE THREAD

**Issue by K4stor** [Nozbe/WatermelonDB#635]
Hello,

I am trying to get a minimal react native app with watermelon up and running.
You can check my code here https://github.com/K4stor/AwesomeNativeApe

I get the message 

```
console.error: "[DB] Uh-oh. Database failed to load, we're in big trouble", TypeError: undefined is not an object (evaluating 'this.schema.version')

_construct
    construct.js:30:26
Wrapper
    wrapNativeSuper.js:26:23
SyntheticError
    index.bundle?platform=ios&dev=true&minify=false:28714:111
reactConsoleErrorHandler
    ExceptionsManager.js:135:52
error
    index.js:33:53
$Try_1_Catch
    common.js:66:29
tryCallOne
    core.js:37:14
setImmediate$argument_0
    core.js:123:25
callImmediates
    [native code]:0
flushedQueue
    [native code]:0
```

Any Idea what to do ?

**Comment by radex** [comment]
your schema export is wrong

**Comment by K4stor** [comment]
OK, what must it look like ?

**Comment by FabianEscarate** [comment]
hi, i have the same problem..  just change de export part.

export const mySchema [Remove]
export default mySchema [OK]

or when you called, you should be do this.

import { mySchema } from '[Location]'

**Comment by finom** [comment]
I think this needs to be fixed in documentation.

**Comment by radex** [comment]
@finom please send a quick PR correcting the documentation - look at docs-master/ folder

**Comment by blackgeneration** [comment]
😆😆😆 My sins were that there was a mismatch in my model fields definition and schema definition

**It was like this in the model definition:**





`@field('medicine') medicine`

**And my schema was like this**

`{ name: 'my_medicine', type: 'string' },`

**To correct this:** I changed `@field('medicine') medicine` to `@field('my_medicine') medicine`

And my sins were forgiven.....🙏🏾🙏🏾🙏🏾

It started working...

**Comment by rvwehk** [comment]
@blackgeneration thanks bro
