### ISSUE TITLE
Handling dynamic forms

### ISSUE THREAD

**Issue by Foosballfan** [Nozbe/WatermelonDB#638]
Hi,

I'm looking into creating an offline first app and WatermelonDB looks like a good fit.

In my application there are server side defined forms which doesn't play nicely with the concept of defining schemas before creating a model.

Does anyone have smart strategies to handle this scenario? e.g. dynamic schema generation or migrations?

I see there is an `@json` field type which would be suitable. Will there be a noticeable input lag while a user is filling in a form that updates an `@json` in the background?

Thanks

**Comment by radex** [comment]
@Foosballfan Hey, did you find a solution to this problem in the end?

**Comment by Foosballfan** [comment]
Hi @radex. We decided to handle the state of the form within a json form schema renderer and only push to watermelon on save. It meant losing the ability to save progress in case of app closures but was simple enough to justify itself.

**Comment by radex** [comment]
cool, thanks for chipping in.. going to close it now, unless someone finds this issue and wants to reopen

what I'd recommend is throttling user input and storing it as the user types anyway - works for us.

**Comment by Foosballfan** [comment]
@radex thanks for the info on throttling.

Do you have an answer to the first part of the question? To do with dynamic schema generation

**Comment by Foosballfan** [comment]
Great, thanks for your time
