### ISSUE TITLE
Not allowed to change record outside of create/update()

### ISSUE THREAD

**Issue by Mohammad-Adam** [Nozbe/WatermelonDB#639]
**PLZ help; thank you;**
`export class LastScrollPosition extends Model {
    static table = 'last_scroll_position';

    @field('collection') collection;
    @field('last_position') lastPosition;

    static async addEntry(collection, lastPosition) {
        return await zWMDatabase.action(async () => {
            return await zWMDatabase.collections.get(this.table).create(lastScrollPosition => {
                lastScrollPosition.collection = collection;
                lastScrollPosition.lastPosition = lastPosition;
            });
        });
    }
}`

i get: 
### Diagnostic error: Not allowed to change record outside of create/update()

**Comment by michaelfsarkis** [comment]
You need to add the decorator @action to the addEntry method. Something like:
```
@action async addEntry(collection, lastPosition) {
//The rest of the method's logic
}

```

**Comment by EngDjango** [comment]
> Not sure, but I think you need to add the decorator @action to the addEntry method?
> Something like:
> 
> ```
> @action async addEntry(collection, lastPosition) {
> //The rest of the method's logic
> }
> ```

already did that, but didn't work also

**Comment by jdnichollsc** [comment]
@EngDjango did you find any workaround? I'm getting the same issue with this code:
```
const addMessage = async (message: string) => {
  await DatabaseService.action(async () => {
    const newMessage = new Message()
    newMessage.message = message
    newMessage.messageType = 'TEXT'
    newMessage.timestamp = new Date().getTime().toString()
    newMessage.roomId = '123'
    newMessage.userId = '111'
    await messagesCollection.create((record) => {
      record._raw.id = new Date().toISOString()
      for (const key in newMessage) {
        if (newMessage.hasOwnProperty(key)) {
          ;(record as any)[key] = (newMessage as any)[key]
        }
      }
    })
  })
}
```

Thanks in advance!

**Comment by rutsatz** [comment]
Did you have added a new field? If so, have you changed the schema version? Because it doesn't create new fields if you don't use migrations. I went through something similar and changed the version of the schema for it to recreate the database, and it seems that it solved it.
