### ISSUE TITLE
Error: Unable to resolve module `./makeDecorator` from `node_modules/@nozbe/watermelondb/utils/common/index.js`: 

### ISSUE THREAD

**Issue by Chethan-Saliyan** [Nozbe/WatermelonDB#640]
HI,
I am getting error while generating android release build

"Error: Unable to resolve module `./makeDecorator` from `node_modules/@nozbe/watermelondb/utils/common/index.js`: "

its working fine in debug build. 

 "@nozbe/watermelondb": "^0.15.0",
   "@nozbe/with-observables": "^1.0.5",
  "react": "16.9.0",
    "react-native": "0.61.5",

Thanks in advance

**Comment by radex** [comment]
assuming the problem's been fixed, closing

**Comment by Shaswati** [comment]
I am still facing this problem
