### ISSUE TITLE
TypeError: Cannot read property 'table' of undefined 

### ISSUE THREAD

**Issue by netdesignr** [Nozbe/WatermelonDB#642]
Hi everyone!

I'm trying to install 🍉 DB to my mobile app and got into some issues. I did go through all the steps in Docs and despite the fact I run into some other issues I manage to fix them until I run into error screen: TypeError: Cannot read property 'table' of undefined 

I'm using:
"react": "16.9.0",
"react-native": "0.61.5", 
"@nozbe/watermelondb": "^0.16.0",
"@nozbe/with-observables": "^1.0.5

index.js
`import {Database} from '@nozbe/watermelondb';
import SQLiteAdapter from '@nozbe/watermelondb/adapters/sqlite';

import {AppRegistry} from 'react-native';

import App from './App';
import {name as appName} from './app.json';

import {mySchema} from './model/Schema';
import {User} from './model/Users';

export const adapter = new SQLiteAdapter({
  dbName: 'myDB',
  schema: mySchema,
});
export const database = new Database({
  adapter,
  modelClasses: [User],
  actionsEnabled: true,
});

AppRegistry.registerComponent(appName, () => App);`

Users.js
`import {Model} from '@nozbe/watermelondb';

export default class User extends Model {
  static table = 'users';
}
`
In one of the components I have imported `import {database} from '../../index.js';`
and console.log(database) // If I delete the console_log I will still see the error screen.

<img width="391" alt="Screenshot 2020-03-07 at 13 13 40" src="https://user-images.githubusercontent.com/5245264/76144298-b3f7f280-6076-11ea-92ee-1728fb7d396a.png">

Anyone stumbled uppon this before?

Thank you!

**Comment by netdesignr** [comment]
Got it fixed!
This is just because I've imported my Model as a named export rather than default export which was obviously causing table to be undefined. A good reason to listen to the body when is time to sleep.

**Comment by iamclaytonray** [comment]
Your solution doesn't fix this issue for me. Looks like it is a named export. Did you change anything else?
