### ISSUE TITLE
How does watermelonDB handle CRDT conflicts with the database backend?

### ISSUE THREAD

**Issue by simkimsia** [Nozbe/WatermelonDB#643]
Hi there, 

Does watermelonDB handle the CRDT conflicts with the database backend?

Or i need to write my own or use something else to handle conflicts?

**Comment by radex** [comment]
Watermelon has no specific knowledge of CRDTs. Have you read the Sync article in docs? Tell me more about your use case, then I may have a more useful answer for you

**Comment by kirolos997** [comment]
Hi there, 

Could you tell me how watermelonDB handles the situation during sync where an object has been deleted from the backend database while the application was offline and made a change on the deleted object before being online again?

> Watermelon has no specific knowledge of CRDTs. Have you read the Sync article in docs? Tell me more about your use case, then I may have a more useful answer for you
