### ISSUE TITLE
error: bundling failed: index.js: [BABEL] path_project/index.js: 'decoratorsBeforeExport' can't be used with legacy decorators.

### ISSUE THREAD

**Issue by auliakbarh** [Nozbe/WatermelonDB#645]
Hi, i have an issue while run react native on android after following the installation guide (https://nozbe.github.io/WatermelonDB/Installation.html)

here is my **babel.config.js** configuration:

module.exports = {
  presets: ['module:metro-react-native-babel-preset'],
  plugins: [
    [
      '@babel/plugin-proposal-decorators',
      {legacy: true, decoratorsBeforeExport: true},
    ],
    ['@babel/plugin-proposal-class-properties', {loose: true}],
  ],
};

and here is my **package.json**:

{
  "name": "WatermelonDBProject",
  "version": "0.0.1",
  "private": true,
  "scripts": {
    "android": "react-native run-android",
    "ios": "react-native run-ios",
    "start": "react-native start",
    "test": "jest",
    "lint": "eslint ."
  },
  "dependencies": {
    "@nozbe/watermelondb": "^0.16.0",
    "@nozbe/with-observables": "^1.0.5",
    "babel-preset-react-app": "^9.1.1",
    "react": "16.9.0",
    "react-native": "0.61.5"
  },
  "devDependencies": {
    "@babel/core": "^7.6.2",
    "@babel/plugin-proposal-decorators": "^7.8.3",
    "@babel/runtime": "^7.6.2",
    "@react-native-community/eslint-config": "^0.0.5",
    "babel-jest": "^24.9.0",
    "eslint": "^6.5.1",
    "jest": "^24.9.0",
    "metro-react-native-babel-preset": "^0.56.0",
    "react-test-renderer": "16.9.0"
  },
  "jest": {
    "preset": "react-native"
  },
  "babel": {
    "presets": [
      "module:metro-react-native-babel-preset"
    ],
    "plugins": [
      [
        "@babel/plugin-proposal-decorators",
        {
          "legacy": true,
          "decoratorsBeforeExport": true
        }
      ],
      ["@babel/plugin-proposal-class-properties", { "loose" : true }]
    ]
  }
}

**Comment by radex** [comment]
assuming the problem's been fixed, closing
