### ISSUE TITLE
how can i use reselect with this ?

### ISSUE THREAD

**Issue by krunaldodiya** [Nozbe/WatermelonDB#654]
when i was using redux to store users list, there were 2 reducers

1) auth 
2) users

auth reducer was containing user_id of loggedin user
users reducer was the list of all users

and using reselect's createSelector, I was computing authenticated user like this

```
const userList = state => state.users
const authUserId = state => state.auth.user_id
const authUser = (userList, authUserId) => {
    return userList.find(user => user.id === authUserId)
}

export default createSelector(authUser)
```

now i don't store users in reducer but using database

const usercollection = database.collection("users").query()

i am not sure how can is get authuser like before ?

**Comment by radex** [comment]
assuming the problem's been fixed, closing
