### ISSUE TITLE
Can't get records with useDatabase

### ISSUE THREAD

**Issue by thiagobrez** [Nozbe/WatermelonDB#657]
Hi!

When trying to connect 🍉 to my React component, I first tried the following:

```js
export default withDatabase(
  withObservables([], ({ database }) => ({
    messages: database.collections
      .get('messages')
      .query(Q.where('id', profileId))
      .observe(),
  }))(ChatScreen),
);
```

It happens that `profileId` is only available in my reducer, so I tried using `useDatabase`:

```js
const { profileId } = useSelector(...);
const database = useDatabase();

const messagesObs$ = database.collections
  .get('messages')
  .query(Q.where('profile_id', profileId))
  .observe();

useEffect(() => {
  console.log('messagesObs$', messagesObs$);
}, [messagesObs$]);
```

But this only logs an Observable:

![image](https://user-images.githubusercontent.com/26878038/78170173-f075fe80-7428-11ea-8137-736389dca234.png)

How can I get my records using `useDatabase()`?

Thanks in advance.

**Comment by thiagobrez** [comment]
Ok, I got it working by using the `subscribe` method:

```js
messagesObs$.subscribe(data => {
  console.log('data', data);
});
```

Tried using this method before posting this issue but apparently I used it wrong back then.

I'd be happy to send a PR adding this method to the docs, if wanted.

**Comment by Stophface** [comment]
@thiagobrez could you show how you provided the database context? Simply calling 

```
import { useDatabase } from '@nozbe/watermelondb/hooks'
const database = useDatabase();

```

Is not doing it. It says

> Could not find database context, please make sure the component is wrapped in the <DatabaseProvider />

**Comment by thiagobrez** [comment]
@Stophface You need to call `useDatabase` in a component that is a children of `DatabaseProvider`, as in:

```tsx
<DatabaseProvider>
  <MyComponent />
</DatabaseProvider>
```

```tsx
const MyComponent = () => {
  const database = useDatabase();

  return (
    <div />
  )
}
```

All React contexts work this way ^

**Comment by Stophface** [comment]
@thiagobrez I understand that :)

I initialize the database object once (!), upon first app start with the bundled database.

    const adapter = new SQLiteAdapter({
        schema: whatever,
        dbName: databasePathAndName,
        jsi: false,
        onSetUpError: error => {
            ...
        }
    });

    const database = new Database({
        adapter,
        modelClasses: [
            Country,
            ...
        ],
    });

Now I have a database object called database because of const `database = new Database(..... `
This database object I can use to access the database, which works fine. 

```
<DatabaseProvider database={database}> 
    <App/> 
</DatabaseProvider>
```

However, imagine I open and close the App. Then I basically loose the database object because I am not initializing the database again. It happened already. By doing it again, I would overwrite my already initialized database. Thus, there is no `const database = new Database(... `executed. 

How would I access the database now?!

**Comment by thiagobrez** [comment]
@Stophface Correct, you only initialize your database once. Now, inside `App` or any of it's children, you should just be able to call `const database = useDatabase()` and it should work, if I'm not mistaken. But take this with a grain of salt, it's been a lot of time since I last used Watermelon. Calling `useDatabase()` just retrieves the instance you first passed to the context when initializing the app.

**Comment by Stophface** [comment]
@thiagobrez See, that is something that is not working. I initialze the database on the very first app start. Then I terminate the app, and then I try to access the database again, and it says "database undefined", eventhough its initialzed properly.

```
const App: () => React$Node = () => {

  const mapstarDatabaseInitialized = useSelector(state => state.database.databaseInitialized);

  useEffect(() => {
    (async function () {
      // set up app if it is the first time the user opens it
      if (!databaseInitialized) {
        const database = await initializeBundledDatabase();
      }
    })();
  }, []);

  return <DatabaseProvider
    database={database}>
    <LoadApp />
  </DatabaseProvider>
}
```
