### ISSUE TITLE
How i use 'withChangesForTables' in my project, of the best way ?

### ISSUE THREAD

**Issue by uellpalma** [Nozbe/WatermelonDB#658]
Hello friends, i'm used Watermelon DB in my project react native >= 0.60, and i have a question, how i use 'withChangesForTables' in my project, of the best way ?

i'm try this:

 ```
import { useDatabase } from '@nozbe/watermelondb/hooks'

  export default function Lists() {
  const database = useDatabase()

  database.withChangesForTables(['lists'], () => {
     /// anything
  })
}
```

**Comment by Skullcan** [comment]
I'd like more examples too. The doc's are not very clear on how to use, at least not the ones I found.

Also, when I tried to set it up, every time there's a change on the tables a new sync process was started and I got warnings about the concurrent syncs. A gist or example on how to properly configure this would be very nice.

**Comment by alexandrumic** [comment]
@uellpalma @Skullcan any luck with this? 🤞

**Comment by Skullcan** [comment]
Sadly, no.
Had to push other priorities on the project and left the idea aside for now.

**Comment by uellpalma** [comment]
@alexandrumic, sadly not, I had to go the other way, but you can try it 'database.experimentalSubscribe(['lists', 'items'], () => anything())', I think getting the same database.withChangesForTables

**Comment by radex** [comment]
`database.withChangesForTables` is roughly the same as `database.experimentalSubscribe`, but returns an rxjs Observable - look it up. closing now ;)

**Comment by KrisLau** [comment]
Did you guys ever figure out how to use it? I looked through the docs but it was really unclear and had no examples haha

**Comment by Skullcan** [comment]
Never got around it anymore. 
Will give it a shot again when our pipeline clears a bit =)
