### ISSUE TITLE
Update is not working

### ISSUE THREAD

**Issue by romanakash** [Nozbe/WatermelonDB#663]
So I'm trying to update a record in the database but I keep getting TypeError: undefined is not an object (evaluating 'columnSchema.type')

```javascript
await database.action(async () => {
    const book = await booksCollection.find(bookId);
    await book.update()
})
```

**Comment by romanakash** [comment]
Well looks like my mistake I didn't add updated_at to the table schema and that fixed it

**Comment by KrisLau** [comment]
Adding a comment here for future me and anyone else who might have the same problem, I didn't want a updated_at but I forgot to remove it from my model which gave the same error.

**Comment by 17Amir17** [comment]
Adding a comment here for anyone else who might encounter this.
My problem was that I had a field called `updatedAt`, renaming that worked

**Comment by KrisLau** [comment]
@17Amir17 Not sure if this was what you were trying to do but 🍉 already has an inbuilt way to track the time when a record is updated: https://watermelondb.dev/Advanced/CreateUpdateTracking.html.

**Comment by 17Amir17** [comment]
@KrisLau yeah my backend already has an `updatedAt` field which is why I did not use this

**Comment by youngzodiac** [comment]
Lost a few hours on this one... I had a field named "updatedAt" in my model and this was causing the error. I changed it to "lastUpdatedAt" and now everything's working.
