### ISSUE TITLE
[Proposal] Distinguish user updates from sync updates inside of `CollectionChange`

### ISSUE THREAD

**Issue by kotielnikov** [Nozbe/WatermelonDB#673]
# Problem
Currently, if subscribe to database updates via `withChangesForTables` or  `collections.get(table).changes` the subscribers will be triggered each time when the database was updated and there is no official API to figure out who was the source of update - user or sync. 

Documentation says:
> You can use database.withChangesForTables to detect when local changes occurred to call sync

This will fall into infinite loop, because sync triggeres subscribe and subscribe triggers sync:
```
database.withChangesForTables(tables).subscribe(changeset => {
  changeset.forEach(({ record }) => {
   this.sync()
  });
});
```

We are solving this by asserting internal key `record._raw._status !== 'synced'`:
```
database.withChangesForTables(tables).subscribe(changeset => {
  changeset.forEach(({ record }) => {
   record._raw._status !== 'synced' && this.sync()
  });
});
```

# Possible solutions:

1. Push events only if they were caused by user and not by sync.
2. Add new `synced` type next to `type CollectionChangeType = 'created' | 'updated' | 'destroyed'` 

I can implement either of them.

**Comment by radex** [comment]
Your solution seems essentially correct. We at @nozbe do essentially the same thing:

```
    // Sync when database is dirtied
    this._database
      .withChangesForTables(values(Tables))
      // $FlowFixMe — broken pipe signature
      .pipe(
        skip$(1),
        // ignore records simply becoming `synced`
        filter$(changes => !changes.every(change => change.record.syncStatus === 'synced')),
        // debounce to avoid syncing in the middle of related actions
        debounceTime(500),
      ),
```

The way you could (should) improve it is by debouncing/throttlign syncs and only doing one sync per changeset - triggering sync after every new record is super inefficient.

Do you have other use cases for `updated by sync` state in CollectionChange than this?

**Comment by kotielnikov** [comment]
Thanks for your reply. `syncStatus` is the API I was looking for.

 `this.sync` is a debounced function in our case so no worries.

**Comment by KrisLau** [comment]
@kotielnikov  Where are you guys calling `withChangesForTables`?

**Comment by KrisLau** [comment]
@kotielnikov How to debounce the `withChangesForTables`? I tried to debounce mine but it's still being called dozens of times? #1229

**Comment by KrisLau** [comment]
@kotielnikov Do you just put the `withChangesForTables` in a use effect?
