### ISSUE TITLE
IOS Building Issues - Can Not Find Foundation Headers

### ISSUE THREAD

**Issue by vladamx** [Nozbe/WatermelonDB#674]
Hi guys,

I have spent two days trying to resolve the issue with including WatermelonDB in my IOS Project.
It seems like XCode can not find appropriate libraries which is very weird.

I did all steps mentioned in the installation guide.
I have tried to switch to legacy build system, but it keeps showing the same errors.

<img width="269" alt="Screenshot 2020-05-08 at 15 45 37" src="https://user-images.githubusercontent.com/11381171/81412131-b09ae900-9143-11ea-90e0-946af6903822.png">

**Comment by vladamx** [comment]
What solved the problem for me was adding header search path in build settings with following content: $(SRCROOT)/../node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/SupportingFiles

**Comment by vladamx** [comment]
Reopening this due to the fact that this issue is still present on CI for me even though header search path is configured properly.

XCode 11.3

**Comment by radex** [comment]
how does your project folder structure look like? do you have standard ios/ catalog in the same root as node_modules ?

**Comment by vladamx** [comment]
Hi @radex ! Yes, standard react native setup.

**Comment by dmarkow** [comment]
Same issue here. Builds fine for the simulator, but when building for an iOS device I'm getting the exact same errors.

**Comment by dmarkow** [comment]
Seems to be the same issue as #655. Removed Flipper from my project and it builds fine now.

**Comment by radex** [comment]
@dmarkow can you submit a quick pull request changing the installation guide (docs-master/) to add a "troubleshooting" section explaining that this may happen with flipper at the moment?
