### ISSUE TITLE
Question: Is it possible to connect to get or fix the sqlite connection string

### ISSUE THREAD

**Issue by palmithor** [Nozbe/WatermelonDB#683]
Thanks for what seems to be an awesome product!

As the javascript / typescript world is fast moving, when my team does tech decisions we like to plan ahead. Thus I would like to ask if it is possible to get the connection string or set it to something fixed, f, in the future we would like to use a different approach connecting to the same database without losing the data existing on the device.

Unfortunately I don't have the time myself these days but it would be really nice to get autolinking implemented as it gives you a lot more confidence that the product is up to date and in active development.

**Comment by radex** [comment]
> Thus I would like to ask if it is possible to get the connection string or set it to something fixed

I don't know what you're asking about.

>. Unfortunately I don't have the time myself these days but it would be really nice to get autolinking implemented as it gives you a lot more confidence that the product is up to date and in active development.

Autolinking is not necessary, takes 3 minutes to link manually, and I don't have the time myself for stuff like that. The stuff that really matters though - is in active development ;)

**Comment by palmithor** [comment]
Thanks for a quick response. 

Considering the first question, for example if all of a sudden I would need to use another library to interact with Sqlite, let's say this one https://github.com/andpor/react-native-sqlite-storage. When you connect to a db instance you have to know the name given to that instannce
`SQLite.openDatabase("test.db", "1.0", "Test Database", 200000, openCB, errorCB);` in this case "test.db". 

So my question is, is it possible to define this name  in watermelondb? Or at least get the one set?

Concerning the autolinking, the only reason why I ask is because of the deprecation warning. But I agree, active development weighs more for sure! :)

**Comment by radex** [comment]
> So my question is, is it possible to define this name in watermelondb? Or at least get the one set?

yes
