### ISSUE TITLE
[Proposal] Add info about migrations to adapter or database object

### ISSUE THREAD

**Issue by kotielnikov** [Nozbe/WatermelonDB#685]
# Problem

Normally, our backend doesn't send all database per sync, it sends only changeset since lastPulledIn timestamp. If we introduce a new field to the entity, then it's value is not present in entities which already have been earlier synced without this field. But everything works fine if we perform full database sync. Which we ideally want to do only if schema was updated and some migrations occured.

# Possible solution

Add a new key to adapter object
```
type StartStatus = 'normal' | 'error' | 'migrated'
....
// And then we can do:
if(database.adapter.startStatus === 'migrated') {
    sync(...)
} 
```

or
```
type MigrationStatus = boolean;
...

if(database.adapter.migrationPerformed) {
    sync(...)
} 
```

I can build it if needed.

**Comment by radex** [comment]
I'm working on a proper solution to the problem of migration syncs here: https://github.com/Nozbe/WatermelonDB/pull/714 -- you're welcome to comment and/or contribute :)

**Comment by radex** [comment]
assuming that this can be closed now -- if you have more to add here, please do, i'll reopen

**Comment by kotielnikov** [comment]
ok
