### ISSUE TITLE
Qn: props for `withObservables`

### ISSUE THREAD

**Issue by bsr203** [Nozbe/WatermelonDB#69]
Hi,
Looking at the example code, I see [this comment](https://github.com/Nozbe/WatermelonDB/blob/master/examples/native/src/components/helpers/Navigation.js#L13) 

```     
   // We have to use a little wrapper because React Navigation doesn't pass simple props (and withObservables needs that)

```
I know, `react-navigation` wont pass the props, and normally you achieve this with [extending the navigator](https://reactnavigation.org/docs/en/custom-navigators.html)

Please let me know what all props `withObservables` needs to be passed through?

thanks.
bsr

**Comment by radex** [comment]
@bsr203 `withObservables` is only used to inject whatever you want to observe into one specific component. You don't need to pass it through deeply.

The comment you're linking to refers to the `database` object which you might need to make a global query — it's probably best to just use a `React.Context` to pass this object into your component hierarchy. See: 
https://github.com/Nozbe/WatermelonDB/issues/11

does this answer your question?

**Comment by bsr203** [comment]
thanks. that indeed answered the question.
