### ISSUE TITLE
[QUESTION] Server Column names not matching database column names

### ISSUE THREAD

**Issue by AppcDevSon** [Nozbe/WatermelonDB#694]
Hi,
I have a mongodb database and my column names are camel case for example a booleab isPinned, I can't use this name for a column in my schema for my model since it has to be is_pinned, is there any workaround for this other than looping through all the data from the server?

**Comment by radex** [comment]
@AppcDevSon what solution did you use in the end?

**Comment by AppcDevSon** [comment]
Since my database is small (less than 400 records for the entire database) and I have a tight deadline I ended using async storage

**Comment by AppcDevSon** [comment]
The solution I was working on was torename keys in my Json object received from the server but it didn't think it worth it for a small database
