### ISSUE TITLE
Pre-populated SQLite database

### ISSUE THREAD

**Issue by jdnichollsc** [Nozbe/WatermelonDB#695]
Hello folks,

Is this feature supported?

Thanks for your help!

**Comment by jdnichollsc** [comment]
@radex can we add this as a feature request?

**Comment by maoapp** [comment]
Did you get the fix @jdnichollsc ?

**Comment by jdnichollsc** [comment]
@maoapp I was asking but @radex is not interested to discuss about that as you can see in the other issue _"No one is paid to provide support and answer questions"_

Regards 👍

**Comment by jdnichollsc** [comment]
@maoapp and I was asking because I'm creating a template :) https://github.com/proyecto26/MyApp
