### ISSUE TITLE
Strange typing of relation id

### ISSUE THREAD

**Issue by mtford90** [Nozbe/WatermelonDB#696]
I'm not sure if this is a typing bug or else I've screwed something up myself. This problem relates to the `Relation` class:

```typescript
  export default class Relation<T extends Model> {
    public constructor(
      model: Model,
      relationTableName: TableName<T>,
      columnName: ColumnName,
      options: Options,
    )

    public id: $Call<ExtractRecordId<T>>

    public fetch(): Promise<T>

    public set(record: T): void

    public observe(): Observable<T>
  }
```

If I access `myModelInstance.relation.id` I get the type `string | void` which seems... odd. I would expect `string | undefined` or `string | null` or something along those lines.

My relation is defined as follows:

```
  @relation('exercises', 'exercise_id') public exercise!: Relation<
    ExerciseModel
  >;
```

And this what the typing looks like in my IDE:

<img width="483" alt="Screenshot 2020-05-23 at 10 08 43" src="https://user-images.githubusercontent.com/1734057/82726674-99c8ca80-9cdd-11ea-9432-1cfd4b7607a5.png">

**Comment by radex** [comment]
`void` means `undefined`

**Comment by mtford90** [comment]
@radex not quite I don't think. Unfortunately, it introduces complications to any code that depends on the relation id. See the following example:

```typescript
function foo(x?: string | null) {
  console.log(x);
}

const myVar: string | void = undefined;

foo(myVar); // Error
```

Because of this `void` you must use casting, which is a tad unfortunate:

```typescript
foo(myVar as string | undefined);
```

**Comment by zhuSass** [comment]
The official has helped us to configure the type, can be introduced
```
import { default as Relation } from '@nozbe/watermelondb/Relation';
@relation('exercises', 'exercise_id') public exercise!: Relation<
    ExerciseModel
  >;
```

**Comment by radex** [comment]
closing now; TypeScript types are maintained by the community - I'll be happy to merge in improvements to this if someone can figure out the right way to do this
