### ISSUE TITLE
Is this a community oriented plugin?

### ISSUE THREAD

**Issue by jdnichollsc** [Nozbe/WatermelonDB#699]
I'm asking because you closed this other issue without comments: https://github.com/Nozbe/WatermelonDB/issues/695

Thanks for your help

**Comment by radex** [comment]
@jdnichollsc This is an open-source project, largely maintained by one person, for free. No one is paid to provide support and answer questions.

So a kind thing to do when asking for help is to do your research first - check if someone else already asked this question, review source code to look for a feature you're looking for, and ultimately, if you do need to ask a question, make it concrete, not vague, and easy to answer. #695 is vague, and someone asked about this twice already -- just search issues, and you'll find it.

**Comment by jdnichollsc** [comment]
I can't see any other issue related with that https://github.com/Nozbe/WatermelonDB/issues?q=is%3Aissue+populated but it's ok if you don't want to discuss about that, is your project as I can see :)
