### ISSUE TITLE
 Record ID was sent over the bridge, but it's not cached

### ISSUE THREAD

**Issue by code-brewer** [Nozbe/WatermelonDB#706]
@radex 

There is [issue 546](https://github.com/Nozbe/WatermelonDB/issues/546) reported, and I follow on that thread ( [link](https://github.com/Nozbe/WatermelonDB/issues/546#issuecomment-635816486) ), but it was close. 

So, for all attention, I open this issue and copy it here.

My watch log is:

> E/ReactNativeJS(28949): '[AssetsInfo] DBCrud::findByJson() catch exception: ', { [Diagnostic error: Record ID AssetsInfo#0xd5cc3810197238b06f0f333b5cb2046e0c6ece9a was sent over the bridge, but it's not cached]
E/ReactNativeJS(28949): framesToPop: 2,
E/ReactNativeJS(28949): name: 'Diagnostic error',
E/ReactNativeJS(28949): line: 272531,
E/ReactNativeJS(28949): column: 26,

In my case, I use watermelon DB just as storage, not use the reactive feature. So I only use the _raw property and do operation on _raw object.

Bellow is the main API that I wrap base on the watermelon DB.

const mySchema = tableSchema({
            name: 'AssetsInfo',
            columns: [
                // by default, each table has 'id' column of string type
                    ...
                { name: 'decimals', type: 'number' },
                { name: 'rateUSD', type: 'number' },
                { name: 'version', type: 'string' },
            ],
    })

class AssetsInfo extends Model {
    static table = AssetsInfo;
    **// No other fields, because I don't operate data via model object.**
}

...

    async insert(newDoc) {
        try{
            let dataSet;
            clear_private_field(newDoc);
            (newDoc instanceof Array) ? dataSet = newDoc :  dataSet = [newDoc];

            await this.db.action(async ()=> { 
                let preparedDocs = [];

                for (let i = 0; i < dataSet.length; i++) {
                    let _doc = dataSet[i];

                    const _docToAdd = await this.collection.prepareCreate(doc => {
                        // If insert raw document has id field, ensure it is of string type.
                        if(_doc.id === undefined || _doc.id === null) {
                            _doc.id = doc._raw.id
                        }else {
                            ensureDocIdType(_doc);
                        }
                       // _sanitizedRaw() is copy from this lib source folder.
                        doc._raw = _sanitizedRaw(_doc, this.collection.schema);
                    })
                    preparedDocs.push(_docToAdd)
                }
                await this.db.batch(...preparedDocs);
            })
            return newDoc;
        }catch (e) {
            console.error(`Failed insert doc to ${this.collection.schema.name}, error: `, e);
            return []; 
        }
    }

async findByJson(filterObj) { 
        ensureDocIdType(filterObj);  // filterObj is an Json style object that follow the mongoDB style

        let foundDocs = []

        try {
            let condSet;
            condSet = convert(filterObj);
            if(condSet) {
                foundDocs = await this.collection.query(...condSet).fetch()
                if(! (foundDocs instanceof Array)) {
                    console.log(`[${this.collection.schema.name}]DbCrud::findByJson} got no docs.` )
                    return []
                }
                foundDocs = foundDocs.map(doc => doc._raw)
            }
        }catch (e) {
            console.error(`[${this.collection.schema.name}] DBCrud::findByJson() catch exception: `, e);
        }

        // delete _status and _changed field
        if(foundDocs.length > 0) clear_private_field(foundDocs);
        return foundDocs;
    }

   async update(id, newDoc) {

        let retVal = 1;

        id = ensureToString(id);

        let doc = await this.collection.find(id).catch(e => {
            console.log(`DBCrud::update(${id}) catch exception: `, e);
            return 0
        })
        if(!doc) {
            console.log(`DBCrud::update(${id}) no such document`);
            return 0;
        }

        await this.db.action(async () => {
            await doc.update(doc => {
                clear_private_field(newDoc)
                let _tempDoc = Object.assign(doc._raw, newDoc)
                doc._raw = _sanitizedRaw(_tempDoc, this.collection.schema);
            })
        }).catch(e=>{
            console.log(`DBCrud::update(${id}) catch exception: `, e);
            retVal = 0;
        })
        return retVal
    }

Is there anything wrong with my code?

Can this error message be ignored if unable to solve?

Also, in my case, not use reactive, are there configurations to tune? 

Thank a lot~

**Comment by radex** [comment]
> Can this error message be ignored if unable to solve?

probably not, this is an error.

this is the source of the error: https://github.com/Nozbe/WatermelonDB/blob/fb111f2d620bfe7cb31da33c5d36ce76f3db1fed/src/Collection/RecordCache.js#L58

add some console logs in your node_modules copy of watermelon to track down what's happening with this record. there is some reason why native code thinks JS has a record with this ID, but actually does not.

**Comment by code-brewer** [comment]
Nearby,  can see many logs like: 

> W/ReactNativeJS(13448): [WatermelonDB] The action you're trying to perform (unnamed) can't be performed yet, because there are 28 actions in the queue. Current action: unnamed. Ignore this message if everything is working fine. But if your actions are not running, it's because the current action is stuck. Remember that if you're calling an action from an action, you must use subAction(). See docs for more details.

**Comment by code-brewer** [comment]
> > Can this error message be ignored if unable to solve?
> 
> probably not, this is an error.
> 
> this is the source of the error:
> 
> https://github.com/Nozbe/WatermelonDB/blob/fb111f2d620bfe7cb31da33c5d36ce76f3db1fed/src/Collection/RecordCache.js#L58
> 
> add some console logs in your node_modules copy of watermelon to track down what's happening with this record. there is some reason why native code thinks JS has a record with this ID, but actually does not.

Thanks, I will give it a try.

**Comment by radex** [comment]
@code-brewer did you find the root cause of the problem?

**Comment by martinodonnell** [comment]
@code-brewer I was having a similar error message and discovered I accidentally added the line `@field('id_backend') id;` in my Table. The field didn't match up to the `id_backend` on I declared in my schema. Could you be doing something similar? What does you full schema look like?

**Comment by code-brewer** [comment]
Sorry，I haven't. 

I ran into another urgent problem, also waterleonDB related, and spent time on it. 

I do operation on watermelonDB document's  '_raw' member, not on model variable.

My schema has a field name 'jsonObj' of string type, and do JSON.parse/stringify on read/write to DB.

First, I do read:

>  doc = db.read(...); doc.jsonObj=JSON.parse(doc.jsonObj)

then do modification ： 

> ...

and finally save to DB:  

> clonedDoc.jsonObj=JSON.stringify(clonedDoc.jsonObj) ; db.save(clonedDoc);

but after save to DB, my doc.jsonObj change to stringify value, which suprise me and cause exception when try to access member of  'jsonObj' object.

I found this after days investigation.  ^^" 

[The graph summary of my problem](https://imgur.com/QVS88pe) 

But i still can't understand why（´＠＿＠｀ ）

**Comment by code-brewer** [comment]
> @code-brewer I was having a similar error message and discovered I accidentally added the line `@field('id_backend') id;` in my Table. The field didn't match up to the `id_backend` on I declared in my schema. Could you be doing something similar? What does you full schema look like?

It is weird that add this single line could cause error message.  
In my app, I have not utilized the Model, not the same scenario as you.
Maybe 'id' has special purpose, you can try change to another name and see what happens.

**Comment by martinodonnell** [comment]
> @code-brewer I was having a similar error message and discovered I accidentally added the line `@field('id_backend') id;` in my Table. The field didn't match up to the `id_backend` on I declared in my schema. Could you be doing something similar? What does you full schema look like?

I believe I got the error because I set the @field to id_backend and the second to id. When I changed the id to id_backend, it stopped the error

**Comment by eshunnar** [comment]
I'm having this exact issue on `react-native@63.3.3` and `@nozbe/watermelondb@0.20.0` with the following code:

```
const assignmentCheckCollection = db.collections.get('checks');

assignmentCheckCollection.query().fetch().then((res) => {
  console.log(res);
});
```

**Comment by KrisLau** [comment]
I'm getting this error when I change my `_id` to an integer instead of a string. Any solution for this? Why was this closed?

**Comment by paul-rchds** [comment]
I was getting this error when my sync function pulled in new results for a collection that was being observed. I had _unsafeBatchPerCollection set to true in my synchronize function. Changing _unsafeBatchPerCollection  to false fixed the issue for me. 

(Running with the Loki Adaptor with WMDB v0.24.0)
