### ISSUE TITLE
Is there no flatlist support or am i missing something?

### ISSUE THREAD

**Issue by genesy** [Nozbe/WatermelonDB#709]
I keep seeing *.map instead of using Flatlist in examples. I don't see an example anywhere that uses flatlist so i can compare my usage because i'm getting weird behaviors when i use the observable collection as my data.

**Comment by radex** [comment]
use of FlatList has nothing to do with 🍉 really - sure you can use it. if you post a larger chunk of your code then maybe someone can help ;)

**Comment by radex** [comment]
assuming this has been fixed, closing
