### ISSUE TITLE
Require cycles

### ISSUE THREAD

**Issue by bsr203** [Nozbe/WatermelonDB#71]
Hi just noticed this warning on chrome console while debugging.

```
require.js:109 Require cycle: node_modules/@nozbe/watermelondb/Collection/index.js -> node_modules/@nozbe/watermelondb/Query/index.js -> node_modules/@nozbe/watermelondb/observation/observeQuery.js -> node_modules/@nozbe/watermelondb/observation/simpleObserver/index.js -> node_modules/@nozbe/watermelondb/Collection/index.js

Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.

```

Is it possible to avoid this?

thanks.

**Comment by radex** [comment]
yes, `simpleObserver` imports a constant from Collection it shouldn't need to. That constant should be moved to Collection/common.js. Feel free to send a pull request

**Comment by bsr203** [comment]
@radex  please see https://github.com/Nozbe/WatermelonDB/pull/72

**Comment by radex** [comment]
fixed

**Comment by arahmanali** [comment]
`
Require cycles are allowed, but can result in uninitialized values. Consider refactoring to remove the need for a cycle.
Require cycle: src/navigation/Navigation.js -> src/navigation/registerScreens.js -> src/containers/Authentication/index.js -> src/components/Authentication/index.js -> src/navigation/Navigation.js

`
