### ISSUE TITLE
WatermelonDB viewer?

### ISSUE THREAD

**Issue by finom** [Nozbe/WatermelonDB#710]
Hey guys! Is there a tool which allows to look at tables visually? I'm developing a normal multi table DB and I need to check how do fields populated, removed etc. CLI output is also OK.

**Comment by djorkaeffalexandre** [comment]
Hey @finom, you can use DB Browser for SQLite.
https://sqlitebrowser.org/

**Comment by finom** [comment]
@djorkaeffalexandre thank you but how can I open a DB which is in an emulator?

**Comment by djorkaeffalexandre** [comment]
I think it's logged to someplace that I never saw.
@radex where we can see this log? https://github.com/Nozbe/WatermelonDB/blob/876fe190f2dc57820780b11522c43d15b170f384/native/ios/WatermelonDB/Database.swift#L30

**Comment by radex** [comment]
in the iOS system log -- e.g. via xcode

**Comment by davidsonsns** [comment]
This comment can also help you all, at least for me it was
https://github.com/Nozbe/WatermelonDB/issues/105#issuecomment-453815987

@radex I'm thinking about creating a reference for that on the documentation. Sharing how to find the complete path to `watermelon.db` file. Once with that, we can easily open any SQLite GUI to see data. Sounds good?

**Comment by radex** [comment]
@davidsonsns Yes, please do! That would be very helpful to a lot of people to have it right in the docs. Find (or make) the right file in docs-master/ (the docs/ folder is compiled when releasing a new version of 🍉, don't worry about that)

**Comment by StefanBlamberg** [comment]
The new database inspector which is built-in into the Android Studio Beta version is also a very convenient and powerful tool to inspect the emulator database
Works perfectly with Watermelon

https://medium.com/androiddevelopers/database-inspector-9e91aa265316

**Comment by mattfrances** [comment]
For viewing the watermelon db using an iOS simulator on Mac, check out [this stackoverflow link](https://stackoverflow.com/a/64210098/13110687) which has the following steps:
1. cd /Users/<your username>/Library/Developer/CoreSimulator/Devices
2. find . -name "{your database name}.db"
3. sqlite 3 /Users/<your username>/Library/Developer/CoreSimulator/Devices/{paste the path outputted from Step 2 here}

Once complete, you'll be able to access your tables using the CLI!
(btw the brackets {} in step 2 and 3 should not be included when performing your commands, they just indicate placeholders)

**Comment by kkkasio** [comment]
Hello friends, I develop with React Native, I almost always need to keep looking at the database during development.
to get my file straight from my emulator I use the following command:

``
adb shell "run-as com.package.name cat /data/data/com.package.name/watermelon.db" > ./folder_destiny/watermelon.db
``
and later I use another program (DBeaver, Beekeeper) to view the file.
I lost some time, but I soon found the above solution. I wouldn't want to get involved with Android Studio's "App Inspector"

**Comment by KrisLau** [comment]
@kkkasio What would be the pc path folder? Is that the path to my project?

**Comment by KrisLau** [comment]
@kkkasio When I try to open the file, it says:
![image](https://user-images.githubusercontent.com/46275463/151422960-0059b7c9-53a6-4ba9-92db-36295d5555b9.png)

**Comment by Danu-rxone** [comment]
My workaround in RN 0.73.8:

In the android directory:
`cd ./android`

and run the following command: 
`run adb shell "run-as com.valnas cat /data/data/com.valnas/ValidationDB.db" > ../database.db
`

The database name should come from your configuration:

```
const adapter = new SQLiteAdapter({
  dbName: 'ValidationDB',
  schema,
  migrations,
  jsi: true /* Platform.OS === 'ios' */,
  onSetUpError: error => {
    console.warn(error, 'on SetUp Error');
  },
});
```

Then you will get database.db in the root of the project.

You can open this file in any database viewer, such as DB Browser for SQLite.

**Comment by rhenandias** [comment]
Using the method with adb shell, I can extract the .db file from the application's package folder, but no visualization tool is able to parse the .db file, as if something is corrupted...

The only solution that worked for me was using Android Studio's viewer, but this tool consumes an impressive amount of resources from my machine. So much RAM just to view the database is not an ideal trade-off.

Any fix to correctly parse the file extracted with adb shell?

**Comment by gabrielforcellini** [comment]
This worked for me on windows:

1. Find the database
```
adb shell
run-as com.package.name
cd /data/data/com.package.name/
ls
```
2. Exit the adb shell
3. Run
```
adb pull /data/data/com.package.name/your-database-name.db.db ./your_pc_path_folder/watermelon.db
```
4. Open in DB Browser for SQLite
![image](https://github.com/user-attachments/assets/51336348-525c-481b-8108-050867f546f3)

**Comment by LovesWorking** [comment]
This script worked for me. You may need to modify it.

```js

#!/bin/bash

# Get the latest simulator's WatermelonDB
SIMULATOR_DB=$(find ~/Library/Developer/CoreSimulator/Devices -name watermelon.db | grep -v Cache | head -n 1)

if [ -z "$SIMULATOR_DB" ]; then
    echo "No WatermelonDB found in simulators"
    exit 1
fi

# Create a directory in the project root for the database
mkdir -p ./tmp/db

# Remove existing symlink if it exists
rm -f ./tmp/db/watermelon.db

# Create symlink instead of copying
ln -s "$SIMULATOR_DB" ./tmp/db/watermelon.db

echo "Database symlinked from: $SIMULATOR_DB"
echo "To: $(pwd)/tmp/db/watermelon.db"
echo ""
echo "You can now open this file in TablePlus or SQLite browser"
echo "The symlink will automatically reflect any changes to the database"

# Automatically open the database file
open ./tmp/db/watermelon.db 

```
