### ISSUE TITLE
Support for react-native auto-link

### ISSUE THREAD

**Issue by mjstelly** [Nozbe/WatermelonDB#711]
As of Sept 2019, there was no support for the RN auto-linking for 0.60+. Has that functionality been added to your roadmap?

My current packages
```
    "@nozbe/watermelondb": "^0.16.1",
    "@nozbe/with-observables": "^1.0.5",
    "react": "16.11.0",
    "react-native": "0.62.2",
```
As of this RN version, I still get `[!] use_native_modules! skipped the react-native dependency '@nozbe/watermelondb'. No podspec file was found.` The test app compiles, but I haven't implemented wdb in the app yet. So I don't know if this is a latent bug or not.

**Comment by radex** [comment]
autolinking is not yet supported - docs have installation steps

**Comment by pokey** [comment]
So is this issue closed because auto-linking is tracked by https://github.com/Nozbe/WatermelonDB/issues/279?

**Comment by radex** [comment]
yup
