### ISSUE TITLE
[Website issue] Link to doc is broken

### ISSUE THREAD

**Issue by mjstelly** [Nozbe/WatermelonDB#712]
The url for the link to your documentation is self-referencing. It should probably point to the [installation doc.](https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Installation.md).

**Comment by radex** [comment]
@mjstelly would you mind sending a quick PR fixing the link? :)

**Comment by mjstelly** [comment]
I was wrong. The link points to a web-rendered version of the markdown files. The header text is so faint I totally missed it. May want to change the font color.
