### ISSUE TITLE
Manually adding Xcode library crashes build

### ISSUE THREAD

**Issue by mjstelly** [Nozbe/WatermelonDB#718]
I don't know how I got my demo app working before, but it must've been pure luck. I revisited the app today. No changes had been made to the code since last Friday. While attempting to build it for iOS, the compiler crashed with a log file full of Swift errors. I have no idea why. 

Here are the steps to recreate my issue.

If I remove `libWatermelonDB.a` from the project, the app will build in Xcode. If I remove/re-add the `.xcodeproj` file _and_ the library. BOOM! Crashes again. It's definitely not my app causing problems. It's the WatermelonDB project. 

I've tried multiple times linking/unlinking the library both through Xcode and using `react-native link/unlink`. I get the same result every time.

I've attached the project. Just unzip it, install node modules and pod files as usual. I hope someone can decipher what the hell the problem is. Thanks.

[homee_wdb-feature-demo.zip](https://github.com/Nozbe/WatermelonDB/files/4755106/homee_wdb-feature-demo.zip)

**Comment by radex** [comment]
you mean the build failed, not that the compiler crashed, yeah? can you paste what errors you get?

**Comment by mjstelly** [comment]
At my next opportunity, I’ll get you more detail. For now, watermelon is not stable enough nor has the proper JSI for us to proceed with implementation. 

You have a good start, but are in dire need of a retooling for ESnext and ReactNative > 0.60. Good luck.

**Comment by radex** [comment]
that's fine, but out of curiosity:

> watermelon is not stable enough

what do you mean there?

> nor has the proper JSI

do you have a specific _need_ for a JSI-based implementation, or are you simply seeking more performance than what it has now?

> in dire need of a retooling for ESnext

again, what do you mean there? old-style decorators?

**Comment by alexandrumic** [comment]
Hello. @radex I had a similar issue today. No changes since last Friday, and today when trying to build the app I encountered all kinds of native errors. 

I have Xcode 11.5 (latest) and tried to manually link again the library, removed the files and added them again, re-installing the library (but now I have v0.15.1 instead of 0.16.0 as before - I think latest release has changed - but the issue is the same).

Here is the log from `react-native run-ios`:

```
❌  /Users/alexandrumic/Documents/Alex/Projects/equinet/equinet-mobile/node_modules/@nozbe/watermelondb/native/ios/../../../../../ios/Pods/Headers/Public/abseil/absl/time/time.h:77:10: 'chrono' file not found

#include <chrono>  // NOLINT(build/c++11)
         ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/System/Library/Frameworks/CoreFoundation.framework/Headers/CoreFoundation.h:16:10: could not build module 'Darwin'

#include <sys/types.h>
        ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/usr/include/dispatch/dispatch.h:25:10: could not build module 'Darwin'

#include <Availability.h>
        ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/usr/include/os/object.h:25:10: could not build module 'Darwin'

#include <Availability.h>
        ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/System/Library/Frameworks/Foundation.framework/Headers/Foundation.h:6:10: could not build module 'CoreFoundation'

#include <CoreFoundation/CoreFoundation.h>
        ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/usr/include/objc/objc.h:31:10: could not build module 'Darwin'

#include <sys/types.h>      // for __DARWIN_NULL
         ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/System/Library/Frameworks/Security.framework/Headers/SecBase.h:27:10: could not build module 'Darwin'

#include <TargetConditionals.h>
         ^



❌  /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator13.5.sdk/System/Library/Frameworks/CoreServices.framework/Headers/UTCoreTypes.h:19:10: could not build module 'CoreFoundation'

#include <CoreFoundation/CoreFoundation.h>
         ^



❌  /Users/alexandrumic/Documents/Alex/Projects/equinet/equinet-mobile/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/SupportingFiles/../FMDB/src/fmdb/FMDB.h:1:9: could not build module 'Foundation'

#import <Foundation/Foundation.h>
        ^



❌  error: failed to emit precompiled header '/Users/alexandrumic/Library/Developer/Xcode/DerivedData/Equinet-fplpsagbqcpeuddadhyzlwchftma/Build/Intermediates.noindex/PrecompiledHeaders/Bridging-swift_Z979SN04K4SV-clang_8AH9QGFMG752.pch' for bridging header /Users/alexandrumic/Documents/Alex/Projects/equinet/equinet-mobile/node_modules/@nozbe/watermelondb/native/ios/WatermelonDB/SupportingFiles/Bridging.h
```

Hope this helps 🤞

**Comment by alexandrumic** [comment]
@radex I'm coming back with an update, still not manage to make it work, but I think this issues were started to happen after I've added Firebase in the project: 
* `@react-native-firebase/app 7.2.1`
* `@react-native-firebase/firestore 7.1.7`
* `@react-native-firebase/storage 7.1.4`

I don't know if is related and if some Pods from Firebase are leading to this errors in Watermelon but maybe this information will help

**Comment by igor-peregudov** [comment]
I have the same problem. I want to add watermelondb to my project, but after adding the library, the app crashes.

in Xcode: "11.4.1"
react native: "0.62.2"
watermelondb: "0.15.1"

**Comment by alexandrumic** [comment]
fyi: It is working if you change the Build System to Legacy. I don't think this is the best approach to make it work, but it is fine for now.

**Comment by igor-peregudov** [comment]
Updating to 0.16.1-0 helped me
