### ISSUE TITLE
Node JS client

### ISSUE THREAD

**Issue by sidferreira** [Nozbe/WatermelonDB#721]
Hi! We use some command-line tools to help with our project.
At this moment we use a workaround as `LokiJS` is `web` and `sqlite` has native dependencies.

I tried to write my own adapter but I couldn't write it properly as we had no access to some parts of code through import.

At first glance, I believe `sqlite` can be modified in order to handle both `native` and `node`, but before starting this PR, I would like to know if it sounds interesting for the maintainers.

**Comment by radex** [comment]
Sure, sqlite adapter for node would be nice. I'm not sure what's the use case for you, but why not. `LokiJS` also can absolutely work for node, it just has to be reconfigured from an IndexedDB backing to `fs` (or memory, depending on what you're trying to do)

**Comment by sidferreira** [comment]
We use it to generate a local db file that will be shipped with our app.

**Comment by radex** [comment]
ah! that's a cool idea!

**Comment by sidferreira** [comment]
@radex it seems to me that `LokiJS` won't handle a SQLite file... So my current idea is something like:

- move `adapter/sqlite`'s `makeDispatcher` to a different place as `makeDispatcherNative`
- create a version of it as `makeDispatcherNode`

I'm just not sure WHERE should I do it... I mean, there are many versions (0.15.*, 0.16.*, and 0.17.*) and I would like to have it available soon (I don't like to use github as project dependencies).

**Comment by radex** [comment]
> move adapter/sqlite's makeDispatcher to a different place as makeDispatcherNative

good idea

 > I'm just not sure WHERE should I do it

Make a branch of off master. Next release will be 0.17.0

> This would be easier if many of the types used weren't blocked for outside access (Flow) or missing (v0.17 has some differences between TypeScript and Flow types)

I should make it more clear in the docs - Flow types are official (maintained by me and Nozbe), TypeScript types are maintained by the community. I'm all for better types, but I don't use it, so I don't maintain it — but I happily merge TS improvement PRs

**Comment by sidferreira** [comment]
Thanks for all the info!
Will be able to work on it today :)

**Comment by sidferreira** [comment]
@radex I'm having a weird error on ci: 

```
Unable to resolve path to module 'big-list-of-naughty-strings'
```

have you guys faced it?
the module is in `node_modules` tho...
