### ISSUE TITLE
React Native Autolinking Support

### ISSUE THREAD

**Issue by mmosayed** [Nozbe/WatermelonDB#722]
So I was able to get WatermelonDB running successfully by using the following versions:
- "@nozbe/watermelondb": "^0.17.0-4"
- "@nozbe/with-observables": "^1.0.6-0"

And running the `react-native link @nozbe/watermelondb` command.

But I always get the following:
```
error React Native CLI uses autolinking for native dependencies, but the following modules are linked manually:
  - @nozbe/watermelondb (to unlink run: "react-native unlink @nozbe/watermelondb")
This is likely happening when upgrading React Native from below 0.60 to 0.60 or above. Going forward, you can unlink this dependency via "react-native unlink <dependency>" and it will be included in your app automatically. If a library isn't compatible with autolinking, disregard this message and notify the library maintainers.
Read more about autolinking: https://github.com/react-native-community/cli/blob/master/docs/autolinking.md
```

Is it on the roadmap to support autolinking? Because seems like manual linking is going to be soon deprecated by RN and even if I try to run `npx react-native unlink @nozbe/watermelondb` I get an error:

```
error Something went wrong while unlinking. Reason Cannot read property 'find' of undefined. Run CLI with --verbose flag for more details.
TypeError: Cannot read property 'find' of undefined
at removeFromProjectReferences (../node_modules/@react-native-community/cli-platform-ios/build/link/removeFromProjectReferences.js:30:53)
```

This is my first time using using WatermelonDB, so just wanted to also to make it easier for any new comers.

**Comment by radex** [comment]
> Is it on the roadmap to support autolinking?

if someone does the work and sends a pull request, I'll accept it

> Because seems like manual linking is going to be soon deprecated by RN

no. it works.
