### ISSUE TITLE
Random query possible?

### ISSUE THREAD

**Issue by cristian-milea** [Nozbe/WatermelonDB#723]
Hello,

Is there any way to query a table for a random result? 
Example: I have a table with 1000 users and want to randomly select a winner.

I can't find anything related to random in the docs and getting all results and then js Math.random seems heavy.

Is there an equivalent of "SQL ORDER BY RANDOM" ?

**Comment by cristian-milea** [comment]
I think I found a way using rawQuery

```
const records = usersCollection.unsafeFetchRecordsWithSQL(
    'SELECT * FROM users ORDER BY RANDOM() LIMIT 3',
  );
```

is there any other / better way?

**Comment by radex** [comment]
> is there any other / better way?

no, that's the right way
