### ISSUE TITLE
@relation - undefined when observing relation in model

### ISSUE THREAD

**Issue by martinodonnell** [Nozbe/WatermelonDB#726]
I am following the guide from the [docs](https://nozbe.github.io/WatermelonDB/Relation.html) to setup a relation between my supplier and delivery table. Each delivery has a single supplier and a supplier can link to multiple deliveries so I use the supplier_id in the delivery table. When I follow the guide.
1. A table column for the related record's ID
2. A @relation field defined on a Model class:
3. Observe the supplier I get the error:
```
TypeError: undefined is not a function (near '...combineLatest.combineLatest..."
...
*Point to the withObservables function seen below*
```

The code to observe the supplier is seen below. I have tried to use `delivery.supplier` and `delivery.suppliers` but all do not work. When I do `delivery.supplier_id.fetch()`, I get the data but I would like to observe it. (Note, I need to use an await keyword)

```
const enhance = withObservables(['delivery'], ({delivery}) => ({
  delivery: delivery.observe(),
  supplier: delivery.supplier_id.observe(),
}));
```

**Clarification**
Another clarification  would be around the actual guide. In the comments table, author_id is added in the schema and model with a relation back to users. Then when author is observed, `comment.author.observe(),` is used. How does the code know to not use the plural?

Here is the schema for my supplier and delivery table incase
```
tableSchema({
      name: 'suppliers',
      columns: [
        {name: 'supplier_name', type: 'string'},
        {name: 'supplier_address', type: 'string'},
        //...
      ],
    }),
    tableSchema({
      name: 'deliveries',
      columns: [
        {name: 'delivery_date', type: 'string'},
        //...
        {name: 'kitchen_id', type: 'string'},
        **{name: 'supplier_id', type: 'string'},**
      ],
    }),

```

**Comment by martinodonnell** [comment]
`Clarification
Another clarification would be around the actual guide. In the comments table, author_id is added in the schema and model with a relation back to users. Then when author is observed, comment.author.observe(), is used. How does the code know to not use the plural?`

Figured this bit out. The author comes from the field you place in the model. `@relation('users', 'author_id') author` so the field to observe it author

**Comment by martinodonnell** [comment]
I have tried to compose multiple withObservables from [630](https://github.com/Nozbe/WatermelonDB/issues/630#issuecomment-591389424) with the code below.

```
const enhance = compose(
  withObservables(['delivery'], ({delivery}) => ({
    delivery,
  })),
  withObservables(['delivery'], ({delivery}) => ({
    supplier: delivery.supplier_id.observe(),
  })),
);

export default enhance(DeliveryItems);
```
I now get the error
![Screenshot_1592217781](https://user-images.githubusercontent.com/22416103/84648777-66084b80-aefd-11ea-9b8a-8290b98de3fd.png)


Below is my delivery model
```
export default class Delivery extends Model {
  static table = 'deliveries';
  
   //** other fields 
  @relation('suppliers', 'supplier_id') supplier_id;
  
}
```

**Comment by martinodonnell** [comment]
Currently using this but there must be a better solution to this that I am not seeing.

```
const [supplier, setSupplier] = useState();

  useEffect(() => {
    const getSupplier = async () => {
      const supp = await delivery.supplier_id.fetch();
      setSupplier(supp);
    };
    getSupplier();
  }, [supplier]);
```

**Comment by radex** [comment]
This looks like a RxJS configuration issue. Do search for rxjs troubles in issues -- and anyway v0.20  should fix any such issues
