### ISSUE TITLE
Many to many Relationships

### ISSUE THREAD

**Issue by gzumaglini** [Nozbe/WatermelonDB#73]
Thank you for your awesome work on this library!

My question:
Is there support (planed?) for many-to-many relationships?

Example:
I have a cookbook table. A cookbook belongs to a specific user.
I have a recipe table.
A recipe can belong to many cookbooks (a user can „favorite“ the recipe in his personal cookbook).

This could be solved using a associative/pivot table containing foreign keys to the cookbook table and the recipe table.

**Comment by radex** [comment]
> This could be solved using a associative/pivot table containing foreign keys to the cookbook table and the recipe table.

Exactly. There's no explicit support needed for this. Simply create a new model (say, RecipeCookbookMembership), and both Recipe and Cookbook would have a `has_many` association to it, and `RecipeCookbookMembership` would have a `belongs_to` association for both. And you could easily write a query on Recipe to get all cookbooks, and on Cookbook to get all recipes.

Let me know if that makes sense.

And if you get it to work, perhaps you'd be willing to help out writing this up in the docs?

**Comment by Kabangi** [comment]
@radex How would the query for fetching `cookbooks` on `Recipe` look like. Am trying to achieve the same but can't figure out the query.

**Comment by Kabangi** [comment]
Never mind I have figured it out. 

I can write the docs if @gzumaglini Is not on it

**Comment by radex** [comment]
@Kabangi please do!

**Comment by radex** [comment]
@Kabangi hey, did you have a moment to write up a simple example of this?

**Comment by Kabangi** [comment]
Coming up in a few. Sorry for ghosting on this. Am currently working on it.
