### ISSUE TITLE
How can we query (Search filter) for other languages

### ISSUE THREAD

**Issue by shaheem-khanzada** [Nozbe/WatermelonDB#734]
How can we query (Search filter) for other languages like Russian , Spanish users name
eg: Russian names:
Лена
Игорь
Сергей
Иван
Кирилл
Александр

I am using this code for filtering Users from db but its not working for other languages like  Russian , Spanish, Arabic and other

```
const db = database.servers;
		const data = await db.collections
			.get('users').query(
				Q.where('id', Q.notEq(user.id)),
				Q.or(
					Q.where('name', Q.like(`%${ Q.sanitizeLikeString(text) }%`)),
					Q.where('lastname', Q.like(`%${ Q.sanitizeLikeString(text) }%`)),
					Q.where('company', Q.like(`%${ Q.sanitizeLikeString(text) }%`))
				)
			).fetch();
```

**Comment by radex** [comment]
hey - take a look at the definition of `Q.sanitizeLikeString` (use GitHub search). It simply strips all unsafe characters. If you can do sanitization yourself, and strip everything aside from known-safe Unicode ranges for Russian, Spanish, Arabic, that will work as well. Just make sure users can't put arbitrary characters that will mess with Regexp (lokijs) and SQL LIKE syntax under the hood
