### ISSUE TITLE
Build error on iOS - Build input file cannot be found watermelondb/native/shared/Sqlite.cpp

### ISSUE THREAD

**Issue by mlecoq** [Nozbe/WatermelonDB#737]
Hi,

here is my environment : 

```
{  
    "react-native": "0.62.2",
    "@nozbe/watermelondb": "^0.17.0",
    "@nozbe/with-observables": "^1.0.5"
}
```

On Android it works fine but on iOS, I have the following build error:

`Build input file cannot be found: '...node_modules/@nozbe/watermelondb/native/shared/Sqlite.cpp'`

Looking at _project.pbxproj_ there is a reference to _Sqlite.cpp_ in _shared_ directory

```
Sqlite.cpp; path = ../../shared/Sqlite.cpp; sourceTree = "<group>"; };
		6EBBB7152472B4A200E43F26 /* Sqlite.h */ = {isa = PBXFileReference; lastKnownFileType = sourcecode.c.h; name = Sqlite.h; path = ../../shared/Sqlite.h;
```

This directory is really missing in the dependency

**Comment by radex** [comment]
Fixed in 0.17.1
