### ISSUE TITLE
SQLITE_BUSY[5]

### ISSUE THREAD

**Issue by giuseppeabn** [Nozbe/WatermelonDB#739]
I'm getting this error when I start the application and save the user that is registering.

![Screenshot_20200622-184556_BovinoApp](https://user-images.githubusercontent.com/4584293/85602613-8b900600-b61d-11ea-9caa-3a460830ee55.jpg)

**Comment by radex** [comment]
what version are you on? is this Android? what's the settings of the sqlite adapter?

**Comment by giuseppeabn** [comment]
Hello @radex , I appreciate any help you can give
@nozbe/watermelondb": ^0.16.0
react-native: 0.59.9
SO: Android
![image](https://user-images.githubusercontent.com/4584293/85628698-8b543280-b63e-11ea-8a61-68ddf8f220f6.png)

**Comment by radex** [comment]
are you also running your app on iOS? does the same issue occur there?

did you always get this warning, or did it start appearing more recently?

**Comment by giuseppeabn** [comment]
1.- This error only occurs in android, in IOS it works very well.
2.- This warning started to appear recently

**Comment by radex** [comment]
@giuseppeabn do you, by any chance, create multiple Database instances?
