### ISSUE TITLE
Diagnostic error: Database.batch() can only be called from inside of an Action. See docs for more details.

### ISSUE THREAD

**Issue by Miraj98** [Nozbe/WatermelonDB#742]
I am facing an issue where I am executing the `batch` inside an action and yet it is throwing the above error message. Before I copy paste my code I'll just explain my set up it helps.

I am using watermelon for a messaging app. It has three tables `messages`, `messaging_channels` and `media`. `messaging_channels` can be understood as text channels in Slack. Hence every message is a child to some or the other messaging channel. A message may or may not have media as an attachment and that is stored inside a separate table - `media`. I'll even explain the basic flow so it helps any developer trying to resolve this:

1. User inputs message and presses send
2. Before sending to the server it is set in the database and marked as `sending`. If there is a media attachment then, the media is set in the `media` table and set with local `uri` and marked as `uploading`. All this is done as a batch action as it involves setting the messaging channel, setting the message and also setting media. This batch action is executed successfully and there are NO issues here.
3. Once the media is uploaded and message is sent, this information needs to be updated in the database and the message and media need to be marked as `sent` and `uploaded` respectively. This is also attempted through a batch action but it always fails with the above error even though the batch is attempted inside a `Action`.

This is the batch that does not work (the one referred in point 3 above):
```
import lib from './lib';
import watermelon from '../index';

export default async (msg, media) => {
  await watermelon.action(async action => {
    const batchedActions = [];

    const [, messageRecord] = await lib.query.findById(msg.id, 'messages');

    batchedActions.push(
      messageRecord.prepareUpdate(m => {
        m.readStatus = msg.readStatus;
      }),
    );

    const mediaRecord = await messageRecord._media.fetch();
    if (mediaRecord) {
      batchedActions.push(
        mediaRecord.prepareUpdate(med => {
          med.mediaUploadState = media.mediaUploadState;
          med.url = media.url;
        }),
      );
    }

    console.log(batchedActions);

    try {
      await watermelon.batch(...batchedActions);
    } catch (err) {
      console.warn('Err updating media message:', err);
    }
  });
};
```

This is the error message I get:
` Err updating media message: [Diagnostic error: Database.batch() can only be called from inside of an Action. See docs for more details.]`

I don't know what's the issue here. Any help is much appreciated.

**Comment by Miraj98** [comment]
### Update

I was able to fix this issue by writing the actions as methods on the `Message` model. But I am still a bit lost as to why the above way is not working. Anyways, closing the issue but if someone can shed some light then it will be great

**Comment by radex** [comment]
It absolutely should work, and I can't spot a bug, so either you have a misbehaving action code elsewhere, or you somehow constructed code that triggers some Watermelon bug, but I honestly don't see how.
