### ISSUE TITLE
Can a database be shared between multiple devices?

### ISSUE THREAD

**Issue by EricShapiro** [Nozbe/WatermelonDB#744]
1. Can a single database be shared and sync'd to multiple iOS devices?
It seems to me if device 1 adds a record with id 1 and device 2 adds a record id 1 and then they both sync, there will be a conflict. Should UUIDs be used as recordIDs instead?

2. If multiple devices can be synchronized with a shared database, what happens during sync if devices are running different schema versions? Will data be lost if device1 running schema 1 syncs after device2 running schema 2 syncs, assuming schema 2 has additional columns?

Thanks!

**Comment by radex** [comment]
> Can a single database be shared and sync'd to multiple iOS devices?

each device has its own copy and you need a remote server as the master copy - https://nozbe.github.io/WatermelonDB/Advanced/Sync.html

p2p syncing is not supported, but of course we welcome contributions

> It seems to me if device 1 adds a record with id 1 and device 2 adds a record id 1 and then they both sync, there will be a conflict. Should UUIDs be used as recordIDs instead?

Use Watermelon-generated IDs. They're random, so - no conflicts.

> If multiple devices can be synchronized with a shared database, what happens during sync if devices are running different schema versions? Will data be lost if device1 running schema 1 syncs after device2 running schema 2 syncs, assuming schema 2 has additional columns?

WatermelonDB 0.17 introduced migration syncs aiming at solving exactly this problem: https://nozbe.github.io/WatermelonDB/Advanced/Sync.html -- again, backend support is required
