### ISSUE TITLE
npm install in react-native fails

### ISSUE THREAD

**Issue by Deadarius** [Nozbe/WatermelonDB#745]
Trying to install watermelon in a react-native project:
```
npm i @nozbe/watermelondb --save
```

Getting this error
```
code 128
npm ERR! Command failed: /usr/local/bin/git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'original/LokiJS' in .gitmodules
```

**Comment by fbegue** [comment]
yeah not really going to bother considering this if I can't launch the web example and when I try to install it myself, there's issues with the very first step ffs

**Comment by radex** [comment]
@Deadarius that's rather strange... Have you tried using yarn? Does it work with the previous version of WatermelonDB? Indeed the LokiJS version used changed, but I can't see why it would throw the issue it did

**Comment by PaulPaksGitHub** [comment]
The same error with the npm, but using yarn everything works fine

**Comment by radex** [comment]
One thing that comes to mind: see if `npm cache clean` helps - and does the previous version of WatermelonDB work. No one complained that it didn't, and LokiJS version changed, but I can't see how that's related to a gitmodules error

**Comment by fbegue** [comment]
`npm install`  
works with  
```
"@nozbe/watermelondb": "0.17.0",
"@nozbe/with-observables": "^1.0.0"
```

**Comment by KarolHarumi** [comment]
I had the same issue here. I've just downgraded WatermelonDB from 0.18.0 to 0.17 and worked fine. Thanks @fbegue for the clue

**Comment by harji-singh** [comment]
Same issue I too Have

**Comment by uzaircs** [comment]
Same issue. Downgrading to 0.17 works

`36 verbose stack Error: Command failed: git submodule update -q --init --recursive
36 verbose stack fatal: No url found for submodule path 'original/LokiJS' in .gitmodules
36 verbose stack
36 verbose stack     at ChildProcess.exithandler (child_process.js:294:12)
36 verbose stack     at ChildProcess.emit (events.js:198:13)
36 verbose stack     at maybeClose (internal/child_process.js:982:16)
36 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
37 verbose cwd *****
38 verbose Windows_NT 10.0.18363
39 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@nozbe/watermelondb" "--save" "--verbose"
40 verbose node v10.22.0
41 verbose npm  v6.14.6
42 error code 128
43 error Command failed: git submodule update -q --init --recursive
43 error fatal: No url found for submodule path 'original/LokiJS' in .gitmodules`

**Comment by radex** [comment]
can anyone verify if `0.19.0-1` works for you?

**Comment by uzaircs** [comment]
Getting same error with `0.19.0-1`

``` shell
npm i @nozbe/watermelondb@0.19.0-1 --save -verbose
```
**Error**  
```
npm ERR! code 128
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'original/LokiJS' in .gitmodules
``` 

**Complete Output**

``` shell
npm info it worked if it ends with ok
npm verb cli [ 'C:\\Program Files\\nodejs\\node.exe',
npm verb cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
npm verb cli   'i',
npm verb cli   '@nozbe/watermelondb@0.19.0-1',
npm verb cli   '--save',
npm verb cli   '-verbose' ]
npm info using npm@6.14.6
npm info using node@v10.22.0
npm verb npm-session 8d6d3436b69e28d4
npm http fetch GET 200 https://registry.npmjs.org/@nozbe%2fwatermelondb 3390ms
npm http fetch GET 200 https://registry.npmjs.org/@nozbe/watermelondb/-/watermelondb-0.19.0-1.tgz 7194ms
npm timing stage:loadCurrentTree Completed in 11572ms
npm timing stage:loadIdealTree:cloneCurrentTree Completed in 11ms
npm timing stage:loadIdealTree:loadShrinkwrap Completed in 625ms
npm http fetch GET 200 https://registry.npmjs.org/sql-escape-string 1164ms
npm http fetch GET 200 https://registry.npmjs.org/rxjs-compat 1383ms
npm http fetch GET 200 https://registry.npmjs.org/rambdax 2186ms
npm http fetch GET 200 https://registry.npmjs.org/sql-escape-string/-/sql-escape-string-1.1.0.tgz 1089ms
npm http fetch GET 200 https://registry.npmjs.org/rxjs-compat/-/rxjs-compat-6.6.2.tgz 1116ms
npm http fetch GET 200 https://registry.npmjs.org/rambdax/-/rambdax-2.15.0.tgz 335ms
npm http fetch GET 200 https://registry.npmjs.org/@nozbe%2fsqlite 2629ms
npm http fetch GET 200 https://registry.npmjs.org/@nozbe/sqlite/-/sqlite-3.31.1.tgz 7953ms
npm timing stage:rollbackFailedOptional Completed in 0ms
npm timing stage:runTopLevelLifecycles Completed in 26331ms
npm verb stack Error: Command failed: git submodule update -q --init --recursive
npm verb stack fatal: No url found for submodule path 'original/LokiJS' in .gitmodules
npm verb stack
npm verb stack     at ChildProcess.exithandler (child_process.js:294:12)
npm verb stack     at ChildProcess.emit (events.js:198:13)
npm verb stack     at maybeClose (internal/child_process.js:982:16)
npm verb stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:259:5)
npm verb cwd D:\Apps\**
npm verb Windows_NT 10.0.18363
npm verb argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "i" "@nozbe/watermelondb@0.19.0-1" "--save" "-verbose"
npm verb node v10.22.0
npm verb npm  v6.14.6
npm ERR! code 128
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'original/LokiJS' in .gitmodules
npm ERR!
npm verb exit [ 1, true ]
npm timing npm Completed in 26946ms

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\ss\AppData\Roaming\npm-cache\_logs\2020-08-03T13_34_47_103Z-debug.log
```

**Comment by radex** [comment]
@uzaircs What happens if you `rm package-lock.json` then re-run npm install?

**Comment by uzaircs** [comment]
> @uzaircs What happens if you `rm package-lock.json` then re-run npm install?

Tried it. Getting same error.

```
npm ERR! code 128
npm ERR! Command failed: git submodule update -q --init --recursive
npm ERR! fatal: No url found for submodule path 'original/LokiJS' in .gitmodules
```

Also tried removing `node_modules` and ran `npm cache clean --force`. still getting same issue on `0.19.0-1`

**Comment by pedromvgomes** [comment]
Just confirmed the same. It does work with version 0.17.0 but none of the other options mentioned above worked for me. Striking with 0.17.0 for now

**Comment by radex** [comment]
Honestly, it's a bit of a pain in the butt for me, but I changed 🍉 to point to a NPM-published fork of LokiJS instead of a git commit. This should fix your issue.

@pedromvgomes @uzaircs Can you confirm that versin `0.19.0-3` works fine with NPM?

**Comment by rytyr** [comment]
@radex `npm i @nozbe/watermelondb@0.19.0-3` works fine

**Comment by uzaircs** [comment]
> Honestly, it's a bit of a pain in the butt for me, but I changed 🍉 to point to a NPM-published fork of LokiJS instead of a git commit. This should fix your issue.
> 
> @pedromvgomes @uzaircs Can you confirm that versin `0.19.0-3` works fine with NPM?

Can confirm `npm i @nozbe/watermelondb@0.19.0-3` works fine.

**Comment by radex** [comment]
excellent. closing now.
