### ISSUE TITLE
How to load a relationship in model using a different key field ?

### ISSUE THREAD

**Issue by tugzera** [Nozbe/WatermelonDB#749]
In my model i have the following relation ..

Brand 

static associations = {
    brand_machinery: {type: 'has_many', foreignKey: 'brand_id'},
  };

Machinery 

static associations = {
    brand_machinery: {type: 'has_many', foreignKey: 'machinery_id'},
  };

Brand Relation

@lazy
  machinery = this.collections
    .get('machinery')
    .query(Q.on('brand_machinery', 'brand_id', this.real_id));

I want to get the relationship using a different key filed. 

brand_machinery.brand_id = brand.real_id
brand_machinery.machinery_id = machinery.real_id

---------------------------------------------------------------------------------------------------

There is any method that prevent watermelon from creating the uid id ? 

I have some tables that will not be created on the dipositive and i need use the incremetal id from sql ...

**Comment by falquinho** [comment]
I'm also having trouble with this. Documentation makes clear that any column can be used for an association:
`On the "child" side (comments) you define a belongs_to association, and pass a column name (key) that points to the parent `
From what I understand the only requirement is for the column to have the same name.
I'm getting the error:
`null is not an object (evaluating 'childCollection.query')`
when trying to access the @children field. Any tips?
