### ISSUE TITLE
Non-transactional push endpoint

### ISSUE THREAD

**Issue by pokey** [Nozbe/WatermelonDB#752]
For the following requirement of the [spec](https://nozbe.github.io/WatermelonDB/Advanced/Sync.html#implementing-push-endpoint):
> 7. The push endpoint MUST be fully transactional. If there is an error, all local changes MUST be reverted, and en error code MUST be returned.

What is the worst case scenario if this invariant is violated?  Is the problem just that the server may temporarily be in an inconsistent state, but will heal on next successful sync, or is it worse than that?  If all sub-operations are idempotent, imagine it would just be temporary inconsistent state

Also, I find the wording slightly unclear.  When it says "all local changes MUST be reverted", presumably you mean "all local changes MUST be reverted on the server".  Can't imagine we'd want to revert the local changes locally in this situation

Finally (at risk of making this issue too unfocused), I wonder if it would be possible to indicate action groupings to the sync backend so that it can mirror those as transactions supported by server, so that a partial roll-back is possible.  Probably asking for too much 😊

**Comment by radex** [comment]
> Also, I find the wording slightly unclear. When it says "all local changes MUST be reverted", presumably you mean "all local changes MUST be reverted on the server". Can't imagine we'd want to revert the local changes locally in this situation

Yes, of course. I mean that the changes sent to the server should not be applied to the server at all. Can you please hit Edit here: https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Advanced/Sync.md and make this less confusing?

> Finally (at risk of making this issue too unfocused), I wonder if it would be possible to indicate action groupings to the sync backend so that it can mirror those as transactions supported by server, so that a partial roll-back is possible. Probably asking for too much 😊

What do you mean by `action groupings`?

**Comment by pokey** [comment]
> What do you mean by action groupings?

I mean that it might be useful to know during sync which changes occurred in the same action.  That way maybe the requirement could be relaxed to just say that changes in the same group need to be rolled back if any one in that group fails, rather than all changes needing to be rolled back, which may be challenging if we want to support syncing after longer periods offline.  But maybe that's optimizing for a use case that doesn't really exist.

**Comment by pokey** [comment]
Also curious to hear your thoughts on

> What is the worst case scenario if this invariant is violated? Is the problem just that the server may temporarily be in an inconsistent state, but will heal on next successful sync, or is it worse than that? If all sub-operations are idempotent, imagine it would just be temporary inconsistent state

**Comment by radex** [comment]
> I mean that it might be useful to know during sync which changes occurred in the same action. That way maybe the requirement could be relaxed to just say that changes in the same group need to be rolled back if any one in that group fails, rather than all changes needing to be rolled back,

No, Watermelon doesn't support that. That would be a very big change to implement that successfully, since the database would have to work like version control, and persist all changesets until sync. Certainly very interesting (a git-like database could also sync peer to peer, not just client-server), but very hard.

> But maybe that's optimizing for a use case that doesn't really exist.

I think so. We're running this in production and are not running into much trouble with this approach. Sure, occasionally, sync pushes do fail, but that almost inevitably indicates backend bug, since by design, sync should only fail for: a) transient errors (e.g. there's a conflict to resolve and retry), b) grave inconsistencies that can not possibly resolved. Smaller issues should be fixed up if needed by the sync endpoint so that client can sync.

**Comment by pokey** [comment]
Got it thanks!  All makes sense.  And final question: what is the worst case scenario if the push endpoint is not fully transactional? Is the problem just that the server may temporarily be in an inconsistent state, but will heal on next successful sync, or is it worse than that? If all sub-operations are idempotent, I imagine it would just be temporary inconsistent state

**Comment by radex** [comment]
@pokey I haven't thought through this case hard enough to say with certainty - I analyzed the behavior with this assumption in mind. I _think_ that the server state will be eventually consistent… however, this assumes that the app is written with the assumption of likely inconsistency in mind. If it doesn't, you could end up in a situation where the local app has an object which points to its parent, but the paren't doesn't exist (because the creator didn't successfully push it). That could be a problem. If your backend does any validation or sanitization on the relationships between data, then that will also be a problem.

**Comment by pokey** [comment]
Right yes that makes sense.  Thanks!

**Comment by sebastian-schlecht** [comment]
Hey @radex,

hope that message finds you well. We are currently looking evolving our architecture on the BE which has lots of dependencies on sync. I am curious on your thoughts here:

We think about a distributed system of sorts (micro-services or whatever) and wonder about implications for sync. Of course, transactions are way harder in a distributed system but I'd rather lean on eventual consistency (they often are anyways) as opposed to getting transactionality in there. Do you have any experience in that domain with Watermelon?

**Comment by radex** [comment]
> Of course, transactions are way harder in a distributed system but I'd rather lean on eventual consistency (they often are anyways)

Note that synchronization via WatermelonDB sync is `eventually consistent` already -- you're only theoretically consistent with backend at the moment of successful pull iff there's no conflicts and no local data. 

as opposed to getting transactionality in there. Do you have any experience in that domain with Watermelon?

> We think about a distributed system of sorts (micro-services or whatever) and wonder about implications for sync. 
> Do you have any experience in that domain with Watermelon?

Not really. Doing sync without a single source of truth (a single consistent backend sync endpoint) is going to be very, very difficult to get right. It's easy to build systems like this that are _almost_ right and seem ok in most circumstances, but easily get into subtle corruptions of data.  I'd recommend against this. What we do is we have a single database server instance, and multiple backend app instances. So we can easily scale the backend app, and manage its overhead this way, as long as the database server can handle the load of queries on it. You can go very far with this approach.  Another thing you can do if you worry about scaling is to create independent buckets (e.g. teams) with which you can sync independently - and then maybe you'd have a single shared bucket (e.g. users or other common data), and only have to worry about consistency between that. But I'd avoid p2p-style syncing or syncing with different endpoints that sync with each other, that's risky.
