### ISSUE TITLE
Support Hermes engine 

### ISSUE THREAD

**Issue by binbinla** [Nozbe/WatermelonDB#755]
Hermes comes from react-native 0.60.2 and significantly improves app performance on Android. I would like to know that if WatermelonDB support Hermes engine or not. Thinks.

**Comment by radex** [comment]
@binbinla I don't know. Why are you even asking? Just try it out and see for yourself!

**Comment by keima** [comment]
I curious Hermes supports WatermelonDB or not.

My simple projects works WatermelonDB on Hermes engine.
(So far, async/await, observe updates, CRUD operation is OK)

I consider switch from Realm and WatermelonDB is one of good path for now.
Thanks for maintain great projects.

**Comment by diegolmello** [comment]
Hey.
It does support Hermes.
We use it on our project for a long time.
WatermelonDB is ❤️ !
