### ISSUE TITLE
Relying on `_changed` in change set

### ISSUE THREAD

**Issue by pokey** [Nozbe/WatermelonDB#757]
Can we rely on `_changed` continuing to be part of the `changes` object passed to `pushChanges`?  I see this comment: https://github.com/Nozbe/WatermelonDB/blob/master/src/sync/impl/fetchLocal.js#L41-L43

I was thinking of using it during sync to automatically filter down to the fields that have changed and then passing them to firestore's [`update`](https://firebase.google.com/docs/firestore/manage-data/add-data#update-data) method.  This way updates on the server between pull and push would still end up with client-wins behaviour, albeit implemented server-side.

I think the current setup gives a nice compromise because if Watermelondb were to filter to changed fields before passing to `pushChanges` (as suggested in comment), the `pushChanges` implementation wouldn't be able to see the full object, but passing in `_changed` (as is done today) allows `pushChanges` to filter if it would like to.  Might be worth exposing a method to do the filtering or get the changed column list though so that sync impl isn't expected to directly do a `change["_changed"].split(",")`.

**Comment by radex** [comment]
@pokey From my standpoint, `_changed` being in `changes` is a lazy oversight, and I want to get rid of it, because it unnecessarily increases data size that's pushed over the network

But of course, your use case is legitimate. I think the correct thing to do, if you need `_changed` is to introduce either a flag to `synchronize()`, or a function parameter for doing the filtering.

**Comment by pokey** [comment]
So the problem with adding a function parameter requesting filtering, if I've understood your proposal, is that there are certain fields that I may want.  For example, I'm looking into supporting firestore [subcollections](https://firebase.google.com/docs/firestore/data-model#subcollections), so I'd like for each row to have a `_path` attribute indicating which subcollection it is a part of.  Any ideas how I'd do that, as well as tracking changes, without relying on getting the full object including `_changed`?
