### ISSUE TITLE
Is Watermelon compatible with Expo?

### ISSUE THREAD

**Issue by Cleversou1983** [Nozbe/WatermelonDB#758]
I've successfully installed watermelon via `expo-install`, followed the instructions on the documentation, but couldn't get it working... It gives me the following error message: 
![Captura de Tela 2020-07-11 às 08 17 07](https://user-images.githubusercontent.com/34983085/87222975-f85e0c80-c34e-11ea-8df5-b802bef3cc52.png)

**Comment by radex** [comment]
> Is Watermelon compatible with Expo

No. You need to eject.
