### ISSUE TITLE
Err on attempt to get list of child objects

### ISSUE THREAD

**Issue by Dodotree** [Nozbe/WatermelonDB#76]
The query gets the parent object from db by id. -> MyObjectInstance

MyObjectInstance = await database.collections.get('parentTableName').query(Q.where('id', id)).fetch();

When I try to to get MyObjectInstance.collectionOfAssociated, I get:

Exception: TypeError: Cannot read property 'query' of undefined at MyObjectInstance.get
at MyObjectInstance.remoteFunction (<anonymous>:2:14)]

But it works when I do the query on child Model:

await database.collections.get('childTableName').query(Q.where('parent_id', MyObjectInstance.id)).fetch();

Can you please help me to understand why this is happening? When I use your samples that do calls from UI, everything works as expected, it seems to return list of child objects.

Thank you!

**Comment by radex** [comment]
```
MyObjectInstance = await database.collections.get('parentTableName').query(Q.where('id', id)).fetch();
```

why do you query by ID? The correct API for this is `collection.find(id)`

```
Exception: TypeError: Cannot read property 'query' of undefined at MyObjectInstance.get
at MyObjectInstance.remoteFunction (:2:14)]
```

Like the error says, `database.collections.get('parentTableName')` is undefined. Which means that you either have a typo in the table name, or you forgot to add your new Model to Database constructor (see https://github.com/Nozbe/WatermelonDB/blob/master/docs/Model.md#create-a-model )

**Comment by Dodotree** [comment]
Totally missed inserting model reference into table description. Thank you very much for pointing that out! (Since I was not the only one who somehow missed that, maybe it will help others to stress it out more in the documentation. Because it doesn't give you a clear failure when you create tables and models, only later you have problems with associated queries) Thanks again.

**Comment by radex** [comment]
> Since I was not the only one who somehow missed that, maybe it will help others to stress it out more in the documentation. Because it doesn't give you a clear failure when you create tables and models, only later you have problems with associated queries)

Agreed! You can shoot us a quick pull request with an improved documentation and I'll be happy to merge it in ;) And we could use more sanity checks to show error messages instead of cryptic messages, there's also an Issue explaining how to start working on that if you'd like: https://github.com/Nozbe/WatermelonDB/issues/42
