### ISSUE TITLE
Syncing local data

### ISSUE THREAD

**Issue by horlaarsco** [Nozbe/WatermelonDB#766]
When i create a data locally and sync , sync first run pull and the set a last pulled at it then get pushed, when running pull again it used my last pulled at from former pulling and then the data i created on the server from client get pulled again as a new data and then i get this Warning.

![image](https://user-images.githubusercontent.com/10059733/88060879-b018c880-cb5e-11ea-92a1-2c92a6ff53ec.png)

**Comment by KrisLau** [comment]
Running into this what did you do to fix it?
