### ISSUE TITLE
Couldn't find the binary git

### ISSUE THREAD

**Issue by suxgatov** [Nozbe/WatermelonDB#767]
Running `yarn add @nozbe/watermelondb` results in the named error. 
In some of my tests I tried instaling previous versions, in which I was finally able to install the lib, on version 0.14.1.

Although, I wanted to use the latest version.

Using the --json flag, amoung other logs, there was the following: 
`//...
{"type":"activityTick","data":{"id":0,"name":"@nozbe/watermelondb"}}
{"type":"activityTick","data":{"id":0,"name":"@nozbe/sqlite@3.31.1"}}
{"type":"activityTick","data":{"id":0,"name":"lodash.clonedeep@^4.5.0"}}
{"type":"activityTick","data":{"id":0,"name":"lokijs@git+https://github.com/Nozbe/LokiJS.git#fabe503"}}
{"type":"activityTick","data":{"id":0,"name":"rambdax@2.15.0"}}
{"type":"activityTick","data":{"id":0,"name":"rxjs@^6.2.2"}}
{"type":"activityTick","data":{"id":0,"name":"rxjs-compat@^6.3.2"}}
{"type":"activityTick","data":{"id":0,"name":"sql-escape-string@^1.1.0"}}
{"type":"error","data":"Couldn't find the binary git"}
{"type":"info","data":"Visit \u001b[1mhttps://yarnpkg.com/en/docs/cli/add\u001b[22m for documentation about this command."}`
Maybe a problem with a dependency?
Is there any know fix for this issue? 
Thanks in advance.

**Comment by radex** [comment]
Have you fixed the issue @suxgatov ?

**Comment by suxgatov** [comment]
> Have you fixed the issue @suxgatov ?

After creating this issue I researched a little more to try and find the fix, without any luck.
However, I just tried to build the project again and it just worked. 

I can't tell if I just did something wrong before, because it's the same project, or it just decided to run out of nowhere.
Is there anything I should post or may I close the issue?
