### ISSUE TITLE
error initialising Sqlite adapter

### ISSUE THREAD

**Issue by rishidutt2792** [Nozbe/WatermelonDB#768]
Hi, I am getting an error with the SQLite adapter in android.

I am using react native version 0.62.2.

My index file - 
<img width="676" alt="Screen Shot 2020-07-23 at 9 51 03 AM" src="https://user-images.githubusercontent.com/19925964/88251991-41587e00-ccca-11ea-8511-e38cf479faa3.png">

Error - 
<img width="354" alt="Screen Shot 2020-07-23 at 9 50 30 AM" src="https://user-images.githubusercontent.com/19925964/88251994-44536e80-ccca-11ea-8eb5-233ccf0740c3.png">

**Comment by radex** [comment]
have you read installation docs
