### ISSUE TITLE
Updated is sent as created 

### ISSUE THREAD

**Issue by horlaarsco** [Nozbe/WatermelonDB#769]
When i create.a post and then sync when its updated from the client an d try to sync again it get sent to the backend as created again not updated

**Comment by radex** [comment]
can you explain in full sentences, i don't understand your question

**Comment by horlaarsco** [comment]
I am working on building a sync server for nodejs and mongoDB, so here's the approach im following, I read through the elixir own and decided to build mine.

Step 1: When data is created on the client and I asked to sync , in my sync function I created a pushtimestamp while ill use later, and the pull changes I sent request to my api with the last pulled at so I fetch data from my api , that was updated after the last pulled at and them make sure the result was following the required shape, then on the push changes I send the changed to my api and then I perform a transaction to talk to my database, lastly in the push changes I returned the timestamp at which this was completed. So in my sync function I set the time stamp to the pushtimestamp I created above, then I call the synchronise again passing the pushtimestamp to my timestamp can be updated as the pushtimestamp own so I don’t have to pull data I already have locally

Then when I create data locally and then sync it created , but when I update I get this error

![image](https://user-images.githubusercontent.com/10059733/88356078-8d550280-cd5e-11ea-8052-a1f77d3c1bf7.png)


When I reload the app and then sync again my data is sent to the server as created again not updated so it get cloned on the server

Same data received 3 times as created

![image](https://user-images.githubusercontent.com/10059733/88356126-b07fb200-cd5e-11ea-8623-ee62724742f5.png)
