### ISSUE TITLE
Xcode 12 built iOS app has fatal error on WatermelonDB initialization

### ISSUE THREAD

**Issue by akread** [Nozbe/WatermelonDB#772]
Has anyone else run into any issues running an app with WatermelonDB on iOS 14 build from Xcode 12 Beta? We are preparing our app for iOS 14 and it appears like builds from Xcode 12 do not run. I am not sure if something with sqlite changed in the iOS 14 SDK and I need to add a compile time flag or what? I wanted to see if anyone else was running into issues or if this has been tested by the maintainers.

I have not tested the demo app into the repo yet but I will likely set that up tomorrow to see if the issue persists there. I looked online but could not find any information about changes in Xcode 12 / iOS 14 that might cause this. I am running the app in an iOS 14 simulator. Our app runs on iOS 14 in the wild on physical devices but with builds from Xcode 11 using the iOS 13 SDK.

https://github.com/Nozbe/WatermelonDB/blob/master/native/ios/WatermelonDB/Database.swift#L115 is what causes the crash. I have setup break points and identified that line as the cause.

<img width="1645" alt="Screen Shot 2020-07-27 at 4 56 48 PM" src="https://user-images.githubusercontent.com/6855046/88591800-e789e800-d02a-11ea-8b09-2374d008ca90.png">

`table sqlite_master may not be modified`

I have confirmed, via breakpoints, that the same code flow while building using Xcode 11 / iOS 13 SDK does not crash and runs as expected on iOS 13.

**Comment by akread** [comment]
I tested this on a physical device and I have the same results as the simulator. Xcode 12 built apps on iOS 14 choke when attempting to `try execute("delete from sqlite_master")`. This does not occur on iOS 14 when the app is built using Xcode 11.

I am going to test the example app in this repo on Monday.

Has anyone else successfully built their app with WatermelonDB using Xcode 12?

**Comment by akread** [comment]
I built and ran the example app in this repo on Xcode 12 and it suffers from the exact same crash on launch as I saw on my app. As the example app suffers the same problem, it does not appear to be an integration issue and is easily reproducible for troubleshooting.

This is a critical issue as it prevents us from using Xcode 12 which we need to use to access the new privacy SDKs available on the platform.

**Comment by akread** [comment]
Long story short, 0.16.x fixes this issue for me. I didn't see that update, that is my fault. The example iOS app in this project is using an outdated version of the package which is why that doesn't work properly either.

I am closing this issue although it would be good to have the example app always running the latest version of the package.

For anyone who may stumble upon this in the future:
0.16.x doesn't work with 0.62 of react native with out a patch. see https://github.com/Nozbe/WatermelonDB/issues/691.
0.18.x doesn't compile with out a patch. see https://github.com/Nozbe/WatermelonDB/commit/cd38a8cff7d88a6ad07567db007bb35ed796cb48 which fixes the issue but is only contained in an unreleased version.

I updated to 0.18.x and patched it locally for now. I will update to 0.19.x that contains a fix when it is released.

**Comment by radex** [comment]
Hi, in case someone's still looking for this issue:

You still may encounter this if you're using in-memory database, or (undocumented) JSI adapter. Available workarounds are:

- use the latest version of WatermelonDB
- don't use in-memory-database
- use standard (non-JSI) iOS adapter
- … or compile your app with Xcode 11/targetting iOS 13

I think I found the root cause and I should release a patch fixing it for ALL cases in up to a week or two.
