### ISSUE TITLE
Race condition with _hasPendingUpdate

### ISSUE THREAD

**Issue by pokey** [Nozbe/WatermelonDB#779]
As mentioned in https://github.com/Nozbe/WatermelonDB/blob/d361036dbc2ae384142bf16e044bebf7ae09a21f/src/Database/index.js#L107 it seems like we'd lose an update if SQLite write fails.  Why not reset `_hasPendingUpdate` after write has committed to DB, eg in the same [place](https://github.com/Nozbe/WatermelonDB/blob/d361036dbc2ae384142bf16e044bebf7ae09a21f/src/Collection/index.js#L147) that we reset `_isCommitted` for creates?

**Comment by pokey** [comment]
Hi @radex just wanted to see why you closed this one?

**Comment by radex** [comment]
@pokey Hey, sorry I closed without any comment. 🍉 is not yet resilient enough to handle a situation where a SQLite write fails. So, if it does, having this flag set incorrectly is just the beginning of many problems you'll have. TL;DR: You really want your queries to be _correct_ (at least as far as correct completion goes)

I'm aware of this limitation and have a task to improve this in the future.

**Comment by pokey** [comment]
Ok that makes sense thanks @radex
