### ISSUE TITLE
Is it safe to use _raw?

### ISSUE THREAD

**Issue by williamgurzoni** [Nozbe/WatermelonDB#780]
I don't need to observe changes, as my data is static.
Just wondering if it's safe to use _raw instead of HOC (withObservables).

If not, is there any other way to get the data without HOC?

Thank you.

**Comment by radex** [comment]
No, it's not safe to use `_raw`. Follow this guide: https://nozbe.github.io/WatermelonDB/Model.html and you can access data this way. If you absolutely do not want to use decorators, you can use `._getRaw()`

**Comment by williamgurzoni** [comment]
Thanks for answering @radex, but I tried to use `._getRaw()` but it's not available.
I'll past a code of what I'm trying to do:

`
export const getBlocksById = async (ids) => {
  const data = await blocksCollection.query(Q.where('id_api', Q.oneOf(ids)));
  return data.map(el => el._raw);
};
`
Maybe the `_getRaw()` isn't working because I'm trying to use after a query? Does it make sense?
I'm trying to do this, because I'm replacing part of Redux / Reselect structure for local database, so to keep using the current structure, HOC will not be a good alternative without rewriting.

This is currently working, but my concern is about using in a not expected way, and loose this support in future.

Thanks :)

**Comment by radex** [comment]
OK, but _why_ are you trying to convert the JS object into the raw representation? Why not use the model object as is?

If you absolutely must, reading `record._raw` is safe to do, but you MUST NOT change its contents. There's also no API stability guarantees, so `_raw` may change its name in the future (this would be marked in the changelog)

**Comment by diegolmello** [comment]
We're using `record._raw` all the time to overwrite `id`.
```js
const newRecord = { ... }
yield db.action(async() => {
	await collection.create((r) => {
		r._raw = sanitizedRaw({ id: newRecord.id }, collection.schema);
		Object.assign(r, newRecord);
	});
});
```
https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/sagas/createChannel.js#L49

Do we have a better way to do so?
We can't use sync.
