### ISSUE TITLE
Can't perform update action

### ISSUE THREAD

**Issue by tugzera** [Nozbe/WatermelonDB#783]
async edit(id, params) {
    const item = await this.collections.find(id);
    await database.action(async () => {
      await item.update((post) => {
        post.title = 'Updated title';
      });
    });
    return item.show();
  }

Always when i call the update method i get: 

TypeError: undefined is not an object (evaluating 'columnSchema.type')

I have checked my schema and it works fine on create method.

**Comment by radex** [comment]
no updates in 2 months, assuming it's been fixed
