### ISSUE TITLE
[help] How can i deep query ? 

### ISSUE THREAD

**Issue by shaheem-khanzada** [Nozbe/WatermelonDB#784]
Suppose I have a modal of Projects and each project contain user object I need to query inside user object 
example
`db.collections.get('projects').query(Q.Where('user._id', 'xdowskdkwjcbsl')).fetch();`

**Comment by shaheem-khanzada** [comment]
@radex need your help

**Comment by radex** [comment]
please read the docs

**Comment by shaheem-khanzada** [comment]
@radex I read the docs but unable to find a solution
