### ISSUE TITLE
CNAME

### ISSUE THREAD

**Issue by jrounsav** [Nozbe/WatermelonDB#785]
borked the github pages 😉 

```
This site can’t be reached
watermelondb.dev’s server IP address could not be found.
DNS_PROBE_FINISHED_NXDOMAIN
```

Thank you for the ongoing improvements!
Would love to contribute. Maybe Cocoapods?

**Comment by nikhilbatra789** [comment]
Yes. It is broken. Can someone fix this urgently? It's really hard to find the scattered documentation.

**Comment by radex** [comment]
Hi, I messed something up - I reverted to the old domain for now

**Comment by nikhilbatra789** [comment]
Now its showing

Attackers might be trying to steal your information from watermelondb.dev (for example, passwords, messages, or credit cards). Learn more
NET::ERR_CERT_COMMON_NAME_INVALID

**Comment by radex** [comment]
@nikhilbatra789 just use this address: https://nozbe.github.io/WatermelonDB/ - you might need to clear dns and browser caches
