### ISSUE TITLE
Require Cycles

### ISSUE THREAD

**Issue by sators** [Nozbe/WatermelonDB#786]
Similarly to https://github.com/Nozbe/WatermelonDB/issues/71

On v0.19.0-3, I receive the following React Native warning when using the DatabaseProvider component:

> Require cycle: node_modules/@nozbe/watermelondb/DatabaseProvider/index.js -> node_modules/@nozbe/watermelondb/DatabaseProvider/withDatabase.js -> index.js

> Require cycles are allowed, but can result in uninitialized values.  Consider refactoring to remove the need for a cycle.

**Comment by radex** [comment]
Hi @sators ! Good catch — wouldn't you like to contribute to WatermelonDB? You should be able to fix the issue very easily, then send a PR to fix this warning

**Comment by fabianmedina09** [comment]
why is this happening, and how could the fix be made?

**Comment by gmonte** [comment]
Hi guys!

@radex I opened a pull request with this fix. I just create a separate file to DialogContext.

https://github.com/Nozbe/WatermelonDB/pull/816
