### ISSUE TITLE
just can't seem to get watermelonDb going from empty

### ISSUE THREAD

**Issue by andrewlorenz** [Nozbe/WatermelonDB#787]
am I doing something wrong here?  I'm following the documentation but it seems I can't query a (non-existent) collection from empty, and yet I also can't insert a test row into the collection either ?!
```
const database = new Database({
  adapter : new SQLiteAdapter({
    dbName : 'TestData',
    schema : mySchema,
  }),
  modelClasses   : dbModels,
  actionsEnabled : true,
});

const initialiseData = async() => {
  const trackers = database.collections.get('trackers');
  let currentTrackers = null;
  try {
    currentTrackers = await trackers.query(Q.where('tracker_name', 'messages'));
    console.log('currentTrackers', currentTrackers);
  } catch(error) {
    console.log('error querying messages - ', error);
  }
  if (!currentTrackers) {
    await database.action(async() => {
      try {
        const tester = await trackers.create(tracker => {
          tracker.tracker_name = 'messages';
        });
        console.log('tester', tester);
      } catch(error) {
        console.log('error in create - ', error);
      }
    });
  }
});
```
but when I call initialiseData(), I get:
* error querying messages - no such table: trackers (code 1 SQLITE_ERROR)
ok - that's to be expected, after all that table hasn't been created yet.  But then the create fails too:
* error in create - no such table: trackers (code 1 SQLITE_ERROR)

If that's the case, how do you create the table - besides defining a schema, a model, and passing it to the database object ?!
What am I doing wrong - because I can't see anything in the documentation which says another step is required

**Comment by radex** [comment]
> If that's the case, how do you create the table - besides defining a schema, a model, and passing it to the database object ?!
What am I doing wrong - because I can't see anything in the documentation which says another step is required

You create a table by defining a schema. I bet you added a new table but didn't bump the schema version, didn't you? 🍉 won't know that it needs to create/delete tables then

**Comment by andrewlorenz** [comment]
Thank you radex, that's exactly the problem.  I'm afraid I'm a newbie to watermelon and just didn't appreciate how the version numbering was affecting me.  Hopefully this ticket will help others who hit the same wall.

**Comment by radex** [comment]
@andrewlorenz It would be kind of you to contribute a few words to the documentation — you know what confused you, and so you're the best person to add the missing sentence or word to explain to newcomers how this works. https://github.com/Nozbe/WatermelonDB/tree/master/docs-master — you can just hit edit in the browser and send a PR this way

**Comment by andrewlorenz** [comment]
sure @radex I will do that for the project - I also have run into an issue on a query with no such column for _status (which I have worked out is the status field for optional sync) so I will include a doc update for that gotcha too once I have understood it.
