### ISSUE TITLE
Why is there a _raw attribute on the model?

### ISSUE THREAD

**Issue by gliesche** [Nozbe/WatermelonDB#788]
Can you elaborate what the _raw attribute (RawModel) is used for exactly? I understand it as a JSON representation of the model. Is there any logic applied to this attribute, e.g. when updating a model locally on the client?

I am using this attribute to save the server representation, which also holds a unique id, which is need for custom syncing. Do you see a problem in that?

**Comment by radex** [comment]
`_raw` is a raw JSON representation of the model - before the high-level JS magic with @field, @date, etc. are applied. When you update the model, `_raw` is also updated.

It should be safe (but I make no guarantees about the future — it's not meant to be exposed as an API, it's an internal detail. But I'll note it in the CHANGELOG if the semantics/name/anything changes there) to read from `_raw`. However, it's not safe to write to `_raw` (you have to understand some Watermelon internals to do this correctly).

**Comment by gliesche** [comment]
@radex thanks a lot. 

Implementing my own sync logic, will I even need the `_raw` attribute? I will have to add columns for a models attribute (let's say `title` for a post. Anyways and I can read/write to these columns, does that make sense?

**Comment by radex** [comment]
> If I understand it right, watermelonDB will internally update the json representation of the _raw attribute by changing the title attribute in this json internally, is that correct?

yes

> I can read/write to this column so I do not need raw, does that make sense?

you don't _need_ it, no
