### ISSUE TITLE
Have you put any thought into recursive queries? (Or are they available and I missed them?)

### ISSUE THREAD

**Issue by jessep** [Nozbe/WatermelonDB#789]
We (workflowy.com) have a data model that requires/involves recursion. Doing it on the app side and going back and forth to the DB would be very slow. Have you thought about enabling recursive queries? If not, would you be open to the idea?

**Comment by radex** [comment]
@jessep can you define (or give an example) on what precisely you mean by `recursive` queries?

**Comment by jessep** [comment]
Yes, happily. There are some good examples of these types of queries you
can do in SQLite on this page:
https://sqlite.org/lang_with.html#hierarchical_query_examples

I can also give some examples from our situation if you’d like.

**Comment by jessep** [comment]
Just seeing the whole raw queries discussion ... this would probably fall under that, and my sense from those discussions is we might be better served by a simpler direct to sqlite adapter, because almost everything we'd need to do would involve ordering, limiting, etc..

**Comment by radex** [comment]
Hi. Have you read the docs? As long as a query returns a list of records from one table, you can query using SQL: https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Query.md#unsafe-raw-queries
