### ISSUE TITLE
Is it okay to use WatermelonDB with MobX?

### ISSUE THREAD

**Issue by sbtly** [Nozbe/WatermelonDB#79]
I'm using MobX in my project.
After reading the docs, I think I might have to choose between MobX + some other DB(eg. pouchDB) or WatermelonDB, since both MobX and WatermelonDB will automatically update components with 'observing' feature.
Is this right? or is it okay to use MobX and WatermelonDB together?

Also, I use MobX's 'computed' feature a lot in my project.
For example, there's **@observable myColor**, and whenever user changes **myColor**, 
**@computed myColorMatrixValue** have to be calculated automatically. (I want to persist **myColorMatrixValue**, also.)

Is there a way to do this in WatermelonDB?

**Comment by radex** [comment]
Sure, I think using MobX as a local state management system + WatermelonDB as the database should work just fine.

**Comment by sbtly** [comment]
Interesting!
But wouldn't it cause component to be updated twice every time some value changes?

for example, 
```
// mobX part
@observable myColor

// watermelon part
...color.value = myColor...
```

user changes **@observable myColor** -> 
mobX will update related component -> 
mobX's changed observable value will update watermelon's **color.value** ->  
watermelon will update related component **again**

This is what I think might happen when using MobX and WatermelonDB together.
Is this wrong or is this perfectly okay?

**Comment by radex** [comment]
I don't get it. Why do you want to use both MobX and Watermelon to manage the same data? I get using MobX as local-state-only library, but why go through MobX to modify persistent data?

**Comment by sbtly** [comment]
oh, now I see.
This is my first time trying backend myself.
So I got all mixed up about how to deal with data.

I'll try using MobX + WatermelonDB then!
Thanks for the quick reply :)

**Comment by awgv** [comment]
This thread is the first search result, so I’ll post it here. Unless I’m missing something—`withObservables()` can’t be combined with `observer()` HOC—when you have multiple HOCs, you’re supposed to apply `observer()` first, but `observer()` memoizes components, and you should memoize after `withObservables()`. If you apply `observer()` last, an error is thrown; if you apply `observer()` first, everything is now memoized, and changes to `WatermelonDB` models don’t rerender components. As far as I can say, there’s no way to work around this, at least not in a way that’s mentally tolerable.

I don’t know how any of this work, but perhaps, it’ll become possible when and if `WatermelonDB` switches to a hook. I’d also like someone to confirm this, and until someone does, it would be best to take this message with a grain of salt and set up a basic `WatermelonDB`+`MobX` project to see the issues for yourself.
