### ISSUE TITLE
Is Swift really required?

### ISSUE THREAD

**Issue by ivanmoskalev** [Nozbe/WatermelonDB#790]
Hello! First off, thanks for the awesome library. Really liked it.
 
Unfortunately, for our team, the overhead for including Swift runtime in the app bundle is rather punishing. (Since we deploy to older OSes that don't have ABI-compatible versions of the runtime included on the device.) So I wrote a patch that replaced Swift portions with ~good~ ol' Obj-C. 

I can publish the patch as a PR to this repository if you are interested. I kinda see how Swift helps with code ergonomics, but it also introduces some complexity (and an additional integration step).

**Comment by radex** [comment]
Hi. The end game for native bits of WatermelonDB is shared C++ with Android (this is already available under jsi flag, but it's not yet documented) -- then I'll be able to remove pretty much all of Swift, I think. I don't think I want to merge a patch replacing Swift with ObjC, but it would be very kind of you to publish it anyway, as I'm sure there will be someone in the open source who will be able to benefit from it

**Comment by ivanmoskalev** [comment]
@radex Thanks! I'll publish it just as a fork then.

**Comment by radex** [comment]
@ivanmoskalev do let me know once published
