### ISSUE TITLE
How to attach a single record to a React screen

### ISSUE THREAD

**Issue by jrounsav** [Nozbe/WatermelonDB#792]
The docs are pretty clear on pulling collections & then rendering that data across a list of subcomponents, but I am having trouble querying & rendering a single record on a screen. What is the recommended method for this?

In my case a user has a list of contacts which are rendered out, and when a contact is clicked we navigate to a screen where we display all info for that single contact.

I am currently achieving the desired effect with:

```
const mapObservablesToProps = withObservables(
  ['route'],
  ({ database, route }) => {
    const kid = route?.params?.kid;

    const queries = buildQueries({ kid }); // Q.where('kid', kid)

    const contact = database.collections.get('Contacts').query(...queries);

    return {
      contact,
    };
  },
)
```

and then using `contact[0]` in the wrapped screen.
Seems uncouth 😄 

kid is our own ID, as opposed to the ones watermelon spins up.

**Comment by radex** [comment]
The idiomatic way is to use `collection.findAndObserve(id)`, but since you're using your own ids, a query is best you can do, alas.

**Comment by jrounsav** [comment]
Ahh ok, thank you

I've seen a few discussions on overriding the raw id but got the impression that doing so could mess with some functionality. Can I safely set that value to our id when creating a new record?

**Comment by jrounsav** [comment]
kid is starting to look like an artifact from our realm implementation. Dropping that in favor of the melon ID and leveraging findAndObserve.

Thanks again!

**Comment by radex** [comment]
@jrounsav You can use `collection.prepareCreateFromDirtyRaw({ id: foo, a: z, b: y })` and then pass it to `db.batch()`. That's safe. You can do `record._raw.id = foo`, but ONLY in a create/prepareCreate, and I make no guarantees about stability of this API
