### ISSUE TITLE
Watermelon db won't install with RN 0.63 

### ISSUE THREAD

**Issue by PritishSawant** [Nozbe/WatermelonDB#794]
I have installed following to my package json

```
 "@nozbe/watermelondb": "^0.19.0",
   "@nozbe/with-observables": "^1.0.5",
```

I have added .babelrc file with following data
```
{
  "presets": ["module:metro-react-native-babel-preset"],
  "plugins": [["@babel/plugin-proposal-decorators", { "legacy": true }]]
}
```

I have already enabled swift support in my iOS project.
RN 0.63 supports auto linking so when I do `pod install `in iOS folder I get following error 

`The Swift pod `WatermelonDB` depends upon `React-jsi`, which does not define modules. To opt into those targets generating module maps (which is necessary to import them from Swift when building as static libraries), you may set `use_modular_headers!` globally in your Podfile, or specify `:modular_headers => true` for particular dependencies.`

I tried adding following in my Podfile as well

![Screenshot 2020-08-24 at 5 44 28 PM](https://user-images.githubusercontent.com/24708929/91043577-77728000-e631-11ea-9ecf-76c0fc2871bf.png)

but still getting same issue. Are the docs updated for RN 0.63

**Comment by Arthurneres** [comment]
That worked for me
```
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'ProjectName' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'


  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
  end
end
```

**Comment by PritishSawant** [comment]
@Arthurneres  
![Screenshot 2020-09-30 at 8 39 55 AM](https://user-images.githubusercontent.com/24708929/94638882-85828300-02f8-11eb-862b-252c3c6a2012.png)

Here is my pod file

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'Leeao' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi', :modular_headers => true
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  pod 'GoogleMLKit/Translate'
  pod 'GoogleMLKit/LanguageID'
  
  

  use_react_native!(:path => config["reactNativePath"])


  target 'LeeaoTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  post_install do |installer|
    flipper_post_install(installer)
      installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
          config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
        end
      end
  end
end

target 'ShareExtension' do
  use_react_native!

  pod 'RNShareMenu', :path => '../node_modules/react-native-share-menu'
  # Manually link packages here to keep your extension bundle size minimal
end

target 'Leeao-tvOS' do
  # Pods for Leeao-tvOS

  target 'Leeao-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end

I am still facing the issue
