### ISSUE TITLE
[Question] [iOS] Sharing database across targets

### ISSUE THREAD

**Issue by thiagobrez** [Nozbe/WatermelonDB#799]
Hi!

Is sharing the database across Xcode targets something possible? I've created a Share Extension target and wanted to use the same db as my main target. I've sucessfully set up Watermelon, but when querying for records the collections exist but are empty. Maybe I'm missing something? Already tried exporting the Database and Adapter instances as singletons, with no luck. It's worth noting that I'm using two separate DatabaseProviders.

**Comment by radex** [comment]
you need to set up db path to be within a shared container.

**Comment by thiagobrez** [comment]
Ok! Appreciate your quick response. But is this something I'll have to write in Watermelon files or the Extension files? Looking into it, my targets are already in the same App Group and setting the shared container seems fairly easy, but I'm kind of lost where to start. Could you point me in the right direction?

Anyway, thanks for your help!

**Comment by radex** [comment]
@thiagobrez I'll try my best to help you with this, if you agree to write it up nicely in https://github.com/Nozbe/WatermelonDB/tree/master/docs for others to see

**Comment by thiagobrez** [comment]
@radex For sure! I'd love to contribute

**Comment by radex** [comment]
Okay:

1. You need to get an URL for the app group:

```swift
FileManager.default.containerURL(forSecurityApplicationGroupIdentifier: "group.MY-GROUP_ID").appendingPathComponent("MY-APP.db")
```

(you need to generate an app group id via apple developer site; in Obj-C, start typing NSFileManager, and follow autocompletions and you'll figure it out)

2. You need to pass this URL to React Native land via a Native Module:

```swift
@objc(constantsToExport)
    var constantsToExport: NSDictionary {
        return [
            "databasePath": databaseUrl.path,
        ]
    }
```

see this guide for making a native module + ObjC equivalent: https://reactnative.dev/docs/native-modules-ios#exporting-constants

3. when initializing DB from JS, use:

```js
  return new SQLiteAdapter({
    // Use db in app group folder on iOS, standard folder on Android
    dbName: platform.isiOS ? NativeModules.MyAppPlugin.databasePath : 'nozbe',
    // ... rest of parameters
  })
```

looking forward to that mini-guide more nicely explained than this!

**Comment by thiagobrez** [comment]
Perfect! I'll start digging into this in a few hours and once I get it working will open a PR into the docs so we can review and discuss.

**Comment by diegolmello** [comment]
Hey! :)
Here's how we do: https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L30
I hope it helps.
Thanks!

**Comment by thiagobrez** [comment]
I can confirm this works, such a simple and useful snippet, thanks @diegolmello!

What do you think @radex ? I understand that maybe you don't want to introduce a dependency on `rn-fetch-blob`, and if that's the case I can continue on the idea of doing it native-side, but I think that the probabilities are that an advanced user that requires the db across multiple targets is already using an FS manager.

If we continue with this, I can see the guide basically explaining the following:
* Setting up an App Group
* Setting up dbName with appGroupPath (diego's snippet)
* Querying db on the new target

**Comment by thiagobrez** [comment]
@diegolmello the only issue I have is that `RNFetchBlob.fs.syncPathAppGroup` breaks Chrome debugging with `Invariant Violation: Calling synchronous methods on native modules is not supported on Chrome`, but I'm on RN 0.61.5. I see that you guys are using 0.63.0, is this an issue too?

**Comment by djorkaeffalexandre** [comment]
@thiagobrez yes, that is an issue for us too, we're using Reactotron to debug our app, if you use something like [Radex suggest](https://github.com/Nozbe/WatermelonDB/issues/799#issuecomment-682698310), a constant, it'll be better and don't break anything, for us it's not possible, since our app can be "whitelabeled" and have constants on native side can be a problem for people that want to do a whitelabel of our app without much native knowledge.

**Comment by radex** [comment]
@thiagobrez Sure, that will absolutely work, too! Thanks @diegolmello for sharing. I prefer my method for production work, because it's (to me, someone who knows native iOS development) simpler and more reliable, but I agree that Diego's solution is much more approachable to newcomers. 

```
If we continue with this, I can see the guide basically explaining the following:

Setting up an App Group
Setting up dbName with appGroupPath (diego's snippet)
Querying db on the new target
```

sounds great!

**Comment by diegolmello** [comment]
I'd like to get Chrome debug back, if that's the issue 😛

**Comment by thiagobrez** [comment]
Great! Thanks guys. I'll be investigating into exposing this constant with your suggestions because I'm very interested in learning more from native ios, and I really don't like the idea of breaking chrome debugging. Maybe we can put both options (native solution vs JS solution) in the docs, with it's pros and cons.

**Comment by djorkaeffalexandre** [comment]
@thiagobrez you can check [this commit](https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2439/commits/45d8fbba50bc1e9f98b8f14ba773745035f7a50b) to see how we did what radex suggest, now chrome debugging get back. :)

**Comment by thiagobrez** [comment]
Nice @djorkaeffalexandre, appreciate so much! So as this is basically done, I'll be opening the PR to the docs this week still. Sorry for the lateness, this week's being very busy.

**Comment by jsvde** [comment]
I'm successfully using the same database across my main app and share extension. However If I add an item to any table from the share menu and go back to the main app, I do not see the added item. Even if I add new items to the same collection from the main app, they appear instantly. Only when I force the app to reload the js bundle I see all items, the ones added from the app and the item added from the share extension. Is there any way to force the database to "refresh" when the app resumes to be used in the foreground?
