### ISSUE TITLE
Wrong path to MainApplication.java in docs

### ISSUE THREAD

**Issue by fletling** [Nozbe/WatermelonDB#8]
quickly jotting this down: 

in https://github.com/Nozbe/WatermelonDB/blob/master/docs/Installation.md there's 

> And finally, in android/src/main/java/{YOUR_APP_PACKAGE}/MainApplication.java, add:

The path here is wrong, it's supposed to be `android/app/src/main/java/...`

**Comment by radex** [comment]
Do you mind sending a quick pull request? You can do it from the browser :)
