### ISSUE TITLE
create inside model  ("static method") 

### ISSUE THREAD

**Issue by andrewlorenz** [Nozbe/WatermelonDB#800]
following on from issue #224 , I'm finding myself in the same position - I'd really like to have the code that adds a message to my database as a model method, but find I can't do either this:

```
export default class Message extends Model {
  // fields definition
  @action async addNew(msg) {
    await this.create(message => { ... });
  }
}
```
obviously - "this" has the wrong context
but I also can't do this:
```
export default class Message extends Model {
  // fields definition
  @action async addNew(msg) {
    await this.collections.get('messages').create(message => { ... });
  }
}
```
though the documentation says 
* Although you can .create() and .update() records anywhere in your app, we recommend defining explicit Actions to encapsulate all ways to make changes.
and
* You can use this.collections to access Database.collections

All the examples provided show a create of a record in another (related) collection not the model itself (which doesn't help, and I'll push a doc PR once I have a full understanding of how watermelon is working)

**Comment by andrewlorenz** [comment]
ps - I do have this working outside of the model:
```
  const msgCollection = database.collections.get('messages');
  await database.action(async() => {
    await msgCollection.create(message => { ... });
  });
```
its just that it would be so much better if it could be encapsulated inside the model itself - like mongoose allows you define statics and methods.

**Comment by ortonomy** [comment]
Why was this closed? The documentation is unhelpful and only talks about methods on relations or doing work on single records. Ok, this isn't meant to be a full ORM, but I don't get why there isn't a provision for defining (I come from a ruby background) things like scopes such as active record or even eloquent from laravel and PHP.

Even the 'quickest way to make a query is using `@children`' (https://nozbe.github.io/WatermelonDB/Query.html#children) is frankly bizarre to me. 

Ugh, yeah, it's the quickest way to get a reltion.

But what about scoped queries?

```
class MyModel extends Model {
 @scope last30Minutes(collection) {
  return await collection.query(Q.where(...))
  } 
}
```

etc

Right now, I'm having to write a JS file with a bunch of function elsewher, away from my models, with all of my scoped queries, which feels a little bonkers

**Comment by radex** [comment]
@ortonomy You seem annoyed. This is open source - don't pour out your frustration asking why the community isn't doing something for you, ask what *you* can do for the community ;) 

I'm not familiar with `scoped query` nomenclature - I assume you mean queries that refer to the entire collection, not a particular record? I'm of course not against having a nice API for collection-level queries and actions, but I haven't come up with a design that I'd be happy with, and I don't really need it myself (the schema in my app is such that pretty much every record has a parent, so it's natural to put relevant queries and actions in the parent). I think the latest thread on this topic is #1010.

If you can come up (or even better, implement) a design that makes sense for the rest of 🍉db, that would be awesome!
