### ISSUE TITLE
how run action as transaction

### ISSUE THREAD

**Issue by genie09** [Nozbe/WatermelonDB#807]
Hi. I'm using WatermelonDB as a chat history. 

I want to have a unique msg on my database. So I fetch chat_msg to check if same msg_id is exist.
And if not exist, I create a new record.

But the problem is, between the query, and create statement, context switching happens.
so, if same msgs comes from socket within a very tiny moment, WatermelonDB cannot check the record.

It works like

--timeline------------------------------------->
-> action1[query..............................create]
__________________-> action2[query.......................create]

How can I make like followoing?

-> action1[query............................create]
___________________________________________-> action2[query.......................create]

```
      const db = DatabaseService.database;
      const c = db.collections.get('chat_history');
      await db.action(async action => {
          try {
            // let record = await action.subAction(() => c.query(Q.where('text_id',msg.msg_id)).fetch());  
            let record = await c.query(Q.where('text_id',msg.msg_id)).fetch();  
            console.log(`[LENGTH]${record.length}`);
            if (record.length === 0) exist = false;
          } catch (e) {
            console.log(`[QUERY_SUBACTION_ERROR]${e}`);
          }
          if (!exist) {
            let newRecord = await action.subAction(()=>c.create(r => {
                r.trade_id = msg.trade_id;
                r.text_id = msg.msg_id;
                r.text = msg.text;
            }));
            return newRecord;
          }
        });
```

**Comment by radex** [comment]
Hi. Use `database.batch()` to ensure transactionality
