### ISSUE TITLE
Help sorting by joined table column

### ISSUE THREAD

**Issue by genesy** [Nozbe/WatermelonDB#817]
I have a table for translations and want to sort by the translation.

I can't figure out how to query to join the translation table and sort by the column of that table. 

table 1
```
+----+-------+
| id | name  |
+----+-------+
| 1  | chair |
+----+-------+
```
table 2
```
+----+-------------+
| id | translation |
+----+-------------+
| 1  | silla       |
+----+-------------+
```

the ids are associated with each other but i'm not sure how to query the first table so that it joins and sorts by table2. is this possible?

also
```
// Full syntax:
commentCollection.query(
  Q.on('posts', Q.where('author_id', john.id)),
)
```
how would I do Q.where('author_id', comment.author_id) here instead of a static id? where comment is the row the query is checking

**Comment by radex** [comment]
@genesy hey, have you figured it out?

**Comment by genesy** [comment]
@radex nope. I gave up lol
