### ISSUE TITLE
How to query by date (created_at)?

### ISSUE THREAD

**Issue by uellpalma** [Nozbe/WatermelonDB#820]
this is my code, but not work.
return 0 rows.

```
collection.unsafeFetchRecordsWithSQL(
 `select * from shoppings where strftime('%Y', created_at) = 2020`
)
```

**Comment by diegolmello** [comment]
```js
collection.query(
	Q.where('created_at', Q.gte('2020-01-01'))
)
```

**Comment by uellpalma** [comment]
@diegolmello thanks for you answer, but it don't worked with timestamp date 😕

**Comment by radex** [comment]
@uellpalma What @diegolmello suggested, but instead of passing text representation of 2020-01-01, transform that into JavaScript timestamps (ms-resolutioin unix timestamp)

**Comment by uellpalma** [comment]
Thanks @diegolmello and @radex, i got make work through this code.

```
collection.query(
	Q.and(
		Q.where('created_at', Q.gt(new Date('2020-01-01').getTime())),
		Q.where('created_at', Q.lt(new Date('2021-01-01').getTime()))
	)
)
```
