### ISSUE TITLE
Migration issue on release mode

### ISSUE THREAD

**Issue by diegolmello** [Nozbe/WatermelonDB#821]
Hey!
I've been trying to fix this issue for a couple of days now.
We're receiving lots of migrations (see error below) on release mode.
Migrations are properly implemented and do work on debug mode.
It happens when the user is logged in (db has data) and the app is updated.
I've been trying to find the root cause this whole week, but no luck.
It happens both on Android and iOS.
I appreciate some help.
Thanks.

```
WatermelonDB: 0.18.0 and 0.19.0
RN: 0.63.1
synchronous: false
jsi: false
```

```
Error no such column: enterprise_modules (code 1 SQLITE_ERROR): , while compiling: update "servers" set "id"=?, "_status"=?, "_changed"=?, "name"=?, "icon_url"=?, "use_real_name"=?, "file_upload_media_type_white_list"=?, "file_upload_max_file_size"=?, "rooms_updated_at"=?, "version"=?, "last_local_authenticated_session"=?, "auto_lock"=?, "auto_lock_time"=?, "biometry"=?, "unique_id"=?, "enterprise_modules"=?, "e2e_enable"=? where "id" is ? 
    unknown or: no such column: enterprise_modules
    node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:103:50 anonymous
    native apply
    node_modules/@nozbe/watermelondb/adapters/sqlite/index.js:113:51 anonymous
    node_modules/@nozbe/watermelondb/adapters/sqlite/index.js:409:23 anonymous
    node_modules/@nozbe/watermelondb/adapters/compat.js:60:38 anonymous
    node_modules/@nozbe/watermelondb/utils/fp/Result/index.js:13:4 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:45:4 c
    node_modules/react-native/node_modules/promise/setimmediate/core.js:200:12 X
    node_modules/react-native/node_modules/promise/setimmediate/core.js:66:2 _
    node_modules/@nozbe/watermelondb/utils/fp/Result/index.js:12:13 anonymous
    node_modules/@nozbe/watermelondb/adapters/compat.js:59:23 anonymous
    node_modules/@nozbe/watermelondb/Database/index.js:133:42 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:45:4 c
    node_modules/react-native/node_modules/promise/setimmediate/core.js:200:12 X
    node_modules/react-native/node_modules/promise/setimmediate/core.js:66:2 _
    node_modules/@nozbe/watermelondb/Database/index.js:71:15 anonymous
    node_modules/@nozbe/watermelondb/Database/index.js:78:28 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:45:4 c
    node_modules/react-native/node_modules/promise/setimmediate/core.js:200:12 X
    node_modules/react-native/node_modules/promise/setimmediate/core.js:66:2 _
    node_modules/@nozbe/watermelondb/Database/index.js:71:15 anonymous
    node_modules/@nozbe/watermelondb/Model/index.js:77:54 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:45:4 c
    node_modules/react-native/node_modules/promise/setimmediate/core.js:200:12 X
    node_modules/react-native/node_modules/promise/setimmediate/core.js:66:2 _
    node_modules/@nozbe/watermelondb/Model/index.js:73:15 anonymous
    app/lib/methods/enterpriseModules.js:39:19 anonymous
    native call
    node_modules/regenerator-runtime/runtime.js:45:39 p
    node_modules/regenerator-runtime/runtime.js:274:21 anonymous
    node_modules/regenerator-runtime/runtime.js:97:20 anonymous
    native call
    node_modules/regenerator-runtime/runtime.js:45:39 p
    node_modules/regenerator-runtime/runtime.js:135:19 o
    node_modules/regenerator-runtime/runtime.js:170:10 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:45:4 c
    node_modules/react-native/node_modules/promise/setimmediate/core.js:200:12 X
    node_modules/react-native/node_modules/promise/setimmediate/core.js:66:2 _
    node_modules/regenerator-runtime/runtime.js:169:19 h
    node_modules/regenerator-runtime/runtime.js:192:12 anonymous
    node_modules/regenerator-runtime/runtime.js:97:20 anonymous
    node_modules/regenerator-runtime/runtime.js:219:13 anonymous
    app/lib/methods/enterpriseModules.js:38:28 anonymous
    node_modules/@nozbe/watermelondb/Database/ActionQueue.js:105:22 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:45:4 c
    node_modules/react-native/node_modules/promise/setimmediate/core.js:200:12 X
    node_modules/react-native/node_modules/promise/setimmediate/core.js:66:2 _
    node_modules/@nozbe/watermelondb/Database/ActionQueue.js:69:15 anonymous
    node_modules/@nozbe/watermelondb/Database/ActionQueue.js:53:14 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:45:4 c
    node_modules/react-native/node_modules/promise/setimmediate/core.js:200:12 X
    node_modules/react-native/node_modules/promise/setimmediate/core.js:66:2 _
    node_modules/@nozbe/watermelondb/Database/ActionQueue.js:33:15 anonymous
    node_modules/@nozbe/watermelondb/Database/index.js:171:29 anonymous
    app/lib/methods/enterpriseModules.js:38:21 anonymous
    native call
    node_modules/regenerator-runtime/runtime.js:45:39 p
    node_modules/regenerator-runtime/runtime.js:274:21 anonymous
    node_modules/regenerator-runtime/runtime.js:97:20 anonymous
    native call
    node_modules/regenerator-runtime/runtime.js:45:39 p
    node_modules/regenerator-runtime/runtime.js:135:19 o
    node_modules/regenerator-runtime/runtime.js:145:12 anonymous
    node_modules/react-native/node_modules/promise/setimmediate/core.js:37:11 f
    node_modules/react-native/node_modules/promise/setimmediate/core.js:123:14 anonymous
    native apply
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:274:17 anonymous
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:130:6 x
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:181:4 y
    node_modules/react-native/Libraries/Core/Timers/JSTimers.js:441:11 callImmediates
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:387:11 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:135:11 anonymous
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:364:8 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:134:9 value
    node_modules/react-native/Libraries/BatchedBridge/MessageQueue.js:112:16 value
```

**Comment by radex** [comment]
@diegolmello can you link me to the migrations and schema files?

**Comment by diegolmello** [comment]
@radex Sure.
[Model](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/model/Server.js#L31), [Schema](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/schema/servers.js#L34), [Migration](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/model/serversMigrations.js#L47)

**Comment by diegolmello** [comment]
I managed to reproduce on 0.16.2, so it's not an update thing.
The issue persists though.
I'll update this issue when I figure it out.

**Comment by diegolmello** [comment]
I can't reproduce it on debug and it's making me nuts.

**Comment by radex** [comment]
by debug you mean native compilation mode? or are you using chrome debugger?

**Comment by diegolmello** [comment]
Yeah, I wasn't able to reproduce the error without building it on release mode.

**Comment by radex** [comment]
Are you running release mode both in native and JS code?

**Comment by diegolmello** [comment]
Tricky question. I'm not sure I've got it right.
I'm building an apk with `./gradlew assembleRelease` (not `bundle` just to be easier to install on my device).
We use Hermes.

**Comment by diegolmello** [comment]
@radex Does migrations run instantly or they take a while?
That `update` above happens immediately after the app is resumed and it looks like migrations didn't finish running yet.

Here are the migrations being executed:
```
"alter table \"servers\" add \"enterprise_modules\";
update \"servers\" set \"enterprise_modules\" = null;
alter table \"users\" add \"login_email_password\";
update \"users\" set \"login_email_password\" = null;
alter table \"servers\" add \"e2e_enable\";
update \"servers\" set \"e2e_enable\" = null;
create table \"servers_history\" (\"id\" primary key, \"_changed\", \"_status\", \"url\", \"username\", \"updated_at\");
create index \"servers_history_url\" on \"servers_history\" (\"url\");
create index \"servers_history__status\" on \"servers_history\" (\"_status\");"
```

**Comment by diegolmello** [comment]
I think I've found a fix: https://github.com/RocketChat/Rocket.Chat.ReactNative/pull/2480
I grouped the migrations in one step and removed `isOptional`.
This `isOptional` might not be necessary.
@radex Thoughts? :)

**Comment by radex** [comment]
> Thoughts? :)

No clue as of now, without more data, but your issue is worrying, because it likely is a Watermelon bug.

I don't like your fix - if you've shipped the app with schema versions 7, 8, then you'll break migrations for people on these versions. I do wonder why they fixed the issue.

Do you by any chance have multiple `Database` objects connected to the same physical database?

**Comment by diegolmello** [comment]
Yeah, I don't like it either.

Let me know if you find something odd and I'll check it out right away.
We can have a quick call so I can explain it to you properly, but here's how we do.

In short, our app is similar to Slack/Discord: A user can connect to multiple servers.
There's a [database to store servers info](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L69).
After logged in, [each server has its own database](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L123) created based on the server url.

We export these DBs as an [object](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L128).
This way the servers DB is [`database.servers`](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L93) and the active server is [`database.active`](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/database/index.js#L81).

A simple update on the new column is executed [this way](https://github.com/RocketChat/Rocket.Chat.ReactNative/blob/develop/app/lib/methods/enterpriseModules.js#L35).

**Comment by diegolmello** [comment]
I also see this error:
```
	15:02:31.798	27583	SQLiteConnectionPool
	A SQLiteConnection object for database '/data/user/0/chat.rocket.reactnative/default.db.db' was leaked!
	Please fix your application to end transactions in progress properly and to close the database when it is no longer needed.
```

**Comment by diegolmello** [comment]
@radex False alarm.
The error isn't gone with that patch.

**Comment by diegolmello** [comment]
Ok, now I think we found it, but we're not sure why it happened.
It looks like the `database version` is set as the next migration.
Then the migrations steps skips the first missing one.

#### Here's what happened
- Last migration number was to version 5.
- This update needs to migrate from 6 to 9.
- When migration starts, SQLite returns db version as 6 (!!)
- WM then migrates from 7 to 9, skipping 6
- Migration completes with success, but there're some missing columns
- The app finishes starting, tries to update that columns and explodes :)

#### Temp fix
It looks like adding an empty step (`unsafeExecuteSql('')`) as migration 6 will solve the issue

#### Next steps
I don't know what happened to set the db version wrong here: https://github.com/Nozbe/WatermelonDB/blob/master/native/android/src/main/java/com/nozbe/watermelondb/DatabaseDriver.kt#L230
It looks like we messed up on the migrations somewhere, but I wasn't able to find anything on git history.

@radex Do you know if you guys changed anything like `>` or `>=` on migrations logic?

**Comment by diegolmello** [comment]
Oh, now it makes sense.
We messed up.
🤦‍♂️ 

I'm sorry about the confusion, @radex.

**Comment by radex** [comment]
> Do you know if you guys changed anything like > or >= on migrations logic?

No, there's been no change

**Comment by KrisLau** [comment]
Any clue as to how I can run a sync and then just completely reset the DB to mitigate having to implement migrations? 
- #1609
