### ISSUE TITLE
[Help] observable.subscribe object reference remains same

### ISSUE THREAD

**Issue by shaheem-khanzada** [Nozbe/WatermelonDB#822]
this.subscription = observable.subscribe((projects = []) => {
	const selectedProject = projects.find(project => project.selected);
       // this.state.selectedProject === selectedProject => always true
	this.setState({ selectedProject });
       // as we updating state directly from observable, so object reference remains same so force update
      this.forceUpdate();
});

how to setState immutable in watermelondb so the object reference get change

**Comment by radex** [comment]
> how to setState immutable in watermelondb so the object reference get change

It won't. WatermelonDB records have a stable identity. This has pros and cons, and I understand this may be confusing/irritating/different from what you may be used to. The easiest/best way is to use `withObservables` HOC. Or, force and update.
