### ISSUE TITLE
Tutorial for the web asks you to install a dependency that requires fs (I'm using rollup)

### ISSUE THREAD

**Issue by frederikhors** [Nozbe/WatermelonDB#823]
Following the tutorial https://nozbe.github.io/WatermelonDB/Installation.html#set-up-database I'm having issues with `fs` dependency needed from `@nozbe/lokijs` (Imported by: node_modules\lokijs\src\lokijs.js).

Is there another way to do it?

Why `fs` if I need it in browser?

Is there a fix?

**Comment by frederikhors** [comment]
I have a workaround.

I have this file in my `node_modules/lokijs/src/lokijs.js` and if I comment line 2403 it works, like this:

```js
    /**
     * A loki persistence adapter which persists using node fs module
     * @constructor LokiFsAdapter
     */
    function LokiFsAdapter() {
      try {
        // this.fs = require('fs'); // this line
      } catch (e) {
        this.fs = null;
      }
    }
```

Where does this package come from?

Can we use an ESM version?

**Comment by radex** [comment]
@frederikhors what packager are you using?

**Comment by radex** [comment]
@frederikhors we're using a fork of LokiJS anyway, so send a PR with edit of this file: https://github.com/Nozbe/LokiJS/blob/master/src/lokijs.js - and remove the extraneous requires. I'll merge it and include in the next version of 🍉

**Comment by frederikhors** [comment]
> @frederikhors what packager are you using?

I'm using https://github.com/sveltejs/template right now. So pure Rollup for Svelte.

> so send a PR with edit of this file

Done here: https://github.com/Nozbe/LokiJS/pull/3.

Thanks!

**Comment by frederikhors** [comment]
> Done here: Nozbe/LokiJS#3.

Please look at it, I don't know if it makes sense like this.
