### ISSUE TITLE
Can we export ES modules, please?

### ISSUE THREAD

**Issue by frederikhors** [Nozbe/WatermelonDB#825]
I'm trying to use this AMAZING project with [ViteJS](https://github.com/vitejs/vite) (using [Svite](https://github.com/dominikg/svite/)).

It works fine but I have a lot of problems when I import something.

## Problem

Example:

```js
import { field } from '@nozbe/watermelondb/decorators'
```

This is a problem because `@nozbe/watermelondb/decorators` is not an ES module, it simply doesn't work.

So I have to explicitly [use a setting](https://github.com/vitejs/vite/issues/813#issuecomment-691799104) and then I can use it like this:

```js
import allDecoratorsPackage from '@nozbe/watermelondb/decorators'

class Post extends Model {
  // ...
  @allDecoratorsPackage.field('title') title
  @allDecoratorsPackage.field('body') body
  @allDecoratorsPackage.field('is_pinned') isPinned
}
```

As you can see this is not great.

And IDEs become crazy.

## Solution

Can we export ES modules?

**Comment by frederikhors** [comment]
Another example:

`import LokiJSAdapter from '@nozbe/watermelondb/adapters/lokijs'`

I need to use it like this:

`const adapter = new LokiJSAdapter.default({})`

with all the Typescript errors like:

`Property 'default' does not exist on type 'typeof LokiJSAdapter'.ts(2339)`

So sad. :(

**Comment by radex** [comment]
```
import LokiJSAdapter from '@nozbe/watermelondb/adapters/lokijs'

I need to use it like this:

const adapter = new LokiJSAdapter.default({})
```

this looks as if your packager is misconfigured. `exports.default` being the default export should work in any packager

**Comment by frederikhors** [comment]
Nope, because of this: https://github.com/vitejs/vite/issues/844.

**Comment by radex** [comment]
Closing now. @frederikhors I hope you figured out your issue, but alas I'm not planning to export ES modules as the _need_ for them is very rare (metro, webpack support CJS just fine), and it would complicate the setup quite a lot. If someone proposes and implements the proper build system for this, taking into account all the issues I want to avoid, then I'll consider it.

**Comment by leejunhui** [comment]
@frederikhors Hi, it's been a long time since the issue being created.And recently I want to transform my cra+ts project to vite,and I encountered the decorator issue of watermelondb, the console was no warning, but the `@field` syntax seems not working, because the data is not written into the IndexDB.I am so wondering how your project make the vite + watermelondb work successfully, thank you so much!

Below is my vite config:

```js
import react from '@vitejs/plugin-react';
import dns from 'dns';
import { defineConfig } from 'vite';
import topLevelAwait from 'vite-plugin-top-level-await';
import wasm from 'vite-plugin-wasm';
import { viteRequire } from 'vite-require';
import pluginRewriteAll from 'vite-plugin-rewrite-all';
import svgr from 'vite-plugin-svgr';
import babel from 'vite-plugin-babel';

dns.setDefaultResultOrder('verbatim');

const filesPathToExclude = ['../../node_modules/.pnpm/react-native'];

export default defineConfig(({ command, mode, ssrBuild }) => {
  return {
    optimizeDeps: {
      include: ['react', 'react-dom'],
      exclude: ['react-native'],
      esbuildOptions: { loader: { '.jsx': 'tsx', '.js': 'ts' } },
    },
    plugins: [
      react({
        babel: {
          plugins: [
            ['@babel/plugin-proposal-decorators', { legacy: true }],
            ['@babel/plugin-proposal-class-properties', { loose: true }],
            [
              '@babel/plugin-transform-runtime',
              {
                helpers: true,
                regenerator: true,
              },
            ],
          ],
        },
      }),
      wasm(),
      topLevelAwait(),

      // fix: requirer is not defined
      viteRequire(),
      pluginRewriteAll(),
      // svgr options: https://react-svgr.com/docs/options/
      svgr({ svgrOptions: { icon: true } }),
      babel({
        babelConfig: {
          babelrc: false,
          configFile: false,
          plugins: [
            ['@babel/plugin-proposal-decorators', { legacy: true }],
            ['@babel/plugin-proposal-class-properties', { loose: true }],
            [
              '@babel/plugin-transform-runtime',
              {
                helpers: true,
                regenerator: true,
              },
            ],
          ],
        },
      }),
    ],
    server: {
      open: true,
    },
    build: {
      sourcemap: true,
      rollupOptions: {
        external: [...filesPathToExclude],
      },
    },
    css: {
      preprocessorOptions: {
        less: {
          math: 'always',
          relativeUrls: true,
          javascriptEnabled: true,
        },
      },
    },
  };
});

```

**Comment by azuy212** [comment]
I was able to make it work with my Vue + Vite project. Here's the minimal setup you need for it to work

`npm install -D vite-plugin-babel @babel/plugin-proposal-class-properties @babel/plugin-proposal-decorators @babel/plugin-transform-runtime`

If needed, install `@babel/core`

If using typescript
`npm install -D @babel/preset-typescript`

.babelrc
```
{
  "presets": ["@babel/preset-typescript"], // if using typescript
  "plugins": [
    ["@babel/plugin-proposal-decorators", { "legacy": true }],
    ["@babel/plugin-proposal-class-properties", { "loose": true }],
    [
      "@babel/plugin-transform-runtime",
      {
        "helpers": true,
        "regenerator": true
      }
    ]
  ]
}
```
vite.config.ts
```
import { defineConfig } from 'vite'
import vue from '@vitejs/plugin-vue'
import babel from 'vite-plugin-babel';

export default defineConfig({
  plugins: [
    babel({
      filter: /models\.ts$/ // or whatever the file name is where you keep your models
    }),
    vue(),
  ],
});
```

tsconfig.json
```
{
  "compilerOptions": {
    ...
    "experimentalDecorators": true,
    "emitDecoratorMetadata": true,
  }
}
```
