### ISSUE TITLE
ios archive build error

### ISSUE THREAD

**Issue by lander854** [Nozbe/WatermelonDB#829]
Multiple commands produce '/Users/aislanlander/Library/Developer/Xcode/DerivedData/fieldsales-ernxnbjfdpnaumaatvxkksyeecpc/Build/Intermediates.noindex/ArchiveIntermediates/nectarApp2/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libWatermelonDB.a':
1) Target 'WatermelonDB' has a command with output '/Users/aislanlander/Library/Developer/Xcode/DerivedData/fieldsales-ernxnbjfdpnaumaatvxkksyeecpc/Build/Intermediates.noindex/ArchiveIntermediates/nectarApp2/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libWatermelonDB.a'
2) Target 'WatermelonDB' has a command with output '/Users/aislanlander/Library/Developer/Xcode/DerivedData/fieldsales-ernxnbjfdpnaumaatvxkksyeecpc/Build/Intermediates.noindex/ArchiveIntermediates/nectarApp2/IntermediateBuildFilesPath/UninstalledProducts/iphoneos/libWatermelonDB.a'

 no such file or directory: '/Users/aislanlander/Library/Developer/Xcode/DerivedData/fieldsales-ernxnbjfdpnaumaatvxkksyeecpc/Build/Intermediates.noindex/ArchiveIntermediates/nectarApp2/BuildProductsPath/Release-iphoneos/libWatermelonDB.a'

**Comment by radex** [comment]
@lander854 did you get it to work?

**Comment by lander854** [comment]
Yeah, just removed the reference to the duplicated folder, thanks

Em seg., 5 de out. de 2020 às 06:21, Radek Pietruszewski <
notifications@github.com> escreveu:

**Comment by diegobonagurio** [comment]
@lander854 Could you elaborate on how you did this process? I'm in the same problem :/

**Comment by lander854** [comment]
on xcode you can remove references for libraries, not 100% sure of the path but something like Target > Build Settings > Search paths

**Comment by diegobonagurio** [comment]
searching for Watermelon returns these two files

![Captura de Tela 2022-07-21 às 10 54 09](https://user-images.githubusercontent.com/56571038/180230993-10fa4206-727c-417b-b521-6f3f90a4fff4.png)
