### ISSUE TITLE
Question: Batch behavior during large write

### ISSUE THREAD

**Issue by jrounsav** [Nozbe/WatermelonDB#830]
Supposing a large batch write to the DB, what is the behavior if I restart the app on mobile while a batch is in progress?

Is the batch information somehow cached on the native side while it is being processed or does it all get blown away and require another attempt?

Are the writes "all or nothing", or can some of it be successfully written without the rest of the batch?

Thank you!

**Comment by radex** [comment]
`Database.batch()` calls are transactional with SQLiteAdapter, i.e. all or nothing. If you don't want transactionality, split it into multiple batches.
