### ISSUE TITLE
What is the storage data limit for watermelon db?

### ISSUE THREAD

**Issue by dpdhruv** [Nozbe/WatermelonDB#834]
Async-storage says there is a limit of 6MB storage limit for Android devices which is because they use SQLITE under the hood. 

I went through your docs , watermelon db is built on top of SQLITE so I'm assuming same limit would be present for watermelon db also? 

Can someone clarify?

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/issues/614
