### ISSUE TITLE
Usage with react memo

### ISSUE THREAD

**Issue by alwex** [Nozbe/WatermelonDB#836]
I am using `withObservables` HOC and from my understanding, it kind of prevent the usage of pure component as it pass down the same observable object as props for each render mutating the previous state as well as the next state which prevent the comparison from working correctly.

Here is an example to illustrate what I mean:
```jsx
class Observed extends Model {
  // ...
  @field('data') data!: string
}

const enhanced = withObservables(['observed'], ({observed}) => {
  return {
    observed
  }
})

const isEqual = (prevProps, nextProps) => {
  // prevProps is always === nextProps as this is an observable and not a copy of the props
  // as prevProps is referencing nextProps, mutating nextProps will mutate prevProps and the
  // diff will always return true
  prevDrops.observed.data === nextProps.observed.data
}

const component = enhanced(React.memo(MyComponent, isEqual))
```

passing down the `_raw` property of the entity can solve the issue, but then each equality function has to be fine tuned and the code start to get harder to maintain.

Is there something I missed or is this the expected behaviour?

**Comment by radex** [comment]
No, this is expected behavior -- you should memoize _after_ withObservables, i.e. `memo(withObservables(...)(component))` or `compose(memo, withObservables)(component)`

**Comment by iliapnmrv** [comment]
in case someone needs this, just passing 

```ts
const enhance = withObservables()

enhance(memo(component))
```

is enough
