### ISSUE TITLE
HELPFUL - DB location

### ISSUE THREAD

**Issue by yazmnh87** [Nozbe/WatermelonDB#838]
For what its worth.  The path to the watermelon db on IOS simulator is @ /Users/$user/Library/Developer/CoreSimulator/Devices/5CA2031E-DF5A-4BFB-B053-6E46F84EED2E/data/Containers/Data/Application/5D60BE41-FC88-47F6-B732-876DD83696AE/Documents

the UUID for the devices will be unique, just sort by date modified in finder. Im using SQLite browser, hope this helps others.

**Comment by felipegs31** [comment]
A better way to find it (in my opinion) is to run `find ~ -name WatermelonDemo.db` and you are going to have the actual location on the iOS simulator

**Comment by radex** [comment]
@felipegs31 Excellent tip! Mind hitting Edit on https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Advanced/ProTips.md and adding it there? That will help others!

**Comment by KrisLau** [comment]
Is there a way to retrieve it programmatically? Was hoping to allow users to create database backup and save it in their phone storage and/or send it for debugging if they have a particularly tough bug to diagnose.
