### ISSUE TITLE
how to access updated record, after updating?

### ISSUE THREAD

**Issue by yazmnh87** [Nozbe/WatermelonDB#839]
after you update, how do you access the updated record without querying the DB again?   

ie.

await database.action(async () => {
  await somePost.update(post => {
    post.title = 'Updated title'
  })
})
_____________________________________________________

const newPost = await database.action(async () => {
  await somePost.update(post => {
    post.title = 'Updated title'
  })
})

//returns undefined

or 

await database.action(async () => {
 newPost = await somePost.update(post => {
    post.title = 'Updated title'
  })
})

//returns undefined

^neither of these return anything

TIA

**Comment by leo-tavares** [comment]
Hello @yazmnh87 !
after you update the record, you can access it by your own reference. In the **example** below we have a demonstration. (code in _typescript_)

- retrieve meals
- log property name of meal
- action for update the name
- log a new property name from same record instance

```typescript
      const [mealRecord, ...rest] = await database.collections
        .get<MealModel>('meals')
        .query()
        .fetch();//retrieve all meals
      //mealRecord is the instance with desestruturação
      console.log('before the updatee =>' + mealRecord.name);

      database.action(async () => {
        await mealRecord.update((m) => (m.name = 'foo'));
      });

     console.log('after the update => ' + mealRecord.name);
```

The update method does not return

look the signature => ```    public update(recordUpdater?: (record: this) => void): Promise<void> ```

> note: This exemple use DatabaseProvider with useDatabase hook

**Comment by yazmnh87** [comment]
@leo-tavares, Thank you much for the reply, I'm going to work with this :) thanks!
