### ISSUE TITLE
Invalid Comparison passed to Query builder

### ISSUE THREAD

**Issue by leo-tavares** [Nozbe/WatermelonDB#840]
I am trying to retrieve "meals" from the past seven days. The code snippet below is being used within a useEffect

### snippet
```typescript

    const loadMeals = async () => {
      const mealsRecord = await database.collections
        .get<MealModel>('meals')
        .query(
          Q.where('created_at', {
            operator: 'gte',
            right: {value: subDays(new Date(), 7).getTime()},
          }),
        )
        .fetch();

```

### error message
``` 
Diagnostic error: Invalid Comparison passed to Query builder. You seem to be passing unsanitized user data to Query builder!
```

### database related files (models, schema, initialization) 

[link](https://github.com/leo-tavares/log-alimentar-mobile/tree/master/src/database)

#### link do date-fns
[subDays](https://date-fns.org/v2.16.1/docs/subDays)
#### link of project
[log-alimentar](https://github.com/leo-tavares/log-alimentar-mobile)

#### issue related
https://github.com/Nozbe/WatermelonDB/issues/820

**Comment by alexandrumic** [comment]
hello @leo-tavares.

You can try something like this:
```javascript
// ...
await database.collections.get('meals').query(
    Q.where('created_at', Q.gte(some_date_type_value))
).fetch()
```
this is how I'm using this kind of queries

**Comment by leo-tavares** [comment]
Hello @alexandrumic !

thanks for your reply!
this solved my problem
