### ISSUE TITLE
Android failed - TypeError: null is not an object (evaluating 'DatabaseBridge[methodName]')

### ISSUE THREAD

**Issue by rafameyer** [Nozbe/WatermelonDB#844]
<img width="396" alt="Screen Shot 2020-10-13 at 09 55 38" src="https://user-images.githubusercontent.com/22173714/95863177-40b80c80-0d3a-11eb-8160-9186c738357e.png">

**Comment by leo-tavares** [comment]
Hello @rafameyer !
I had this same mistake! The problem was the android link that was having problems.

I reviewed the entire installation of the "native" part and solved the problem!

**please check the installation very carefully**

https://nozbe.github.io/WatermelonDB/Installation.html

> android installation ** must be**  manual do not use autolink

**Comment by rafameyer** [comment]
Hi @leo-tavares I did it before. The problem is when I'm using a native project instead of react app default

**Comment by leo-tavares** [comment]
@rafameyer  I don't understand, you use rn project? The message error suggests that the lib is not installed correctly.

You can share you code with us?

**Comment by rafameyer** [comment]
@leo-tavares I'm using a normal native project "Android" and run react-native inside of rim. I'll share the code with you.

Estou usando um projeto android nativo, e rodando react-native em uma parte dele. vou partilhar o codigo contigo

**Comment by rafameyer** [comment]
<img width="836" alt="Screen Shot 2020-10-13 at 14 46 06" src="https://user-images.githubusercontent.com/22173714/95896585-d5366500-0d62-11eb-9938-ba8b5eef541d.png">
<img width="545" alt="Screen Shot 2020-10-13 at 14 48 33" src="https://user-images.githubusercontent.com/22173714/95896821-4118cd80-0d63-11eb-969f-279c4a0fb025.png">
<img width="573" alt="Screen Shot 2020-10-13 at 14 48 50" src="https://user-images.githubusercontent.com/22173714/95896882-44ac5480-0d63-11eb-8e42-ef6ef83fdf73.png">
<img width="694" alt="Screen Shot 2020-10-13 at 14 53 10" src="https://user-images.githubusercontent.com/22173714/95897386-d320d600-0d63-11eb-9097-72b2cfefe6c3.png">

**Comment by leo-tavares** [comment]
- in your ``` android/app/build.gradle ``` file,  you had included ```apply plugin: 'kotlin-android' ``` on top of file?

- in your ``` android/app/src/main/java/{YOUR_APP_PACKAGE}/MainApplication.java ``` ,  you had imported ``` import com.nozbe.watermelondb.WatermelonDBPackage; ```? 

These were the only parts that were not shown in the screenshot. The rest of the code is ok.

**Comment by rafameyer** [comment]
Yes, both of them are ok

**Comment by rafameyer** [comment]
I'm using android flavors, it's maybe causing problems

**Comment by rafameyer** [comment]
@leo-tavares thanks for everything, I missed to insert "**packages.add(new WatermelonDBPackage());**" in determined file.

It's already resolved ;)
