### ISSUE TITLE
Overriding created_at and updated_at generators

### ISSUE THREAD

**Issue by NiloDrumond** [Nozbe/WatermelonDB#847]
Hello everyone,

Our application needs trustworthy time, so we have an internal clock, synced with ntp-servers so the user can't mock the dates.
However, I imagine WatermelonDB uses the regular time from the device, correct? In this case, I wan't to know if it's possible to override the date generator for created_at and updated_at. (similar to the setGenerator for IDs)

**Comment by radex** [comment]
> Our application needs trustworthy time, so we have an internal clock, synced with ntp-servers so the user can't mock the dates.

There's no such thing as "trustworthy time" on client side. If you need a consistent timeline between syncs and devices, the only way to guarantee that time makes sense and only ever increases monotonically, is if you ensure it on backend side - by rewriting client-provided timestamps with current server time. With the downside being that you get "synced at" time, not "performed at" time.

> In this case, I wan't to know if it's possible to override the date generator for created_at and updated_at. (similar to the setGenerator for IDs)

Send a pull request, and I'll be happy to merge this capability.
