### ISSUE TITLE
Version 0.20 breaks withObservables, Unable to resolve module `rxjs-compat/operators/map`

### ISSUE THREAD

**Issue by StefanBlamberg** [Nozbe/WatermelonDB#849]
The removal of the `rxjs-compat` dependency with https://github.com/Nozbe/WatermelonDB/commit/b0d9e8d breaks the latest released version of `@nozbe/with-observables`, which will probably break many projects as well.

Of course this is more of an issue with https://github.com/Nozbe/withObservables, I am opening the issue here to increase visibility for other developers though, feel free to close ;)

`@nozbe/with-observables` still uses outdated imports from `rxjs` which depend on `rxjs-compat`. While a new dependency was added with https://github.com/Nozbe/withObservables/commit/f5ef728 it is not published to npm yet.

It is possible to change the dependency to the latest master as a workaround, nevertheless I would say it might be good to mention it as a breaking change in the Watermelon release logs.

**Comment by radex** [comment]
Hi, try the latest version of withObservables (1.0.7) and let me know if it works now

**Comment by StefanBlamberg** [comment]
Yes, 1.0.7 has the correct dependencies and works fine.

Still makes sense to fix the imports to avoid compat altogether imo.
I saw that there is an kinda old PR to remove rxjs - https://github.com/Nozbe/withObservables/pull/93
Are you still working on this? Otherwise I will try to find some time to create a PR to fix the imports

**Comment by radex** [comment]
> Otherwise I will try to find some time to create a PR to fix the imports

that would be great if you did it!

> I saw that there is an kinda old PR to remove rxjs - Nozbe/withObservables#93 Are you still working on this?

Not at the moment. I absolutely have an intention of finishing this, as this has a nice performance benefit, but I probably won't get to it in coming weeks/months, as my priorities shifted for a bit.

**Comment by radex** [comment]
I noted in CHANGELOG that there's been (unintentionally) a breaking change: https://github.com/Nozbe/WatermelonDB/blob/master/CHANGELOG.md
