### ISSUE TITLE
Execute raw statement "delete from tableName"

### ISSUE THREAD

**Issue by HosseinRashno** [Nozbe/WatermelonDB#850]
First of all, I want to thank you for this amazing package.   
I have a table with over 300k rows and at some point, I want to delete all rows and start fetching data from an API and insert the data in this table again.
I tried to achieve this as follow:
```javascript
await Database.action(async () => {
      const pricesCollection = Database.get(Tables.prices);
      const allPrices = await pricesCollection.query().fetch();
      const deleteList = allPrices.map((p) => p.prepareDestroyPermanently());

      await Database.batch(deleteList);
      return true;
    }, 'batchDeleteAllPrices');
```
But this takes forever to be done. Then I thought, I shouldn't get all data in order to delete them. There should be a way to delete all data of a table without getting them first. Unfortunately, I couldn't find this functionality in WatermelonDB.   
Then I tried to find a way to execute this raw query: `delete from prices`   
My first attempt is as follow:
```javascript
const tag = Database.adapter._tag;
const bridge = NativeModules.DatabaseBridge;
 await bridge.query(tag, 'delete from prices');
```
But I get an error about 'query got 4 arguments but it expects 5 arguments!'.   
This is my second attempt:
```javascript
const tag = Database.adapter._tag;
const bridge = NativeModules.DatabaseBridge;

await bridge.query(
      tag,
      'prices',
      'delete from prices',
      () => {
        console.log('resolved');
      },
      () => {
        console.log('reject');
      },
    );
```
This one also produces an error!   
This is my last attempt:
```javascript
const pricesCollection = Database.get(Tables.prices);
await pricesCollection.unsafeFetchRecordsWithSQL('delete from prices',);
```
This one does nothing at all! How can I delete all rows of a table? Thanks.

**Comment by radex** [comment]
```
await pricesCollection.unsafeFetchRecordsWithSQL('delete from prices',);
```

this _should_ work, I think, though it's geared towards fetching, not executing updates, maybe that trips up some sqlite thing.

here's something else you can try:

https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/sqlite/index.js#L231

this private unsafe endpoint is used for executing updates, but if you trigger the underlying native method passing your own SQL, that should work.

> But I get an error about 'query got 4 arguments but it expects 5 arguments!'.

it does ;) check out: https://github.com/Nozbe/WatermelonDB/blob/master/native/ios/WatermelonDB/DatabaseBridge.swift#L163

**Comment by uzegonemad** [comment]
I was having an issue with `_tag` earlier which may be related to the issue @HosseinRashno is having. `Database.adapter._tag` is returning null for us.

I worked around it by setting a variable for the adapter tag where we are declaring the adapter, like so:

```js
const adapter = new SQLiteAdapter({
  dbName: 'WatermelonDemo',
  schema: mySchema,
});

export const adapterTag = adapter._tag;
```

And then calling `await bridge.query(adapterTag, ...);`

**Comment by HosseinRashno** [comment]
@uzegonemad thanks for the suggestion. I actually getting a correct tag with this: `Database.adapter.underlyingAdapter._tag`.   
Could you please share your query with me? When I try the following code, I get the error in the screenshot:
```javascript
await bridge.query(tag, 'delete from prices');
```
<img src="https://user-images.githubusercontent.com/9047556/97615179-43de1880-1a1b-11eb-9cca-7ccf8eb43fae.jpg" width="200" height="400" />   
And when I try the following code, I get this error: `Exception in HostFunction: Malformed calls from JS: field sizes are different`   

```javascript
await bridge.query(
      tag,
      'prices',
      'delete from prices',
      () => {
        console.log('resolved');
      },
      () => {
        console.log('reject');
      },
    );
```
