### ISSUE TITLE
Current podspec creates many different checksums

### ISSUE THREAD

**Issue by jrounsav** [Nozbe/WatermelonDB#851]
Every time a member of my team runs pod install they receive a different checksum for their `Podfile.lock` to commit into git. 
It looks like this is caused by line 14 in WatermelonDB.podspec
` s.source       = { :http => 'file:' + __dir__ + '/'  }`
since `__dir__` is specific to every individual user's machine.

Is it important to keep `__dir__` or could we update that to something like:
`s.source         = { :git => "https://github.com/Nozbe/WatermelonDB.git", :tag => "v#{s.version}" }`

Happy to put a PR together if that is acceptable

**Comment by radex** [comment]
@jrounsav I'm not 100% sure (I didn't write it) -- take a look at what other Podspecs that you use do. If there's a clear pattern/best practice (e.g. what you're proposing) then just do that and please submit a PR :)

**Comment by jrounsav** [comment]
Will do, thank you!

**Comment by radex** [comment]
thanks!
