### ISSUE TITLE
[SYNC] Override default id on sync

### ISSUE THREAD

**Issue by luk3skyw4lker** [Nozbe/WatermelonDB#856]
I have a offline app that receives pre-created data from the backend on start, this makes the whole possibility of using WDB ids on the backend a little bad. Could I try to make a PR that makes possible the id override on the sync process?

**Comment by pranavbabu** [comment]
If you receiving right data from backend with `id` fields , WDB will take this `ids` . Should mention that `id` should be a string, then if you want to use your own `id` type you can provide generator in `setGenerator` function.
