### ISSUE TITLE
Could not resolve project :watermelondb on Android Studio

### ISSUE THREAD

**Issue by ViT4RGh0ST** [Nozbe/WatermelonDB#859]
settings.gradle

include ':watermelondb'
project(':watermelondb').projectDir =
new File(rootProject.projectDir, '../node_modules/@nozbe/watermelondb/native/android')

rootProject.name = 'nativeApp'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':app'

I followed the install steps for android, maybe project version?, any example for a latest version of react native project?

**Comment by ViT4RGh0ST** [comment]
settings.gradle
`include ':watermelondb'
project(':watermelondb').projectDir =
    new File(rootProject.projectDir, '../node_modules/@nozbe/watermelondb/native/android')

rootProject.name = 'nativeApp'
apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)

include ':app'
`

**Comment by ViT4RGh0ST** [comment]
I followed the install steps for android, maybe project version?

**Comment by leo-tavares** [comment]
Hello @ViT4RGh0ST !

I use watermelondb in react-native 0.63.2, you may check my project look => [log-alimentar](https://github.com/leo-tavares/log-alimentar-mobile). The android "side" work's perfectly


```
rootProject.name = 'logAlimentar'

include ':watermelondb'
project(':watermelondb').projectDir = new File(rootProject.projectDir, '../node_modules/@nozbe/watermelondb/native/android')

apply from: file("../node_modules/@react-native-community/cli-platform-android/native_modules.gradle"); applyNativeModulesSettingsGradle(settings)
include ':app'

```

**Comment by ViT4RGh0ST** [comment]
Hello @leo-tavares, thank you!
Yes, it's okey now

I had to reinstall everything properly
