### ISSUE TITLE
synchronize() is not triggering the observe().subscribe() callback when pulling new data

### ISSUE THREAD

**Issue by cjroth** [Nozbe/WatermelonDB#863]
I'm not sure if this is a bug or intended behavior, but here's what I do:

```js
const load = async () => {
	const documents = await collection.query().fetch()
	collection.query().observe().subscribe(() => 'detected changes')
}
```

Updating or creating records correctly triggers the subscribe callback but the pull method that I pass to synchronize does not. If I manually query the collection after the synchronize() method has finished, all of the records were updated correctly.

**Comment by radex** [comment]
remember that observing this way, only added or removed record in this collection will trigger your observer, not changes. Otherwise, it should work just fine.

**Comment by ViT4RGh0ST** [comment]
Well, we need this. Any suggestions?

**Comment by cjroth** [comment]
@ViT4RGh0ST If I understand @radex, I think this is an Observable issue, not a Watermelon issue. I could be wrong as I'm not very familiar with Observables. I think you'd basically need to subscribe to the individual records as well as the collection, if I'm not mistaken.

**Comment by ViT4RGh0ST** [comment]
@cjroth Hello, I solved it by returning from the sync method the objects in question directly from the collection:

```js
export default async function sync() {
  let results = {
    objects: []
  };

  await synchronize({...}); // Watermelon Implementation

  const objectsCollection = database.collections.get('objects');
  results.objects = await objectsCollection.query().fetch();

  return results;
}
```

Then I use that to update the list(table/whatever), and it does not collide with the components with observables.

**Comment by cjroth** [comment]
@ViT4RGh0ST ha that's exactly what I'm doing as well. Great minds think alike.
