### ISSUE TITLE
how to undelete

### ISSUE THREAD

**Issue by barbalex** [Nozbe/WatermelonDB#864]
I have found the methods to `markAsDeleted()` and `prepareMarkAsDeleted()`.

I am not using the syncing and conflict managing methods of watermelondb but rather the CouchDB style.

So when data arrives from the server the app needs to be able to undelete a record if it was undeleted on another device and that happened to be the winning revision.

Can I `prepareMarkAsUndeleted()`?

**Comment by radex** [comment]
Hi. WatermelonDB assumes `marked as deleted` records to be dead and unrecoverable. Only their IDs are kept, and only for sync purposes.

If you want a `trash can` sort of feature, you'll need to implement that as part of your app's logic

**Comment by barbalex** [comment]
O.k., thanks, will use my own _deleted field
