### ISSUE TITLE
Observe Collection

### ISSUE THREAD

**Issue by luk3skyw4lker** [Nozbe/WatermelonDB#869]
Is there a way that I can observe the whole collection to get to know when a record was created or updated based on a query?

I'm totally new to WatermelonDB and Observables.

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/blob/master/src/Database/index.js#L166

**Comment by luk3skyw4lker** [comment]
Thanks! I didn't saw it on the docs :c
