### ISSUE TITLE
one to one relationship

### ISSUE THREAD

**Issue by rohit-32** [Nozbe/WatermelonDB#870]
How do i create a one to one relationship, the document does not explain it very well

**Comment by avinashlng1080** [comment]
Hello @rohit-32 ,

Please try the following: 

1. Define the schema for two tables.  In our case, it will be Post and Comment.
2. For each model, create an association:

```
class Post extends Model {
  static table = 'posts'
  static associations = {
    comments: { type: 'has_many', foreignKey: 'post_id' },
  }
}

class Comment extends Model {
  static table = 'comments'
  static associations = {
    posts: { type: 'belongs_to', key: 'post_id' },
  }

  @relation('posts', 'post_id') post  //<<<< This creates the relationship from Comment to Post as post_id is the foreign key used to reference a post from within the 'comment' table.
}
```

**Comment by rohit-32** [comment]
> Hello @rohit-32 ,
> 
> Please try the following:
> 
>     1. Define the schema for two tables.  In our case, it will be Post and Comment.
> 
>     2. For each model, create an association:
> 
> 
> ```
> class Post extends Model {
>   static table = 'posts'
>   static associations = {
>     comments: { type: 'has_many', foreignKey: 'post_id' },
>   }
> }
> 
> class Comment extends Model {
>   static table = 'comments'
>   static associations = {
>     posts: { type: 'belongs_to', key: 'post_id' },
>   }
> 
>   @relation('posts', 'post_id') post  //<<<< This creates the relationship from Comment to Post as post_id is the foreign key used to reference a post from within the 'comment' table.
> }
> ```

Hello, This will create one to many relations, and if not, how ill i access comment from post

**Comment by avinashlng1080** [comment]
```
class Post extends Model {
  static table = 'posts'
  static associations = {
    comments: { type: 'has_many', foreignKey: 'post_id' },
  }
}

@children('Comment') comment // <<< like this 
```

**Comment by rohit-32** [comment]
> ```
> class Post extends Model {
>   static table = 'posts'
>   static associations = {
>     comments: { type: 'has_many', foreignKey: 'post_id' },
>   }
> }
> 
> @children('Comment') comment // <<< like this 
> ```

This will create one to many relationship, correct me if i am wrong. I have two Tables
`class Broadcast extends Model {
  static table = 'broadcast'
}

class Feed extends Model {
  static table = 'feed'
}
`
Broadcast will always have one feed with it and Feed will always be part of one Broadcast.
Let me know if i am missing something

**Comment by avinashlng1080** [comment]
what if you try using the

``` @relation('Broadcast', broadcast_id) broadCast within the Feed model ``` and ``` @relation('Feed', Feed_id) broadCast within the Broadcast model ```  while dropping the associations and children?

**Comment by rohit-32** [comment]
Ill try this and update

> what if you try using the
> 
> `@relation('Broadcast', broadcast_id) broadCast within the Feed model` and `@relation('Feed', Feed_id) broadCast within the Broadcast model` while dropping the associations and children?

**Comment by avinashlng1080** [comment]
@rohit-32 how did it go ?

**Comment by rohit-32** [comment]
> @rohit-32 how did it go ?

I am refactoring from realm, i'll post the results

**Comment by rohit-32** [comment]
> @rohit-32 how did it go ?

It does not work

**Comment by rohit-32** [comment]
> How do i create a one to one relationship, the document does not explain it very well

@radex Is there any solution to this

**Comment by xiaobingkenny** [comment]
static associations = {
    comments: { type: 'has_many', foreignKey: 'post_id' },
  }

"comments" is table name?

**Comment by KrisLau** [comment]
@xiaobingkenny Yup
