### ISSUE TITLE
observeWithColumns on related tables or lazy fields

### ISSUE THREAD

**Issue by barbalex** [Nozbe/WatermelonDB#888]
In our app gardeners count plants in plant cultures. 
Often the plants are distributed over several plant beds.
So gardeners enter the counts for every plant bed in the count form inside rows contained for every plant bed.

In the navigation tree counts are placed as children of plant cultures. There are no nodes for beds.
Counts are labeled by their date _and the sum of the counts_ summed over all plant beds.
I am trying to make the label update when the gardener enters a new count in a plant bed.

The problem is: I cant add the count field to `observeWithColumns` as it is not included in the count table.
I tried adding a @lazy to the model like this:
```js
@lazy anzahl_pflanzen = this.observe().pipe(
    distinctUntilChanged(),
    map$(async (zaehlung) => {
      const tzs = await zaehlung.teilzaehlungs.fetch()
      const anzs = tzs.filter((t) => exists(t.anzahl_pflanzen))
      const anzahl_pflanzen = anzs.length ? sum(anzs) : null

      return anzahl_pflanzen
    }),
  )
```
but adding `anzahl_pflanzen` to  `observeWithColumns` does not work. Probably as that field is not a raw value.

I'm sure there is a trick to get this to work using rxjs but I'm new to that.
Is there a way to get this to work using watermelonDB's own tools?

**Comment by quolpr** [comment]
You should use `switchMap` I guess 🤔

**Comment by barbalex** [comment]
@quolpr 
You are probably right. I will close this issue as rxjs is probably the way to go, so this is not a watermelon db issue

**Comment by LuizCristino** [comment]
@barbalex  I don't know if you still has this problem after this much time but it can also help another githuber.

This gave me the start point https://github.com/Nozbe/WatermelonDB/issues/910#issuecomment-755980464
