### ISSUE TITLE
Sync between two tabs in browser

### ISSUE THREAD

**Issue by quolpr** [Nozbe/WatermelonDB#890]
I am just curious: Is it possible to synchronize the DB state of two tabs in one browser that uses the same DB? If yes, then how could it be implemented?

**Comment by radex** [comment]
No such feature is provided. I would mostly rely on having a backend server synchronizing with all tabs, keeping them in sync with each other as long as you're online... Tab-to-tab syncing sounds possible, but very tricky with WatermelonDB, probably not something you'd code up in a day or two. I guess you could elect one of the tabs as leader, and implement a watermelon sync backend service in the leader tab, and then communicate from the others with it to sync. Leader election, alas, is not possible in JS with perfect reliability (AFAIK), and this scheme is going to get very complicated is you ALSO want to sync with a backend server...

**Comment by quolpr** [comment]
Hmm, I see. I want to have mutlitab support even when the user goes offline. Maybe I will need to switch sync strategy when the user online and offline 🤔️ Thank you for your thoughts!

**Comment by radex** [comment]
quolpr: Yes, indeed that would be a very great feature to have as part of WatermelonDB. Alas, I don't know how to implement this correctly and performantly, so I have no plans to work on this. If you do, contributions are welcome ;)

BTW: In next release of 🍉, you can catch the situation where another tab overwrote the web database, so that you can trigger sync, and if it fails, warn the user NOT to close any tabs until you go online.

**Comment by castroCrea** [comment]
@radex I have a question to find a solution about how 🍉 works:
* When an app with watermelon come up, 🍉 cache the DB and update this cache ?
  * Then it persist the cache into the DB ?

When you do a modification in on window (or tab) it is persisted un DB, if in the other tab you reload the page it will show the modification.

So my guess is that :
   * the Db is cached in window local and doesn't listen external update

Did I'm right ?

**Comment by radex** [comment]
@castroCrea I'm not sure if I understood your comment. On web, database is loaded into memory at launch, and does not listen to external updates - that is correct.

> Maybe we can refresh the cache on window focus ?

Like I said:

> I don't know how to implement this correctly and performantly

It's a truly difficult problem to solve.

**Comment by radex** [comment]
Related: https://github.com/Nozbe/WatermelonDB/issues/827
