### ISSUE TITLE
running integration tests on Android fails

### ISSUE THREAD

**Issue by likern** [Nozbe/WatermelonDB#894]
I've tried to run integration tests as described in [integration-tests section](https://github.com/Nozbe/WatermelonDB/blob/master/CONTRIBUTING.md#integration-tests). 

But I get errors, whether I used `yarn test:android` or running tests manually in Android Studio.

<table>
  <tr>
  </tr>
  <tr>
    <td valign="top"><img src="https://user-images.githubusercontent.com/842306/101992079-ba7c6000-3cc1-11eb-9f69-b84058895fd2.jpg"></td>
    <td valign="top"><img src="https://user-images.githubusercontent.com/842306/101992080-bbad8d00-3cc1-11eb-9739-bebd2b433e35.jpg"></td>
  </tr>
 </table>

**Comment by radex** [comment]
Assuming it's out of date, closing.

PS: Some errors shown are to be expected, doesn't mean the tests themselves are failing
