### ISSUE TITLE
Error: invalid comparisonRight

### ISSUE THREAD

**Issue by gabrnunes** [Nozbe/WatermelonDB#896]
Hey!

My App started to show an error when I trying to update or create a post in Watermelon. I am creating a white label Rocket Chat, that use the DB.

The code where the error occurred:

```javascript
await db.action(async() => {
	try {
		const pollOptionVote = await pollOptionVoteCollection.find(data.id);
		await pollOptionVote.update(protectedFunction((p) => {
			Object.assign(p, data);
		}));
	} catch (error) {
		await pollOptionVoteCollection.create(protectedFunction((p) => {
			p._raw = sanitizedRaw({ id: data.id }, pollOptionVoteCollection.schema);
			Object.assign(p, data);
		}));
	}
});
```

I tried to change all the code, but doesn't have succeeded. 

This become after I created a component who make a `subscribe` in same table.

**Comment by gabrnunes** [comment]
The error not occurred anymore.

**Comment by paul-rchds** [comment]
Hi there, I am getting this same error. How did you resolve it?

**Comment by KrisLau** [comment]
Same problem here how did you solve it?

**Comment by KrisLau** [comment]
Having the same issue has anyone figured this out yet? #1185

**Comment by KrisLau** [comment]
@gabrnunes @topwebtek7 @paul-rchds Running into this again in another one of my methods #1288. Has anyone figured out what caused it? I have a feeling it has something to do with the way I'm using `Promise.all` but I'm not sure and no refactoring I've done seems to be resolving it

**Comment by KrisLau** [comment]
@gabrnunes ?
