### ISSUE TITLE
Column names not escaped properly

### ISSUE THREAD

**Issue by sebastian-schlecht** [Nozbe/WatermelonDB#9]
When using SQL keywords as column names, the application dies on launch.

Example:
```
tableSchema({
      name: 'ticket_statuses',
      columns: [
        { name: 'name', type: 'string' },
        { name: 'order', type: 'string' },
      ]
    })
```

while *order* is a SQL keyword. Stacktrace shows `Syntax error near "order"`

**Comment by radex** [comment]
Ooh! That's not good.

The generated SQL should put double quotes around column names.

This should be an easy fix (the helpers here: https://github.com/Nozbe/WatermelonDB/tree/master/src/adapters/sqlite )

I'll try to write up a basic Contributing.md guide with the how to for running tests and whatnot tomorrow, and maybe you'd like to take a stab at fixing it?

**Comment by sebastian-schlecht** [comment]
Sure - just ping me here as soon as the guide is up and I'll give it a shot.

**Comment by radex** [comment]
@sebastian-schlecht OK, check out:

https://github.com/Nozbe/WatermelonDB/blob/master/CONTRIBUTING.md

And let me know if you run into any issues

**Comment by sebastian-schlecht** [comment]
@radex started working on this - changing `encodeSchema` seems to be insufficient. Shouldn't also insert, update and query operations escape column (& table) names in order to be safe?

https://www.sqlite.org/lang_keywords.html

**Comment by radex** [comment]
>  Shouldn't also insert, update and query operations escape column (& table) names in order to be safe?

Yep, exactly!
