### ISSUE TITLE
TypeError: null is not an object (evaluating 'DatabaseBridge[methodName]')

### ISSUE THREAD

**Issue by idkDemo** [Nozbe/WatermelonDB#904]
Hey ! I'm new with WatermelonDB. I'm trying to develop an app with react-native and i use expo to test the app. But when i try to run it i get this error. I already have better-sqlite3 installed and i followed the installation notes.

This is how i intialize the database. 

 ```js

	const adapter = new SQLiteAdapter({
		schema: appSchema,
	})
	this.database = new Database({
		adapter,
		modelClasses: models,
		actionsEnabled: true
	})
```

The error message.
![image](https://user-images.githubusercontent.com/50049020/102773989-6987fe00-438a-11eb-833c-7596d2db56f0.png)

(My english might be pretty bad.. sorry for that ^^')

**Comment by mohamedanwer123** [comment]
r u solved this issue ?

**Comment by idkDemo** [comment]
No :c

**Comment by RageCrezz** [comment]
Can you share the whole code with us please?
As far as I am concerned, you didn't pass anything to `appSchema` and `models`:

for appSchema you could define something like

```
const tables = new tableSchema({
  name: 'example',
  columns: [
    { name: 'name1', type: 'string/int/bool' },
    ...
  ]
})

new appSchema({
  version: 1,
  tables
})
```
