### ISSUE TITLE
DatabaseBridge.swift - Expression pattern of type 'String' cannot match values of type 'String?'

### ISSUE THREAD

**Issue by WillDent** [Nozbe/WatermelonDB#91]
Build works fine on Android, just on iOS having this issue. Tried inside of Xcode and from command line.

Xcode version: 9.2 (9C40b)

"dependencies": {
    "@nozbe/watermelondb": "^0.6.0",
    "@nozbe/with-observables": "^1.0.0",
    "jsc-android": "224109.x.x",
    "react": "16.5.1",
    "react-native": "0.57.1",
    "react-native-prompt-android": "^0.3.3",
    "react-navigation": "^2.12.1"
  },

![screen shot 2018-10-12 at 1 07 38 pm](https://user-images.githubusercontent.com/753691/46883366-d5bc5e00-ce1f-11e8-9c33-4beeba18823a.png)

**Comment by radex** [comment]
Try on Xcode 9.4 or later

**Comment by radex** [comment]
no response
