### ISSUE TITLE
How to perform a sum operation

### ISSUE THREAD

**Issue by sutuioncode** [Nozbe/WatermelonDB#910]
Supposing that I have a MusicModel and AlbumModel (Collection of MusicModel) model I i want the get the total playback time for a given playlist by summing the duration of each music.
I have tried with RxJs but I'm not very good at that.
This is what I have tried:
```
export MusicModel extends Model{
   static table = "musics"
   static associations = {
    musics: { type: "belongs_to", key: "music_id" },
   }
  @field title
  @field artist
  @field uri
  @field duration
 
}

export AlbumModel extends Model{
   static table = "albums"
   static associations = {
    musics: { type: "has_many", foreignKey: "album_id" },
  }
  @field name
  @children("musics", "music_id")
  @lazy duration = this.songs.observe().pipe(
    switchMap(async (value) => {
      return Observable.create(emitter => {
        for (const iterator of value) {
          )
          iterator.subscribe(next => emitter.next(next.duration))
        }
      })
    }),
    reduce((acc, item) => acc + item)
    )
}
```

**Comment by radex** [comment]
```js
this.songs.observe().pipe(map(
  songs => sum(songs.map(song => song.duration))
))
```

**Comment by phamquyhai** [comment]
> ```js
> (
> ```

I have 35 thousand records, I use the above func not so well, it takes a long time (5-10 seconds) and the UI is blocking. Can I use the raw query? I tested the raw query via Flipper very quickly (156 ms). 
@radex 
I need the `sum` func to generate the reports. What suggestions do you have for this

**Comment by przbadu** [comment]
@radex 

I used raw unsafeSqlQuery for this. Raw sql used in unsafesqlquery is returning expected result in query browser, but it is returning empty [] with watermelon query builder:


```
  records
    .query(
      Q.unsafeSqlQuery(
        'select kind, SUM(amount) as amount from table_name' +
          ' group by kind',
      ),
    )
    .observe();
```

**Comment by LuizCristino** [comment]
> ```js
> this.songs.observe().pipe(map(
>   songs => sum(songs.map(song => song.duration))
> ))
> ```

For anyone having a problem where this code for sum doesn't react to updates, just change `observe` for `observeWithColumns`

```ts
this.songs.observeWithColumns(['duration']).pipe(map(
  songs => sum(songs.map(song => song.duration))
))
```
