### ISSUE TITLE
Is it possible to check whether there is unsynced data that has yet to be synced?

### ISSUE THREAD

**Issue by Tharinducn** [Nozbe/WatermelonDB#911]
I want to check whether there is any unsynced data in WatermelonDB. Is there any function implemented to check that currently?

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/blob/master/src/sync/index.js#L84

Please hit `edit` on https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Advanced/Sync.md and document this, might be helpful to others

**Comment by Tharinducn** [comment]
Hi @radex, To which branch should I merge my pull request?

**Comment by radex** [comment]
@Tharinducn master
