### ISSUE TITLE
[Feature request] Merge "Model" and "Schema" into one

### ISSUE THREAD

**Issue by thanhtunguet** [Nozbe/WatermelonDB#914]
I have used watermelonDB for a few months. For each project, I have to define both schemas and models. It's hard to keep schemas and models to be synced. Whenever I add or change a field, I have to do it in both the model class and the table schema.

If Model and Schema can be merged into one, it would be easier for developers to define their database.

I currently do not have any good idea. I can think of some:
- We may use the "?" syntax to mark a field is optional or required but need a plugin to transform the code
- We may use decorator chain:
```ts
export class Device extends Model {
  @Optional()
  @Indexed()
  @field('name')
  public name?: string;
}
```
- We may use decorators with an extendable options param:
```ts
export class Device extends Model {
  @field('name', {isIndexed: true, isOptional: false})
  public name?: string;
}
```

Is there any great idea? or any drawback?

Thank in advanced!

**Comment by radex** [comment]
> or any drawback?

Yes. What you're proposing may feel a little easier for you, but it makes managing schema and migrations really error prone, and makes certain optimizations hard to do. WatermelonDB prioritizes suitability for high-quality production applications over small DX improvements. For improving DX, one thing that would be nice is a Watermelon CLI and a generator, where you could do `wmelon schema add ....`, and it would make the right changes to schema, migrations, and add a stub to Model....

**Comment by thanhtunguet** [comment]
Thank you for your reply!
