### ISSUE TITLE
Typescript error with documentation example

### ISSUE THREAD

**Issue by angelod1as** [Nozbe/WatermelonDB#915]
When I write the following code, straight from docs:

```
class Post extends Model {
  static table = 'posts'
  static associations = {
    comments: { type: 'has_many', foreignKey: 'post_id' },
  }
}
```

Typescript complains:

```
Class static side 'typeof Post' incorrectly extends base class static side 'typeof Model'.
  Types of property 'associations' are incompatible.
    Type '{ comments: { type: string; foreignKey: string; }; }' is not assignable to type 'Associations'.
      Property 'comments' is incompatible with index signature.
        Type '{ type: string; foreignKey: string; }' is not assignable to type 'AssociationInfo'.
          Type '{ type: string; foreignKey: string; }' is not assignable to type 'HasManyAssociation'.
            Types of property 'type' are incompatible.
              Type 'string' is not assignable to type '"has_many"'.
```

Is there a way to solve this?

**Comment by angelod1as** [comment]
The solutions was declare `associations` `as const`

```typescript
class Post extends Model {
  static table = 'posts'
  static associations = {
    comments: { type: 'has_many', foreignKey: 'post_id' },
  } as const  // <- here
} 
```

**Comment by dhmacs** [comment]
@angelod1as out of curiosity, can you elaborate on this? I had the same issue. What's the purpose of const? and why does it solve the problem?

**Comment by angelod1as** [comment]
I'll *try* to elaborate, as I don't know exactly what's going wrong myself.

AFAIK, the error complains that the types don't match, specially because the object property (`comments`) and the information in `type` (`has_many`) and `foreignKey` (`post_id`) aren't found within the typeseting of `Post` or `Model` type. **There's an issue here that I'll address later on this text**.

What `as const` does it: instead of saying "`type` is receiving a value type `string`", it turns the strings into *constants*. So it says: "`type` is receiving a value type `has_many`". As I say the whole object is `as const`, the program understands that all the object is a constant and valid.

If anyone could elaborate this better (and even maybe say I got all this wrong), I'd be happy.

The main issue (highlighted above) is that I believe the typesetting of Watermelon isn't very good. It throws errors here and there and the typescript documentation is a single `.ts` file without real implementation. I do not have enough knowledge to PR a new example, so all I can do is file issues :cry:

**Comment by jasonnathan** [comment]
yep, the only `ts-ignore` I have in my entire code base is in the watermelondb functionality

**Comment by lucksp** [comment]
this is still an issue FWIW...docs aren't clear on this

**Comment by Jenspi** [comment]
Still an issue!

btw, anyone who ends up here like I did: don't forget to use `belongs_to` with `key`... If you'e still getting an error after adding `as const`, chances are that's what it is :)
