### ISSUE TITLE
Action is not a function

### ISSUE THREAD

**Issue by angelod1as** [Nozbe/WatermelonDB#916]
I build the following model with the `getPhotos` action, as explained in the docs:

```js
export default class Photo extends Model {
  static table = 'photos'

  @readonly @date('created_at') createdAt
  @readonly @date('updated_at') updatedAt

  @field('url') url
  @field('exif') exif

  @action async getPhotos() {
    return await this.collection.query().fetch()
  }
}
```

Then, a button triggers the following function:

```js
  const actionTest = async () => {
    const photoCollection = database.collections.get('photos')
    const allPhotos = await photoCollection.getPhotos()
    console.log(allPhotos)
  }
```

When I call the function, the console gives me `Possible Unhandled Promise Rejection (id: 5): TypeError: photos.getPhotos is not a function`

I tried removing the `@action` decorator and also running `await photoCollection.getPhotos()` inside a `database.action`, like this:

```js
  const actionTest = async () => {
    const photoCollection = database.collections.get('photos')
    database.action(async () => {
      const allPhotos = await photoCollection.getPhotos()
      console.log(allPhotos)
    })
  }
```

I believe there's something I'm doing wrong. Typescript is not getting things right (subject for another issue) so I can't understand if the intelisense errors are bad typing or actual errors.

(I don't know if the content of the action itself is written in a correct way, I tried a `console.log` in it's place and the error persisted)

**Comment by radex** [comment]
```
const allPhotos = await photoCollection.getPhotos()
```

`photos.getPhotos is not a function`, becausse `photos.getPhotos` *is not* a function! ` photoCollection` is a `Collection`, not a `Photo`. You confused two different object types

**Comment by angelod1as** [comment]
oh I feel so stupid right now.

So, as I can see, there's no way to create such general function as an action, right? Like get all photos or get all something?

**Comment by radex** [comment]
No. A pattern I use is to keep handy a `ModelRoot` object, which contains top-level database actions and such, but it's just a design pattern, it's not a feature

**Comment by ortonomy** [comment]
@angelod1as -- I wouldn't feel stupid. the name 'actions' completely suggests that it's a place to store model scoped queries (for the whole collection of Models)

I also made this mistake and I don't understand a) why it was closed without a real explanation or example b) what the 'solution' was. It's a missing feature for me.
