### ISSUE TITLE
sendCreatedAsUpdated not working

### ISSUE THREAD

**Issue by luk3skyw4lker** [Nozbe/WatermelonDB#918]
I am setting sendCreatedAsUpdated on sync since my backend can't see the diff between created and udpated records but the offline DB still complains about the "created" key and doesn't create the records I am sending as updated.

**Comment by KrisLau** [comment]
@luk3skyw4lker Did you ever figure this out? On mine it worked as soon as I sent an empty array for the `created` for all the tables

**Comment by luk3skyw4lker** [comment]
> @luk3skyw4lker Did you ever figure this out? On mine it worked as soon as I sent an empty array for the `created` for all the tables

Yeah, I got it working by doing that too. It was the only way I could do it.

Maybe if @radex allow it, I could take a look and remove the warning when the option is true.

**Comment by KrisLau** [comment]
Not sure if you ran into this but my deletes are causing errors?  When `sendCreatedAsUpdated ` is false:
```
[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally and is marked as deleted. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will delete local record and recreate it instead.]
```
 When `sendCreatedAsUpdated ` is true, the `pushChanges` fails

**Comment by KrisLau** [comment]
@luk3skyw4lker  Not sure if you ran into this but my deletes are causing errors? When `sendCreatedAsUpdated ` is false, I get the `[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally and is marked as deleted. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will delete local record and recreate it instead.]` error. When `sendCreatedAsUpdated ` is true, the timestamps are getting set to 0.0.

**Comment by luk3skyw4lker** [comment]
> @luk3skyw4lker Not sure if you ran into this but my deletes are causing errors? When `sendCreatedAsUpdated ` is false, I get the `[Diagnostic error: [Sync] Server wants client to create record table_name#id1234567890123, but it already exists locally and is marked as deleted. This may suggest last sync partially executed, and then failed; or it could be a serious bug. Will delete local record and recreate it instead.]` error. When `sendCreatedAsUpdated ` is true, the local db timestamps (created_at & updated_at) are getting set to 0.0.

I didn't ran into specifically this problem (especially the timestamps being 0), but I received this error once and it turns out that the problem was on my backend not filtering the deletedAt field on the SQL queries.
