### ISSUE TITLE
Typescript Definitely assigned fields problem when defining models

### ISSUE THREAD

**Issue by angelod1as** [Nozbe/WatermelonDB#920]
Following the typescript example, I created the following class:

```typescript
import { Model } from '@nozbe/watermelondb'
import { field, children, date } from '@nozbe/watermelondb/decorators'

export default class Farm extends Model {
  static table = 'farms'

  static associations = {
    user: { type: 'has_many', foreignKey: 'user_id' },
    cattle: { type: 'has_many', foreignKey: 'cattle_id' },
  } as const

  @date('created_at') createdAt!: string
  @date('updated_at') updatedAt!: string

  @field('name') name!: string
  @field('car_number') carNumber!: string
  @field('car_data') carData!: string

  @children('users') users!: string
  @children('cattle') cattle!: string
}
```

When I save my file, TS throws the following error:

```zsh
error: src/services/adapter/watermelonDB/models/Farm.ts: /home/angelo/Documentos/GIT/professional/databoi/databoi-front/src/services/adapter/watermelonDB/models/Farm.ts: Definitely assigned fields cannot be initialized here, but only in the constructor
  10 |   } as const
  11 | 
> 12 |   @date('created_at') createdAt!: string
     |   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  13 |   @date('updated_at') updatedAt!: string
  14 | 
  15 |   @field('name') name!: string
```

Turning off `strictPropertyInitialization` in `tsconfig` is not acceptable (I'd need to turn `strict` off and that defeats the purpose of strict typechecking).

Defining the variables inside a constructor, like below, gives me `ExceptionsManager.js:179 Diagnostic error: Diagnostic error: Not allowed to change record outside of create/update()` error.

```typescript
import { Model } from '@nozbe/watermelondb'
import { field, children, date } from '@nozbe/watermelondb/decorators'

export default class Farm extends Model {
  constructor() {
    super()
    this.createdAt = ''
    this.updatedAt = ''
    this.name = ''
    this.carNumber = ''
    this.carData = ''
    this.users = ''
    this.cattle = ''
  }
  static table = 'farms'

  static associations = {
    user: { type: 'has_many', foreignKey: 'user_id' },
    cattle: { type: 'has_many', foreignKey: 'cattle_id' },
  } as const

  @date('created_at') createdAt
  @date('updated_at') updatedAt

  @field('name') name
  @field('car_number') carNumber
  @field('car_data') carData

  @children('users') users
  @children('cattle') cattle
}
```

How can I solve this problem?

**Comment by avinashlng1080** [comment]
hey @angelod1as ,  I was also facing this issue and this is what helped me.  

The issue stems from the different @babel plugins and you would need to add a few and no need for a constructor.

Install the following babel plugins and add them under plugins in your babel.config.js file: 

```
  plugins: [
        ['@babel/plugin-proposal-decorators', {legacy: true}],
        ['@babel/plugin-transform-flow-strip-types'],
        ['@babel/plugin-proposal-class-properties', {loose: true}],
        // add other plugins afterwards ....
]
```

**Comment by angelod1as** [comment]
@avinashlng1080 whoa, this worked like a charm.

Another doubt: how do you type relations and children? Strings? Objects?

**Comment by radex** [comment]
`@date('created_at') createdAt!: string`

this is not correct. this is not a `string`, it's a `Date`.

**Comment by angelod1as** [comment]
@radex sure, it was for example sake, just to note the error. I'm fixing those right now. I'll ask the same to you: what's the types of `@children` and `@relation`?

On a side note, I'd like to contribute with documenting my Typescript experience. How can I do that? I mean, is there a document on typescript, should I create a `typescript.md`, or else? My idea is to put info like this issue out to the world.

**Comment by radex** [comment]
>  I'll ask the same to you: what are the types of @children and @relation?

Don't ask me - look at the code :)

https://github.com/Nozbe/WatermelonDB/blob/master/src/decorators/children/index.js#L17
https://github.com/Nozbe/WatermelonDB/blob/master/src/decorators/relation/index.js#L23

> I mean, is there a document on typescript

There is not. This is the docs for Flow typing: https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Advanced/Flow.md -- an equivalent explanation for TypeScript would be cool, I encourage you to contribute that.

**Comment by angelod1as** [comment]
@radex Nice, didn't know where to look for.

I'll start working on this PR as soon as I get 5 minutes from solving this actual issue at work.

Thanks a lot. Closing.

**Comment by angelod1as** [comment]
@radex another question about TS, won't open another issue.

Whenever I try to create or update something, TS gives me erros. Eg:

```typescript
    await database.action(async () => {
      const newCattle = await cattleCollection.create((thisCattle) => {
        thisCattle.name = data.name
        thisCattle.age = data.age
      })
    })
```

It complains saying that `property 'name' does not exist on type 'Model'`, which is right, it actually doesn't... but it does in type `Cattle` (the defined model).

When I try to force `Cattle`, seen below, it gives me another error.

```typescript
    await database.action(async () => {
      const newCattle = await cattleCollection.create((thisCattle: Cattle) => {  // <- here
        thisCattle.name = data.name
        thisCattle.age = data.age
      })
    })
```
```
Argument of type '(thisCattle: Cattle) => void' is not assignable to parameter of type '(record: Model) => void'.
  Types of parameters 'thisCattle' and 'record' are incompatible.
    Type 'Model' is missing the following properties from type 'Cattle': createdAt, updatedAt, name, weight, and 7 more.ts(2345)
```

**Comment by angelod1as** [comment]
I believe I fixed this doing `const cattleCollection: Collection<Cattle> = database.collections.get('cattle')`

If this is the right way, I'll gladly add to the documentation. If not, please let me know.

**Comment by radex** [comment]
@angelod1as do it

**Comment by praveens96** [comment]
better than this would be use the below way:
`this.collections
      .get< Cattle >('cattle')
      .create(cattle => {
        cattle.name = age;
        cattle.type = age;
      });`
