### ISSUE TITLE
Is watermelonDB thread safety?

### ISSUE THREAD

**Issue by code-assist** [Nozbe/WatermelonDB#922]
I'm developing a mobile app with ReactNative that use watermelonDB . 

It found that there are some CPU intensive code that need to operate with DB, and i plan to bundle these code into one JS file, then create a new WebView to load and run this JS file. In this case, the code will run in a separate thread. 

It sound feasible, but the key point i wonder is : does it safe to do read/write on DB from multiple threads?

**Comment by radex** [comment]
> It sound feasible, but the key point i wonder is : does it safe to do read/write on DB from multiple threads?

No exactly, native-side DB works on _its own_ thread (queue), and all calls which are not done automatically from React Native should be done by synchronizing to Watermelon's queue

**Comment by code-assist** [comment]
I afraid i don't catch your meaning.   Does the native-side DB works run on RN's JS-thread ? so you mean DB r/w can not be invoked from any other threads? 

As you mention the idea 'queue', I  check the native (iOS swift) code just now , and find that there are many [connection: Queue] mapping without sync/lock. It seem that watermelonDB don't worry about thread-safe problem at all. 
Also, I do some google about underline FMDB and found it design to be thread safe .

So, I think  watermelonDB can be thread safe, but lack of test.

PS: what does the 'connection' in swift code mean? How does a new connection created? It sound like connection in tcp domain.

**Comment by code-assist** [comment]
If avoid write same table from both thread, then seem work. Just finish a simple demo.

```
+--------------------------------+     +--------------------------------+
|                                |     |                                |
|    React Native JS-Thread      |     |       New Fork Thread          |
|                                |     |                                |
| ------------------------------ |     | ------------------------------ |
|                                |     |                                |
|    new SQLiteAdapter(...)      |     |      new SQLiteAdapter(...)    |
|    new Database(...);          |     |      new Database(...);        |
|                                |     |                                |
|                                |     |                                |
|  +------------------------+    |     |   +------------------------+   |
|  |  Table-1-read-write op |    |     |   |     Table-1-read  op   |   |
|  +------------------------+    |     |   +------------------------+   |
|               .                |     |               .                |
|               .                |     |               .                |
|               .                |     |               .                |
|  +------------------------+    |     |   +------------------------+   |
|  |  Table-N-read-write op |    |     |   |     Table-N-read  op   |   |
|  +------------------------+    |     |   +------------------------+   |
|                                |     |                                |
|                                |     |                                |
|                                |     |                                |
|  +------------------------+    |     |   +------------------------+   |
|  |  Table-X1-read op      |    |     |   | Table-X1-read-write op |   |
|  +------------------------+    |     |   +------------------------+   |
|  +------------------------+    |     |   +------------------------+   |
|  |  Table-X2-read op      |    |     |   | Table-X2-read-write op |   |
|  +------------------------+    |     |   +------------------------+   |
|                                |     |                                |
|                                |     |                                |
|                                |     |                                |
+--------------------------------+     +--------------------------------+
```
