### ISSUE TITLE
Can't observe without get().query(), props return {}

### ISSUE THREAD

**Issue by angelod1as** [Nozbe/WatermelonDB#923]
Two issues in one.

I have the following code: 
```typescript
const enhance = withObservables(['cattle'], () => {
  return {
    cattleNumber: database.collections
      .get('cattle')
      .observeCount(),
  }
})
```

In docs I saw I could do:
```typescript
withObservables(['post'], ({ post }) => ({
  post: post.observe(),
  comments: post.comments.observe(),
  verifiedCommentCount: post.verifiedComments.observeCount(),
}))
```

so I did it:
```typescript
const enhance = withObservables(['cattle'], ({ cattle }) => {
  return {
    cattleNumber: cattle.observeCount(),
  }
})
```
It then throws me an error saying `Cannot read property 'observeCount' of undefined`

If I change `{ cattle }` to `props` I see it's an empty `{}`. My first approach works, so I thought about sticking to it... until I needed to query something *inside* cattle, like the query `photos`:

```typescript
export default class Cattle extends Model {
  static table = 'cattle'

  static associations = {
    photos: { type: 'has_many', foreignKey: 'cattle_id' },
  } as const

  @date('created_at') createdAt!: Date
  @date('updated_at') updatedAt!: Date
  @children('photos') photos!: Query<Photo>
}
```
Using the docs example, I tried ` cattle.photos.observeCount()`, which threw error.

I tried solving it querying like the first block of code, but then I'd need to `async map` each photo and `await get().fetch()` then reduce to get the photo numbers... see the difference of labor involved?

What do I need to do to make the docs example run?

**Comment by radex** [comment]
you seem to be confusing different object types. `database.collections
      .get('cattle')` this is a `Collection`. `.observeCount()` this is a method on a `Query`

**Comment by angelod1as** [comment]
Sorry, I seem to be having this confusion all the time. How am I supposed to set up my models or whatnot to make code like in the docs work? Because I can't seem to understand this concept.

**Comment by KrisLau** [comment]
Did you manage to figure out how to use props in your withObservables query? I'm struggling with the same thing right now
