### ISSUE TITLE
Proposal: synchonous fetching of data in relationships.

### ISSUE THREAD

**Issue by GiridharKarnik** [Nozbe/WatermelonDB#940]
Excuse my beginner question spree, but hopefully, this will help someone when it's answered.

Given that an author can write many posts and a post can have many others, here are the Models.

```typescript
//Author
class AuthorModel extends Model {
  static table = 'authors';
  static associations = {
    author_posts: {
      type: 'has_many',
      foreignKey: 'author_id',
    },
  };

  @field('name') name: string;

  @lazy
  posts = this.collections
    .get('posts')
    .query(Q.on('author_posts', 'author_id', this.id))
    .fetch();
}

//AuthorPost -- Pivot table
class AuthorPost extends Model {
  static table = 'author_posts';
  static associations = {
    authors: {
      type: 'belongs_to',
      foreignKey: 'author_id',
    },
    posts: {
      type: 'belongs_to',
      foreignKey: 'post_id',
    },
  };

  @field('author_id') name: string;
  @field('post_id') name: string;
}

//Post
class PostModel extends Model {
  static table = 'posts';
  static associations = {
    author_posts: {
      type: 'has_many',
      foreignKey: 'post_id',
    },
  };

  @field('name') name: string;
}

```

**Question 1**

How to fetch the author and the post data synchronously?

Right now I am forced to await on `authors.post`, is there a way to not do this, and get all the required and related data in one asynchronous call?

```typescript
const authorsCollection = database.collections.get<AuthorModel>('authors');

const authors = await authorsCollection.query().fetch();
const posts = await authors.posts;
```

**Question 2**

Why am I not able to swap out `@lazy` with `@children` which seems to be the answer to my previous question but throws the following error?

> Diagnostic error: @children decorator used for a table that's not has_many
> Diagnostic error: @children decorator used for a table that's not has_many

It's a great library btw. Any help will be much appreciated. Thanks.

**Comment by GiridharKarnik** [comment]
After looking at the code, here are my conclusions.

1. Each `query().fetch()` on a collection results in a SQL statement generated by the underlying SQL adapter.
2. In order to fetch the `Author` and the author's `Posts` sequentially before resolving the fetch, [the SQL lite query method](https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/sqlite/index.js#L204) has to do a SQL query to fetch the parent object's data from the main table and then go on to fetch the data related to all (one or more) associations (in this case) the `Post`.
3. Essentially resulting in n (no of associations) parallel calls to [`unsafeSqlQuery`](https://github.com/Nozbe/WatermelonDB/blob/master/src/adapters/sqlite/index.js#L209).
4. The function signature of `unsafeSqlQuery` has to be slightly modified to return a promise or a new wrapper should be written to it to support this.
5. Not to mention, probably a new decorator to indicate `non-lazy` way of loading association data.
6. And finally all the associations marked as `non-lazy` has to be collected and passed to the adapter's `query` method.

:thinking: can be done I guess.

All of this can be avoided by grouping promises outside the lib, but in my point of view, this should not be done, as the consumers of watermelonDB should not be needed to understand the underlying SQL structure of the data when fetching results.

Or at least the users should be given an option to fetch the results synchronously in a "non-lazy" way.

If this is something the @radex are willing to consider, I can work on it and raise a PR asap.

Or there may be a completely different angle to solve this problem which is already implemented which I have overlooked. Either way, really awesome work. This library has great potential to fill a massive void.

**Comment by KrisLau** [comment]
Did you ever figure this out? I'm struggling with the same thing
