### ISSUE TITLE
Discussion: Making _raw immutable

### ISSUE THREAD

**Issue by jrounsav** [Nozbe/WatermelonDB#942]
I just ran into a situation where some code wrote over the _raw attribute for one of my queried records.

The new _raw for that record persisted throughout the app until I restarted which created some trouble in one of our forms.

Any thoughts on freezing _raw after it is generated for a Watermelon record?

**Comment by radex** [comment]
Yes, I thought about it, and it has potential not just to increase reliability, but allow for a simple CoW architecture for performance... But it's going to be tricky to do, since currently, there is an assumption that _raw is directly mutated on updates, so there would be a lot of auditing to do to change this... It's also unclear to me what the performance cost would be of copying _raw for updaets

The question though is: why do you have code that touches _raw directly?

**Comment by diegolmello** [comment]
We can't use the sync feature, so we touch `_raw` in some places to make local id to be equal to the server's.
```js
await collection.create((c) => {
	c._raw = sanitizedRaw({ id: newRecord.id }, collection.schema);
	Object.assign(c, newRecord);
});
```

Can we do it differently?

**Comment by radex** [comment]
@diegolmello  as long as whatever you're assigning to _raw is sanitized and happens in .create or .update, you should be OK 👍 But you can also use `Collection.createFromRaw` in this case

**Comment by jrounsav** [comment]
@radex The changes to the raw attributes were accidental 😅  but we leverage those values in a few places. 

We've found that the records (specifically the circular references) returned by watermelon don't play very well with our redux-saga implementation unless we flatten out the data and the easiest way to do so has been to use the raw values.

It has also been a quick way to leverage components that we had prior to our migration to watermelon, which have been a major source of tech debt that we intend to kill once Realm has been completely removed from the app 😄 

There is a lot going on inside of the data returned by watermelon and so far `_raw` has been the easiest way to grab the attributes that we expect

**Comment by radex** [comment]
> easiest way to do so has been to use the raw values.

So, why not copy _raw instead of just assigning it someplace else?

**Comment by jrounsav** [comment]
Ah, that's exactly what we are doing!

The assignment was a dev accident and prompted the question on my end. Was just curious if it was being considered.

Thank you for the info!

**Comment by radex** [comment]
@jrounsav Might be a good idea for you to add `Model.raw()` method/getter to avoid directly touching _raw and make sure assigning w/o copy never happens again :)
