### ISSUE TITLE
Change of screen with observables

### ISSUE THREAD

**Issue by osvaldokalvaitir** [Nozbe/WatermelonDB#947]
I have an application, with login screen, choice of company and dashboard.

I had a redux structure that on my routes I did something like:

```
  if (signedUser) {
    if (signedCompany) {
      return <AppRoutes />;
    }
    return <CompanyRoutes />;
  }

  return <AuthRoutes />;

```

It worked well, as it was with reducer and it redirected itself to the route if it changed these variables.

With the use of Watermelon, I tried to use getLocal, but it does not observe the variables as it is in the documentation.

So, I had to make an 'auth' scheme and model and put the columns 'signed_user', 'signed_company' to make it observable, the only way I thought to make it observable, this table would have only one record.

At login, create the record, and when choosing a company, update the record.

In my routes it is:

```
const enhance = withObservables(['auth'], ({ database }) => ({
  auth: database.get('auth').query().observe(),
}));

export default withDatabase(enhance(Routes));
```
I happen to be looking at a list, and when it updates the record, it doesn't.

How would you observe the update of the first record?

I tried to do otherwise, at login, create a user with id: '00000000-0000-0000-0000-000000000001'

And on the routes it would look like:

```
  auth: database.get('auth').findAndObserve('00000000-0000-0000-0000-000000000001').observe(),
```

But the routes happen before and there is a registration error not found because it has not yet been created.

So, I would have to add this single record to the auth after creating the database. But I saw that it doesn't have this native and I saw an issue that needs to do several things to create a database with preloading, as I'm new to this tool, I didn't understand almost anything.

If anyone can help me, because something that seemed to be easy, is leaving me with no options.

**Comment by blixit** [comment]
could you provide a code sample ?

**Comment by osvaldokalvaitir** [comment]
@blixit Hello, so what did you not understand? because for me to make an example of this I will take a long time, because there are many screens and code! But tell me which part I explain better! Thank you very much =)

**Comment by blixit** [comment]
I mean the minimal code that can help to reproduce.

You provided a code for the redux structure but the watermelon one is not clear.

BTW, this code looks strange to me:

```ts
.findAndObserve('00000000-0000-0000-0000-000000000001').observe()
```

findAndObserve() and observe() are similar since they return observables. You should not call observe().

Actually, you can't call observe() on an observable. you may subscribe(), lift(), foreach(), pipe() or toPromise()

![image](https://user-images.githubusercontent.com/6025710/108746033-183bec80-753c-11eb-9419-50ba0d12f4ad.png)

**Comment by osvaldokalvaitir** [comment]
Hi! sorry, i ended up getting confused!

The following is happening, in my old structure I used redux, I had variables like 'signed_user' and 'signed_company' and when I updated the reducer, I entered routes and updated the route, changing from one screen to another.

1 option - I tried to do this with getLocal, but it has no observable.

2 option - I tried to make an 'auth' table just to record these variables, so it would only have one record with the columns 'signed_user' and 'signed_company'. But it turns out that if I observable at a list, when creating a record it goes into the route file, but if I just edit it, it doesn't go into the route file. In this case, I would have to look at the list and look at the first record, if it does, you can't make an error if you don't, because it will be created later.

3 option - I tried to make an 'auth' table with the 'key' and 'value' columns and fill these tables with the values ​​'key = signed_user' and 'value =' 2903409234 ... ''. This option worked better than the second option, as I always create a record and delete the record, always causing a change in the list's observable. But it may be that on the same screen it creates two records and ends up entering routes twice.

I'll leave the code I made with option 3: 

routes.js

```
import React from 'react';

import PropTypes from 'prop-types';

import { withDatabase } from '@nozbe/watermelondb/DatabaseProvider';
import withObservables from '@nozbe/with-observables';

import api from '~/services/api';

import AppRoutes from './app.routes';
import AuthRoutes from './auth.routes';
import CompanyRoutes from './company.routes';

function Routes({ auth }) {
  let token = null;
  let signedUser = null;
  let signedCompany = null;

  auth.map((item) => {
    switch (item.key) {
      case 'token':
        token = item.value;
        break;
      case 'signedUser':
        signedUser = item.value;
        break;
      case 'signedCompany':
        signedCompany = item.value;
        break;
      default:
        break;
    }

    return null;
  });

  if (signedUser) {
    if (signedCompany) {
      return <AppRoutes />;
    }
    return <CompanyRoutes />;
  }

  return <AuthRoutes />;
}

const enhance = withObservables(['auth'], ({ database }) => ({
  auth: database.get('auth').query().observe(),
}));

export default withDatabase(enhance(Routes));
```

signin.js
```
      const authCollection = database.get('auth');

      await database.action(async () => {
        authCollection.create((auth) => {
          auth.key = 'signedCompany';
          auth.value = signedCompany;
        });

        authCollection.create((auth) => {
          auth.key = 'signedUser';
          auth.value = user.id;
        });
      });

```

What I need is, what is the best way to record these variables and observe them, so that when I change any of the two, they change the screen. 

@blixit thank you very much, for the time spent helping me, this is very important, especially since I am starting in this database.

**Comment by Mohamed-kassim** [comment]
@osvaldokalvaitir i hope this is your case
.observe is just observe if the table has new records or not, if a single record changes it won't do any thing 
if you wanna check if some column changed 
like is_signed changed from true to false 
you need to use observeWithColumns['is_signed']
it takes the column names i wanna observe, and be sure u provided them in a snake case
### https://nozbe.github.io/WatermelonDB/Components.html?highlight=sort,list#advanced-observing-sorted-lists
check this example

**Comment by osvaldokalvaitir** [comment]
@Mohamed-kassim  thank you, I think that's what I need, I'll do some tests as soon as possible and put the answer here, thank you very much

**Comment by osvaldokalvaitir** [comment]
@Mohamed-kassim Sorry for the delay, I only worked on the project today.

I put it in my routes file:

```
const enhance = withObservables(['auth'], ({ database }) => ({
  auth: database
    .get('auth')
    .observeWithColumns(['signed_user', 'signed_company']),
}));

export default withDatabase(enhance(Routes));
```

I put it in my signin file:

```
      const authCollection = database.get('auth');

      await database.action(async () => {
        authCollection.create((auth) => {
          auth.token = token;
          auth.signedUser = user.id;
          auth.signedCompany = signedCompany;
        });
      });
```

The error below occurred:

```
TypeError: database.get('auth').observeWithColumns is not a function. (In 'database.get('auth').observeWithColumns(['signed_user', 'signed_company'])', 'database.get('auth').observeWithColumns' is undefined)
```

I know why this error happened. The route file is executed first and since there is no record this error occurs, before this record is registered in the signin.

I thought of two things, popular the database, but I saw an issue and found it very difficult to do at the moment, as I am a beginner in Watermelon. Or if there was a function that when creating the database, I created this record.

Thank you very much for your help, do you know how you could solve this?

**Comment by jrounsav** [comment]
> database.get('auth').observeWithColumns

I think you need to query.
`database.get('auth').query().observeWithColumns()`

**Comment by osvaldokalvaitir** [comment]
@jrounsav  thank you so much! That was what was missing =)
