### ISSUE TITLE
Create/Update very slow

### ISSUE THREAD

**Issue by nmarchais** [Nozbe/WatermelonDB#949]
When I try to update a single field from a model it takes about 3 seconds.
Here is the sample code from my app:
`
await database.action(async () => {
      console.log("before " + dayjs().minute() + ":" + dayjs().second())
      await salePlaceData.update(spdUpdated => {
        spdUpdated.informations = data.informations;
      })
      console.log("after " + dayjs().minute() + ":" + dayjs().second())
    });
`

During the database update, my app is in a freezing state. Everything gets smooth again after the update. 
Is it the WatermelonDB expected behavior on create/update actions?
How can I solve the performance issue?

**Comment by radex** [comment]
no, it's not expected. Run profiler to see what's happening during these 3 seconds.

**Comment by nmarchais** [comment]
Thanks a lot for your quick answer.
I found my problem. I try to track each create/update done in database that are not sync with the server. I need to know if the database is in dirty state. To reach this goal i use "database.withChangesForTables" using the following code:
`
database.withChangesForTables(Object.values(TableName)).pipe(
      skip$(1),
      // ignore records simply becoming `synced`
      // @ts-ignore
      filter$(changes => !changes.every(change => change.record.syncStatus === 'synced')),
    ).subscribe({
      next(x) {
        // console.log("Changes detected in DB")
        if (x && x.length > 0) {
          setDirtyTime(dayjs().valueOf());
          sync.setSyncState({...sync.syncState, syncStatus: "DIRTY"})
        }
      },
      error(err) {
        console.error('something wrong occurred: ' + err);
      },
      complete() {
        console.log('done');
      }
    });

This piece of code takes a long time, almost 3 seconds. Is there any better solution to track dirty states?

**Comment by radex** [comment]
> This piece of code takes a long time, almost 3 seconds. Is there any better solution to track dirty states?

it shouldn't take this much time… Have you ran the profiler?

**Comment by nmarchais** [comment]
I found the bottleneck in my code. The cause of the performance issue was the sync.setSyncState method which triggered too many UI updates.
I changed the way to manage my state using rxjs that allows "push" updates instead of React "pull" updates.
WatermelonDB works like a charm. Sorry for disturbing you.

**Comment by KrisLau** [comment]
@nmarchais How to debounce the `withChangesForTables`? I tried to debounce mine but it's still being called dozens of times? #1229
