### ISSUE TITLE
[Question] - deep joins with one-to-many relationship

### ISSUE THREAD

**Issue by GiridharKarnik** [Nozbe/WatermelonDB#950]
Excuse me if the mistake was obvious.

Given the following query

``` typescript
@lazy
muscles = this.collections
  .get<MuscleModel>(TableNames.muscles)
  .query(
    Q.experimentalNestedJoin(
      TableNames.exercises,
      TableNames.workoutExercises,
    ),
    Q.on(
      TableNames.exercises,
      Q.on(TableNames.workoutExercises, Q.where('workoutId', this.id)),
    ),
  );
```

I get the following error 

> [Diagnostic error: Error: no such column: muscles.undefined (code 1 SQLITE_ERROR): , while compiling: select distinct "muscles".* from "muscles" join "exercises" on "exercises"."id" = "muscles"."undefined" left join "workoutExercises" on "workoutExercises"."exerciseId" = "exercises"."id" where (("workoutExercises"."workoutId" is '5s4unawuuyt8xo43' and "workoutExercises"."_status" is not 'deleted') and "exercises"."_status" is not 'deleted') and "muscles"."_status" is not 'deleted']

Since `exercises` and `muscles` are related via `exerciseId`, shouldn't :watermelon: do the join on `exerciseId` by default instead of trying to do it with undefined?

**Comment by radex** [comment]
you're missing the correct associations() record for Muscles

**Comment by GiridharKarnik** [comment]
@radex thanks for getting back. Here is my model, I have followed the documentation while defining these. As you can see, there is clear one-to-many association between `muscles` and `exercsies`

``` typescript
class MuscleModel extends Model {
  static table = TableNames.muscles;
  static associations = {
    exercises: { type: 'belongs_to', foreignKey: 'exerciseId' },
  };

  @field('name') name: string;
  @field('usage') usage: string;
  @relation(TableNames.exercises, 'exerciseId') exercise;
}
```

```typescript
class ExerciseModel extends Model {
  static table = TableNames.exercises;
  static associations = {
    [TableNames.muscles]: {
      type: 'has_many',
      foreignKey: 'exerciseId',
    },
    [TableNames.equipments]: {
      type: 'has_many',
      foreignKey: 'exerciseId',
    },
    [TableNames.workoutExercises]: {
      type: 'has_many',
      foreignKey: 'exerciseId',
    },
  };

  @field('_id') _id: string;
  @field('createdBy') createdBy: string;
  @field('createdDateTime') createdDateTime: string;
  @field('name') name: string;
}
```

**Comment by radex** [comment]
`exercises: { type: 'belongs_to', foreignKey: 'exerciseId' },` should be `key`, not `foreignKey`, I believe. If that helps, then you can help back by contributing a tweak to the Database constructor that would catch such errors in dev mode and present a helpful error message to the user

**Comment by GiridharKarnik** [comment]
Okay that works. Thanks for the helo @radex, will definitely fortify :watermelon: with additional checks in the db constructor. Good place to start I contributing to this project I guess. Cheers.
