### ISSUE TITLE
Docs for creating a record leads to error

### ISSUE THREAD

**Issue by gabrielgrover** [Nozbe/WatermelonDB#954]
Pretty much following the docs for creating a record.  From the code below I get the following error 

` Unhandled promise rejection [Error: Collection.create() can only be called from inside of an Action. See docs for more details.]`

```typescript
function createHuman(args) {
    return database.action(async (action: any) => {
       const newHuman = await humanCollection.create(h => {
          h.firstName = args.firstName;
          h.lastName = args.lastName;
        })
      });
    };
  }

```

**Comment by MarcosSarges** [comment]
How to solve?
