### ISSUE TITLE
RFC: Creating firestore sync engine for watermelondb

### ISSUE THREAD

**Issue by creatorrr** [Nozbe/WatermelonDB#96]
Hey @radex @nozbetravis @Nozbe, first of all thank you and congratulations for the amazing work on watermelondb! I have been playing around with the API and am beyond impressed. Was thinking of creating a sync engine with [Google Cloud Firestore](https://cloud.google.com/firestore/) as the backend as a weekend project and had some questions:

1. Is the sync engine API stable enough for such an undertaking?
2. Are docs for implementing new sync engines in the works or would you like me to convert my notes into basic first draft for docs?
3. I am planning to use the said engine on [react-native](https://facebook.github.io/react-native/) possibly using the [react-native-firebase](https://github.com/invertase/react-native-firebase) project. Anyone know if this would be non trivial to implement with the existing adapters?
4. Would it be better to start a new adapter implementation from scratch or override the LokiJS adapter for example (maybe for supporting offline operations)?
5. (Bonus question) Would you use it if I built it? :toilet:

**Comment by radex** [comment]
> Is the sync engine API stable enough for such an undertaking?

Probably!

> Are docs for implementing new sync engines in the works or would you like me to convert my notes into basic first draft for docs?

Please contribute! :) A lot of people are asking for this

> I am planning to use the said engine on react-native possibly using the react-native-firebase project. Anyone know if this would be non trivial to implement with the existing adapters?

Don't know

> Would it be better to start a new adapter implementation from scratch or override the LokiJS adapter for example (maybe for supporting offline operations)?

I'm not sure I understand, but I'm not familiar with Firebase. You were asking about **synchronization** which made me think you want to use LokiJS/SQLite and then add a sync engine, so make HTTP requests and connect it to Watermelon.

But it now seems you're asking about **database adapter**, which is a different thing. Adding support for a different underlying database is a much more difficult undertaking. There's more API you'd need to support, most notably a way to convert Watermelon queries to the query language of your database. The question is, why do you want to do that? If you're interested in React Native, you'll either lose the biggest benefit of using SQLite (lazy loading), or add ANOTHER layer of abstraction on top of SQLite (again, not familiar with the tech you're talking about).

> (Bonus question) Would you use it if I built it? 🚽

Not us (we have a semi-custom backend), but I'm sure a lot of people would be very interested in this

**Comment by radex** [comment]
@creatorrr hey, any progress here?

**Comment by creatorrr** [comment]
@radex sorry had been caught up with work. Just started [a fork](https://github.com/creatorrr/WatermelonDB) to start the project and will post updates here. In the meantime, you can close this issue if you'd like.

Also, thanks for your comments above, I have decided to write a **database adapter** instead. Mainly because Firestore's [data model](https://firebase.google.com/docs/firestore/data-model) stores data as _documents_ in _collections_ and this maps rather neatly with [watermelondb](https://github.com/Nozbe/WatermelonDB)'s interface unlike relational database engines.

**Comment by radex** [comment]
OK, thanks! Be sure to let me know if you manage to finish this :)

**Comment by solace** [comment]
@creatorrr Did you end up completing the adapter?
