### ISSUE TITLE
[OPINION] Use Conventional Changelog

### ISSUE THREAD

**Issue by jspizziri** [Nozbe/WatermelonDB#961]
I just submitted [a PR](https://github.com/Nozbe/WatermelonDB/issues/958) that addresses an issue that was introduced by a manual modification to the CHANGELOG.

I'd highly recommend implementing [conventional changelog](https://www.npmjs.com/package/cz-conventional-changelog) in the project.

This would require the following:

1. Identify an adapter/syntax.
2. Setup the commitizen default config.
3. Add some simple scripts surrounding the release process to generate the changelog.
4. Update the contribution guidelines & readme.
5. Update the CI process to validate commit syntax for PR's.

I'd be happy to help get this done if it's desired.

**Comment by radex** [comment]
@jspizziri Hi, thank you for your pull request! I appreciate your effort in improving WatermelonDB, and I think it's unfortunate that a breaking change snuck into a release without properly documenting it. Having said that, I dislike `conventional changelog` and have no plans to adopt it. I know it works for a ton of people, but from my perspective, it puts more strain on me as a maintainer, and auto-generated change logs kinda suck - so manual effort is required anyway to edit it into something easier to digest.
