### ISSUE TITLE
Syncing a single table to the server

### ISSUE THREAD

**Issue by sodiqlawal** [Nozbe/WatermelonDB#962]
I have six(6) tables in my database.
But i just want to sync a single table to my server
How do i do that?

Also, logging out my table data, i get something like this;
Kindly check the attached image
![unwantedInfo](https://user-images.githubusercontent.com/45711490/110424479-2b55cd00-80a3-11eb-8592-9a821c327c4f.png)

How do i exclude those extra info e.g `_isEditing, _isCommented etc,` and have access to just my stored data

Thanks

**Comment by radex** [comment]
duplicate: https://github.com/Nozbe/WatermelonDB/issues/875
