### ISSUE TITLE
 Inform which is the primary key

### ISSUE THREAD

**Issue by osvaldokalvaitir** [Nozbe/WatermelonDB#964]
Hello, I'm new here and I have some questions that I didn't find in the documentation.

I saw that all tables create an id field for the primary key.

I have the tables:

```
devices - id (pk), name...

mobile_devices - device_id (pk), phone_number...
```

In the 'mobile_devices' table an 'id' field is created, but I want to inform you that the 'device_id' field is the primary key. Has as?

If you can do it, I would also like to know if you can enter a double or triple primary key.
(I'm seeing in the documentation on Many-To-Many Relation)

**Comment by radex** [comment]
@osvaldokalvaitir Unfortunately, WatermelonDB does not support specifying a custom primary key. Make mobile_devices.device_id a normal field and guarantee uniqueness on app level.
