### ISSUE TITLE
[Question] How to get values from an observable child of an observable?

### ISSUE THREAD

**Issue by edwardmcleodjones** [Nozbe/WatermelonDB#967]
I have a parent Model (e.g. `Folder`) which has an @children field for some child Models (e.g. `File`s)

In my `withObservables` HOC, I want to observe the parent `folders`, while also observing the child `files` in a custom observable field.

I'm using RxJS to `pipe` and `map` the `folders`, which is working fine at that level, but when I attempt to create a `children` property from piping and mapping the `folder.files.observe()` (using the relation link), the children are returned as type `Observable` instead of the object I'm wanting to map them to.

I assume its something to do with the lazy loading of the child relations, but my RxJS fu is pretty weak, so am unsure how to get it to return it an actual value instead of the Observable itself.

I've attempted to make a sample project at CodeSandbox, but its not able to import the WatermelonDB package for some reason (seems to fail on the custom loki dependency with unpkg?), but you should be able to get an idea of what I'm trying to do from looking at the source:
https://codesandbox.io/s/hardcore-resonance-1kf4n?file=/src/components/TreeView.tsx

My custom field is defined as:
```
treeView: database.collections
    .get("folders")
    .query()
    .observe()
    .pipe(
      map$((folders: Folder[]) => {
        return folders.map((folder) => {
          return {
            label: folder.name,  // <== This is showing up fine in the component 
            // But this "children" property is returned as the observable, not the value from the map...           
            children: folder.files.observe().pipe(  
              map$((files: File[]) => {
                return files.map((file) => {
                  return {
                    label: file.name,
                    parentLabel: folder.name
                  };
                });
              })
            )
          };
        });
      })
    )
```

The JSON value of the children property is:

```
{
  "_isScalar": false,
  "source": {
    "_isScalar": false,
    "source": {
      "_isScalar": false
    },
    "operator": {}
  },
  "operator": {}
}
```
and in Dev-tools shows as: `Observable`

I can hack around it in my component with a useEffect that takes the `folders` and `files` props as dependencies and does the map there instead, but I'd be interested in finding out if what I want to do is possible.

Thanks for the great library, am really enjoying using it now I've got my head wrapped around it!

**Comment by radex** [comment]
the key word you're looking for is `switchMap`. Go look for it and practice using nested Rx Observables this way
