### ISSUE TITLE
experimentalUseJSI does not work on iOS with Hermes enabled

### ISSUE THREAD

**Issue by Mitch528** [Nozbe/WatermelonDB#968]
I'm getting the following error when enabling experimentalUseJSI while on iOS with Hermes enabled with react-native 0.64 and @nozbe/watermelondb version 0.20.0:

```
Error: setValueAtIndex: index 0 is out of bounds [0, 0)
```

![Simulator Screen Shot - iPhone 12 Pro Max - 2021-03-16 at 12 07 20](https://user-images.githubusercontent.com/932976/111366172-6aaa8d80-8650-11eb-8663-8a010005899a.png)

Disabling experimentalUseJSI fixes the problem.

**Comment by radex** [comment]
@Mitch528 Run the app from Xcode with the debugger enabled and see if you can figure out where the error originates

**Comment by radex** [comment]
fixed https://github.com/Nozbe/WatermelonDB/pull/985/commits/124943eea212a4037e77ceb8052292032d991ef9
