### ISSUE TITLE
[Question] How to trigger reload data

### ISSUE THREAD

**Issue by huuthinh245** [Nozbe/WatermelonDB#969]
Thanks for good library
My code 
  ```
    <TouchableOpacity onPress={async () => {
        await database.action(async () => {
          const arr = await  database.collections.get('orders').query()
          await database.collections.get('orders').unsafeFetchRecordsWithSQL('DELETE FROM orders;')
          await database.collections.get('orders').unsafeClearCache()
       })
    }}>
      <Text style={{ fontSize: 25}}>clear database</Text>
    </TouchableOpacity>
```
Wrapper
```
 const observeOrders = () => database.collections.get('orders').query()
// This is how you make your app reactive! ✨
const enhance = withObservables(['orders, count'], (data) => {  
  return {
    orders: observeOrders().observe(),
    count: observeOrders().observeCount()
  }
})
```
It doesn't observer when using unsafeFetchRecordsWithSQL
Any solution for this case 
Thanks for support

**Comment by radex** [comment]
Hard to do easily, as using unsafeFetchRecordsWithSQL by definition works around Watermelon's observation system. Might be a good idea to keep your own Rx signal (a Subject) and trigger it when you delete from orders… and then use the signal (using Rx) on all orders query observations to force re-fetch

**Comment by huuthinh245** [comment]
Could you please show me example or something. I can research more thank you so much

**Comment by radex** [comment]
check out https://github.com/Nozbe/WatermelonDB/blob/master/docs-master/Advanced/AdvancedFields.md#custom-observable-fields for examples of advanced Rx work when using 🍉.

you create a signal by calling `subject.next(null)`, and then you use the signal by doing `subject.pipe(switchMap(() => database.collections.get('orders').query().observe()))`.

check out https://rxjs-dev.firebaseapp.com to learn how to do Rx

**Comment by huuthinh245** [comment]
OK my solution 
```
const Test = () => {
  useEffect(() => {
    ///Trigger observer when first time go to the screen
    subject.next(null)
  }, [])
  return(
    <EnhanceComponent />
  )
}
const aaa = ({ orders }) => {
  return(
    <View>
      <Text>"observer screen</Text>
    </View>
  )
};

const observeOrders = () => database.collections.get('orders').query()
const enhance = withObservables([], (data) => {
  return {
    orders: subject.pipe(
      switchMap(() => database.collections.get('orders').query().observe())
    ),
    count: observeOrders().observeCount()
  }
})
const EnhanceComponent = enhance(aaa)
```

**Comment by huuthinh245** [comment]
Hope this helpful who got this case
