### ISSUE TITLE
support for react native Expo Projects 

### ISSUE THREAD

**Issue by sanjeetiitr** [Nozbe/WatermelonDB#976]
I am trying to use watermelonDB with my expo project. It's not working there. Is there any solution for it ?

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/issues/855

**Comment by RoAppLab** [comment]
An implementation has been release, but I haven't been able to kickstart it.
https://www.npmjs.com/package/@morrowdigital/watermelondb-expo-plugin

Do anyone has try it ? Can you guide us ?
