### ISSUE TITLE
watermelondb and redis sync

### ISSUE THREAD

**Issue by prdpklyn** [Nozbe/WatermelonDB#981]
Hi Team,

We decided to use WaterMelonDB on our react native app as it supports sync with brings your own backend. Does it support Redis and anyone has any experience with using Redis as a backend and what is the consideration for decided the keys for sync service?

Appreciate any help

Thanks!

**Comment by KrisLau** [comment]
Extremely late but watermelondb works with any backend but the implementation of the push/pull endpoints have to be done by you. No idea about the considerations since I've never used Redis but here's the sync documentation: https://nozbe.github.io/WatermelonDB/Advanced/Sync.html
