### ISSUE TITLE
Per-collection sync

### ISSUE THREAD

**Issue by davifalta** [Nozbe/WatermelonDB#989]
Hello!
First of all, I would like to thank for the great tool and the time spent on going through all of these issues. WatermelonDB has helped me and my team creating a performant offline-first app in our company.

I have a usecase in my app in which we have to sync a large collection of items (about 90k records) that only needs to be synced every so often, unlike the rest of the data. The problem is that the first sync is pretty big, takes a lot of time and gives a bad experience to our users. We are having problems pre-caching all the data for this specific collection on the server side since we have the sync API paginated and it includes all the tables.
At the moment I'm wondering if someone could give me some guidance on what would be the downsides of implementing a custom per-collection sync for my usecase, and if feasible, where could I start?
Thank you in advance.

**Comment by radex** [comment]
https://github.com/Nozbe/WatermelonDB/issues/875
