### ISSUE TITLE
Changelog unclear for Android transition to autolinking

### ISSUE THREAD

**Issue by BenjaminSAILcloud** [Nozbe/WatermelonDB#993]
Hi,

With 0.21 comes Android autolinking. In the [changelog](https://github.com/Nozbe/WatermelonDB/blob/master/CHANGELOG.md#new-features) it is stated that : 

> - [Android] Autolinking is now supported.
>   - If You upgrade to `<= v0.21.0` **AND** are on a version of React Native which supports Autolinking, you will need to remove the config manually linking WatermelonDB.
>   - You can resolve this issue by **REMOVING** the lines of config from your project which are _added_ in the `Manual Install ONLY` section of the [Android Install docs](https://nozbe.github.io/WatermelonDB/Installation.html#android-react-native).

There is no such `Manual Install ONLY` section, so are we supposed to remove everything ?
I just removed the 5. part and it works just fine.

**Comment by radex** [comment]
If everything works fine for you, there's nothing you need to do :)

**Comment by BenjaminSAILcloud** [comment]
The issue is that it didn't work. I had this error on Android after updating the package : 

`Native module DatabaseBridge tried to override DatabaseBridge.`
<details>
<summary>Screenshot</summary>

![image](https://user-images.githubusercontent.com/33052668/114685869-89b14380-9d12-11eb-84ec-ecac558ad9bf.png)
</details>

The solution was to undo the section 5. of the Android setup.
```diff
// ...
- import com.nozbe.watermelondb.WatermelonDBPackage;
// ...
@Override
        protected List<ReactPackage> getPackages() {
          @SuppressWarnings("UnnecessaryLocalVariable")
          List<ReactPackage> packages = new PackageList(this).getPackages();
          // Packages that cannot be autolinked yet can be added manually here, for example:
          // packages.add(new MyReactNativePackage());
          packages.add(new RNCPickerPackage());
-         packages.add(new WatermelonDBPackage());
          return packages;
        }
}

```

**Comment by radex** [comment]
I think the mixup was that changelog was modified for the already released version, but documentation for the Installation guide will only be released with v0.22. Sorry.

Your solution looks correct to me.

**Comment by cristianomesquita** [comment]
I am with the same problem, some update?

**Comment by osvaldokalvaitir** [comment]
The same error appeared to me, I did the procedure removing the import and for now it is working well.
