### ISSUE TITLE
Problem passing parameter in React Navigation

### ISSUE THREAD

**Issue by osvaldokalvaitir** [Nozbe/WatermelonDB#995]
I wanted to know what is most suitable.

I have a screen with a list of products and when clicking on a product you are redirected to the details screen for that product.

```
<ListItemButton
        onPress={() => {
          navigation.navigate('ProductDetail', { product });
        }} />
```

If I do it like this, the following error appears:
```
Non-serializable values were found in the navigation state. Check:

ProductDetail > params.product.__changes.observers[0]._subscriptions[0]._parentOrParents (Circular reference)
```

I am currently passing only the id and making a new query passing the product id.

```
<ListItemButton
        onPress={() => {
          navigation.navigate('ProductDetail', { id: product.id });
        }} />
```

```
const enhanceProduct = withObservables(['product'], ({ database, route }) => ({
  product: database.get('products').findAndObserve(route.params.id),
}));

export default withDatabase(enhanceProduct(ProductDetail));
```

I would like to know what is the best way, no matter how much I keep using passing only the id, there are some moments that I will need to pass the object and there will be an error, does anyone know how to solve this React Navigation error?

**Comment by zgid123** [comment]
the only solution for now is create a function to return a plain object and then pass it to the react navigation state

```ts
class YourModel extends Model {
  // define field and association here

  public asJson(): IYourModelProps {
    return {
    }
  }
}
```

**Comment by radex** [comment]
Passing the ID is good 👍
