### ISSUE TITLE
TypeError: null is not an object (evaluating 'DatabaseBridge[methodName]')

### ISSUE THREAD

**Issue by sankomil** [Nozbe/WatermelonDB#997]
Hi, I have just recently picked up Watermelon DB, and went through the other issues that have been submitted before that had the same issue. However I have been unable to rectify this issue, despite having linked it as stated in the docs. 

I have attached the screenshots for each file, but if anyone would like a reproducible demo, then please have a look at the [project](https://github.com/sankomil/watermelon-testing) I was trying to implement on. It is based on this [post](https://blog.logrocket.com/offline-app-react-native-watermelondb/).

Please find the necessary screenshots attached below:

Error message:
![image](https://user-images.githubusercontent.com/43489998/114845728-94510300-9e0e-11eb-8f3e-e2210f9c0b02.png)

.babelrc:
![image](https://user-images.githubusercontent.com/43489998/114845988-d37f5400-9e0e-11eb-97fd-4a54ad99d597.png)

android/settings.gradle:
![image](https://user-images.githubusercontent.com/43489998/114846116-f14cb900-9e0e-11eb-82e3-11edbd809d05.png)

android/app/build.gradle:
![image](https://user-images.githubusercontent.com/43489998/114846361-3375fa80-9e0f-11eb-9dbe-8e0362f1565e.png)
![image](https://user-images.githubusercontent.com/43489998/114846501-599b9a80-9e0f-11eb-9acb-5439ab98b666.png)

android/build.gradle:
![image](https://user-images.githubusercontent.com/43489998/114846650-79cb5980-9e0f-11eb-828a-0425d38172d0.png)

android/app/src/main/java/{YOUR_APP_PACKAGE}/MainApplication.java:
![image](https://user-images.githubusercontent.com/43489998/114846748-8f408380-9e0f-11eb-82a9-662bbf5e7f1c.png)

**Comment by sankomil** [comment]
I recreated the project from scratch, and followed the steps except for adding in `android/app/src/main/java/{YOUR_APP_PACKAGE}/MainApplication.java` as doing that gave me the following error:

![image](https://user-images.githubusercontent.com/43489998/114968776-9f0ca600-9ea9-11eb-82d6-ac4176307435.png)

If I don't insert it, the issue gets resolved and the project builds without any errors.

**Comment by Acetyld** [comment]
No reactions?
