### ISSUE TITLE
possible typo in DatabaseBridge.js

### ISSUE THREAD

**Issue by zhirzh** [Nozbe/WatermelonDB#999]
prettier reported a syntax error when trying to format [DatabaseBridge.js][1]

```
SyntaxError: Unexpected token (29:64)
  27 |   databaseName: string,
  28 |   schemaVersion: number,
> 29 |   resolve: (status: {code: string, databaseVersion?: number,...}) => void,
     |                                                                ^
  30 |   reject: () => void
  31 | ) => void) = (
  32 |     tag: number,
```

there is a trailing tipple dot (`...`) in `resolve()` function signature. typo or some new JS/Flow syntax?

[1]: https://github.com/Nozbe/WatermelonDB/blob/40ff28b6b78a16ae2f4bcdb5b74e7c1688a1e09b/src/adapters/sqlite/makeDispatcher/node/DatabaseBridge.js#L29

**Comment by radex** [comment]
it's legit flow syntax, you might have an old version of prettier?

**Comment by zhirzh** [comment]
Ah, got it. This syntax for inexact object types was added in [flow v0.84.0][1] and its support was added in [prettier v1.15.0][2]. Current prettier version used in project is v1.14.2 [installed by prettier-eslint v9.0.0][3].

[1]: https://github.com/facebook/flow/blob/master/Changelog.md#0840
[2]: https://prettier.io/blog/2018/11/07/1.15.0.html#support-inexact-5304-by-jbrown215-5356-by-existentialism
[3]: https://github.com/Nozbe/WatermelonDB/blob/master/yarn.lock#L7549

**Comment by radex** [comment]
huh! @zhirzh would you mind sending a quick PR fixing the dependency with prettier run on the codebase?

**Comment by zhirzh** [comment]
> prettier run on the codebase

this will create quite a [large PR](https://github.com/Nozbe/WatermelonDB/pull/1002)
